"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SparklesIcon = exports.LockIcon = exports.ShieldIcon = exports.FireIcon = exports.CompressHorizontalIcon = exports.CompressVerticalIcon = exports.EraserIcon = exports.PencilIcon = exports.XCircleIcon = exports.CheckCircleIcon = exports.CopyIcon = exports.DocumentDuplicateIcon = exports.ArrowUturnRightIcon = exports.ArrowUturnLeftIcon = exports.RotateCcwIcon = exports.ArrowRightIcon = exports.ArrowLeftIcon = exports.ArrowDownIcon = exports.ArrowUpIcon = exports.CaretRightIcon = exports.CaretDownIcon = exports.ListBulletIcon = exports.TrashIcon = exports.QuestionMarkCircleIcon = exports.CogIcon = exports.DocumentPlusIcon = exports.PlusCircleIcon = exports.ImageIcon = exports.FolderOpenIcon = exports.SaveFloppyIcon = exports.SaveIcon = exports.LoadIcon = exports.BugIcon = exports.StopIcon = exports.PlayIcon = exports.PatternBrushIcon = exports.PuzzlePieceIcon = exports.MusicNoteIcon = exports.SoundIcon = exports.ASMIcon = exports.CodeIcon = exports.GameFlowIcon = exports.WorldViewIcon = exports.WorldMapIcon = exports.MapIcon = exports.SpriteIcon = exports.TilesetIcon = exports.PlaceholderIcon = exports.SphereIcon = exports.GridIcon = void 0;
exports.WaveformIcon = exports.ScissorsIcon = exports.CompilerIcon = exports.CollapseAllIcon = exports.ExpandAllIcon = exports.SwapVertIcon = exports.SwapHorizIcon = exports.ArrowsPointingOutIcon = exports.PaintBrushIcon = exports.StopCircleIcon = exports.ContourIcon = exports.ViewfinderCircleIcon = exports.PasteIcon = exports.ClipboardDocumentListIcon = exports.ClockIcon = exports.RefreshCwIcon = exports.ArrowPathIcon = exports.ZoomOutIcon = exports.ZoomInIcon = exports.HudIcon = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const react_1 = require("react");
const Lucide = require("lucide-react");
const wrapIcon = (IconComponent, defaultClass = "w-5 h-5") => {
    const WrappedIcon = ({ className }) => ((0, jsx_runtime_1.jsx)(IconComponent, { className: `${defaultClass} ${className || ''}`, strokeWidth: 1.5 }));
    return WrappedIcon;
};
exports.GridIcon = wrapIcon(Lucide.Grid);
exports.SphereIcon = wrapIcon(Lucide.Globe);
exports.PlaceholderIcon = wrapIcon(Lucide.FileQuestion);
exports.TilesetIcon = wrapIcon(Lucide.LayoutGrid);
exports.SpriteIcon = wrapIcon(Lucide.Ghost);
exports.MapIcon = wrapIcon(Lucide.Map);
exports.WorldMapIcon = wrapIcon(Lucide.MapPin);
exports.WorldViewIcon = wrapIcon(Lucide.MonitorSmartphone);
exports.GameFlowIcon = wrapIcon(Lucide.MapPin);
exports.CodeIcon = wrapIcon(Lucide.Code2);
exports.ASMIcon = wrapIcon(Lucide.Code2);
exports.SoundIcon = wrapIcon(Lucide.Volume2);
exports.MusicNoteIcon = wrapIcon(Lucide.Music);
exports.PuzzlePieceIcon = wrapIcon(Lucide.Puzzle);
exports.PatternBrushIcon = wrapIcon(Lucide.Brush, "w-4 h-4");
exports.PlayIcon = wrapIcon(Lucide.PlayCircle);
exports.StopIcon = wrapIcon(Lucide.StopCircle);
exports.BugIcon = wrapIcon(Lucide.Bug);
exports.LoadIcon = wrapIcon(Lucide.Upload);
exports.SaveIcon = wrapIcon(Lucide.Download);
exports.SaveFloppyIcon = wrapIcon(Lucide.Save);
exports.FolderOpenIcon = wrapIcon(Lucide.FolderOpen);
exports.ImageIcon = wrapIcon(Lucide.Image);
exports.PlusCircleIcon = wrapIcon(Lucide.PlusCircle);
exports.DocumentPlusIcon = wrapIcon(Lucide.FilePlus);
exports.CogIcon = wrapIcon(Lucide.Settings);
exports.QuestionMarkCircleIcon = wrapIcon(Lucide.HelpCircle);
exports.TrashIcon = wrapIcon(Lucide.Trash2);
exports.ListBulletIcon = wrapIcon(Lucide.List);
exports.CaretDownIcon = wrapIcon(Lucide.ChevronDown, "w-3 h-3");
exports.CaretRightIcon = wrapIcon(Lucide.ChevronRight, "w-3 h-3");
exports.ArrowUpIcon = wrapIcon(Lucide.ArrowUp);
exports.ArrowDownIcon = wrapIcon(Lucide.ArrowDown);
exports.ArrowLeftIcon = wrapIcon(Lucide.ArrowLeft);
exports.ArrowRightIcon = wrapIcon(Lucide.ArrowRight);
exports.RotateCcwIcon = wrapIcon(Lucide.RotateCcw);
exports.ArrowUturnLeftIcon = wrapIcon(Lucide.Undo2);
exports.ArrowUturnRightIcon = wrapIcon(Lucide.Redo2);
exports.DocumentDuplicateIcon = wrapIcon(Lucide.Copy);
exports.CopyIcon = wrapIcon(Lucide.Copy);
exports.CheckCircleIcon = wrapIcon(Lucide.CheckCircle2);
exports.XCircleIcon = wrapIcon(Lucide.XCircle);
exports.PencilIcon = wrapIcon(Lucide.Pencil);
exports.EraserIcon = wrapIcon(Lucide.Eraser);
exports.CompressVerticalIcon = wrapIcon(Lucide.Minimize2);
exports.CompressHorizontalIcon = wrapIcon(Lucide.Shrink);
exports.FireIcon = wrapIcon(Lucide.Flame);
exports.ShieldIcon = wrapIcon(Lucide.Shield);
exports.LockIcon = wrapIcon(Lucide.Lock);
exports.SparklesIcon = wrapIcon(Lucide.Sparkles);
exports.HudIcon = wrapIcon(Lucide.AppWindow);
exports.ZoomInIcon = wrapIcon(Lucide.ZoomIn);
exports.ZoomOutIcon = wrapIcon(Lucide.ZoomOut);
exports.ArrowPathIcon = wrapIcon(Lucide.RefreshCw);
exports.RefreshCwIcon = wrapIcon(Lucide.RefreshCw);
exports.ClockIcon = wrapIcon(Lucide.Clock);
exports.ClipboardDocumentListIcon = wrapIcon(Lucide.ClipboardList);
exports.PasteIcon = wrapIcon(Lucide.ClipboardList);
exports.ViewfinderCircleIcon = wrapIcon(Lucide.Focus);
exports.ContourIcon = wrapIcon(Lucide.BoxSelect);
exports.StopCircleIcon = wrapIcon(Lucide.Ban);
exports.PaintBrushIcon = wrapIcon(Lucide.PaintBucket);
exports.ArrowsPointingOutIcon = wrapIcon(Lucide.Maximize2);
exports.SwapHorizIcon = wrapIcon(Lucide.ArrowRightLeft);
exports.SwapVertIcon = wrapIcon(Lucide.ArrowUpDown);
exports.ExpandAllIcon = wrapIcon(Lucide.Maximize);
exports.CollapseAllIcon = wrapIcon(Lucide.Minimize);
exports.CompilerIcon = wrapIcon(Lucide.Cpu);
exports.ScissorsIcon = wrapIcon(Lucide.Scissors);
exports.WaveformIcon = wrapIcon(Lucide.Activity);
