# SCC Fase 1 music runtime smoke: fixture song generated by
# test/scc/build_scc_test_rom.mjs through sccSoundGenerator.ts.
# Run:
#   "C:/Program Files/openMSX/openmsx.exe" -machine C-BIOS_MSX2+ \
#     -cart test/scc/scc_track_test.rom -romtype KonamiSCC -script test/scc/scc_track_smoke.tcl
# RAM map: markers #C000.., player RAM chained from #C040 (buildSccMusicRam):
#   C040 active, C042 loop_count, C044 row_countdown, C045 order_pos,
#   C048 pattern_row, C049 pattern_rows, C054 mixer_shadow,
#   C055 ch_note[5], C05F ch_volbase[5], C07D ch_volout[5],
#   C082 loop_enabled, C083 mapper P2 mirror.
set result_path "test/scc/scc_track_result.txt"
set fh_lines [list]
proc log_line {line} { global fh_lines; lappend fh_lines $line }
proc flush_report {} {
    global result_path fh_lines
    set fh [open $result_path w]
    foreach l $fh_lines { puts $fh $l }
    close $fh
    after time 1 { exit }
}
catch { set renderer none }
catch { set throttle off }

after time 8 {
    log_line "boot=[debug read memory 0xC000] (expect 1)"
    log_line "slot=[debug read memory 0xC001] (expect 2)"
    log_line "ready=[debug read memory 0xC005] (expect 5)"
    log_line "active=[debug read memory 0xC040] (expect 1)"
    log_line "mixer_shadow=[debug read memory 0xC054] (expect nonzero: channels 1-3 playing)"
    set ::row_a [debug read memory 0xC048]
    log_line "pattern_row_a=$::row_a (16 rows/pattern)"
    log_line "pattern_rows=[debug read memory 0xC049] (expect 16)"
    set ::vol_a [debug read memory 0xC07D]
    log_line "volout_ch1_a=$::vol_a (envelope-driven)"
    set ::saved_p2 [debug read memory 0xC083]
    log_line "mapper_p2_before_probe=$::saved_p2 (expect 2: restored after SCC tick)"
    debug write memory 0x9000 0x3F
    set w {}
    foreach off {0 1 2 3} {
        lappend w [format %02X [debug read memory [expr {0x9800 + $off}]]]
    }
    log_line "wave_ch1_first4=$w (expect triangle instrument samples)"
    debug write memory 0x9000 $::saved_p2
    log_line "ch_note_4=[debug read memory 0xC058] ch_note_5=[debug read memory 0xC059] (expect 255: unused channels)"
}
after time 8.45 {
    log_line "pattern_row_b=[debug read memory 0xC048] (expect != pattern_row_a: rows advance)"
    log_line "volout_ch1_b=[debug read memory 0xC07D] (27 frames later: different envelope phase)"
}
after time 14 {
    log_line "loop_count=[debug read memory 0xC042] (expect >=1: ~3.2s song wrapped)"
    log_line "order_pos=[debug read memory 0xC045] (expect 0 or 1)"
    log_line "active_end=[debug read memory 0xC040] (expect 1)"
}
after time 15 { debug write memory 0xC010 1 }
after time 16 {
    log_line "stopped=[debug read memory 0xC008] (expect 1)"
    log_line "active_after_stop=[debug read memory 0xC040] (expect 0)"
    flush_report
}
