"use strict";
/**
 * @fileoverview Unified Generator - All-in-one combined file
 * Generates unitedFiles.asm combining all modular files into one
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateUnifiedFile = generateUnifiedFile;
const bankPacker_1 = require("../utils/bankPacker");
/**
 * Convert routine name to lowercase (for labels, CALL, JP, JR targets)
 */
function toRoutineLabel(name) {
    return name.toLowerCase();
}
function formatExecutionPlanComments(executionPlan) {
    const irqTasks = executionPlan.tasks.length > 0
        ? executionPlan.tasks.map((task) => `; IRQ Task: slot ${task.slot} -> ${task.routineLabel} (${task.responsibility}, every ${task.period} frame${task.period === 1 ? '' : 's'})`).join('\n')
        : '; IRQ Task: none';
    const mainlineWork = executionPlan.mainline.length > 0
        ? executionPlan.mainline.map((item) => `; Mainline: ${item.phase} -> ${item.routineLabel} (${item.responsibility})`).join('\n')
        : '; Mainline: none';
    const warnings = executionPlan.diagnostics.warnings.length > 0
        ? executionPlan.diagnostics.warnings.map((warning) => `; Warning: ${warning}`).join('\n')
        : '; Warning: none';
    return `; Engine Execution Mode: ${executionPlan.mode}\n${irqTasks}\n${mainlineWork}\n${warnings}\n`;
}
/**
 * Generate unified file (unitedFiles.asm) - optional all-in-one file
 *
 * @param files - All generated ASM files
 * @param projectName - Name of the project
 * @param analysis - Project analysis with assets and configuration
 * @param config - ROM mode/mapper configuration
 * @returns ASM code string with all files combined
 */
function generateUnifiedFile(files, projectName, analysis, executionPlan, config = {
    romMode: 'simple32k',
    targetFormat: 'konami',
    autoMegaROM: false
}) {
    // Check what features are needed
    const hasMenus = analysis.gameFlow?.nodes?.some(node => node.type === 'SubMenu');
    const hasText = analysis.screenMaps?.some(screen => screen.layers?.text || screen.textElements?.length > 0);
    const hasHud = analysis.screenMaps?.some(screen => screen.hudConfiguration?.elements && screen.hudConfiguration.elements.length > 0);
    const needsFont = hasMenus || hasText || hasHud;
    const bankPackReport = (0, bankPacker_1.buildBankPackReport)(files);
    const bankPackComments = (0, bankPacker_1.formatBankPackReportAsAsmComments)(bankPackReport);
    const executionPlanComments = formatExecutionPlanComments(executionPlan);
    return `; ==================================================================
; ${projectName.toUpperCase()} - UNIFIED FILE
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
;
; OPTIMIZED: Only includes necessary code for this project
; Tiles: ${analysis.tiles?.length || 0}
; Sprites: ${analysis.sprites?.length || 0}
; Screens: ${analysis.screenMaps?.length || 0}
; Entities: ${analysis.entities?.length || 0}
; Menus: ${hasMenus ? 'Yes' : 'No'}
; HUD: ${hasHud ? 'Yes' : 'No'}
; State Machines: ${analysis.stateMachines?.length || 0}
; ROM Mode: ${config.romMode}
; Mapper Target: ${config.targetFormat}
; Auto MegaROM: ${config.autoMegaROM ? 'Yes' : 'No'}
${executionPlanComments}; ==================================================================
${config.romMode === 'plain48k' ? '; EXPERIMENTAL: plain48k plumbing is enabled, but page-0 asset packing is not implemented yet.\n' : ''}${bankPackComments}

; CRITICAL: header.asm with ORG #4000 and "AB" signature MUST be first
; for the ROM to work correctly. EQUs can go after ORG.
${files['header.asm']}

${files['bios.asm']}

${files['constants.asm']}

${files['variables.asm']}

${files['mapper.asm']}

${files['interrupt.asm']}

${analysis.tiles && analysis.tiles.length > 0 ? files['patterns.asm'] : '; [patterns.asm skipped - no tiles]\n'}

${analysis.tiles && analysis.tiles.length > 0 ? files['colors.asm'] : '; [colors.asm skipped - no tiles]\n'}

${files['sprites.asm']}

${analysis.screenMaps && analysis.screenMaps.length > 0 ? files['screens.asm'] : '; [screens.asm skipped - no screens]\n'}

${files['components.asm']}

${analysis.entities && analysis.entities.length > 0 ? files['entities.asm'] : '; [entities.asm skipped - no entities]\n'}

${hasMenus ? files['menus.asm'] : '; [menus.asm skipped - no menus]\n'}

${needsFont ? files['font.asm'] : `; [font.asm skipped - no text/menus]
init_font_system:
    ret

`}

${hasHud ? files['hud.asm'] : '; [hud.asm skipped - no HUD elements]\n'}

${files['sound.asm']}

${files['scroll.asm']}

${files['animtiles.asm']}

${files['particles.asm']}

${files['statemachine.asm'] && files['statemachine.asm'].trim() !== '; No State Machines' ? files['statemachine.asm'] : '; [statemachine.asm skipped - no state machines]\n'}

${analysis.gameFlow ? files['gameflow.asm'] : '; [gameflow.asm skipped - no GameFlow]\n'}

${files['worlds.asm']}

; ==================================================================
; GAME SYSTEM FUNCTIONS
; ==================================================================
; NOTE: The main game loop and execution flow are handled exclusively
; by GameFlow (see gameflow.asm section above).
; This section only contains shared initialization and utility functions.
; ==================================================================

init_game_systems:
    call DISSCR               ; Disable screen while loading VRAM assets
${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize component systems (entities detected)
    call init_components
` : `    ; No entities - skipping component system initialization
`}
${analysis.tiles && analysis.tiles.length > 0 ? `    ; Load pattern and color data (tiles detected)
    call load_pattern_bank0
    call load_pattern_bank1
    call load_pattern_bank2
    call load_color_bank0
    call load_color_bank1
    call load_color_bank2
` : `    ; No tiles detected - skipping pattern/color loading
`}
    ; Initialize animated tile runtime (safe no-op if no animated groups)
    call init_animated_tiles

${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize game entities with real positions from JSON
    call init_entities
` : `    ; No entities to initialize
`}
${analysis.screenMaps && analysis.screenMaps.length > 0 ? `    ; Load the first game screen
    call load_game_screen
` : `    ; No screens - skip screen loading
`}
${needsFont ? `    ; Initialize font system
    call init_font_system
` : `    ; No text/menus - skip font initialization
`}${hasHud ? `    ; HUD dirty flag - will be rendered after screen loading (by GameFlow WorldLink)
    ld a, 1
    ld (hud_dirty_flag), a
` : ``}    call ENASCR               ; Re-enable screen after VRAM updates
    ret

; ==================================================================
; SCREEN LOADING STUB (for compatibility)
; ==================================================================
; NOTE: With GameFlow system, screen loading is handled by GameFlow nodes
; via load_world_X -> load_screen_X. This stub exists for backward
; compatibility with init_game_systems references.
load_game_screen:
    ret

    end                 ; End of assembly
`;
}
