;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS Main Game Loop Integration for MSX
;; Generated by MSX Retro Game IDE
;;
;; Main game loop that integrates the ECS system
;; with input handling, screen updates, and timing
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Include all ECS modules
INCLUDE "ecs_memory_manager.asm"
INCLUDE "ecs_entity_system.asm"
INCLUDE "ecs_component_registry.asm"
INCLUDE "ecs_systems.asm"

; Game state
GAME_STATE:             DB 0    ; 0=Menu, 1=Playing, 2=Paused, 3=GameOver
GAME_INITIALIZED:       DB 0    ; Initialization flag
INPUT_STATE:            DB 0    ; Current input state
PREV_INPUT_STATE:       DB 0    ; Previous frame input state

; Timing variables
FRAME_TIME_TARGET:      EQU 4   ; Target frames per update (15 FPS at 60Hz)
FRAME_TIME_COUNTER:     DB 0    ; Frame timing counter

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Initialize ECS Game Engine
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
INIT_ECS_GAME:
    ; Initialize ECS memory manager
    CALL ECS_INIT
    
    ; Initialize MSX graphics mode
    CALL INIT_GRAPHICS_MODE
    
    ; Initialize sound system
    CALL INIT_SOUND_SYSTEM
    
    ; Load initial game data
    CALL LOAD_INITIAL_ENTITIES
    
    ; Set game as initialized
    LD A, 1
    LD (GAME_INITIALIZED), A
    
    ; Start in menu state
    XOR A
    LD (GAME_STATE), A
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Main Game Loop
;; Input: None
;; Output: None (loops forever)
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MAIN_GAME_LOOP:
    ; Check if game is initialized
    LD A, (GAME_INITIALIZED)
    OR A
    CALL Z, INIT_ECS_GAME
    
GAME_LOOP_FRAME:
    ; Handle frame timing
    LD A, (FRAME_TIME_COUNTER)
    INC A
    LD (FRAME_TIME_COUNTER), A
    CP FRAME_TIME_TARGET
    JP C, GAME_LOOP_FRAME       ; Wait for target frame time
    XOR A
    LD (FRAME_TIME_COUNTER), A
    
    ; Read input
    CALL READ_INPUT
    
    ; Update game based on current state
    LD A, (GAME_STATE)
    CP 0
    CALL Z, UPDATE_MENU_STATE
    CP 1
    CALL Z, UPDATE_PLAYING_STATE
    CP 2
    CALL Z, UPDATE_PAUSED_STATE
    CP 3
    CALL Z, UPDATE_GAMEOVER_STATE
    
    ; Wait for VSync
    CALL WAIT_VSYNC
    
    ; Loop forever
    JP GAME_LOOP_FRAME

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Read controller input
;; Input: None
;; Output: INPUT_STATE updated
;; Destroys: A, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
READ_INPUT:
    ; Store previous input state
    LD A, (INPUT_STATE)
    LD (PREV_INPUT_STATE), A
    
    ; Read MSX joystick/keyboard
    ; This is a simplified version - adapt to your input system
    CALL MSX_READ_JOYSTICK      ; Returns input in A
    LD (INPUT_STATE), A
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Update menu state
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
UPDATE_MENU_STATE:
    ; Check for start game input
    LD A, (INPUT_STATE)
    AND 10h                     ; Fire button
    RET Z                       ; Fire not pressed
    
    ; Check if this is a new press
    LD A, (PREV_INPUT_STATE)
    AND 10h
    RET NZ                      ; Was already pressed
    
    ; Start game
    LD A, 1
    LD (GAME_STATE), A
    
    ; Initialize game entities
    CALL INIT_GAME_ENTITIES
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Update playing state (main gameplay)
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
UPDATE_PLAYING_STATE:
    ; Handle pause input
    LD A, (INPUT_STATE)
    AND 20h                     ; Some pause key
    JR Z, PLAYING_NO_PAUSE
    
    LD A, (PREV_INPUT_STATE)
    AND 20h
    JR NZ, PLAYING_NO_PAUSE     ; Was already pressed
    
    ; Pause game
    LD A, 2
    LD (GAME_STATE), A
    RET

PLAYING_NO_PAUSE:
    ; Handle player input for entities
    CALL HANDLE_PLAYER_INPUT
    
    ; Update all ECS systems
    CALL UPDATE_ALL_SYSTEMS
    
    ; Check for game over conditions
    CALL CHECK_GAME_OVER
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Update paused state
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
UPDATE_PAUSED_STATE:
    ; Check for unpause input
    LD A, (INPUT_STATE)
    AND 20h                     ; Pause key
    RET Z
    
    LD A, (PREV_INPUT_STATE)
    AND 20h
    RET NZ                      ; Was already pressed
    
    ; Resume game
    LD A, 1
    LD (GAME_STATE), A
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Update game over state
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
UPDATE_GAMEOVER_STATE:
    ; Check for restart input
    LD A, (INPUT_STATE)
    AND 10h                     ; Fire button
    RET Z
    
    LD A, (PREV_INPUT_STATE)
    AND 10h
    RET NZ                      ; Was already pressed
    
    ; Restart game
    CALL CLEANUP_GAME_ENTITIES
    LD A, 0
    LD (GAME_STATE), A          ; Back to menu
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Handle player input for game entities
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
HANDLE_PLAYER_INPUT:
    ; Find player entity (assuming first entity with specific components)
    LD A, COMP_ID_TRANSFORM     ; Look for player by transform + specific AI type
    CALL FIND_ENTITY_BY_COMPONENT
    CP 0xFF
    RET Z                       ; No player entity found
    
    LD B, A                     ; B = player entity ID
    
    ; Get player's physics component for movement
    LD A, B
    LD B, COMP_ID_PHYSICS
    CALL GET_ENTITY_COMPONENT
    LD A, H
    OR L
    RET Z                       ; No physics component
    
    ; Apply input to velocity
    ; velX(2), velY(2), accX(2), accY(2), mass(2), friction(2)
    LD DE, HL                   ; DE = physics component
    
    ; Check horizontal input
    LD A, (INPUT_STATE)
    LD B, 0                     ; B = velocity X
    
    BIT 2, A                    ; Left
    JR Z, CHECK_RIGHT
    LD B, -2                    ; Move left
    
CHECK_RIGHT:
    BIT 3, A                    ; Right  
    JR Z, SET_VELX
    LD B, 2                     ; Move right
    
SET_VELX:
    LD A, B
    LD (DE), A                  ; Set velX low
    INC DE
    XOR A
    RLA                         ; Sign extend
    LD (DE), A                  ; Set velX high
    INC DE
    
    ; Check vertical input
    LD B, 0                     ; B = velocity Y
    LD A, (INPUT_STATE)
    
    BIT 0, A                    ; Up
    JR Z, CHECK_DOWN
    LD B, -2                    ; Move up
    
CHECK_DOWN:
    BIT 1, A                    ; Down
    JR Z, SET_VELY
    LD B, 2                     ; Move down
    
SET_VELY:
    LD A, B
    LD (DE), A                  ; Set velY low
    INC DE
    XOR A
    RLA                         ; Sign extend
    LD (DE), A                  ; Set velY high
    
    ; Handle fire button for shooting
    LD A, (INPUT_STATE)
    BIT 4, A                    ; Fire button
    RET Z
    
    ; Check if this is a new press
    LD A, (PREV_INPUT_STATE)
    BIT 4, A
    RET NZ                      ; Was already pressed
    
    ; Create projectile entity
    CALL CREATE_PROJECTILE
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Initialize graphics mode (MSX specific)
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
INIT_GRAPHICS_MODE:
    ; Set up MSX SCREEN 2 or desired graphics mode
    ; This is hardware-specific
    LD A, 2
    CALL 005FH                  ; CHGMOD - Change screen mode
    
    ; Initialize sprite patterns and colors
    CALL INIT_SPRITE_DATA
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Initialize sound system
;; Input: None  
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
INIT_SOUND_SYSTEM:
    ; Initialize PSG or MSX sound hardware
    ; Clear all sound channels
    XOR A
    OUT (0A0H), A               ; PSG register select
    OUT (0A1H), A               ; PSG data
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Load initial entities from templates
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
LOAD_INITIAL_ENTITIES:
    ; This would load entities from your generated template data
    ; For now, create a simple test entity
    
    ; Create a test entity with transform and renderer
    CALL ALLOCATE_ENTITY
    CP 0xFF
    RET Z                       ; Failed to create entity
    
    ; Add transform component
    LD B, COMP_ID_TRANSFORM
    CALL ADD_COMPONENT_TO_ENTITY
    LD A, H
    OR L
    RET Z                       ; Failed to add component
    
    ; Initialize transform (position 100, 100)
    LD (HL), 100                ; X low
    INC HL
    XOR A
    LD (HL), A                  ; X high
    INC HL
    LD (HL), 100                ; Y low
    INC HL
    LD (HL), A                  ; Y high
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Initialize game entities for playing state
;; Input: None
;; Output: None  
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
INIT_GAME_ENTITIES:
    ; Clear existing entities
    CALL ECS_INIT
    
    ; Create player entity
    LD A, 0                     ; Assuming template 0 is player
    CALL CREATE_ENTITY_BY_TEMPLATE_ID
    
    ; Create enemy entities
    LD B, 3                     ; Create 3 enemies
    LD C, 1                     ; Enemy template ID
    
INIT_ENEMIES_LOOP:
    LD A, C
    CALL CREATE_ENTITY_BY_TEMPLATE_ID
    DJNZ INIT_ENEMIES_LOOP
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Check for game over conditions
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CHECK_GAME_OVER:
    ; Check if player is dead (health <= 0)
    ; Find player entity and check health
    
    ; This is a simplified check - implement your game logic
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Create a projectile entity
;; Input: None (uses player position/direction)
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CREATE_PROJECTILE:
    ; Create projectile from template
    LD A, 2                     ; Assuming template 2 is projectile
    CALL CREATE_ENTITY_BY_TEMPLATE_ID
    
    ; Set projectile position and velocity based on player
    ; Implementation depends on your specific projectile logic
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Cleanup all game entities
;; Input: None
;; Output: None
;; Destroys: All registers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
CLEANUP_GAME_ENTITIES:
    ; Free all entities
    LD B, 0
    
CLEANUP_LOOP:
    LD A, B
    CP MAX_ENTITIES
    RET NC
    
    ; Check if entity is active
    CALL GET_ENTITY_PTR
    LD A, (HL)
    OR A
    JR Z, CLEANUP_NEXT
    
    ; Free the entity
    LD A, B
    CALL FREE_ENTITY
    
CLEANUP_NEXT:
    INC B
    JR CLEANUP_LOOP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MSX-specific helper functions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

MSX_READ_JOYSTICK:
    ; Read MSX joystick port
    ; Returns: A = input state (bits: up, down, left, right, fire1, fire2)
    IN A, (0A2H)                ; Read joystick port
    CPL                         ; Invert bits (active low)
    AND 3FH                     ; Mask valid bits
    RET

WAIT_VSYNC:
    ; Wait for vertical synchronization
    CALL 0138H                  ; MSX BIOS VSYNC
    RET

INIT_SPRITE_DATA:
    ; Initialize sprite patterns and colors
    ; Load your sprite data here
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Entry point for the ECS game
;; This should be called from your main program
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ECS_GAME_START:
    ; Disable interrupts during initialization
    DI
    
    ; Initialize the ECS game
    CALL INIT_ECS_GAME
    
    ; Enable interrupts
    EI
    
    ; Enter main game loop (never returns)
    JP MAIN_GAME_LOOP