;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS Memory Manager for MSX
;; Generated by MSX Retro Game IDE
;;
;; This module handles entity and component memory allocation
;; Uses fixed-size pools for deterministic performance
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Memory layout constants
MAX_ENTITIES        EQU 64      ; Maximum number of entities
MAX_COMPONENTS      EQU 128     ; Maximum number of component instances
ENTITY_SIZE         EQU 8       ; Size of each entity record
COMPONENT_SIZE      EQU 16      ; Size of each component instance

; Entity record structure (8 bytes)
; Offset 0: Active flag (1 byte)
; Offset 1: Component count (1 byte)  
; Offset 2-7: Component indices (6 bytes, max 6 components per entity)

; Component record structure (16 bytes)
; Offset 0: Component type ID (1 byte)
; Offset 1: Entity owner ID (1 byte)
; Offset 2-15: Component data (14 bytes)

;; --- Memory Pools ---
ENTITY_POOL:        DS MAX_ENTITIES * ENTITY_SIZE     ; Entity pool
COMPONENT_POOL:     DS MAX_COMPONENTS * COMPONENT_SIZE ; Component pool

;; --- Free List Management ---
ENTITY_FREE_LIST:   DS MAX_ENTITIES                   ; Free entity indices
COMPONENT_FREE_LIST: DS MAX_COMPONENTS                ; Free component indices
ENTITY_FREE_COUNT:  DB 0                             ; Number of free entities
COMPONENT_FREE_COUNT: DB 0                           ; Number of free components

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Initialize ECS Memory Manager
;; Input: None
;; Output: None
;; Destroys: A, B, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ECS_INIT:
    ; Initialize entity free list
    LD HL, ENTITY_FREE_LIST
    LD B, MAX_ENTITIES
    XOR A
ECS_INIT_ENTITIES:
    LD (HL), A
    INC HL
    INC A
    DJNZ ECS_INIT_ENTITIES
    
    ; Initialize component free list
    LD HL, COMPONENT_FREE_LIST
    LD B, MAX_COMPONENTS
    XOR A
ECS_INIT_COMPONENTS:
    LD (HL), A
    INC HL
    INC A
    DJNZ ECS_INIT_COMPONENTS
    
    ; Set free counts
    LD A, MAX_ENTITIES
    LD (ENTITY_FREE_COUNT), A
    LD A, MAX_COMPONENTS
    LD (COMPONENT_FREE_COUNT), A
    
    ; Clear all pools
    LD HL, ENTITY_POOL
    LD BC, MAX_ENTITIES * ENTITY_SIZE
    XOR A
    CALL MEMSET
    
    LD HL, COMPONENT_POOL
    LD BC, MAX_COMPONENTS * COMPONENT_SIZE
    XOR A
    CALL MEMSET
    
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Allocate a new entity
;; Input: None
;; Output: A = Entity ID (0xFF if failed)
;; Destroys: B, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ALLOCATE_ENTITY:
    LD A, (ENTITY_FREE_COUNT)
    OR A
    JR Z, ALLOCATE_ENTITY_FAIL
    
    ; Get free entity from list
    DEC A
    LD (ENTITY_FREE_COUNT), A
    LD B, A
    LD HL, ENTITY_FREE_LIST
    LD A, B
    ADD A, L
    LD L, A
    JR NC, ALLOCATE_ENTITY_NO_CARRY
    INC H
ALLOCATE_ENTITY_NO_CARRY:
    LD A, (HL)              ; Get entity ID
    
    ; Mark entity as active
    PUSH AF
    LD B, A
    CALL GET_ENTITY_PTR
    LD A, 1                 ; Set active flag
    LD (HL), A
    XOR A                   ; Clear component count
    INC HL
    LD (HL), A
    POP AF
    RET

ALLOCATE_ENTITY_FAIL:
    LD A, 0xFF
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Free an entity
;; Input: A = Entity ID
;; Output: None  
;; Destroys: B, C, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
FREE_ENTITY:
    PUSH AF
    
    ; Remove all components from entity
    CALL REMOVE_ALL_COMPONENTS
    
    ; Mark entity as inactive
    POP AF
    PUSH AF
    LD B, A
    CALL GET_ENTITY_PTR
    XOR A
    LD (HL), A              ; Clear active flag
    
    ; Add entity to free list
    POP AF
    LD B, A
    LD A, (ENTITY_FREE_COUNT)
    LD C, A
    INC A
    LD (ENTITY_FREE_COUNT), A
    
    LD HL, ENTITY_FREE_LIST
    LD A, C
    ADD A, L
    LD L, A
    JR NC, FREE_ENTITY_NO_CARRY
    INC H
FREE_ENTITY_NO_CARRY:
    LD (HL), B              ; Store entity ID in free list
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Get pointer to entity record
;; Input: B = Entity ID
;; Output: HL = Pointer to entity record
;; Destroys: A
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
GET_ENTITY_PTR:
    LD HL, ENTITY_POOL
    LD A, B
    ADD A, A                ; * 2
    ADD A, A                ; * 4  
    ADD A, A                ; * 8 (ENTITY_SIZE)
    ADD A, L
    LD L, A
    JR NC, GET_ENTITY_PTR_NO_CARRY
    INC H
GET_ENTITY_PTR_NO_CARRY:
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Allocate a new component
;; Input: A = Component type ID, B = Entity owner ID
;; Output: A = Component index (0xFF if failed)
;; Destroys: C, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ALLOCATE_COMPONENT:
    PUSH AF
    PUSH BC
    
    LD A, (COMPONENT_FREE_COUNT)
    OR A
    JR Z, ALLOCATE_COMPONENT_FAIL
    
    ; Get free component from list
    DEC A
    LD (COMPONENT_FREE_COUNT), A
    LD C, A
    LD HL, COMPONENT_FREE_LIST
    LD A, C
    ADD A, L
    LD L, A
    JR NC, ALLOCATE_COMPONENT_NO_CARRY
    INC H
ALLOCATE_COMPONENT_NO_CARRY:
    LD A, (HL)              ; Get component index
    PUSH AF                 ; Save component index
    
    ; Initialize component record
    LD C, A                 ; Component index
    CALL GET_COMPONENT_PTR  ; HL = component pointer
    POP BC                  ; B = component index
    POP DE                  ; D = entity owner, E = component type
    PUSH BC                 ; Save component index
    
    LD (HL), E              ; Set component type ID
    INC HL
    LD (HL), D              ; Set entity owner ID
    
    ; Add component to entity's component list
    LD B, D                 ; Entity ID
    CALL GET_ENTITY_PTR
    INC HL                  ; Point to component count
    LD A, (HL)              ; Get current component count
    INC (HL)                ; Increment component count
    INC HL                  ; Point to component list
    ADD A, L
    LD L, A
    JR NC, ALLOCATE_COMPONENT_NO_CARRY2
    INC H
ALLOCATE_COMPONENT_NO_CARRY2:
    POP AF                  ; A = component index
    PUSH AF
    LD (HL), A              ; Store component index in entity
    
    POP AF                  ; Return component index
    POP BC
    RET

ALLOCATE_COMPONENT_FAIL:
    POP BC
    POP AF
    LD A, 0xFF
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Get pointer to component record
;; Input: C = Component index
;; Output: HL = Pointer to component record
;; Destroys: A
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
GET_COMPONENT_PTR:
    LD HL, COMPONENT_POOL
    LD A, C
    ADD A, A                ; * 2
    ADD A, A                ; * 4
    ADD A, A                ; * 8
    ADD A, A                ; * 16 (COMPONENT_SIZE)
    ADD A, L
    LD L, A
    JR NC, GET_COMPONENT_PTR_NO_CARRY
    INC H
GET_COMPONENT_PTR_NO_CARRY:
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Memory set utility
;; Input: HL = destination, BC = count, A = value
;; Output: None
;; Destroys: BC, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MEMSET:
    LD (HL), A
    INC HL
    DEC BC
    LD A, B
    OR C
    JR NZ, MEMSET
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Remove all components from entity
;; Input: A = Entity ID
;; Output: None
;; Destroys: B, C, HL, DE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
REMOVE_ALL_COMPONENTS:
    LD B, A                 ; B = Entity ID
    CALL GET_ENTITY_PTR
    INC HL                  ; Point to component count
    LD C, (HL)              ; C = component count
    XOR A
    LD (HL), A              ; Clear component count
    INC HL                  ; Point to component list
    
REMOVE_COMPONENTS_LOOP:
    LD A, C
    OR A
    RET Z                   ; No more components
    
    LD A, (HL)              ; Get component index
    PUSH HL
    PUSH BC
    CALL FREE_COMPONENT     ; Free the component
    POP BC
    POP HL
    INC HL                  ; Next component in list
    DEC C
    JR REMOVE_COMPONENTS_LOOP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Free a component
;; Input: A = Component index
;; Output: None
;; Destroys: B, HL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
FREE_COMPONENT:
    PUSH AF
    
    ; Add component to free list
    LD B, A
    LD A, (COMPONENT_FREE_COUNT)
    INC A
    LD (COMPONENT_FREE_COUNT), A
    DEC A                   ; A = old free count
    LD HL, COMPONENT_FREE_LIST
    ADD A, L
    LD L, A
    JR NC, FREE_COMPONENT_NO_CARRY
    INC H
FREE_COMPONENT_NO_CARRY:
    LD (HL), B              ; Store component index
    
    ; Clear component data (optional)
    POP AF
    LD C, A
    CALL GET_COMPONENT_PTR
    LD B, COMPONENT_SIZE
    XOR A
FREE_COMPONENT_CLEAR:
    LD (HL), A
    INC HL
    DJNZ FREE_COMPONENT_CLEAR
    
    RET