;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; State Machine Usage Example
;; Generated by MSX Retro Game IDE
;;
;; Simple example showing how to use the state machine
;; system in your MSX games
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

INCLUDE "constants.asm"
INCLUDE "state_machine_system.asm"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Main Program Entry Point
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ORG #4000

    ; ROM header
    DB "AB"
    DW MAIN_PROGRAM

MAIN_PROGRAM:
    ; Initialize MSX system
    DI
    LD SP, #F380
    
    ; Reset interrupt hooks
    LD A, #C9
    LD (HKEY), A
    LD (TIMI), A
    EI
    
    ; Set up graphics mode
    LD A, 2
    CALL CHGMOD
    
    ; Initialize the state machine system
    CALL INIT_STATE_MACHINE
    
    ; Main loop - the state machine handles everything via interrupts
MAIN_LOOP:
    HALT                        ; Wait for V-Blank interrupt
    
    ; You can add non-interrupt code here if needed
    ; For example, handling MSX-DOS calls, disk I/O, etc.
    
    JP MAIN_LOOP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Example: How to Change States from Your Code
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Example: Start a new game
START_NEW_GAME:
    ; Initialize player data
    LD A, 3
    LD (player_lives), A
    
    ; Reset score, level, etc.
    XOR A
    LD (player_score), A
    LD (player_score+1), A
    LD (current_level), A
    
    ; Change to playing state
    LD A, STATE_PLAYING
    CALL CHANGE_GAME_STATE
    RET

; Example: Trigger player death
KILL_PLAYER:
    LD A, STATE_DYING
    CALL CHANGE_GAME_STATE
    RET

; Example: Complete a level
COMPLETE_LEVEL:
    ; Increment level
    LD A, (current_level)
    INC A
    LD (current_level), A
    
    ; Change to zone changing state
    LD A, STATE_CHANGING_ZONE
    CALL CHANGE_GAME_STATE
    RET

; Example: Pause the game
PAUSE_GAME:
    ; Only allow pause from playing state
    CALL GET_CURRENT_STATE
    CP STATE_PLAYING
    RET NZ
    
    LD A, STATE_PAUSED
    CALL CHANGE_GAME_STATE
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Example State-Specific Implementations
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Override the stub functions with your actual implementations
UPDATE_GAME_ENTITIES:
    ; Example: Update player position based on input
    LD A, (input_state)
    LD B, A
    
    ; Move left
    BIT INPUT_BIT_LEFT, B
    JR Z, update_no_left
    LD HL, (player_x)
    DEC HL
    LD (player_x), HL
    
update_no_left:
    ; Move right
    BIT INPUT_BIT_RIGHT, B
    JR Z, update_no_right
    LD HL, (player_x)
    INC HL
    LD (player_x), HL
    
update_no_right:
    ; Move up
    BIT INPUT_BIT_UP, B
    JR Z, update_no_up
    LD HL, (player_y)
    DEC HL
    LD (player_y), HL
    
update_no_up:
    ; Move down
    BIT INPUT_BIT_DOWN, B
    JR Z, update_no_down
    LD HL, (player_y)
    INC HL
    LD (player_y), HL
    
update_no_down:
    RET

UPDATE_SPRITES:
    ; Example: Update sprite 0 with player position
    LD HL, (player_y)
    LD A, L
    LD (SPRATR), A              ; Sprite Y position
    
    LD HL, (player_x)
    LD A, L
    LD (SPRATR+1), A            ; Sprite X position
    
    ; Set sprite pattern and color
    LD A, 0                     ; Pattern 0
    LD (SPRATR+2), A
    LD A, 15                    ; White color
    LD (SPRATR+3), A
    
    RET

READ_INPUT_STATE:
    ; Store previous input
    LD A, (input_state)
    LD (prev_input_state), A
    
    ; Read MSX joystick
    IN A, (0A2H)                ; Read joystick port
    CPL                         ; Invert (MSX joystick is active low)
    AND 3FH                     ; Mask valid bits
    LD (input_state), A
    
    RET

CHECK_PLAYER_STATUS:
    ; Example: Check if player fell off screen
    LD HL, (player_y)
    LD A, H
    OR A
    RET Z                       ; Y is positive
    
    ; Player fell off screen - die
    LD A, STATE_DYING
    CALL CHANGE_GAME_STATE
    RET

DISPLAY_PAUSE_MESSAGE:
    ; Example: Display "PAUSED" at center of screen
    LD HL, #1800 + (12 * 32) + 12  ; Center of screen
    LD DE, pause_text
    LD B, 6                     ; Length of "PAUSED"
    
display_pause_loop:
    LD A, (DE)
    CALL WRTVRM
    INC HL
    INC DE
    DJNZ display_pause_loop
    RET

CLEAR_PAUSE_MESSAGE:
    ; Clear the pause message
    LD HL, #1800 + (12 * 32) + 12  ; Center of screen
    LD A, 32                    ; Space character
    LD B, 6                     ; Length of "PAUSED"
    
clear_pause_loop:
    CALL WRTVRM
    INC HL
    DJNZ clear_pause_loop
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Example: State-Based Behavior
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Call this from your game logic to check current state
HANDLE_COLLISION:
    ; Different collision handling based on state
    CALL GET_CURRENT_STATE
    
    CP STATE_PLAYING
    JR Z, collision_playing
    CP STATE_DYING
    JR Z, collision_dying
    
    ; Default: ignore collision
    RET

collision_playing:
    ; Normal collision - reduce health, play sound, etc.
    LD A, (player_health)
    DEC A
    LD (player_health), A
    OR A
    RET NZ                      ; Still alive
    
    ; Health reached 0 - trigger death
    CALL KILL_PLAYER
    RET

collision_dying:
    ; Already dying - ignore additional collisions
    RET

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Game Data
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

player_x:
    DW 128                      ; Player X position

player_y:
    DW 96                       ; Player Y position

player_score:
    DW 0                        ; Player score

current_level:
    DB 1                        ; Current level

player_health:
    DB 3                        ; Player health

pause_text:
    DB "PAUSED"                 ; Pause message

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; How to Add Custom States
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; To add a new state:
; 1. Add the state constant (e.g., STATE_CUTSCENE EQU 7)
; 2. Update MAX_STATES
; 3. Add the routine address to jump_table
; 4. Implement the routine (e.g., logic_cutscene)

; Example custom state:
STATE_CUTSCENE      EQU 7

; Add to jump_table:
; DEFW logic_cutscene         ; STATE_CUTSCENE (7)

logic_cutscene:
    ; Handle cutscene logic
    ; Check for skip input
    LD A, (input_state)
    BIT INPUT_BIT_FIRE1, A
    JR Z, cutscene_no_skip
    
    ; Skip cutscene
    LD A, STATE_PLAYING
    CALL CHANGE_GAME_STATE
    RET
    
cutscene_no_skip:
    ; Continue cutscene
    ; Check timer for auto-advance
    LD A, (state_timer)
    CP 300                      ; 5 seconds
    RET C
    
    ; Cutscene finished
    LD A, STATE_PLAYING
    CALL CHANGE_GAME_STATE
    RET