/**
 * @fileoverview Professional ECS MSX Project Generators
 * Generates all files for the professional ECS MSX project structure
 */

import { ProjectAnalysis } from './asmTemplateGenerator';
import { MSXProjectConfig } from './msxMainGenerator';

/**
 * Generate professional main.asm with proper structure
 */
export function generateProfessionalMainASM(
  projectName: string,
  analysis: ProjectAnalysis,
  config: MSXProjectConfig
): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ${projectName.toUpperCase()} - Professional MSX ECS Game
;; Generated by MSX Retro Game IDE
;; Target: ${config.targetMSX} | Base: #${config.baseAddress.toString(16).toUpperCase()}
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    .org #${config.baseAddress.toString(16).toUpperCase()}

; ROM Header for cartridge
    db "AB"                     ; ROM signature
    dw INIT_PROGRAM            ; Init address
    dw 0,0,0,0,0               ; Statement, Device, Text, Reserved

; Include system files
    .include "constants.asm"
    .include "macros.asm"

${analysis.hasECS ? `; Include ECS core
    .include "ecs/entity_manager.asm"
    .include "ecs/component_types.asm"
    .include "ecs/system_renderer.asm"
    .include "ecs/system_input.asm"
    .include "ecs/system_physics.asm"
    .include "ecs/system_collision.asm"
` : ''}
; Include core systems
    .include "core/memory.asm"
    .include "core/scheduler.asm"

; Include screen managers
    .include "screens/screen_game.asm"
    .include "screens/screen_menu.asm"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MAIN INITIALIZATION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

INIT_PROGRAM:
    di                          ; Disable interrupts
    
    ; Initialize stack
    ld sp, #F380
    
    ; Clear work RAM
    ld hl, #C000
    ld de, #C001
    ld bc, #3FFF
    ld (hl), 0
    ldir
    
    ; Setup MSX environment
    call INIT_MSX_HARDWARE
    call INIT_MEMORY_POOLS
${analysis.hasECS ? '    call INIT_ECS_SYSTEMS' : ''}
    call INIT_SCHEDULER
    
    ; Load game assets
    call LOAD_GAME_ASSETS
    
    ; Start with menu screen
    ld a, SCREEN_MENU
    call CHANGE_SCREEN
    
    ; Enable interrupts and start main loop
    ei
    jp MAIN_LOOP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MAIN GAME LOOP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

MAIN_LOOP:
    halt                        ; Wait for V-Blank
    call RUN_SCHEDULER          ; Execute current systems
    jp MAIN_LOOP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SYSTEM INITIALIZATION
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

INIT_MSX_HARDWARE:
    ; Set screen mode
    ld a, 2                     ; Screen mode 2
    call CHGMOD
    
    ; Disable sprites initially
    call SPROFF
    
    ; Set up colors
    ld a, 15                    ; White on black
    ld (FORCLR), a
    xor a
    ld (BAKCLR), a
    ld (BDRCLR), a
    call CHGCLR
    
    ret

LOAD_GAME_ASSETS:
${analysis.sprites.length > 0 ? '    call LOAD_SPRITE_PATTERNS' : ''}${analysis.tiles.length > 0 ? '    call LOAD_TILE_PATTERNS' : ''}    call LOAD_COLOR_PALETTES
    ret

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SCREEN MANAGEMENT
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

current_screen: db 0

CHANGE_SCREEN:
    ld (current_screen), a
    
    cp SCREEN_MENU
    jr z, .menu
    cp SCREEN_GAME
    jr z, .game
    ret                         ; Invalid screen
    
.menu:
    call INIT_MENU_SCREEN
    ret
    
.game:
    call INIT_GAME_SCREEN
    ret

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ASSET LOADING STUBS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

${analysis.sprites.length > 0 ? `LOAD_SPRITE_PATTERNS:
    ; Load sprite patterns from assets/sprites/*.bin
    ld hl, SPRITE_PATTERNS_DATA
    ld de, SPRPAT
    ld bc, ${analysis.sprites.length * 32}  ; ${analysis.sprites.length} sprites * 32 bytes each
    ldir
    ret

SPRITE_PATTERNS_DATA:
    .incbin "assets/sprites/all_sprites.bin"
` : ''}
${analysis.tiles.length > 0 ? `LOAD_TILE_PATTERNS:
    ; Load tile patterns from assets/maps/*.bin  
    ld hl, TILE_PATTERNS_DATA
    ld de, PATTERNTBL
    ld bc, ${analysis.tiles.length * 8}     ; ${analysis.tiles.length} tiles * 8 bytes each
    ldir
    ret

TILE_PATTERNS_DATA:
    .incbin "assets/maps/tile_patterns.bin"
` : ''}
LOAD_COLOR_PALETTES:
    ; Load color data
    ret

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SCREEN CONSTANTS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SCREEN_MENU     equ 0
SCREEN_GAME     equ 1
`;
}

/**
 * Generate macros.asm file
 */
export function generateMacrosFile(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MACROS FOR MSX ECS GAME
;; Common macros for VDP, ECS operations, and utilities
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; VDP MACROS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Set VRAM address for writing
.macro SET_VRAM_WRITE addr
    ld a, addr & #FF
    out (#99), a
    ld a, (addr >> 8) | #40
    out (#99), a
.endm

; Set VRAM address for reading
.macro SET_VRAM_READ addr
    ld a, addr & #FF
    out (#99), a
    ld a, (addr >> 8) & #3F
    out (#99), a
.endm

; Write byte to VRAM (assumes address already set)
.macro VRAM_WRITE_BYTE value
    ld a, value
    out (#98), a
.endm

; Copy block to VRAM
.macro COPY_TO_VRAM src, dst, size
    SET_VRAM_WRITE dst
    ld hl, src
    ld bc, size
.copy_loop:
    ld a, (hl)
    out (#98), a
    inc hl
    dec bc
    ld a, b
    or c
    jr nz, .copy_loop
.endm

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS MACROS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

${analysis.hasECS ? `; Create new entity
.macro CREATE_ENTITY result_reg
    call ENTITY_CREATE
    ld result_reg, a            ; Entity ID returned in A
.endm

; Add component to entity
.macro ADD_COMPONENT entity_id, component_type, component_data
    ld a, entity_id
    ld b, component_type
    ld hl, component_data
    call COMPONENT_ADD
.endm

; Get component from entity
.macro GET_COMPONENT entity_id, component_type, result_reg
    ld a, entity_id
    ld b, component_type
    call COMPONENT_GET
    ld result_reg, hl           ; Component data pointer returned in HL
.endm

; Remove component from entity
.macro REMOVE_COMPONENT entity_id, component_type
    ld a, entity_id
    ld b, component_type
    call COMPONENT_REMOVE
.endm
` : ''}
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SPRITE MACROS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

${analysis.hasSprites ? `; Set sprite position and pattern
.macro SET_SPRITE sprite_num, x_pos, y_pos, pattern
    ld a, sprite_num
    ld b, x_pos
    ld c, y_pos
    ld d, pattern
    call SPRITE_SET
.endm

; Hide sprite
.macro HIDE_SPRITE sprite_num
    ld a, sprite_num
    call SPRITE_HIDE
.endm
` : ''}
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; UTILITY MACROS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; 16-bit increment
.macro INC16 reg16
    inc reg16
    jr nz, .skip
    inc reg16+1
.skip:
.endm

; 16-bit decrement
.macro DEC16 reg16
    ld a, reg16
    or reg16+1
    jr z, .skip                 ; Don't decrement if already zero
    ld a, reg16
    sub 1
    ld reg16, a
    jr nc, .skip
    dec reg16+1
.skip:
.endm

; Fast clear memory block
.macro CLEAR_MEM start, size
    ld hl, start
    ld de, start + 1
    ld bc, size - 1
    ld (hl), 0
    ldir
.endm

; Random number (simple LFSR)
.macro RANDOM result_reg
    call GET_RANDOM
    ld result_reg, a
.endm
`;
}

/**
 * Generate ECS Entity Manager
 */
export function generateEntityManagerASM(analysis: ProjectAnalysis): string {
  const maxEntities = Math.max(32, analysis.templates.length * 4);
  
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS ENTITY MANAGER
;; Handles entity creation, destruction, and component assignment
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

MAX_ENTITIES            equ ${maxEntities}
ENTITY_INVALID          equ #FF
COMPONENTS_PER_ENTITY   equ 8              ; Max components per entity

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ENTITY DATA STRUCTURES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Entity pool - each entity has a component mask
entity_pool:
    ds MAX_ENTITIES             ; Component masks (bit field)
    
entity_component_data:
    ds MAX_ENTITIES * COMPONENTS_PER_ENTITY * 2  ; Component data pointers

next_entity_id:         db 1   ; Next available entity ID (0 = invalid)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ENTITY MANAGEMENT FUNCTIONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Create a new entity
; Output: A = entity ID (0 if failed)
ENTITY_CREATE:
    push bc
    push hl
    
    ld b, MAX_ENTITIES
    ld hl, entity_pool
    
.search_loop:
    ld a, (hl)                  ; Check if slot is free
    or a
    jr z, .found_slot           ; Found free slot
    
    inc hl
    djnz .search_loop
    
    ; No free slots
    xor a                       ; Return 0 (invalid ID)
    pop hl
    pop bc
    ret
    
.found_slot:
    ; Calculate entity ID
    ld a, MAX_ENTITIES
    sub b                       ; A = slot index
    inc a                       ; Entity IDs start from 1
    
    ; Mark slot as used
    ld (hl), #01               ; Set initial component mask
    
    ; Clear component data for this entity
    push af
    call ENTITY_CLEAR_COMPONENTS
    pop af
    
    pop hl
    pop bc
    ret

; Destroy an entity
; Input: A = entity ID
ENTITY_DESTROY:
    or a
    ret z                       ; Invalid entity ID
    
    push af
    push hl
    
    ; Clear all components
    call ENTITY_CLEAR_COMPONENTS
    
    ; Mark entity slot as free
    dec a                       ; Convert to 0-based index
    ld hl, entity_pool
    ld d, 0
    ld e, a
    add hl, de
    ld (hl), 0                  ; Mark as free
    
    pop hl
    pop af
    ret

; Clear all components from an entity
; Input: A = entity ID
ENTITY_CLEAR_COMPONENTS:
    or a
    ret z                       ; Invalid entity ID
    
    push bc
    push de
    push hl
    
    ; Calculate component data base address
    dec a                       ; Convert to 0-based
    ld h, 0
    ld l, a
    add hl, hl                  ; * 2
    add hl, hl                  ; * 4  
    add hl, hl                  ; * 8
    add hl, hl                  ; * 16 (COMPONENTS_PER_ENTITY * 2)
    ld de, entity_component_data
    add hl, de
    
    ; Clear component data pointers
    ld b, COMPONENTS_PER_ENTITY * 2
.clear_loop:
    ld (hl), 0
    inc hl
    djnz .clear_loop
    
    pop hl
    pop de
    pop bc
    ret

; Check if entity is valid
; Input: A = entity ID
; Output: Zero flag set if valid
ENTITY_IS_VALID:
    or a
    ret z                       ; ID 0 is invalid
    
    cp MAX_ENTITIES + 1
    ccf                         ; Complement carry (set Z if valid)
    ret

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; COMPONENT MANAGEMENT
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Add component to entity  
; Input: A = entity ID, B = component type, HL = component data
COMPONENT_ADD:
    call ENTITY_IS_VALID
    ret z                       ; Invalid entity
    
    push de
    push bc
    
    ; Get component data slot
    call GET_COMPONENT_SLOT     ; Returns DE = slot address
    
    ; Store component data pointer
    ld (de), l
    inc de
    ld (de), h
    
    ; Set component bit in entity mask
    dec a                       ; Convert to 0-based
    ld hl, entity_pool
    ld d, 0
    ld e, a
    add hl, de
    
    ld a, 1
    rlc b                       ; Rotate component type to get bit position
    jr nc, .no_shift
.shift_loop:
    sla a
    djnz .shift_loop
.no_shift:
    
    or (hl)                     ; Set component bit
    ld (hl), a
    
    pop bc
    pop de
    ret

; Get component from entity
; Input: A = entity ID, B = component type
; Output: HL = component data pointer (0 if not found)
COMPONENT_GET:
    call ENTITY_IS_VALID
    jr z, .not_found            ; Invalid entity
    
    ; Check if entity has this component
    push af
    push bc
    dec a                       ; Convert to 0-based
    ld hl, entity_pool
    ld d, 0
    ld e, a
    add hl, de
    
    ld a, 1
    rlc b
    jr nc, .no_shift2
.shift_loop2:
    sla a
    djnz .shift_loop2
.no_shift2:
    
    and (hl)                    ; Check component bit
    pop bc
    pop af
    jr z, .not_found            ; Component not present
    
    ; Get component data
    call GET_COMPONENT_SLOT
    ex de, hl
    ld l, (hl)
    inc hl
    ld h, (hl)                  ; HL = component data pointer
    ret
    
.not_found:
    ld hl, 0
    ret

; Helper: Get component slot address
; Input: A = entity ID, B = component type
; Output: DE = slot address
GET_COMPONENT_SLOT:
    dec a                       ; Convert to 0-based
    ld h, 0
    ld l, a
    add hl, hl                  ; * 2
    add hl, hl                  ; * 4
    add hl, hl                  ; * 8
    add hl, hl                  ; * 16
    
    ; Add component type offset
    ld d, 0
    ld e, b
    sla e                       ; * 2 (each component slot is 2 bytes)
    add hl, de
    
    ld de, entity_component_data
    add hl, de
    ex de, hl                   ; DE = final slot address
    ret
`;
}

/**
 * Generate Component Types definitions
 */
export function generateComponentTypesASM(analysis: ProjectAnalysis): string {
  let componentTypes = `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS COMPONENT TYPE DEFINITIONS
;; Defines all component types and their data structures
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Component type IDs
COMP_POSITION       equ 0
COMP_SPRITE         equ 1
COMP_INPUT          equ 2
COMP_PHYSICS        equ 3
COMP_COLLISION      equ 4`;

  // Add custom components based on analysis
  let compIndex = 5;
  analysis.components.forEach(comp => {
    const sanitizedName = comp.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    componentTypes += `\nCOMP_${sanitizedName}        equ ${compIndex}`;
    compIndex++;
  });

  componentTypes += `

MAX_COMPONENT_TYPES equ ${compIndex}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; COMPONENT DATA STRUCTURES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Position Component (4 bytes)
; +0: X position (16-bit)
; +2: Y position (16-bit)
POSITION_SIZE       equ 4

position_pool:      ds MAX_ENTITIES * POSITION_SIZE
position_free_list: ds MAX_ENTITIES

; Sprite Component (6 bytes)  
; +0: Sprite ID (8-bit)
; +1: Animation frame (8-bit)
; +2: Animation speed (8-bit)
; +3: Animation counter (8-bit)
; +4: Flags (8-bit) - visible, flipped, etc.
; +5: Color (8-bit)
SPRITE_SIZE         equ 6

sprite_pool:        ds MAX_ENTITIES * SPRITE_SIZE
sprite_free_list:   ds MAX_ENTITIES

; Input Component (2 bytes)
; +0: Current input state (8-bit)
; +1: Previous input state (8-bit)  
INPUT_SIZE          equ 2

input_pool:         ds MAX_ENTITIES * INPUT_SIZE
input_free_list:    ds MAX_ENTITIES

; Physics Component (8 bytes)
; +0: Velocity X (16-bit, signed)
; +2: Velocity Y (16-bit, signed)  
; +4: Acceleration X (16-bit, signed)
; +6: Acceleration Y (16-bit, signed)
PHYSICS_SIZE        equ 8

physics_pool:       ds MAX_ENTITIES * PHYSICS_SIZE
physics_free_list:  ds MAX_ENTITIES

; Collision Component (8 bytes)
; +0: Bounding box left (8-bit)
; +1: Bounding box top (8-bit)
; +2: Bounding box right (8-bit)  
; +3: Bounding box bottom (8-bit)
; +4: Collision layer (8-bit)
; +5: Collision mask (8-bit)
; +6: Flags (8-bit)
; +7: Reserved (8-bit)
COLLISION_SIZE      equ 8

collision_pool:     ds MAX_ENTITIES * COLLISION_SIZE
collision_free_list: ds MAX_ENTITIES

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; COMPONENT ALLOCATION FUNCTIONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Allocate a component from the appropriate pool
; Input: B = component type
; Output: HL = pointer to component data (0 if failed)
COMPONENT_ALLOC:
    ld a, b
    cp COMP_POSITION
    jr z, .alloc_position
    cp COMP_SPRITE  
    jr z, .alloc_sprite
    cp COMP_INPUT
    jr z, .alloc_input
    cp COMP_PHYSICS
    jr z, .alloc_physics
    cp COMP_COLLISION
    jr z, .alloc_collision
    
    ; Unknown component type
    ld hl, 0
    ret
    
.alloc_position:
    ld hl, position_pool
    ld de, position_free_list
    ld bc, POSITION_SIZE
    jr .do_alloc
    
.alloc_sprite:
    ld hl, sprite_pool
    ld de, sprite_free_list
    ld bc, SPRITE_SIZE
    jr .do_alloc
    
.alloc_input:
    ld hl, input_pool
    ld de, input_free_list
    ld bc, INPUT_SIZE
    jr .do_alloc
    
.alloc_physics:
    ld hl, physics_pool
    ld de, physics_free_list
    ld bc, PHYSICS_SIZE
    jr .do_alloc
    
.alloc_collision:
    ld hl, collision_pool
    ld de, collision_free_list
    ld bc, COLLISION_SIZE
    
.do_alloc:
    ; Find free slot in the free list
    ex de, hl                   ; DE = pool, HL = free list
    push bc
    ld b, MAX_ENTITIES
    
.find_free:
    ld a, (hl)
    or a
    jr z, .found_free_slot
    inc hl
    djnz .find_free
    
    ; No free slots
    pop bc
    ld hl, 0
    ret
    
.found_free_slot:
    ; Mark slot as used
    ld (hl), #FF
    
    ; Calculate pool address
    ld a, MAX_ENTITIES
    sub b                       ; A = slot index
    pop bc                      ; BC = component size
    
    ld h, 0
    ld l, a
    push de                     ; Save pool base
    ld d, h
    ld e, l
    
    ; Multiply by component size
.mult_loop:
    add hl, de
    dec c
    jr nz, .mult_loop
    
    pop de                      ; DE = pool base
    add hl, de                  ; HL = final component address
    ret
`;

  return componentTypes;
}

/**
 * Generate other ECS systems (stubs for now)
 */
export function generateRendererSystemASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS RENDERER SYSTEM
;; Renders entities with Sprite + Position components
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Run the renderer system
SYSTEM_RENDERER_UPDATE:
    ; TODO: Iterate through entities with COMP_SPRITE + COMP_POSITION
    ; Update sprite positions on screen
    ret
`;
}

export function generateInputSystemASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS INPUT SYSTEM  
;; Updates Input components with current controller state
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Run the input system
SYSTEM_INPUT_UPDATE:
    ; TODO: Read joystick/keyboard and update Input components
    ret
`;
}

export function generatePhysicsSystemASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS PHYSICS SYSTEM
;; Applies velocity and acceleration to Position components
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Run the physics system
SYSTEM_PHYSICS_UPDATE:
    ; TODO: Update positions based on Physics components
    ret
`;
}

export function generateCollisionSystemASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ECS COLLISION SYSTEM
;; Detects collisions between entities with Collision components
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Run the collision system
SYSTEM_COLLISION_UPDATE:
    ; TODO: Check collisions between entities
    ret
`;
}

/**
 * Generate Memory Manager
 */
export function generateMemoryManagerASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MEMORY POOL MANAGER
;; Manages dynamic memory allocation for game objects
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Memory pool constants
POOL_BLOCK_SIZE     equ 16              ; Size of each memory block
POOL_NUM_BLOCKS     equ 64              ; Number of blocks in pool
POOL_TOTAL_SIZE     equ POOL_BLOCK_SIZE * POOL_NUM_BLOCKS

; Memory pool data
memory_pool:        ds POOL_TOTAL_SIZE
memory_free_list:   ds POOL_NUM_BLOCKS

; Initialize memory pools
INIT_MEMORY_POOLS:
    ; Initialize free list - all blocks available
    ld hl, memory_free_list
    ld b, POOL_NUM_BLOCKS
    xor a                       ; 0 = free
    
.init_loop:
    ld (hl), a
    inc hl
    djnz .init_loop
    
    ret

; Allocate a memory block
; Output: HL = pointer to block (0 if failed)
MEMORY_ALLOC:
    push bc
    push de
    
    ; Find free block
    ld hl, memory_free_list
    ld b, POOL_NUM_BLOCKS
    
.search_loop:
    ld a, (hl)
    or a
    jr z, .found_free           ; Found free block
    
    inc hl
    djnz .search_loop
    
    ; No free blocks
    ld hl, 0
    pop de
    pop bc
    ret
    
.found_free:
    ; Mark block as used
    ld (hl), #FF
    
    ; Calculate block address
    ld a, POOL_NUM_BLOCKS
    sub b                       ; A = block index
    
    ld h, 0
    ld l, a
    add hl, hl                  ; * 2
    add hl, hl                  ; * 4
    add hl, hl                  ; * 8
    add hl, hl                  ; * 16 (POOL_BLOCK_SIZE)
    
    ld de, memory_pool
    add hl, de                  ; HL = block address
    
    pop de
    pop bc
    ret

; Free a memory block
; Input: HL = pointer to block
MEMORY_FREE:
    push bc
    push de
    push hl
    
    ; Calculate block index
    ld de, memory_pool
    or a
    sbc hl, de                  ; HL = offset from pool start
    
    ; Divide by block size (16)
    srl h
    rr l
    srl h  
    rr l
    srl h
    rr l
    srl h
    rr l                        ; HL = block index
    
    ; Mark as free
    ld de, memory_free_list
    add hl, de
    ld (hl), 0                  ; 0 = free
    
    pop hl
    pop de
    pop bc
    ret
`;
}

/**
 * Generate Scheduler
 */
export function generateSchedulerASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SYSTEM SCHEDULER
;; Controls execution order and timing of ECS systems
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; System execution flags
system_flags:       db 0

; System flag bits
SYSTEM_INPUT        equ 0
SYSTEM_PHYSICS      equ 1  
SYSTEM_COLLISION    equ 2
SYSTEM_RENDERER     equ 3

; Initialize scheduler
INIT_SCHEDULER:
    ; Enable all systems by default
    ld a, #0F                   ; Enable first 4 systems
    ld (system_flags), a
    ret

; Run enabled systems in order
RUN_SCHEDULER:
    ld a, (system_flags)
    
    ; Check and run input system
    bit SYSTEM_INPUT, a
    call nz, SYSTEM_INPUT_UPDATE
    
    ; Check and run physics system  
    bit SYSTEM_PHYSICS, a
    call nz, SYSTEM_PHYSICS_UPDATE
    
    ; Check and run collision system
    bit SYSTEM_COLLISION, a
    call nz, SYSTEM_COLLISION_UPDATE
    
    ; Check and run renderer system
    bit SYSTEM_RENDERER, a
    call nz, SYSTEM_RENDERER_UPDATE
    
    ret

; Enable a system
; Input: B = system flag bit
ENABLE_SYSTEM:
    ld a, 1
    rlc b
    jr nc, .no_shift
.shift_loop:
    sla a
    djnz .shift_loop
.no_shift:
    
    ld hl, system_flags
    or (hl)
    ld (hl), a
    ret

; Disable a system  
; Input: B = system flag bit
DISABLE_SYSTEM:
    ld a, 1
    rlc b
    jr nc, .no_shift2
.shift_loop2:
    sla a
    djnz .shift_loop2
.no_shift2:
    
    cpl                         ; Invert bits
    ld hl, system_flags
    and (hl)
    ld (hl), a
    ret
`;
}

/**
 * Generate Screen files
 */
export function generateGameScreenASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; GAME SCREEN MANAGER
;; Initializes and manages the main game screen
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Initialize game screen
INIT_GAME_SCREEN:
    call CLS
    
    ; Load level entities from CSV data
    call LOAD_LEVEL_ENTITIES
    
    ; Setup game-specific systems
    ld b, SYSTEM_INPUT
    call ENABLE_SYSTEM
    ld b, SYSTEM_PHYSICS  
    call ENABLE_SYSTEM
    ld b, SYSTEM_COLLISION
    call ENABLE_SYSTEM
    ld b, SYSTEM_RENDERER
    call ENABLE_SYSTEM
    
    ret

; Load entities for current level
LOAD_LEVEL_ENTITIES:
${analysis.templates.length > 0 ? `    ; Create player entity
    CREATE_ENTITY a             ; A = player entity ID
    
    ; Add Position component
    ld hl, player_start_pos
    ADD_COMPONENT a, COMP_POSITION, hl
    
    ; Add Sprite component
    ld hl, player_sprite_data
    ADD_COMPONENT a, COMP_SPRITE, hl
    
    ; Add Input component  
    ld hl, player_input_data
    ADD_COMPONENT a, COMP_INPUT, hl
    
    ; TODO: Load other entities from level data
` : '    ; No entity templates defined'}    ret

; Player initial data
player_start_pos:   dw 128, 100        ; X, Y position
player_sprite_data: db 0, 0, 4, 0, #01, 15  ; sprite_id, frame, speed, counter, flags, color
player_input_data:  db 0, 0            ; current, previous
`;
}

export function generateMenuScreenASM(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MENU SCREEN MANAGER  
;; Handles main menu display and navigation
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Menu state
menu_cursor:        db 0
menu_max_options:   equ 3

; Initialize menu screen
INIT_MENU_SCREEN:
    call CLS
    
    ; Disable game systems, enable only input and renderer
    ld b, SYSTEM_PHYSICS
    call DISABLE_SYSTEM
    ld b, SYSTEM_COLLISION
    call DISABLE_SYSTEM
    
    ld b, SYSTEM_INPUT
    call ENABLE_SYSTEM
    ld b, SYSTEM_RENDERER
    call ENABLE_SYSTEM
    
    ; Display menu text
    call DISPLAY_MENU_TEXT
    
    ret

DISPLAY_MENU_TEXT:
    ; TODO: Display menu options
    ret
`;
}

/**
 * Generate additional files (stubs for brevity)
 */
export function generateEntitiesCSV(analysis: ProjectAnalysis): string {
  return `# Level 1 Entity Definitions
# Format: entity_type,x,y,sprite_id,additional_data
player,128,100,0,
enemy_slime,64,120,1,patrol_left
enemy_slime,192,120,1,patrol_right
pickup_coin,100,80,2,
pickup_coin,156,80,2,
`;
}

export function generateGlassHelpersInc(): string {
  return `; Glass Assembler Helper Definitions
; Common equates and macros for Glass

; BIOS addresses
CHGMOD  .equ #005F
CLS     .equ #00C3
CHPUT   .equ #00A2
GTSTCK  .equ #00D5
GTTRIG  .equ #00D8
SPROFF  .equ #0069

; MSX system variables
FORCLR  .equ #F3E9
BAKCLR  .equ #F3EA
BDRCLR  .equ #F3EB

; VRAM addresses (Screen mode 2)
NAMETBL  .equ #1800
PATTERNTBL .equ #0000
COLORTBL   .equ #2000
SPRATR     .equ #1B00
SPRPAT     .equ #3800
`;
}

export function generatePNG2MSXTool(): string {
  return `#!/usr/bin/env python3
"""
PNG to MSX Sprite Converter
Converts PNG files to MSX sprite format (.bin)
Usage: python png2msx.py input.png output.bin
"""

import sys
from PIL import Image

def convert_png_to_msx(png_file, bin_file):
    # Load PNG
    img = Image.open(png_file)
    img = img.convert('RGB')
    
    # Ensure 8x8 size
    if img.size != (8, 8):
        img = img.resize((8, 8))
    
    # Convert to MSX format (simplified)
    sprite_data = []
    for y in range(8):
        byte = 0
        for x in range(8):
            r, g, b = img.getpixel((x, y))
            # Simple threshold - improve this for real projects
            if r + g + b > 384:  # White-ish
                byte |= (1 << (7 - x))
        sprite_data.append(byte)
    
    # Write binary file
    with open(bin_file, 'wb') as f:
        f.write(bytes(sprite_data))
    
    print(f"Converted {png_file} to {bin_file}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python png2msx.py input.png output.bin")
        sys.exit(1)
    
    convert_png_to_msx(sys.argv[1], sys.argv[2])
`;
}

export function generateCSVParserTool(): string {
  return `#!/usr/bin/env python3
"""
CSV Entity Parser
Converts entity CSV files to ASM data structures
Usage: python csv_entities_parser.py entities.csv output.asm
"""

import sys
import csv

def parse_entities_csv(csv_file, asm_file):
    entities = []
    
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row['entity_type'].startswith('#'):
                continue  # Skip comments
            entities.append(row)
    
    # Generate ASM code
    with open(asm_file, 'w') as f:
        f.write("; Generated entity data from " + csv_file + "\\n")
        f.write("LEVEL_ENTITY_COUNT equ " + str(len(entities)) + "\\n\\n")
        
        f.write("level_entity_data:\\n")
        for i, entity in enumerate(entities):
            f.write(f"    ; Entity {i}: {entity['entity_type']}\\n")
            f.write(f"    db '{entity['entity_type']}', {entity['x']}, {entity['y']}, {entity['sprite_id']}\\n")
        f.write("\\n")
    
    print(f"Generated {len(entities)} entities in {asm_file}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python csv_entities_parser.py entities.csv output.asm")
        sys.exit(1)
    
    parse_entities_csv(sys.argv[1], sys.argv[2])
`;
}

export function generateECSDesignDoc(analysis: ProjectAnalysis): string {
  return `# ECS Design for ${analysis.projectName}

## Architecture Overview

This MSX game uses an Entity-Component-System (ECS) architecture implemented in Z80 assembly.

### Components

- **Position**: X/Y coordinates (16-bit each)
- **Sprite**: Visual representation and animation
- **Input**: Controller input state
- **Physics**: Velocity and acceleration
- **Collision**: Bounding boxes and collision detection

### Systems

- **Input System**: Reads controller input and updates Input components
- **Physics System**: Applies velocity/acceleration to Position components  
- **Collision System**: Detects entity collisions
- **Renderer System**: Draws sprites based on Position + Sprite components

### Memory Layout

Each entity has a component mask (bitmask) indicating which components it has.
Component data is stored in separate pools for cache efficiency.

### Entity Creation Example

\`\`\`asm
CREATE_ENTITY a                 ; Create entity, ID in A
ld hl, player_pos_data
ADD_COMPONENT a, COMP_POSITION, hl
ld hl, player_sprite_data  
ADD_COMPONENT a, COMP_SPRITE, hl
\`\`\`

## Performance Notes

- Maximum ${Math.max(32, analysis.templates.length * 4)} entities
- Component data stored in pools for memory efficiency
- System execution controlled by scheduler
- V-Blank synchronized updates
`;
}

export function generateMemoryLayoutDoc(analysis: ProjectAnalysis): string {
  return `# Memory Layout for ${analysis.projectName}

## MSX Memory Map

\`\`\`
#0000 - #7FFF  ROM area (cartridge)
#8000 - #BFFF  Game code and data  
#C000 - #FFFF  RAM area
\`\`\`

## Game Memory Usage

### #C000 - #C3FF: Entity System (1024 bytes)
- Entity pool: 64 bytes (entity component masks)
- Component data: 960 bytes (component pointers and data)

### #C400 - #C7FF: Memory Pools (1024 bytes)  
- Dynamic allocation pool: 64 blocks × 16 bytes each

### #C800 - #CBFF: Component Data Pools (1024 bytes)
- Position pool: ${Math.max(32, analysis.templates.length * 4)} × 4 bytes
- Sprite pool: ${Math.max(32, analysis.templates.length * 4)} × 6 bytes  
- Input pool: ${Math.max(32, analysis.templates.length * 4)} × 2 bytes
- Physics pool: ${Math.max(32, analysis.templates.length * 4)} × 8 bytes
- Collision pool: ${Math.max(32, analysis.templates.length * 4)} × 8 bytes

### #CC00 - #CFFF: Game Variables (1024 bytes)
- System flags, timers, game state
- Sprite attribute buffer
- Temporary calculation space

### VRAM Layout (Screen Mode 2)
- #0000-#17FF: Pattern Table (6144 bytes)
- #1800-#1AFF: Name Table (768 bytes)  
- #1B00-#1B7F: Sprite Attribute Table (128 bytes)
- #2000-#37FF: Color Table (6144 bytes)
- #3800-#3FFF: Sprite Pattern Table (2048 bytes)

## Stack Usage
- Stack pointer starts at #F380
- Maximum depth: ~100 bytes during system updates
`;
}

export function generateGlassConfig(projectName: string): string {
  return `# Glass Assembler Configuration
# Project: ${projectName}

[assembler]
case_sensitive = true
optimize = true
list_file = true
symbol_file = true

[output]
format = rom
start_address = 0x8000

[paths]
include_dirs = include/
source_dirs = src/

[warnings]  
unused_labels = true
undefined_symbols = error
`;
}

export function generateProfessionalMakefile(projectName: string, analysis: ProjectAnalysis): string {
  const romName = projectName.toLowerCase();
  
  // Create makefile using template literal with proper escaping
  const makefile = [
    `# Professional Makefile for ${projectName}`,
    `# MSX ECS Game Build System`,
    ``,
    `# Tools`,
    `ASM = glass`,
    `PYTHON = python3`,
    `RM = rm -f`,
    `MKDIR = mkdir -p`,
    ``,
    `# Directories`,
    `SRC_DIR = src`,
    `ASSETS_DIR = assets`,
    `BUILD_DIR = build`,
    `TOOLS_DIR = tools`,
    `INCLUDE_DIR = include`,
    ``,
    `# Files`,
    `MAIN_SRC = $$(SRC_DIR)/main.asm`,
    `ROM_OUTPUT = $$(BUILD_DIR)/${romName}.rom`,
    `SYMBOLS_OUTPUT = $$(BUILD_DIR)/symbols.txt`,
    `LISTING_OUTPUT = $$(BUILD_DIR)/listing.txt`,
    ``,
    `# Glass assembler flags`,
    `ASMFLAGS = --rom --sym $$(SYMBOLS_OUTPUT) --list $$(LISTING_OUTPUT)`,
    ``,
    `# Default target`,
    `all: $$(ROM_OUTPUT)`,
    ``,
    `# Create build directory`,
    `$$(BUILD_DIR):`,
    `\t$$(MKDIR) $$(BUILD_DIR)`,
    ``,
    `# Main ROM build`,
    `$$(ROM_OUTPUT): $$(MAIN_SRC) $$(BUILD_DIR)`,
    `\t$$(ASM) $$(ASMFLAGS) $$(MAIN_SRC) $$(ROM_OUTPUT)`,
    ``,
    `# Convert PNG sprites (manual process)`,
    `sprites:`,
    `\t@echo "Converting PNG sprites to MSX format..."`,
    `\t@cd $$(ASSETS_DIR)/sprites && for png in *.png; do \\`,
    `\t\tif [ -f "$$$$png" ]; then \\`,
    `\t\t\t$$(PYTHON) ../../$$(TOOLS_DIR)/png2msx.py "$$$$png" "$$$$\{png%.*\}.bin"; \\`,
    `\t\tfi; \\`,
    `\tdone`,
    ``,
    `# Convert entity CSV to ASM data`,
    `entities: $$(SRC_DIR)/level_entities.asm`,
    ``,
    `$$(SRC_DIR)/level_entities.asm: $$(ASSETS_DIR)/maps/level1_entities.csv`,
    `\t$$(PYTHON) $$(TOOLS_DIR)/csv_entities_parser.py $$< $$@`,
    ``,
    `# Clean build artifacts`,
    `clean:`,
    `\t$$(RM) $$(BUILD_DIR)/*`,
    `\t$$(RM) $$(ASSETS_DIR)/sprites/*.bin`,
    ``,
    `# Development targets`,
    `run: $$(ROM_OUTPUT)`,
    `\t@echo "ROM ready: $$(ROM_OUTPUT)"`,
    `\t@echo "Load in your favorite MSX emulator"`,
    ``,
    `debug: $$(ROM_OUTPUT)`,
    `\t@echo "Symbols file: $$(SYMBOLS_OUTPUT)"`,
    `\t@echo "Listing file: $$(LISTING_OUTPUT)"`,
    ``,
    `# Help target`,
    `help:`,
    `\t@echo "Available targets:"`,
    `\t@echo "  all     - Build ROM (default)"`,
    `\t@echo "  sprites - Convert PNG sprites to BIN"`,
    `\t@echo "  entities- Convert CSV entities to ASM"`,
    `\t@echo "  clean   - Remove build artifacts"`,
    `\t@echo "  run     - Build and show run instructions"`,
    `\t@echo "  debug   - Build with debug info"`,
    `\t@echo "  help    - Show this help"`,
    ``,
    `.PHONY: all sprites entities clean run debug help`
  ].join('\n');
  
  return makefile;
}

export function generateREADME(projectName: string, analysis: ProjectAnalysis): string {
  return `# ${projectName} - MSX ECS Game

A professional MSX game built with Entity-Component-System architecture in Z80 assembly.

## 🎮 Game Features

- **ECS Architecture**: Modular, data-oriented design
${analysis.hasSprites ? '- **Sprite System**: Animated sprites with collision detection' : ''}${analysis.hasCollisions ? '- **Physics**: Gravity, velocity, and collision systems' : ''}${analysis.hasMenuSystem ? '- **Menu System**: Professional menu interface' : ''}${analysis.screenMaps.length > 0 ? '- **Level System**: Multi-screen game world' : ''}

## 🏗️ Project Structure

\`\`\`
${projectName.toLowerCase()}_ecs_msx/
├── src/                     # Source code
│   ├── main.asm            # Main entry point
│   ├── constants.asm       # System constants
│   ├── macros.asm          # Useful macros
│   ├── ecs/                # ECS system modules
│   ├── core/               # Core systems (memory, scheduler)
│   └── screens/            # Screen managers
├── assets/                 # Game assets  
│   ├── sprites/            # Sprite PNG files (auto-converted)
│   ├── maps/               # Level entity definitions
│   └── sfx/                # Sound effects
├── include/                # Include files
├── tools/                  # Asset conversion tools
├── docs/                   # Documentation
└── build/                  # Output directory
\`\`\`

## 🚀 Building

### Prerequisites
- Glass Z80 Assembler
- Python 3.x (for asset conversion)
- Make (optional)

### Quick Build
\`\`\`bash
make all
\`\`\`

### Manual Build  
\`\`\`bash
# Convert assets
python tools/png2msx.py assets/sprites/player.png assets/sprites/player.bin

# Assemble ROM
glass --rom --sym build/symbols.txt src/main.asm build/${projectName.toLowerCase()}.rom
\`\`\`

## 🎯 ECS Architecture

### Components
- **Position**: Entity location (X, Y)
- **Sprite**: Visual representation and animation
- **Input**: Controller input processing
- **Physics**: Movement and collision physics
- **Collision**: Bounding box collision detection

### Systems  
- **Input System**: Reads joystick/keyboard
- **Physics System**: Updates positions based on velocity
- **Collision System**: Detects entity interactions
- **Renderer System**: Draws sprites to screen

### Adding New Components

1. Define component type in \`src/ecs/component_types.asm\`
2. Add component pool and allocation functions
3. Create system to process the component
4. Register system in scheduler

## 📝 Asset Pipeline

### Sprites
1. Create 8×8 PNG files in \`assets/sprites/\`
2. Run \`make\` to auto-convert to MSX format
3. Reference in entity definitions

### Entities
1. Edit \`assets/maps/level1_entities.csv\`
2. Define entity types, positions, and properties
3. Build system converts to ASM data

## 🎨 Customization

### Adding New Entity Types
1. Define in CSV: \`new_entity,x,y,sprite_id,data\`
2. Add creation code in \`src/screens/screen_game.asm\`
3. Assign appropriate components

### Custom Systems
1. Create system file: \`src/ecs/system_custom.asm\`
2. Add update function following ECS patterns  
3. Register in \`src/core/scheduler.asm\`

## 📊 Memory Usage

- **Entities**: Up to ${Math.max(32, analysis.templates.length * 4)} simultaneous
- **Components**: Pool-based allocation
- **RAM Usage**: ~4KB for ECS system
- **ROM Size**: Varies with assets

## 🐛 Debugging

- Build with \`make debug\` for symbol files
- Use \`build/symbols.txt\` with debugger
- Check \`build/listing.txt\` for assembly output

## 📚 Documentation

- \`docs/ecs_design.md\` - ECS architecture details
- \`docs/memory_layout.txt\` - Memory organization
- Source comments explain system interactions

## 🤝 Contributing

1. Follow existing code style
2. Document new systems
3. Update this README for new features
4. Test on real MSX hardware when possible

## 📄 License

[Add your license here]

---

Generated by MSX Retro Game IDE - Professional ECS Template
`;
}

// ============================================================================
// HOOK SYSTEM GENERATORS
// ============================================================================

/**
 * Generate Hook System Core - The main dispatcher that manages dynamic system loading
 */
export function generateHookCore(): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; HOOK SYSTEM CORE - Dynamic System Dispatcher
;; Loads and executes systems on demand
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Hook system variables
hook_system_table:      dw 0            ; Pointer to current system table
hook_current_system:    db 0            ; Current active system ID

; System execution states
HOOK_STATE_INIT         equ 0            ; System initialization
HOOK_STATE_UPDATE       equ 1            ; System update/logic
HOOK_STATE_RENDER       equ 2            ; System rendering
HOOK_STATE_CLEANUP      equ 3            ; System cleanup

; ============================================================================
; INIT_HOOK_SYSTEM - Initialize the Hook dispatcher
; ============================================================================
INIT_HOOK_SYSTEM:
    ; Clear system state
    xor a
    ld (hook_current_system), a
    
    ; Setup system table pointer
    ld hl, hook_systems_table
    ld (hook_system_table), hl
    
    ; Initialize all systems to dormant state
    call HOOK_INIT_ALL_SYSTEMS
    
    ret

; ============================================================================
; HOOK_ACTIVATE_SYSTEM - Activate a specific system
; Input: A = System ID to activate
; ============================================================================
HOOK_ACTIVATE_SYSTEM:
    ; Store new system ID
    ld (hook_current_system), a
    
    ; Get system table entry
    call HOOK_GET_SYSTEM_ENTRY
    ret c                           ; Return if invalid system
    
    ; Call system initialization
    ld de, HOOK_STATE_INIT
    call HOOK_CALL_SYSTEM_FUNCTION
    
    ret

; ============================================================================
; HOOK_EXECUTE_CURRENT_SYSTEM - Execute the currently active system
; ============================================================================
HOOK_EXECUTE_CURRENT_SYSTEM:
    ; Get current system
    ld a, (hook_current_system)
    call HOOK_GET_SYSTEM_ENTRY
    ret c                           ; Return if no active system
    
    ; Execute system update
    ld de, HOOK_STATE_UPDATE
    call HOOK_CALL_SYSTEM_FUNCTION
    
    ; Execute system render
    ld de, HOOK_STATE_RENDER
    call HOOK_CALL_SYSTEM_FUNCTION
    
    ret

; ============================================================================
; HOOK_CHECK_SYSTEM_CHANGE - Check if system needs to change
; ============================================================================
HOOK_CHECK_SYSTEM_CHANGE:
    ; This is called by each system to request transitions
    ; Systems set transition flags that are checked here
    
    ; Check menu system transition
    ld a, (menu_transition_flag)
    or a
    jr z, .check_game_transition
    
    ; Transition to game
    xor a
    ld (menu_transition_flag), a
    ld a, HOOK_GAME_SYSTEM
    call HOOK_ACTIVATE_SYSTEM
    ret
    
.check_game_transition:
    ; Check game system transition
    ld a, (game_transition_flag)
    or a
    ret z
    
    ; Transition to menu
    xor a
    ld (game_transition_flag), a
    ld a, HOOK_MENU_SYSTEM
    call HOOK_ACTIVATE_SYSTEM
    ret

; ============================================================================
; HOOK_GET_SYSTEM_ENTRY - Get system table entry for given ID
; Input: A = System ID
; Output: HL = System table entry address, Carry = Error flag
; ============================================================================
HOOK_GET_SYSTEM_ENTRY:
    ; Validate system ID
    cp HOOK_MAX_SYSTEMS
    jr nc, .invalid_system
    
    ; Calculate table entry (4 bytes per entry)
    ld hl, (hook_system_table)
    ld b, a
    ld de, 8                        ; 8 bytes per system entry
    
.calc_offset:
    ld a, b
    or a
    jr z, .found_entry
    add hl, de
    dec b
    jr .calc_offset
    
.found_entry:
    or a                            ; Clear carry flag
    ret
    
.invalid_system:
    scf                             ; Set carry flag for error
    ret

; ============================================================================
; HOOK_CALL_SYSTEM_FUNCTION - Call specific system function
; Input: HL = System entry, DE = Function type (HOOK_STATE_*)
; ============================================================================
HOOK_CALL_SYSTEM_FUNCTION:
    ; Calculate function address offset
    ld a, e                         ; Get state type
    add a, a                        ; * 2 (word addresses)
    ld c, a
    ld b, 0
    add hl, bc                      ; HL = entry + offset
    
    ; Get function address and call it
    ld a, (hl)
    inc hl
    ld h, (hl)
    ld l, a
    
    ; Check for null pointer
    ld a, h
    or l
    ret z                           ; Return if null function
    
    ; Call the function
    jp (hl)

; ============================================================================
; SYSTEM TABLE - Function pointers for each system
; Format: INIT_ADDR, UPDATE_ADDR, RENDER_ADDR, CLEANUP_ADDR (8 bytes per system)
; ============================================================================
hook_systems_table:
    ; HOOK_MENU_SYSTEM (0)
    dw MENU_INIT, MENU_UPDATE, MENU_RENDER, MENU_CLEANUP
    
    ; HOOK_GAME_SYSTEM (1) 
    dw GAME_INIT, GAME_UPDATE, GAME_RENDER, GAME_CLEANUP
    
    ; HOOK_PAUSE_SYSTEM (2)
    dw PAUSE_INIT, PAUSE_UPDATE, PAUSE_RENDER, PAUSE_CLEANUP
    
    ; HOOK_TRANSITION_SYS (3)
    dw TRANS_INIT, TRANS_UPDATE, TRANS_RENDER, TRANS_CLEANUP

HOOK_MAX_SYSTEMS        equ 4

; System transition flags
menu_transition_flag:   db 0
game_transition_flag:   db 0
pause_transition_flag:  db 0

; ============================================================================
; HOOK SYSTEM INITIALIZATION HELPERS
; ============================================================================
HOOK_INIT_ALL_SYSTEMS:
    ; Initialize all systems to dormant state
    ; This is called once at startup
    ret

; MSX Hardware initialization through Hook
HOOK_INIT_MSX_HARDWARE:
    ; Set screen mode
    ld a, 2                         ; Screen mode 2
    call CHGMOD
    
    ; Disable sprites initially
    call SPROFF
    
    ; Set up colors
    ld a, 15                        ; White on black
    ld (FORCLR), a
    xor a
    ld (BAKCLR), a
    ld (BDRCLR), a
    call CHGCLR
    
    ret

; Memory initialization through Hook
HOOK_INIT_MEMORY:
    ; Initialize memory pools
    ; Setup entity/component memory
    ret

; Asset loading through Hook
HOOK_LOAD_ASSETS:
    ; Load all game assets
    ; This loads sprites, tiles, fonts, etc.
    ret
`;
}

/**
 * Generate Hook System Implementations - Individual system implementations
 */
export function generateHookSystems(analysis: ProjectAnalysis): string {
  return `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; HOOK SYSTEM IMPLEMENTATIONS
;; Individual system implementations that work through Hook dispatcher
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; ============================================================================
; MENU SYSTEM - Runs main menu, options, etc.
; ============================================================================
MENU_INIT:
    ; Initialize menu system
    ; Setup menu graphics, load menu assets
    call CLEAR_SCREEN
    call LOAD_MENU_GRAPHICS
    
    ; Reset menu state
    xor a
    ld (menu_selection), a
    ret

MENU_UPDATE:
    ; Handle menu input and logic
    call READ_INPUT
    
    ; Check menu navigation
    ld a, (input_pressed)
    bit 0, a                        ; Up
    jr z, .check_down
    ld a, (menu_selection)
    dec a
    jr .update_selection
    
.check_down:
    bit 1, a                        ; Down
    jr z, .check_select
    ld a, (menu_selection)
    inc a
    
.update_selection:
    ; Clamp selection to valid range
    cp MENU_MAX_OPTIONS
    jr c, .selection_ok
    ld a, MENU_MAX_OPTIONS - 1
.selection_ok:
    ld (menu_selection), a
    
.check_select:
    ld a, (input_pressed)
    bit 4, a                        ; Space/Fire button
    ret z
    
    ; Handle menu selection
    ld a, (menu_selection)
    or a
    jr z, .start_game
    cp 1
    jr z, .options_menu
    cp 2
    jr z, .exit_game
    ret
    
.start_game:
    ; Transition to game system
    ld a, 1
    ld (menu_transition_flag), a
    ret
    
.options_menu:
    ; Handle options (or do nothing for now)
    ret
    
.exit_game:
    ; Handle exit
    ret

MENU_RENDER:
    ; Render menu graphics
    call DRAW_MENU_BACKGROUND
    call DRAW_MENU_OPTIONS
    call DRAW_MENU_CURSOR
    ret

MENU_CLEANUP:
    ; Cleanup menu resources
    ret

; Menu variables
menu_selection:     db 0
MENU_MAX_OPTIONS    equ 3

; ============================================================================
; GAME SYSTEM - Main gameplay logic
; ============================================================================
GAME_INIT:
    ; Initialize game system
    call CLEAR_SCREEN
    call LOAD_GAME_GRAPHICS
    call SETUP_GAME_WORLD
    
    ${analysis.hasECS ? '; Initialize ECS systems\n    call INIT_ENTITY_SYSTEM\n    call INIT_COMPONENT_POOLS\n' : ''}${analysis.hasSprites ? '    call INIT_SPRITE_SYSTEM\n' : ''}${analysis.hasCollisions ? '    call INIT_COLLISION_SYSTEM\n' : ''}
    ret

GAME_UPDATE:
    ; Main game logic update
    call READ_INPUT
    
    ; Check for pause
    ld a, (input_pressed)
    bit 5, a                        ; Escape/Select
    jr z, .no_pause
    ld a, 1
    ld (pause_transition_flag), a
    ret
    
.no_pause:
    ${analysis.hasECS ? '; Update ECS systems\n    call UPDATE_ENTITY_SYSTEM\n    call UPDATE_PHYSICS_SYSTEM\n' : '; Update game objects\n    call UPDATE_PLAYER\n    call UPDATE_ENEMIES\n'}${analysis.hasCollisions ? '    call UPDATE_COLLISION_SYSTEM\n' : ''}${analysis.hasSprites ? '    call UPDATE_SPRITE_ANIMATIONS\n' : ''}
    ; Check for game over or level complete
    call CHECK_GAME_STATE
    ret

GAME_RENDER:
    ; Render game world
    ${analysis.hasSprites ? 'call RENDER_SPRITES\n    ' : ''}call RENDER_GAME_WORLD
    call RENDER_UI
    ret

GAME_CLEANUP:
    ; Cleanup game resources
    ${analysis.hasECS ? 'call CLEANUP_ENTITIES\n    ' : ''}ret

; ============================================================================
; PAUSE SYSTEM - Pause overlay
; ============================================================================
PAUSE_INIT:
    ; Setup pause overlay
    call DRAW_PAUSE_OVERLAY
    ret

PAUSE_UPDATE:
    ; Handle pause input
    call READ_INPUT
    
    ld a, (input_pressed)
    bit 5, a                        ; Escape/Select to unpause
    ret z
    
    ; Return to game
    ld a, 1
    ld (game_transition_flag), a
    ret

PAUSE_RENDER:
    ; Render pause overlay (already drawn in init)
    ret

PAUSE_CLEANUP:
    ; Remove pause overlay
    ret

; ============================================================================
; TRANSITION SYSTEM - Screen transitions, effects
; ============================================================================
TRANS_INIT:
    ; Initialize transition effect
    ret

TRANS_UPDATE:
    ; Update transition animation
    ; When complete, trigger final system change
    ret

TRANS_RENDER:
    ; Render transition effect
    ret

TRANS_CLEANUP:
    ; Cleanup transition resources
    ret

; ============================================================================
; SHARED SYSTEM FUNCTIONS
; ============================================================================

; Input handling (shared by all systems)
READ_INPUT:
    ; Read MSX keyboard/joystick
    ; Set flags in input_pressed variable
    xor a
    ld (input_pressed), a
    
    ; Example: Read keyboard
    ld a, 8                         ; Row 8
    call SNSMAT
    bit 5, a                        ; Space
    jr nz, .no_space
    ld a, (input_pressed)
    set 4, a
    ld (input_pressed), a
.no_space:
    
    ret

; Graphics helper functions
CLEAR_SCREEN:
    call CLS
    ret

LOAD_MENU_GRAPHICS:
    ; Load menu-specific graphics assets
    ret

LOAD_GAME_GRAPHICS:
    ; Load game-specific graphics assets
    ret

SETUP_GAME_WORLD:
    ; Initialize game world state
    ret

CHECK_GAME_STATE:
    ; Check for game over, level complete, etc.
    ret

DRAW_MENU_BACKGROUND:
    ; Draw menu background
    ret

DRAW_MENU_OPTIONS:
    ; Draw menu option text
    ret

DRAW_MENU_CURSOR:
    ; Draw cursor at current selection
    ret

RENDER_GAME_WORLD:
    ; Render the main game world
    ret

RENDER_UI:
    ; Render game UI elements
    ret

DRAW_PAUSE_OVERLAY:
    ; Draw pause screen overlay
    ret

; Shared variables
input_pressed:      db 0            ; Input state flags
`;
}