# GENERATED by scripts/check_msx2_boss_path_phase_switch_openmsx.mjs -- do not hand-edit.
# Addresses come from the build being probed; every one of them moves when the
# project turns another boss subsystem on or off.
set log_path "C:/Users/salam/Documents/Programacion/Mideas/test/msx2-boss/path_phase_switch.txt"
set f [open $log_path "w"]
proc logline {msg} { global f; puts $f $msg; flush $f }
proc mem8 {addr} { return [debug read memory $addr] }
set throttle off

set ACTIVE 0xD1D2
set X 0xD1D3
set Y 0xD1D4
set HP 0xD1D9
set IDX 0xD1E7
set PENDING 0xD1E9
set HPLIVE 0xD176
set INTRO 0xD1CA

set frame 0
set pokeFrame -1 ; set pokeX -1 ; set pokeY -1
set swapFrame -1 ; set swapX -1 ; set swapY -1
set bxmin 255 ; set bxmax 0 ; set bymin 255 ; set bymax 0
set sxmin 255 ; set sxmax 0 ; set symin 255 ; set symax 0

proc watch {} {
    global frame ACTIVE X Y IDX swapFrame swapX swapY
    global bxmin bxmax bymin bymax sxmin sxmax symin symax
    incr frame
    if {[mem8 $ACTIVE] == 1} {
        set x [mem8 $X]
        set y [mem8 $Y]
        set p [mem8 $IDX]
        if {$p == 1} {
            if {$x < $bxmin} { set bxmin $x }
            if {$x > $bxmax} { set bxmax $x }
            if {$y < $bymin} { set bymin $y }
            if {$y > $bymax} { set bymax $y }
        } elseif {$p == 2} {
            if {$swapFrame < 0} { set swapFrame $frame ; set swapX $x ; set swapY $y }
            if {$x < $sxmin} { set sxmin $x }
            if {$x > $sxmax} { set sxmax $x }
            if {$y < $symin} { set symin $y }
            if {$y > $symax} { set symax $y }
        }
    }
    after frame watch
}

foreach t {6 8 10} {
    after time $t "keymatrixdown 8 0x01"
    after time [expr {$t + 0.5}] "keymatrixup 8 0x01"
}
after time 12 {
    # Skip the Room Lock entry sequence. The boss body does not update until it
    # has run, and this fixture's legacy chain intro parks on its "walk the
    # player to the centre" step -- which has nothing to do with routes.
    debug write memory $INTRO 0
}
after time 13 {
    watch
    logline "START x=[mem8 $X] y=[mem8 $Y] hp=[mem8 $HP] path=[mem8 $IDX]"
}
after time 26 {
    global frame pokeFrame pokeX pokeY
    set pokeFrame $frame
    set pokeX [mem8 $X]
    set pokeY [mem8 $Y]
    debug write memory $HP 10
    debug write memory $HPLIVE 10
    logline "POKE hp=10 frame=$pokeFrame x=$pokeX y=$pokeY path=[mem8 $IDX]"
}
after time 27 { logline "AFTER1S path=[mem8 $IDX] pending=[mem8 $PENDING] x=[mem8 $X] y=[mem8 $Y]" }
after time 60 {
    global pokeFrame pokeX pokeY swapFrame swapX swapY
    global bxmin bxmax bymin bymax sxmin sxmax symin symax
    logline "BOX x $bxmin $bxmax y $bymin $bymax"
    logline "SWEEP x $sxmin $sxmax y $symin $symax"
    logline "POKED frame $pokeFrame at $pokeX $pokeY"
    logline "SWAPPED frame $swapFrame at $swapX $swapY"
    logline "FINAL path=[mem8 $IDX] pending=[mem8 $PENDING] hp=[mem8 $HP]"
    after time 1 { exit }
}
