; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SPRITES                   EQU 1
RESOURCE_GROUP_PATTERNS                  EQU 2
RESOURCE_GROUP_COLORS                    EQU 3
RESOURCE_GROUP_SCREENS                   EQU 4
RESOURCE_GROUP_FONT                      EQU 5
RESOURCE_GROUP_PRESENTATION              EQU 6

RESOURCE_TYPE_SPRITE_PATTERNS            EQU 1
RESOURCE_TYPE_TILE_PATTERNS              EQU 2
RESOURCE_TYPE_TILE_COLORS                EQU 3
RESOURCE_TYPE_SCREEN_LAYOUT              EQU 4
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 5
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 6
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 7
RESOURCE_TYPE_FONT_PATTERNS              EQU 8
RESOURCE_TYPE_FONT_COLORS                EQU 9
RESOURCE_TYPE_SCREEN_NAME_TABLE          EQU 10
RESOURCE_TYPE_SCREEN_PATTERNS            EQU 11
RESOURCE_TYPE_SCREEN_COLORS              EQU 12

RESOURCE_TABLE_COUNT EQU 105

resource_table:
    ; ANEC_RIGHT_0_F0_LAYER1
    db RESOURCE_ID_ANEC_RIGHT_0_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9F88
    dw 32
    ; ANEC_RIGHT_0_F0_LAYER2
    db RESOURCE_ID_ANEC_RIGHT_0_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9FA8
    dw 32
    ; ANEC_RIGHT_0_F1_LAYER1
    db RESOURCE_ID_ANEC_RIGHT_0_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9FC8
    dw 32
    ; ANEC_RIGHT_0_F1_LAYER2
    db RESOURCE_ID_ANEC_RIGHT_0_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F10
    dw 32
    ; BOLA_1_F0_LAYER1
    db RESOURCE_ID_BOLA_1_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F30
    dw 32
    ; BOLA_1_F1_LAYER1
    db RESOURCE_ID_BOLA_1_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F50
    dw 32
    ; PANELL_2_F0_LAYER1
    db RESOURCE_ID_PANELL_2_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F70
    dw 32
    ; NINA_WALK_RIGHT_3_F0_LAYER0
    db RESOURCE_ID_NINA_WALK_RIGHT_3_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F90
    dw 32
    ; NINA_WALK_RIGHT_3_F0_LAYER1
    db RESOURCE_ID_NINA_WALK_RIGHT_3_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9FB0
    dw 32
    ; NINA_WALK_RIGHT_3_F1_LAYER0
    db RESOURCE_ID_NINA_WALK_RIGHT_3_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9FD0
    dw 32
    ; NINA_WALK_RIGHT_3_F1_LAYER1
    db RESOURCE_ID_NINA_WALK_RIGHT_3_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #88D0
    dw 32
    ; NINA_JUMP_RIGHT_4_F0_LAYER0
    db RESOURCE_ID_NINA_JUMP_RIGHT_4_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #88F0
    dw 32
    ; NINA_JUMP_RIGHT_4_F0_LAYER1
    db RESOURCE_ID_NINA_JUMP_RIGHT_4_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8910
    dw 32
    ; NINA_LAND_RIGHT_5_F0_LAYER0
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8930
    dw 32
    ; NINA_LAND_RIGHT_5_F0_LAYER1
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8950
    dw 32
    ; NINA_LAND_RIGHT_5_F1_LAYER0
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8970
    dw 32
    ; NINA_LAND_RIGHT_5_F1_LAYER1
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8990
    dw 32
    ; NINA_LAND_RIGHT_5_F2_LAYER0
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F2_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #89B0
    dw 32
    ; NINA_LAND_RIGHT_5_F2_LAYER1
    db RESOURCE_ID_NINA_LAND_RIGHT_5_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #89D0
    dw 32
    ; NINA_DEAD_RIGHT_6_F0_LAYER0
    db RESOURCE_ID_NINA_DEAD_RIGHT_6_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #89F0
    dw 32
    ; NINA_DEAD_RIGHT_6_F0_LAYER2
    db RESOURCE_ID_NINA_DEAD_RIGHT_6_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8A10
    dw 32
    ; NINA_DEAD_RIGHT_6_F1_LAYER0
    db RESOURCE_ID_NINA_DEAD_RIGHT_6_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8A30
    dw 32
    ; NINA_DEAD_RIGHT_6_F1_LAYER2
    db RESOURCE_ID_NINA_DEAD_RIGHT_6_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8A50
    dw 32
    ; NINA_IDLE_RIGHT_7_F0_LAYER0
    db RESOURCE_ID_NINA_IDLE_RIGHT_7_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8A70
    dw 32
    ; NINA_IDLE_RIGHT_7_F0_LAYER1
    db RESOURCE_ID_NINA_IDLE_RIGHT_7_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8A90
    dw 32
    ; NINA_IDLE_RIGHT_7_F1_LAYER0
    db RESOURCE_ID_NINA_IDLE_RIGHT_7_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8AB0
    dw 32
    ; NINA_IDLE_RIGHT_7_F1_LAYER1
    db RESOURCE_ID_NINA_IDLE_RIGHT_7_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8AD0
    dw 32
    ; NINA_FALL_RIGHT_8_F0_LAYER0
    db RESOURCE_ID_NINA_FALL_RIGHT_8_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8AF0
    dw 32
    ; NINA_FALL_RIGHT_8_F0_LAYER1
    db RESOURCE_ID_NINA_FALL_RIGHT_8_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8B10
    dw 32
    ; CAPCUADRAT1_RIGHT_9_F0_LAYER3
    db RESOURCE_ID_CAPCUADRAT1_RIGHT_9_F0_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8B30
    dw 32
    ; CAPCUADRAT1_RIGHT_9_F1_LAYER3
    db RESOURCE_ID_CAPCUADRAT1_RIGHT_9_F1_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8B50
    dw 32
    ; ANEC_LEFT_10_F0_LAYER1
    db RESOURCE_ID_ANEC_LEFT_10_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8B70
    dw 32
    ; ANEC_LEFT_10_F0_LAYER2
    db RESOURCE_ID_ANEC_LEFT_10_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8B90
    dw 32
    ; ANEC_LEFT_10_F1_LAYER1
    db RESOURCE_ID_ANEC_LEFT_10_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8BB0
    dw 32
    ; ANEC_LEFT_10_F1_LAYER2
    db RESOURCE_ID_ANEC_LEFT_10_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8BD0
    dw 32
    ; NINA_WALK_LEFT_11_F0_LAYER0
    db RESOURCE_ID_NINA_WALK_LEFT_11_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8BF0
    dw 32
    ; NINA_WALK_LEFT_11_F0_LAYER1
    db RESOURCE_ID_NINA_WALK_LEFT_11_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8C10
    dw 32
    ; NINA_WALK_LEFT_11_F1_LAYER0
    db RESOURCE_ID_NINA_WALK_LEFT_11_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8C30
    dw 32
    ; NINA_WALK_LEFT_11_F1_LAYER1
    db RESOURCE_ID_NINA_WALK_LEFT_11_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8C50
    dw 32
    ; NINA_JUMP_LEFT_12_F0_LAYER0
    db RESOURCE_ID_NINA_JUMP_LEFT_12_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8C70
    dw 32
    ; NINA_JUMP_LEFT_12_F0_LAYER1
    db RESOURCE_ID_NINA_JUMP_LEFT_12_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8C90
    dw 32
    ; NINA_LAND_LEFT_13_F0_LAYER0
    db RESOURCE_ID_NINA_LAND_LEFT_13_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8CB0
    dw 32
    ; NINA_LAND_LEFT_13_F0_LAYER1
    db RESOURCE_ID_NINA_LAND_LEFT_13_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8CD0
    dw 32
    ; NINA_LAND_LEFT_13_F1_LAYER0
    db RESOURCE_ID_NINA_LAND_LEFT_13_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8CF0
    dw 32
    ; NINA_LAND_LEFT_13_F1_LAYER1
    db RESOURCE_ID_NINA_LAND_LEFT_13_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8D10
    dw 32
    ; NINA_LAND_LEFT_13_F2_LAYER0
    db RESOURCE_ID_NINA_LAND_LEFT_13_F2_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8D30
    dw 32
    ; NINA_LAND_LEFT_13_F2_LAYER1
    db RESOURCE_ID_NINA_LAND_LEFT_13_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8D50
    dw 32
    ; NINA_DEAD_LEFT_14_F0_LAYER0
    db RESOURCE_ID_NINA_DEAD_LEFT_14_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8D70
    dw 32
    ; NINA_DEAD_LEFT_14_F0_LAYER2
    db RESOURCE_ID_NINA_DEAD_LEFT_14_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8D90
    dw 32
    ; NINA_DEAD_LEFT_14_F1_LAYER0
    db RESOURCE_ID_NINA_DEAD_LEFT_14_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8DB0
    dw 32
    ; NINA_DEAD_LEFT_14_F1_LAYER2
    db RESOURCE_ID_NINA_DEAD_LEFT_14_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8DD0
    dw 32
    ; NINA_IDLE_LEFT_15_F0_LAYER0
    db RESOURCE_ID_NINA_IDLE_LEFT_15_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8DF0
    dw 32
    ; NINA_IDLE_LEFT_15_F0_LAYER1
    db RESOURCE_ID_NINA_IDLE_LEFT_15_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8E10
    dw 32
    ; NINA_IDLE_LEFT_15_F1_LAYER0
    db RESOURCE_ID_NINA_IDLE_LEFT_15_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8E30
    dw 32
    ; NINA_IDLE_LEFT_15_F1_LAYER1
    db RESOURCE_ID_NINA_IDLE_LEFT_15_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8E50
    dw 32
    ; NINA_FALL_LEFT_16_F0_LAYER0
    db RESOURCE_ID_NINA_FALL_LEFT_16_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8E70
    dw 32
    ; NINA_FALL_LEFT_16_F0_LAYER1
    db RESOURCE_ID_NINA_FALL_LEFT_16_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8E90
    dw 32
    ; CAPCUADRAT1_LEFT_17_F0_LAYER3
    db RESOURCE_ID_CAPCUADRAT1_LEFT_17_F0_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8EB0
    dw 32
    ; CAPCUADRAT1_LEFT_17_F1_LAYER3
    db RESOURCE_ID_CAPCUADRAT1_LEFT_17_F1_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8ED0
    dw 32
    ; SPRITE_PLACEHOLDER_PATTERN
    db RESOURCE_ID_SPRITE_PLACEHOLDER_PATTERN, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #8EF0
    dw 32
    ; tile_pattern_bank0
    db RESOURCE_ID_TILE_PATTERN_BANK0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 19
    dw #8410
    dw 304
    ; tilebank_pattern_data_0
    db RESOURCE_ID_TILEBANK_PATTERN_DATA_0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 19
    dw #8540
    dw 304
    ; tile_color_bank0
    db RESOURCE_ID_TILE_COLOR_BANK0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 19
    dw #8670
    dw 304
    ; tilebank_color_data_0
    db RESOURCE_ID_TILEBANK_COLOR_DATA_0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 19
    dw #87A0
    dw 304
    ; SCREEN_PAN1_0_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8BA0
    dw 768
    ; SCREEN_PAN1_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8EA0
    dw 768
    ; SCREEN_PAN1_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF0
    dw 1
    ; BEHAVIOR_PAN1_0_DATA
    db RESOURCE_ID_BEHAVIOR_PAN1_0_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 16
    dw #91A0
    dw 768
    ; SCREEN_PAN2_1_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #94A0
    dw 768
    ; SCREEN_PAN2_1_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #97A0
    dw 768
    ; SCREEN_PAN2_1_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF1
    dw 1
    ; BEHAVIOR_PAN2_1_DATA
    db RESOURCE_ID_BEHAVIOR_PAN2_1_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 16
    dw #9AA0
    dw 768
    ; SCREEN_BACKGROUND1_2_LAYOUT
    db RESOURCE_ID_SCREEN_BACKGROUND1_2_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8000
    dw 768
    ; SCREEN_BACKGROUND1_2_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_BACKGROUND1_2_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8300
    dw 768
    ; SCREEN_BACKGROUND1_2_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_BACKGROUND1_2_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF2
    dw 1
    ; BEHAVIOR_BACKGROUND1_2_DATA
    db RESOURCE_ID_BEHAVIOR_BACKGROUND1_2_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #8600
    dw 768
    ; SCREEN_PAN3_3_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_3_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8900
    dw 768
    ; SCREEN_PAN3_3_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_3_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8C00
    dw 768
    ; SCREEN_PAN3_3_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN3_3_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF3
    dw 1
    ; BEHAVIOR_PAN3_3_DATA
    db RESOURCE_ID_BEHAVIOR_PAN3_3_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #8F00
    dw 768
    ; SCREEN_PAN4_4_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_4_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #9200
    dw 768
    ; SCREEN_PAN4_4_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_4_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #9500
    dw 768
    ; SCREEN_PAN4_4_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN4_4_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF4
    dw 1
    ; BEHAVIOR_PAN4_4_DATA
    db RESOURCE_ID_BEHAVIOR_PAN4_4_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #9800
    dw 768
    ; SCREEN_PAN5_5_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_5_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #9B00
    dw 768
    ; SCREEN_PAN5_5_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_5_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8000
    dw 768
    ; SCREEN_PAN5_5_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN5_5_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FE8
    dw 8
    ; BEHAVIOR_PAN5_5_DATA
    db RESOURCE_ID_BEHAVIOR_PAN5_5_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 18
    dw #8300
    dw 768
    ; SCREEN_PAN6_6_LAYOUT
    db RESOURCE_ID_SCREEN_PAN6_6_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8600
    dw 768
    ; SCREEN_PAN6_6_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN6_6_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8900
    dw 768
    ; SCREEN_PAN6_6_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN6_6_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF5
    dw 1
    ; BEHAVIOR_PAN6_6_DATA
    db RESOURCE_ID_BEHAVIOR_PAN6_6_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 18
    dw #8C00
    dw 768
    ; SCREEN_PAN1_2_7_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_2_7_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8F00
    dw 768
    ; SCREEN_PAN1_2_7_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_2_7_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #9200
    dw 768
    ; SCREEN_PAN1_2_7_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN1_2_7_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF6
    dw 1
    ; BEHAVIOR_PAN1_2_7_DATA
    db RESOURCE_ID_BEHAVIOR_PAN1_2_7_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 18
    dw #9500
    dw 768
    ; FONT_PATTERN_DATA
    db RESOURCE_ID_FONT_PATTERN_DATA, RESOURCE_TYPE_FONT_PATTERNS, RESOURCE_GROUP_FONT, 18
    dw #9DA8
    dw 360
    ; FONT_COLOR_DATA
    db RESOURCE_ID_FONT_COLOR_DATA, RESOURCE_TYPE_FONT_COLORS, RESOURCE_GROUP_FONT, 19
    dw #82A8
    dw 360
    ; PRESENTATION_SCREEN_NAMETBL
    db RESOURCE_ID_PRESENTATION_SCREEN_NAMETBL, RESOURCE_TYPE_SCREEN_NAME_TABLE, RESOURCE_GROUP_PRESENTATION, 18
    dw #9800
    dw 768
    ; PRESENTATION_SCREEN_PATTERNS_B0
    db RESOURCE_ID_PRESENTATION_SCREEN_PATTERNS_B0, RESOURCE_TYPE_SCREEN_PATTERNS, RESOURCE_GROUP_PRESENTATION, 18
    dw #9B00
    dw 680
    ; PRESENTATION_SCREEN_PATTERNS_B1
    db RESOURCE_ID_PRESENTATION_SCREEN_PATTERNS_B1, RESOURCE_TYPE_SCREEN_PATTERNS, RESOURCE_GROUP_PRESENTATION, 16
    dw #8000
    dw 1488
    ; PRESENTATION_SCREEN_PATTERNS_B2
    db RESOURCE_ID_PRESENTATION_SCREEN_PATTERNS_B2, RESOURCE_TYPE_SCREEN_PATTERNS, RESOURCE_GROUP_PRESENTATION, 16
    dw #9DA0
    dw 488
    ; PRESENTATION_SCREEN_COLORS_B0
    db RESOURCE_ID_PRESENTATION_SCREEN_COLORS_B0, RESOURCE_TYPE_SCREEN_COLORS, RESOURCE_GROUP_PRESENTATION, 19
    dw #8000
    dw 680
    ; PRESENTATION_SCREEN_COLORS_B1
    db RESOURCE_ID_PRESENTATION_SCREEN_COLORS_B1, RESOURCE_TYPE_SCREEN_COLORS, RESOURCE_GROUP_PRESENTATION, 16
    dw #85D0
    dw 1488
    ; PRESENTATION_SCREEN_COLORS_B2
    db RESOURCE_ID_PRESENTATION_SCREEN_COLORS_B2, RESOURCE_TYPE_SCREEN_COLORS, RESOURCE_GROUP_PRESENTATION, 17
    dw #9E00
    dw 488
