; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SPRITES                   EQU 1
RESOURCE_GROUP_PATTERNS                  EQU 2
RESOURCE_GROUP_COLORS                    EQU 3
RESOURCE_GROUP_SCREENS                   EQU 4

RESOURCE_TYPE_SPRITE_PATTERNS            EQU 1
RESOURCE_TYPE_TILE_PATTERNS              EQU 2
RESOURCE_TYPE_TILE_COLORS                EQU 3
RESOURCE_TYPE_SCREEN_BLOCK_CATALOG       EQU 4
RESOURCE_TYPE_SCREEN_BLOCK_MAP           EQU 5
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 6
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 7
RESOURCE_TYPE_SCREEN_DATA                EQU 8
RESOURCE_TYPE_SCREEN_LAYOUT              EQU 9
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 10

RESOURCE_TABLE_COUNT EQU 55

resource_table:
    ; NINA_WALK_RIGHT_0_F0_LAYER0
    db RESOURCE_ID_NINA_WALK_RIGHT_0_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #85B8
    dw 32
    ; NINA_WALK_RIGHT_0_F0_LAYER1
    db RESOURCE_ID_NINA_WALK_RIGHT_0_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #85D8
    dw 32
    ; NINA_WALK_RIGHT_0_F1_LAYER0
    db RESOURCE_ID_NINA_WALK_RIGHT_0_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #85F8
    dw 32
    ; NINA_WALK_RIGHT_0_F1_LAYER1
    db RESOURCE_ID_NINA_WALK_RIGHT_0_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8618
    dw 32
    ; NINA_GRUB_RIGHT_1_F0_LAYER1
    db RESOURCE_ID_NINA_GRUB_RIGHT_1_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8638
    dw 32
    ; NINA_GRUB_RIGHT_1_F0_LAYER2
    db RESOURCE_ID_NINA_GRUB_RIGHT_1_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8658
    dw 32
    ; NINA_GRUB_RIGHT_1_F1_LAYER1
    db RESOURCE_ID_NINA_GRUB_RIGHT_1_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8678
    dw 32
    ; NINA_GRUB_RIGHT_1_F1_LAYER2
    db RESOURCE_ID_NINA_GRUB_RIGHT_1_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8698
    dw 32
    ; NEW_SPRITE_2_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_2_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #86B8
    dw 32
    ; NEW_SPRITE_2_F0_LAYER2
    db RESOURCE_ID_NEW_SPRITE_2_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #86D8
    dw 32
    ; NEW_SPRITE_2_F0_LAYER3
    db RESOURCE_ID_NEW_SPRITE_2_F0_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #86F8
    dw 32
    ; NINA_JUMP_RIGHT_3_F0_LAYER0
    db RESOURCE_ID_NINA_JUMP_RIGHT_3_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8718
    dw 32
    ; NINA_JUMP_RIGHT_3_F0_LAYER1
    db RESOURCE_ID_NINA_JUMP_RIGHT_3_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8738
    dw 32
    ; NINA_IDLE_RIGHT_4_F0_LAYER1
    db RESOURCE_ID_NINA_IDLE_RIGHT_4_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8758
    dw 32
    ; NINA_IDLE_RIGHT_4_F0_LAYER2
    db RESOURCE_ID_NINA_IDLE_RIGHT_4_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8778
    dw 32
    ; NEW_SPRITE_RIGHT_5_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_RIGHT_5_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8798
    dw 32
    ; NEW_SPRITE_RIGHT_5_F0_LAYER2
    db RESOURCE_ID_NEW_SPRITE_RIGHT_5_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #87B8
    dw 32
    ; NINA_WALK_LEFT_6_F0_LAYER0
    db RESOURCE_ID_NINA_WALK_LEFT_6_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #87D8
    dw 32
    ; NINA_WALK_LEFT_6_F0_LAYER1
    db RESOURCE_ID_NINA_WALK_LEFT_6_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #87F8
    dw 32
    ; NINA_WALK_LEFT_6_F1_LAYER0
    db RESOURCE_ID_NINA_WALK_LEFT_6_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8818
    dw 32
    ; NINA_WALK_LEFT_6_F1_LAYER1
    db RESOURCE_ID_NINA_WALK_LEFT_6_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8838
    dw 32
    ; NINA_GRUB_LEFT_7_F0_LAYER1
    db RESOURCE_ID_NINA_GRUB_LEFT_7_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8858
    dw 32
    ; NINA_GRUB_LEFT_7_F0_LAYER2
    db RESOURCE_ID_NINA_GRUB_LEFT_7_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8878
    dw 32
    ; NINA_GRUB_LEFT_7_F1_LAYER1
    db RESOURCE_ID_NINA_GRUB_LEFT_7_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8898
    dw 32
    ; NINA_GRUB_LEFT_7_F1_LAYER2
    db RESOURCE_ID_NINA_GRUB_LEFT_7_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #88B8
    dw 32
    ; NINA_JUMP_LEFT_8_F0_LAYER0
    db RESOURCE_ID_NINA_JUMP_LEFT_8_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #88D8
    dw 32
    ; NINA_JUMP_LEFT_8_F0_LAYER1
    db RESOURCE_ID_NINA_JUMP_LEFT_8_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #88F8
    dw 32
    ; NINA_IDLE_LEFT_9_F0_LAYER1
    db RESOURCE_ID_NINA_IDLE_LEFT_9_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8918
    dw 32
    ; NINA_IDLE_LEFT_9_F0_LAYER2
    db RESOURCE_ID_NINA_IDLE_LEFT_9_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8938
    dw 32
    ; NEW_SPRITE_LEFT_10_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_LEFT_10_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8958
    dw 32
    ; NEW_SPRITE_LEFT_10_F0_LAYER2
    db RESOURCE_ID_NEW_SPRITE_LEFT_10_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8978
    dw 32
    ; SPRITE_PLACEHOLDER_PATTERN
    db RESOURCE_ID_SPRITE_PLACEHOLDER_PATTERN, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #8998
    dw 32
    ; tile_pattern_bank0
    db RESOURCE_ID_TILE_PATTERN_BANK0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 16
    dw #9E00
    dw 392
    ; tilebank_pattern_data_0
    db RESOURCE_ID_TILEBANK_PATTERN_DATA_0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 17
    dw #8288
    dw 232
    ; tilebank_pattern_data_1
    db RESOURCE_ID_TILEBANK_PATTERN_DATA_1, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 17
    dw #8458
    dw 152
    ; tile_color_bank0
    db RESOURCE_ID_TILE_COLOR_BANK0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 17
    dw #8000
    dw 392
    ; tilebank_color_data_0
    db RESOURCE_ID_TILEBANK_COLOR_DATA_0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 17
    dw #8370
    dw 232
    ; tilebank_color_data_1
    db RESOURCE_ID_TILEBANK_COLOR_DATA_1, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 17
    dw #84F0
    dw 152
    ; SCREEN_PAN1_0_BLOCK_CATALOG
    db RESOURCE_ID_SCREEN_PAN1_0_BLOCK_CATALOG, RESOURCE_TYPE_SCREEN_BLOCK_CATALOG, RESOURCE_GROUP_SCREENS, 16
    dw #9F88
    dw 96
    ; SCREEN_PAN1_0_BLOCK_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_BLOCK_MAP, RESOURCE_TYPE_SCREEN_BLOCK_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #8588
    dw 48
    ; SCREEN_PAN1_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8000
    dw 768
    ; SCREEN_PAN1_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF3
    dw 1
    ; SCREEN_PAN1_0_BOSS_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_BOSS_TABLE, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #9FE8
    dw 11
    ; SCREEN_PAN1_0_CHAR_BEHAVIOR_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_CHAR_BEHAVIOR_TABLE, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #8188
    dw 256
    ; SCREEN_PAN1_0_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #8300
    dw 768
    ; SCREEN_PAN1_0_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #8600
    dw 768
    ; SCREEN_PAN1_0_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #8900
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_LAYOUT
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8C00
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8F00
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF4
    dw 1
    ; SCREEN_NEW_DIALOG_SCREEN_1_BOSS_TABLE
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_BOSS_TABLE, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #9FF5
    dw 1
    ; BEHAVIOR_NEW_DIALOG_SCREEN_1_DATA
    db RESOURCE_ID_BEHAVIOR_NEW_DIALOG_SCREEN_1_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 16
    dw #9200
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #9500
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #9800
    dw 768
    ; SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_NEW_DIALOG_SCREEN_1_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #9B00
    dw 768
