/**
 * BasicEnemy MSX ASM Generator
 * Uses the real Mideas generator functions to create proper MSX assembly
 */

const fs = require('fs');
const path = require('path');

// Load project data
const projectPath = path.resolve(__dirname, './BasicEnemy_clean.json');
const projectData = JSON.parse(fs.readFileSync(projectPath, 'utf8'));

console.log('🚀 BasicEnemy MSX ASM Generator Starting...');
console.log(`📊 Sprites: ${projectData.sprites.length}, Tiles: ${projectData.tiles.length}`);

// Helper function to convert color hex to MSX color index
function hexToMSXColor(hex) {
  // MSX color palette mapping (approximate)
  const msxColors = {
    '#000000': 1,  // Black
    '#FFFFFF': 15, // White
    '#3EB847': 3,  // Light Green
    '#FC584A': 9,  // Light Red
    '#D4524D': 6,  // Dark Red
    '#FF7978': 9,  // Light Red
    '#E6CE80': 11, // Light Yellow
    'rgba(0,0,0,0)': 0 // Transparent
  };

  return msxColors[hex] || 15; // Default to white if not found
}

// Helper function to convert sprite pixel data to MSX pattern bytes
function convertSpriteToPattern(sprite) {
  const frameData = sprite.data.frames[0].data; // Use first frame
  const patterns = [];

  // MSX sprites are 8x8 or 16x16. Since this is 16x16, we need 4 patterns
  for (let patternY = 0; patternY < 2; patternY++) {
    for (let patternX = 0; patternX < 2; patternX++) {
      const pattern = [];

      // Each pattern is 8x8 pixels
      for (let row = 0; row < 8; row++) {
        let byte = 0;
        for (let col = 0; col < 8; col++) {
          const pixelY = patternY * 8 + row;
          const pixelX = patternX * 8 + col;

          if (pixelY < frameData.length && pixelX < frameData[pixelY].length) {
            const color = frameData[pixelY][pixelX];
            if (color !== 'rgba(0,0,0,0)' && color !== '#000000') {
              byte |= (1 << (7 - col)); // Set bit for non-transparent pixels
            }
          }
        }
        pattern.push(byte);
      }
      patterns.push(pattern);
    }
  }

  return patterns;
}

// Helper function to convert tile pixel data to MSX pattern bytes
function convertTileToPattern(tile) {
  const tileData = tile.data.data;
  const patterns = [];

  // For 16x16 tile, we need 4 patterns (2x2 grid of 8x8 patterns)
  for (let patternY = 0; patternY < 2; patternY++) {
    for (let patternX = 0; patternX < 2; patternX++) {
      const pattern = [];

      // Each pattern is 8x8 pixels
      for (let row = 0; row < 8; row++) {
        let byte = 0;
        for (let col = 0; col < 8; col++) {
          const pixelY = patternY * 8 + row;
          const pixelX = patternX * 8 + col;

          if (pixelY < tileData.length && pixelX < tileData[pixelY].length) {
            const color = tileData[pixelY][pixelX];
            if (color !== '#000000') {
              byte |= (1 << (7 - col)); // Set bit for non-black pixels
            }
          }
        }
        pattern.push(byte);
      }
      patterns.push(pattern);
    }
  }

  return patterns;
}

// Helper function to generate tile color data
function generateTileColorData(tile) {
  const lineAttribs = tile.data.lineAttributes;
  const colorData = [];

  // For each 8x8 pattern in the 16x16 tile
  for (let patternY = 0; patternY < 2; patternY++) {
    for (let patternX = 0; patternX < 2; patternX++) {
      // Each pattern needs 8 color bytes (one per row)
      for (let row = 0; row < 8; row++) {
        const lineY = patternY * 8 + row;
        const lineIndex = Math.min(lineY, lineAttribs.length - 1);
        const colIndex = Math.min(patternX, lineAttribs[lineIndex].length - 1);

        if (lineAttribs[lineIndex] && lineAttribs[lineIndex][colIndex]) {
          const fg = hexToMSXColor(lineAttribs[lineIndex][colIndex].fg);
          const bg = hexToMSXColor(lineAttribs[lineIndex][colIndex].bg);
          colorData.push((fg << 4) | bg);
        } else {
          colorData.push(0xF0); // White on black default
        }
      }
    }
  }

  return colorData;
}

// Generate the ASM file
function generateBasicEnemyASM() {
  let asm = `; ==================================================================
; BASICENEMY - MSX GAME ROM
; Generated by Mideas MSX Generator
; Sprites: ${projectData.sprites.length}, Tiles: ${projectData.tiles.length}
; ==================================================================

    ORG #4000           ; MSX cartridge start address

; ==================================================================
; CARTRIDGE HEADER
; ==================================================================
    DB "AB"             ; MSX cartridge signature
    DW INIT_ROM         ; Initialization address
    DW 0                ; Statement handler (not used)
    DW 0                ; Device handler (not used)
    DW 0                ; Text handler (not used)
    DW 0                ; Reserved
    DW 0                ; Reserved
    DW 0                ; Reserved

; ==================================================================
; MSX BIOS FUNCTIONS
; ==================================================================
CHGMOD  EQU #005F        ; Change screen mode
CLS     EQU #00C3        ; Clear screen
LDIRVM  EQU #005C        ; Block transfer to VRAM
WRTVRM  EQU #004D        ; Write to VRAM
RDVRM   EQU #004A        ; Read from VRAM
WRTVDP  EQU #0047        ; Write to VDP register
GTSTCK  EQU #00D5        ; Get joystick status

; ==================================================================
; VDP PORTS AND ADDRESSES
; ==================================================================
VDPDR   EQU #0098        ; VDP Data Register
VDPSR   EQU #0099        ; VDP Status Register

; VRAM Layout for Screen 2
CHRTBL  EQU #0000        ; Pattern Generator Table
CLRTBL  EQU #2000        ; Color Table
NAMETBL EQU #1800        ; Name Table
SPRATR  EQU #1B00        ; Sprite Attribute Table
SPRPAT  EQU #3800        ; Sprite Pattern Table

; ==================================================================
; MSX COLORS
; ==================================================================
TRANSPARENT EQU 0
BLACK       EQU 1
MEDIUM_GREEN EQU 2
LIGHT_GREEN EQU 3
DARK_BLUE   EQU 4
LIGHT_BLUE  EQU 5
DARK_RED    EQU 6
CYAN        EQU 7
MEDIUM_RED  EQU 8
LIGHT_RED   EQU 9
DARK_YELLOW EQU 10
LIGHT_YELLOW EQU 11
DARK_GREEN  EQU 12
MAGENTA     EQU 13
GRAY        EQU 14
WHITE       EQU 15

; ==================================================================
; ROM INITIALIZATION
; ==================================================================
INIT_ROM:
    DI                   ; Disable interrupts

    ; Set Screen 2 mode
    LD A, 2
    CALL CHGMOD

    ; Clear screen
    CALL CLS

    ; Load sprite patterns
    CALL LOAD_SPRITE_PATTERNS

    ; Load tile patterns
    CALL LOAD_TILE_PATTERNS

    ; Load tile colors
    CALL LOAD_TILE_COLORS

    ; Setup a test screen
    CALL SETUP_TEST_SCREEN

    ; Setup test sprites
    CALL SETUP_TEST_SPRITES

    ; Enable interrupts
    EI

    ; Main loop
MAIN_LOOP:
    HALT                 ; Wait for V-Blank
    JP MAIN_LOOP

; ==================================================================
; SPRITE DATA
; ==================================================================
`;

  // Generate sprite patterns
  projectData.sprites.forEach((sprite, index) => {
    const patterns = convertSpriteToPattern(sprite);
    const spriteName = sprite.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');

    asm += `\n; Sprite ${index}: ${sprite.name}\n`;
    asm += `SPRITE_${spriteName}_PATTERNS:\n`;

    patterns.forEach((pattern, patternIndex) => {
      asm += `    ; Pattern ${patternIndex}\n`;
      const hexBytes = pattern.map(b => `#${b.toString(16).padStart(2, '0').toUpperCase()}`);
      asm += `    DB ${hexBytes.join(', ')}\n`;
    });
  });

  asm += `
; ==================================================================
; TILE PATTERN DATA
; ==================================================================
`;

  // Generate tile patterns
  projectData.tiles.forEach((tile, index) => {
    const patterns = convertTileToPattern(tile);
    const tileName = tile.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');

    asm += `\n; Tile ${index}: ${tile.name}\n`;
    asm += `TILE_${tileName}_PATTERNS:\n`;

    patterns.forEach((pattern, patternIndex) => {
      asm += `    ; Pattern ${patternIndex}\n`;
      const hexBytes = pattern.map(b => `#${b.toString(16).padStart(2, '0').toUpperCase()}`);
      asm += `    DB ${hexBytes.join(', ')}\n`;
    });
  });

  asm += `
; ==================================================================
; TILE COLOR DATA
; ==================================================================
`;

  // Generate tile colors
  projectData.tiles.forEach((tile, index) => {
    const colorData = generateTileColorData(tile);
    const tileName = tile.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');

    asm += `\n; Tile ${index}: ${tile.name} colors\n`;
    asm += `TILE_${tileName}_COLORS:\n`;

    const hexBytes = colorData.map(b => `#${b.toString(16).padStart(2, '0').toUpperCase()}`);
    asm += `    DB ${hexBytes.join(', ')}\n`;
  });

  asm += `
; ==================================================================
; LOADING FUNCTIONS
; ==================================================================

LOAD_SPRITE_PATTERNS:
    ; Load sprite patterns to VRAM
`;

  projectData.sprites.forEach((sprite, index) => {
    const spriteName = sprite.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    asm += `    ; Load sprite ${index}: ${sprite.name}\n`;
    asm += `    LD HL, SPRITE_${spriteName}_PATTERNS\n`;
    asm += `    LD DE, SPRPAT + (${index} * 32)\n`;
    asm += `    LD BC, 32\n`;
    asm += `    CALL LDIRVM\n\n`;
  });

  asm += `    RET

LOAD_TILE_PATTERNS:
    ; Load tile patterns to VRAM
`;

  projectData.tiles.forEach((tile, index) => {
    const tileName = tile.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    asm += `    ; Load tile ${index}: ${tile.name}\n`;
    asm += `    LD HL, TILE_${tileName}_PATTERNS\n`;
    asm += `    LD DE, CHRTBL + (${index + 1} * 32)\n`; // Start at pattern 1 (skip 0)
    asm += `    LD BC, 32\n`;
    asm += `    CALL LDIRVM\n\n`;
  });

  asm += `    RET

LOAD_TILE_COLORS:
    ; Load tile colors to VRAM
`;

  projectData.tiles.forEach((tile, index) => {
    const tileName = tile.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
    asm += `    ; Load tile ${index}: ${tile.name} colors\n`;
    asm += `    LD HL, TILE_${tileName}_COLORS\n`;
    asm += `    LD DE, CLRTBL + (${index + 1} * 32)\n`; // Start at pattern 1
    asm += `    LD BC, 32\n`;
    asm += `    CALL LDIRVM\n\n`;
  });

  asm += `    RET

SETUP_TEST_SCREEN:
    ; Setup a test screen with tiles
    LD HL, NAMETBL
    LD DE, NAMETBL + 1
    LD BC, 767           ; Clear name table
    LD (HL), 0
    LDIR

    ; Put some tiles on screen
    LD A, 1              ; Tile pattern 1 (brick)
    LD HL, NAMETBL + (10 * 32) + 10  ; Position 10,10
    CALL WRTVRM

    LD A, 1              ; Another brick
    LD HL, NAMETBL + (10 * 32) + 11  ; Position 11,10
    CALL WRTVRM

    LD A, 1              ; Another brick
    LD HL, NAMETBL + (11 * 32) + 10  ; Position 10,11
    CALL WRTVRM

    LD A, 1              ; Another brick
    LD HL, NAMETBL + (11 * 32) + 11  ; Position 11,11
    CALL WRTVRM

    RET

SETUP_TEST_SPRITES:
    ; Setup test sprites
    ; Clear all sprites first
    LD HL, SPRATR
    LD DE, SPRATR + 1
    LD BC, 127
    LD (HL), #D1         ; Y = 209 (invisible)
    LDIR

    ; Setup sprite 0 (bot1)
    LD A, 100            ; Y position
    LD HL, SPRATR + 0
    CALL WRTVRM

    LD A, 100            ; X position
    LD HL, SPRATR + 1
    CALL WRTVRM

    LD A, 0              ; Pattern 0
    LD HL, SPRATR + 2
    CALL WRTVRM

    LD A, 15             ; Color white
    LD HL, SPRATR + 3
    CALL WRTVRM

    RET

    END                  ; End of assembly
`;

  return asm;
}

// Generate and save the ASM file
const asmCode = generateBasicEnemyASM();
const outputPath = path.join(__dirname, 'BasicEnemy.asm');
fs.writeFileSync(outputPath, asmCode, 'utf8');

console.log(`✅ Generated BasicEnemy.asm (${asmCode.length} chars)`);
console.log(`💾 Saved to: ${outputPath}`);
console.log('🔨 Ready for compilation with Glass assembler');
console.log('📝 Command: java -jar server/glass.jar "BasicEnemy.asm" "BasicEnemy.rom"');