; ==================================================
; HEADER.ASM
; ==================================================
; MSX Konami ROM Header for BasicEnemy(7)
; Generated by Mideas MSX Summary System

        ORG     #4000           ; Konami ROM start address

HEADER:
        DB      "AB"            ; Konami ROM signature
        DW      INIT            ; Initialize routine
        DW      0               ; Statement handler (not used)
        DW      0               ; Device handler (not used)
        DW      0               ; Reserved
        DS      6,0             ; Reserved space

; ==================================================
; CONSTANTS.ASM
; ==================================================
; Constants for BasicEnemy(7)

; Project configuration
SPRITE_COUNT    EQU 1
SCREEN_COUNT    EQU 1
MAX_ENTITIES    EQU 16

; GameFlow states
GAMEFLOW_INIT   EQU 0
GAMEFLOW_GAME   EQU 1
GAMEFLOW_PAUSE  EQU 2

; Screen 2 configuration
SCREEN_MODE     EQU 2
SCREEN_WIDTH    EQU 32
SCREEN_HEIGHT   EQU 24

; Animation constants
ANIM_SPEED      EQU 8           ; Frames per animation update
MAX_FRAMES      EQU 2

; ==================================================
; VARIABLES.ASM
; ==================================================
; RAM Variables (C000h-F37Fh)

        ORG     #C000

; System variables
GAME_STATE:     DS 1            ; Current game state
FRAME_COUNTER:  DS 2            ; Frame counter for timing
VBLANK_FLAG:    DS 1            ; V-Blank synchronization

; Sprite variables
SPRITE_X:       DS 1    ; Sprite X positions
SPRITE_Y:       DS 1    ; Sprite Y positions
SPRITE_FRAME:   DS 1    ; Current animation frames
SPRITE_TIMER:   DS 1    ; Animation timers

; Entity system variables
ENTITY_COUNT:   DS 1            ; Active entity count
ENTITY_STATE:   DS 16           ; Entity states (16 max)
ENTITY_X:       DS 16           ; Entity X positions
ENTITY_Y:       DS 16           ; Entity Y positions

; Patrol AI variables
PATROL_DIR:     DS 16           ; Patrol directions
PATROL_TIMER:   DS 16           ; Patrol timers
WAYPOINT_X1:    DS 16           ; Waypoint 1 X
WAYPOINT_Y1:    DS 16           ; Waypoint 1 Y
WAYPOINT_X2:    DS 16           ; Waypoint 2 X
WAYPOINT_Y2:    DS 16           ; Waypoint 2 Y

; ==================================================
; SPRITES.ASM
; ==================================================
; Sprite data and routines


; Sprite: bot1 (16x16, 2 frames)
BOT1_PATTERNS:

; Frame 0
        DB      #00,#00,#00,#00,#00,#00,#00,#00  ; Pattern data placeholder
        DB      #00,#00,#00,#00,#00,#00,#00,#00
        DB      #00,#00,#00,#00,#00,#00,#00,#00
        DB      #00,#00,#00,#00,#00,#00,#00,#00
; Frame 1
        DB      #00,#00,#00,#00,#00,#00,#00,#00  ; Pattern data placeholder
        DB      #00,#00,#00,#00,#00,#00,#00,#00
        DB      #00,#00,#00,#00,#00,#00,#00,#00
        DB      #00,#00,#00,#00,#00,#00,#00,#00

BOT1_FRAME_COUNT EQU 2


; Update sprite animation
UPDATE_SPRITE_ANIMATION:
        ; Cycle through frames based on timer
        LD      A,(FRAME_COUNTER)
        AND     #07             ; Every 8 frames
        RET     NZ

        ; Update frame for sprite 0
        LD      A,(SPRITE_FRAME)
        INC     A
        CP      2
        JR      C,SET_FRAME
        XOR     A               ; Reset to frame 0
SET_FRAME:
        LD      (SPRITE_FRAME),A
        RET

; ==================================================
; SCREENS.ASM
; ==================================================
; Screen data for 1 screen(s)


; Screen: pantalla1 (32x24)
PANTALLA1_WIDTH  EQU 32
PANTALLA1_HEIGHT EQU 24

PANTALLA1_DATA:
        ; Background layer data (placeholder)
        DS      768, #00


; Load screen data to VRAM
LOAD_SCREEN:
        ; A = screen number
        ; Load screen tiles to VRAM
        LD      HL,PANTALLA1_DATA
        LD      DE,#1800        ; Name table in VRAM
        LD      BC,768
        CALL    LDIRVM
        RET

; ==================================================
; COMPONENTS.ASM
; ==================================================
; Component system for ECS

; Component masks
COMP_POSITION_MASK EQU #01
COMP_RENDERABLE_MASK EQU #02
COMP_PATROL_MASK EQU #04
COMP_ANIMATION_MASK EQU #08

; Component update routines
UPDATE_COMPONENTS:
        ; Update Position components
        CALL    UPDATE_POSITION

        ; Update Render components
        CALL    UPDATE_RENDER

        ; Update Patrol components
        CALL    UPDATE_PATROL

        ; Update Animation components
        CALL    UPDATE_ANIMATION
        RET

UPDATE_POSITION:
        ; Update entity positions
        RET

UPDATE_RENDER:
        ; Update sprite rendering
        RET

UPDATE_PATROL:
        ; Update AI patrol logic
        LD      A,(PATROL_TIMER)
        DEC     A
        LD      (PATROL_TIMER),A
        RET     NZ

        ; Change direction
        LD      A,(PATROL_DIR)
        XOR     #01
        LD      (PATROL_DIR),A
        LD      A,60            ; Reset timer
        LD      (PATROL_TIMER),A
        RET

UPDATE_ANIMATION:
        ; Update animation frames
        CALL    UPDATE_SPRITE_ANIMATION
        RET

; ==================================================
; ENTITIES.ASM
; ==================================================
; Entity definitions

; Entity: BasicPatrol
BASICPATROL_TEMPLATE:
        DB      COMP_POSITION_MASK | COMP_RENDERABLE_MASK | COMP_PATROL_MASK | COMP_ANIMATION_MASK
        DW      14*8, 13*8      ; Initial position (in pixels)
        DB      0               ; Initial sprite frame
        DB      0               ; Initial patrol direction

; Initialize entities
INIT_ENTITIES:
        ; Set up BasicPatrol entity
        LD      A,1
        LD      (ENTITY_COUNT),A

        ; Set initial position
        LD      A,14*8
        LD      (ENTITY_X),A
        LD      A,13*8
        LD      (ENTITY_Y),A

        ; Set sprite position
        LD      (SPRITE_X),A
        LD      A,(ENTITY_Y)
        LD      (SPRITE_Y),A

        ; Initialize patrol
        LD      A,60
        LD      (PATROL_TIMER),A
        XOR     A
        LD      (PATROL_DIR),A
        RET

; ==================================================
; MAIN.ASM
; ==================================================
; Main program for BasicEnemy(7)

INIT:
        ; Disable interrupts during setup
        DI

        ; Initialize MSX Screen 2
        LD      A,2
        CALL    CHGMOD          ; Set screen mode 2

        ; Initialize sprite system
        CALL    INIT_SPRITES

        ; Initialize entities
        CALL    INIT_ENTITIES

        ; Load screen
        XOR     A
        CALL    LOAD_SCREEN

        ; Set initial game state
        LD      A,GAMEFLOW_GAME
        LD      (GAME_STATE),A

        ; Enable interrupts
        EI

; Main game loop
MAIN_LOOP:
        ; Wait for V-Blank
        HALT

        ; Update frame counter
        LD      HL,(FRAME_COUNTER)
        INC     HL
        LD      (FRAME_COUNTER),HL

        ; Update game systems
        CALL    UPDATE_COMPONENTS

        ; Update sprites on screen
        CALL    UPDATE_SPRITE_POSITIONS

        ; Continue main loop
        JR      MAIN_LOOP

; Initialize sprite system
INIT_SPRITES:
        ; Set sprite patterns
        LD      HL,BOT1_PATTERNS
        LD      DE,#3800        ; Sprite pattern table
        LD      BC,32           ; 32 bytes per sprite
        CALL    LDIRVM
        RET

; Update sprite positions on screen
UPDATE_SPRITE_POSITIONS:
        ; Set sprite 0 position
        LD      A,(SPRITE_X)
        LD      B,A
        LD      A,(SPRITE_Y)
        LD      C,A
        LD      D,0             ; Sprite number
        LD      A,(SPRITE_FRAME) ; Load frame number
        LD      E,A             ; Pattern number
        CALL    PUT_SPRITE
        RET

; Put sprite on screen (B=X, C=Y, D=sprite#, E=pattern)
PUT_SPRITE:
        ; Placeholder for sprite positioning
        RET

; ==================================================
; BIOS.ASM
; ==================================================
; MSX BIOS function addresses

CHGMOD  EQU     #005F           ; Change screen mode
LDIRVM  EQU     #005C           ; Load data to VRAM
LDIRMV  EQU     #0059           ; Load data from VRAM