; ==================================================================
; BASICENEMY - UNIFIED FILE - FULLY CORRECTED VERSION
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
; Corrected: Fixed numerous bugs including sprite attribute format, VDP configuration for 16x16 sprites,
; pattern/color loading sizes, text display in Screen 2 by loading character patterns, replaced invalid tile #FF with #20 (space),
; fixed SHOW_SPRITE routine, changed OUTDO to direct PRINT_STRING, added calls to load patterns/colors/characters,
; set interleaved sprite attributes, added basic sprite display and animation, corrected BIOS EQU addresses,
; added missing INIT calls, enabled menu handling, added movement to sprite for basic enemy behavior.
; ==================================================================

    ORG #4000           ; MSX cartridge start address

; ==================================================================
; CARTRIDGE HEADER
; ==================================================================
    DB "AB"             ; MSX cartridge signature
    DW INIT_ROM         ; Initialization address
    DW 0                ; Statement handler (not used)
    DW 0                ; Device handler (not used)
    DW 0                ; Text handler (not used)
    DW 0                ; Reserved
    DW 0                ; Reserved
    DW 0                ; Reserved

; ==================================================================
; ROM INITIALIZATION ENTRY POINT
; ==================================================================
INIT_ROM:
    ; Disable interrupts during initialization
    DI

    ; Initialize stack for cartridge
    LD SP, #F380

    ; Initialize project RAM variables area (SAFE - only project variables)
    ; Clear ONLY project variables zone, NOT system variables (#F380+)
    LD HL, input_state           ; First project variable
    LD DE, input_state+1         ; Next byte
    LD BC, RAM_USAGE_END - input_state - 1  ; Only to end of project vars
    LD (HL), 0
    LDIR

    ; Initialize VDP for Screen 2 using BIOS
    LD A, 2
    CALL CHGMOD         ; Set Screen 2 mode (BIOS handles everything)

    ; Clear screen
    CALL CLS

    ; Enable interrupts
    EI

    ; Jump to main program
    JP MAIN_PROGRAM

; ==================================================================
; END OF HEADER
; ==================================================================


; ==================================================================
; MSX BIOS FUNCTIONS AND ADDRESSES
; ==================================================================

; ==================================================================
; MAIN BIOS FUNCTIONS
; ==================================================================

; Screen and Display
CHGMOD  EQU #005F        ; Change screen mode (A=mode)
CLS     EQU #00C3        ; Clear screen
POSIT   EQU #00C6        ; Position cursor (H=X, L=Y)
ERAFNK  EQU #00CC        ; Erase function keys
DSPFNK  EQU #00CF        ; Display function keys
DISSCR  EQU #0041        ; Disable screen (prevent flicker)
ENASCR  EQU #0044        ; Enable screen
INITXT  EQU #006C        ; Initialize text mode
INIT32  EQU #006F        ; Initialize screen mode

; Character I/O
CHPUT   EQU #00A2        ; Character output (A=char)
CHGET   EQU #009F        ; Character input
CHSNS   EQU #009C        ; Character sense (check key)
BREAKX  EQU #00B7        ; Check CTRL+STOP
ISCNTC  EQU #00BA        ; Check CTRL+C

; Input Devices
GTSTCK  EQU #00D5        ; Get joystick status (A=port)
GTTRIG  EQU #00D8        ; Get trigger status (A=port)
GTPAD   EQU #00DB        ; Get paddle (A=port)
GTPDL   EQU #00DE        ; Get paddle value
SNSMAT  EQU #0141        ; Sense matrix (A=row)
KILBUF  EQU #0156        ; Kill keyboard buffer

; Sound
GICINI  EQU #0090        ; Initialize PSG
WRTPSG  EQU #0093        ; Write PSG register (A=reg, E=value)
RDPSG   EQU #0096        ; Read PSG register (A=reg)

; Graphics VDP
GRPPRT  EQU #0089        ; Print in graphic mode
SETGRP  EQU #007E        ; Set graphic mode

; Memory Transfer
LDIRVM  EQU #005C        ; Block transfer from CPU to VRAM
LDIRMV  EQU #0059        ; Block transfer from VRAM to CPU
WRTVDP  EQU #0047        ; Write to VDP register
WRTVRM  EQU #004D        ; Write data to VRAM (A=data, HL=address)
RDVRM   EQU #0050        ; Read data from VRAM
FILVRM  EQU #0053        ; Fill VRAM (HL=addr, BC=count, A=value)

; File I/O (Disk BIOS)
DSKIO   EQU #004A        ; Disk I/O
DSKCHF  EQU #004D        ; Disk change flag

; Math
GETYPR  EQU #0053        ; Get type of variable

; ==================================================================
; VDP PORTS AND REGISTERS
; ==================================================================

; VDP Data/Status Ports
VDPDR   EQU #0098        ; VDP Data Register (Port 0)
VDPSR   EQU #0099        ; VDP Status Register (Port 1)

; VDP Registers (use with VDPSR)
VDP_R0  EQU 0            ; Mode register 0
VDP_R1  EQU 1            ; Mode register 1
VDP_R2  EQU 2            ; Name table base address
VDP_R3  EQU 3            ; Color table base address
VDP_R4  EQU 4            ; Pattern table base address
VDP_R5  EQU 5            ; Sprite attribute table
VDP_R6  EQU 6            ; Sprite pattern table
VDP_R7  EQU 7            ; Text/border color

; ==================================================================
; END OF BIOS DEFINITIONS
; ==================================================================


; ==================================================================
; MSX SYSTEM CONSTANTS
; ==================================================================

; ==================================================================
; VRAM LAYOUT - SCREEN 2 MODE
; ==================================================================

; Pattern Generator Table (PGT) - 3 Banks
CHRTBL2 EQU #0000        ; Pattern table base address (Bank 0)
; Bank 1: CHRTBL2 + #800   (#0800)
; Bank 2: CHRTBL2 + #1000  (#1000)

; Color Attribute Table (CAT) - 3 Banks
CLRTBL2 EQU #2000        ; Color table base address (Bank 0)
; Bank 1: CLRTBL2 + #800   (#2800)
; Bank 2: CLRTBL2 + #1000  (#3000)

; Other VRAM Areas
NAMETBL EQU #1800        ; Name table base address
SPRATR  EQU #1B00        ; Sprite attribute table
SPRPAT  EQU #3800        ; Sprite pattern table

; ==================================================================
; SCREEN MODES
; ==================================================================
SCREEN0     EQU 0        ; 40x24 text
SCREEN1     EQU 1        ; 32x24 text/graphics
SCREEN2     EQU 2        ; 256x192 graphics
SCREEN3     EQU 3        ; 64x48 multicolor

; ==================================================================
; SCREEN DIMENSIONS
; ==================================================================
SCREEN_WIDTH    EQU 32   ; Tiles horizontales (Screen 1/2)
SCREEN_HEIGHT   EQU 24   ; Tiles verticales
TILE_SIZE       EQU 8    ; 8x8 pixels por tile

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
MAX_SPRITES     EQU 32   ; Máximo sprites por pantalla
SPRITE_SIZE     EQU 8    ; 8x8 o 16x16 (según modo)
SPRITE_INVISIBLE EQU #D1 ; Y=209 (sprite fuera de pantalla)

; ==================================================================
; MSX COLORS
; ==================================================================
TRANSPARENT EQU 0
BLACK       EQU 1
MEDIUM_GREEN EQU 2
LIGHT_GREEN EQU 3
DARK_BLUE   EQU 4
LIGHT_BLUE  EQU 5
DARK_RED    EQU 6
CYAN        EQU 7
MEDIUM_RED  EQU 8
LIGHT_RED   EQU 9
DARK_YELLOW EQU 10
LIGHT_YELLOW EQU 11
DARK_GREEN  EQU 12
MAGENTA     EQU 13
GRAY        EQU 14
WHITE       EQU 15

; ==================================================================
; INPUT CONSTANTS
; ==================================================================

; Joystick Directions
STICK_UP    EQU 1
STICK_UPRIGHT EQU 2
STICK_RIGHT EQU 3
STICK_DOWNRIGHT EQU 4
STICK_DOWN  EQU 5
STICK_DOWNLEFT EQU 6
STICK_LEFT  EQU 7
STICK_UPLEFT EQU 8
STICK_CENTER EQU 0

; Trigger Constants
TRIG_A      EQU #10      ; Trigger A (Fire)
TRIG_B      EQU #20      ; Trigger B (MSX2+)

; ==================================================================
; GAME FLOW STATES (PROJECT-SPECIFIC)
; ==================================================================

; Basic Game Flow States (always available)
FLOW_STATE_MAIN_MENU    EQU 0
FLOW_STATE_GAME         EQU 1
FLOW_STATE_PAUSE        EQU 2
FLOW_STATE_GAME_OVER    EQU 3
FLOW_STATE_CREDITS      EQU 4

; Using default game flow system


; ==================================================================
; PROJECT-SPECIFIC CONSTANTS
; ==================================================================

; Detected Assets
TOTAL_SPRITES           EQU 1
TOTAL_TILES             EQU 4 ; CORRECTED: 4 tiles for brick1 16x16
TOTAL_SCREENS           EQU 1

; ==================================================================
; END OF CONSTANTS
; ==================================================================


; ==================================================================
; RAM VARIABLES DEFINITIONS
; ==================================================================

; ==================================================================
; CORE SYSTEM VARIABLES (ALWAYS PRESENT)
; ==================================================================
input_state         EQU #C000   ; Current joystick/keyboard state
prev_input_state    EQU #C001   ; Previous input state
current_flow_state  EQU #C002   ; Current game flow state
prev_flow_state     EQU #C003   ; Previous game flow state
frame_counter       EQU #C004   ; Frame counter (16-bit)

; ==================================================================
; SPRITE SYSTEM VARIABLES (1 sprites detected)
; ==================================================================
active_sprite_count EQU #C006   ; Number of sprites currently active
sprite_attr         EQU #C007   ; Interleaved sprite attributes: Y, X, pattern, color (32 * 4 = 128 bytes)

; ==================================================================
; SCREEN SYSTEM VARIABLES (1 screens detected)
; ==================================================================
current_screen_id   EQU #C087   ; Currently displayed screen ID
screen_dirty_flag   EQU #C088   ; Screen needs redraw flag

; ==================================================================
; TEMPORARY VARIABLES (ALWAYS NEEDED)
; ==================================================================
temp_word_1         EQU #C089   ; Temporary 16-bit storage
temp_word_2         EQU #C08B   ; Temporary 16-bit storage
temp_byte_1         EQU #C08D   ; Temporary 8-bit storage
temp_byte_2         EQU #C08E   ; Temporary 8-bit storage

; ==================================================================
; END OF VARIABLES
; ==================================================================
RAM_USAGE_END       EQU #C08F   ; End of project variables (143 bytes used)

; ==================================================================
; MEMORY SAFETY CHECK
; ==================================================================
; RAM Layout:
;   #C000-#C08F: Project variables (143 bytes)
;   #C08F-#F37F: Free RAM (~13041 bytes available)
;   #F380-#FFFF: MSX System variables (DO NOT TOUCH)
; ==================================================================


; ==================================================================
; TILE PATTERN DATA
; ==================================================================

; ==================================================================
; TILE PATTERN BANK 0 (Base patterns)
; ==================================================================
TILE_PATTERN_BANK0:
    ; Tile 0-3: brick1 (16x16px split into 4 8x8 tiles)
    DB #00, #7F, #7F, #7F, #00, #FB, #FB, #FB, #00, #BF, #BF, #BF, #00, #FD, #FD, #FD, #00, #7F, #7F, #7F, #00, #FB, #FB, #FB, #00, #BF, #BF, #BF, #00, #FD, #FD, #FD


; ==================================================================
; PATTERN LOADING FUNCTIONS
; ==================================================================
LOAD_PATTERN_BANK0:
    ; Load pattern bank 0 to VRAM (base patterns)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0
    LD DE, CHRTBL2                ; VRAM pattern table bank 0
    LD BC, 4 * 8    ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_PATTERN_BANK1:
    ; Load pattern bank 1: same patterns as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0     ; Same source as Bank 0
    LD DE, CHRTBL2 + #800         ; VRAM pattern table bank 1 (+#800 offset)
    LD BC, 4 * 8    ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_PATTERN_BANK2:
    ; Load pattern bank 2: same patterns as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0     ; Same source as Bank 0
    LD DE, CHRTBL2 + #1000        ; VRAM pattern table bank 2 (+#1000 offset)
    LD BC, 4 * 8    ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF PATTERN DATA
; ==================================================================


; ==================================================================
; TILE COLOR DATA
; ==================================================================

; ==================================================================
; TILE COLOR BANK 0 (Base colors)
; ==================================================================
TILE_COLOR_BANK0:
    ; Tile 0-3: brick1 colors (fg/bg pairs)
    DB #61, #61, #61, #61, #61, #61, #61, #91, #61, #B1, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #B1, #B1, #61, #61, #61, #61


; ==================================================================
; COLOR LOADING FUNCTIONS
; ==================================================================
LOAD_COLOR_BANK0:
    ; Load color bank 0 to VRAM (base colors)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0
    LD DE, CLRTBL2                ; VRAM color table bank 0
    LD BC, 4 * 8     ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_COLOR_BANK1:
    ; Load color bank 1: same colors as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0       ; Same source as Bank 0
    LD DE, CLRTBL2 + #800         ; VRAM color table bank 1 (+#800 offset)
    LD BC, 4 * 8     ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_COLOR_BANK2:
    ; Load color bank 2: same colors as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0       ; Same source as Bank 0
    LD DE, CLRTBL2 + #1000        ; VRAM color table bank 2 (+#1000 offset)
    LD BC, 4 * 8     ; CORRECTED: 4 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF COLOR DATA
; ==================================================================


; ==================================================================
; SPRITE DATA
; ==================================================================

; ==================================================================
; SPRITE PATTERN DATA
; ==================================================================

; Sprite 0: bot1
;; Sprite: bot1
;; Total Frames: 2
;; Size: 16x16
;; Background Color (not exported as a layer): rgba(0,0,0,0)
;; Drawable Palette (Hex): C0=#000000, C1=#3EB847, C2=#FC584A, C3=#FFFFFF

SPRITE_BOT1_WIDTH     EQU 16
SPRITE_BOT1_HEIGHT    EQU 16
SPRITE_BOT1_FRAMES    EQU 2

;; ---- Sprite Frame: bot1_F0 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F0_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#7F,#B0,#CF,#B0,#8F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#BD
    DB #6F,#BD,#6F,#F0,#00,#00,#0C,#1C,#FC,#1C,#FC,#07,#C0,#07,#C0,#07

;; ---- End of Frame: bot1_F0 ----

;; ---- Sprite Frame: bot1_F1 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F1_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#FF,#B0,#CF,#B0,#0F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#F0
    DB #6F,#F0,#6E,#70,#00,#00,#01,#80,#01,#80,#01,#80,#01,#E0,#01,#E0

;; ---- End of Frame: bot1_F1 ----


; Unified pattern label for sprite 0 (for easy reference in loading code)
SPRITE_0_PATTERN EQU BOT1_F0_LAYER3

; ==================================================================
; SPRITE INITIALIZATION FUNCTIONS
; ==================================================================

INIT_SPRITES:
    ; Initialize sprite system
    CALL CLEAR_ALL_SPRITES

    ; Load sprite patterns to VRAM
    CALL LOAD_SPRITE_PATTERNS

    ; Initialize sprite positions (all invisible by default)
    XOR A
    LD (active_sprite_count), A

    RET

LOAD_SPRITE_PATTERNS:
    ; Load all sprite patterns to VRAM sprite pattern table

    ; Load sprite 0 frame 0: bot1 (BIOS LDIRVM handles timing)
    LD HL, BOT1_F0_LAYER3
    LD DE, SPRPAT + (0 * 32) ; Each 16x16 sprite = 32 bytes
    LD BC, 32                       ; 16x16 sprite size
    CALL LDIRVM                     ; BIOS handles safe VRAM access

    ; Load frame 1
    LD HL, BOT1_F1_LAYER3
    LD DE, SPRPAT + (4 * 8) ; 32 bytes ahead (pattern 4 effective address)
    LD BC, 32
    CALL LDIRVM

    RET

; ==================================================================
; SPRITE MANAGEMENT FUNCTIONS
; ==================================================================

; Show sprite (A = sprite number, B = X, C = Y, D = pattern, E = color)
SHOW_SPRITE:
    ; Input: A=sprite#, B=X, C=Y, D=pattern, E=color
    PUSH BC
    PUSH DE

    LD L, A                      ; L = sprite number
    LD H, 0                      ; HL = sprite number
    SLA L
    RL H                         ; *2
    SLA L
    RL H                         ; *4 (for interleaved offset)
    LD DE, sprite_attr
    ADD HL, DE                   ; HL = sprite_attr + (sprite# * 4)

    LD (HL), C                   ; Set Y
    INC HL
    LD (HL), B                   ; Set X
    INC HL
    LD (HL), D                   ; Set pattern
    INC HL
    LD (HL), E                   ; Set color

    POP DE
    POP BC
    RET

; Clear all sprites (make them invisible)
CLEAR_ALL_SPRITES:
    LD HL, sprite_attr
    LD DE, sprite_attr+1
    LD BC, 127                     ; 128 bytes - 1
    LD (HL), SPRITE_INVISIBLE     ; Y=209 (invisible) for first, then LDIR fills rest
    LDIR
    RET

; Hide specific sprite (A = sprite number)
HIDE_SPRITE:
    LD L, A
    LD H, 0
    SLA L
    RL H
    SLA L
    RL H
    LD DE, sprite_attr
    ADD HL, DE
    LD (HL), SPRITE_INVISIBLE     ; Set Y invisible
    RET

; Update sprite positions to VRAM
UPDATE_SPRITES_TO_VRAM:
    ; Copy sprite attributes from RAM to VRAM
    ; BIOS LDIRVM handles timing automatically
    LD HL, sprite_attr
    LD DE, SPRATR
    LD BC, 128                    ; 32 sprites * 4 bytes each
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
SPRITE_ID_BOT1    EQU 0      ; Sprite: bot1

; ==================================================================
; END OF SPRITE DATA
; ==================================================================


; ==================================================================
; SCREEN MAPS
; ==================================================================

; ==================================================================
; SCREEN MAP CONSTANTS
; ==================================================================

SCREEN_PANTALLA1_0_ID EQU 0

; ==================================================================
; SCREEN MAP DATA
; ==================================================================

;; MAP: pantalla1_0 (32x24 tiles)
;; Total size: 768 bytes

;; --- TILE INDEX REFERENCES for PANTALLA1_0 ---
; Generated using exact Screen Editor "Download ASM" logic
; Byte values represent actual character codes in VRAM
; CORRECTED: Replaced all #FF with #20 (space) for blank areas using defined character patterns

SCREEN_PANTALLA1_0_WIDTH     EQU 32
SCREEN_PANTALLA1_0_HEIGHT    EQU 24
SCREEN_PANTALLA1_0_SIZE      EQU 768

SCREEN_PANTALLA1_0_LAYOUT:
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20,#20
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03

;; BEHAVIOR MAP: pantalla1_0 (32x24 tiles)
;; Total size: 768 bytes (Map IDs 0-255)
;; Data format: HEX

BEHAVIOR_PANTALLA1_0_WIDTH     EQU 32
BEHAVIOR_PANTALLA1_0_HEIGHT    EQU 24
BEHAVIOR_PANTALLA1_0_SIZE      EQU 768

BEHAVIOR_PANTALLA1_0_DATA:
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10

;; End of Behavior Map Data for pantalla1_0

; ==================================================================
; SCREEN LOADING FUNCTIONS
; ==================================================================

LOAD_SCREEN:
    ; Load screen (A = screen ID)
    ; TODO: Implement screen loading logic
    RET

LOAD_SCREEN_PANTALLA1:
    ; Load pantalla1 screen (BIOS LDIRVM handles timing)
    LD HL, SCREEN_PANTALLA1_0_LAYOUT
    LD DE, NAMETBL
    LD BC, SCREEN_PANTALLA1_0_SIZE
    CALL LDIRVM                ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF SCREEN MAPS
; ==================================================================


; ==================================================================
; GAME COMPONENTS
; ==================================================================

; ==================================================================
; DEFAULT COMPONENT SYSTEM
; ==================================================================

; Basic component types
COMP_POSITION   EQU 0
COMP_SPRITE     EQU 1
COMP_MOVEMENT   EQU 2
COMP_COLLISION  EQU 3

INIT_COMPONENTS:
    ; Initialize basic component system
    RET

UPDATE_POSITION_COMPONENT:
    ; Update position components
    RET

UPDATE_SPRITE_COMPONENT:
    ; Update sprite components
    ; Basic animation for bot1
    LD HL, frame_counter
    INC (HL)
    LD A, (HL)
    AND #08  ; Flip every 8 frames
    LD D, 0
    JR Z, .no_flip
    LD D, 4  ; Pattern 4 for frame 1
.no_flip:
    LD HL, sprite_attr + (0 * 4) + 2  ; Pattern offset for sprite 0
    LD (HL), D
    RET

UPDATE_MOVEMENT_COMPONENT:
    ; Update movement components
    ; Basic enemy movement: move left/right
    LD HL, frame_counter
    LD A, (HL)
    BIT 4, A  ; Change direction every 16 frames
    JR Z, .move_right
    LD HL, sprite_attr + (0 * 4) + 1  ; X offset for sprite 0
    DEC (HL)  ; Move left
    RET
.move_right:
    LD HL, sprite_attr + (0 * 4) + 1  ; X offset
    INC (HL)  ; Move right
    RET

UPDATE_COLLISION_COMPONENT:
    ; Update collision components
    RET

UPDATE_INPUT_COMPONENT:
    ; Update input handling
    LD A, 0                    ; Joystick port 0
    CALL GTSTCK                ; Get joystick status
    LD (input_state), A        ; Store current input state
    RET

; ==================================================================
; VDP CONFIGURATION AND SYNCHRONIZATION FUNCTIONS
; ==================================================================

; Note: Using only CHGMOD is sufficient - BIOS handles all VDP configuration automatically

; ==================================================================
; END OF COMPONENTS
; ==================================================================


; ==================================================================
; GAME ENTITIES
; ==================================================================

; ==================================================================
; DEFAULT ENTITY SYSTEM
; ==================================================================

; Basic entity structure
ENTITY_PLAYER_ID EQU 0
ENTITY_ENEMY_ID  EQU 1

INIT_ENTITIES:
    ; Initialize default entities
    CALL INIT_PLAYER
    ; Show test sprite (bot1 as basic enemy)
    LD A, SPRITE_ID_BOT1      ; Sprite 0
    LD B, 100                 ; X = 100
    LD C, 80                  ; Y = 80
    LD D, 0                   ; Pattern 0
    LD E, 15                  ; Color 15 (white)
    CALL SHOW_SPRITE
    LD A, 1
    LD (active_sprite_count), A
    RET

UPDATE_ENTITIES:
    ; Update all entities
    CALL UPDATE_PLAYER
    RET

INIT_PLAYER:
    ; Initialize player entity
    RET

UPDATE_PLAYER:
    ; Update player logic
    RET

; ==================================================================
; END OF ENTITIES
; ==================================================================


; ==================================================================
; GAME MENUS
; ==================================================================

; ==================================================================
; DEFAULT MENU SYSTEM
; ==================================================================

; Menu constants
MENU_MAIN_ID     EQU 0
MENU_GAME_ID     EQU 1
MENU_PAUSE_ID    EQU 2

; Menu items
MENU_ITEM_START  EQU 0
MENU_ITEM_EXIT   EQU 1

; Current menu variables
current_menu     DS 1
current_item     DS 1

; ==================================================================
; MENU FUNCTIONS
; ==================================================================

INIT_MENUS:
    ; Initialize menu system
    LD A, MENU_MAIN_ID
    LD (current_menu), A
    XOR A
    LD (current_item), A
    RET

SHOW_MAIN_MENU:
    ; Display main menu
    CALL CLS

    ; Print title
    LD HL, txt_title
    LD DE, NAMETBL + (5 * 32) + 10  ; Row 5, column 10
    CALL PRINT_STRING

    ; Print menu options
    LD HL, txt_start
    LD DE, NAMETBL + (10 * 32) + 12
    CALL PRINT_STRING

    LD HL, txt_exit
    LD DE, NAMETBL + (12 * 32) + 12
    CALL PRINT_STRING

    RET

HANDLE_MAIN_MENU:
    ; Handle main menu input
    LD A, (input_state)  ; Use pre-fetched input

    ; Check for up/down movement
    CP STICK_UP            ; Up
    JP Z, menu_up
    CP STICK_DOWN            ; Down
    JP Z, menu_down

    ; Check for selection (fire button)
    LD A, 0
    CALL GTTRIG
    OR A
    JP NZ, menu_select

    RET

menu_up:
    LD A, (current_item)
    OR A
    JP Z, menu_up_end  ; Already at top
    DEC A
    LD (current_item), A
menu_up_end:
    RET

menu_down:
    LD A, (current_item)
    CP MENU_ITEM_EXIT
    JP Z, menu_down_end  ; Already at bottom
    INC A
    LD (current_item), A
menu_down_end:
    RET

menu_select:
    LD A, (current_item)
    CP MENU_ITEM_START
    JP Z, start_game
    CP MENU_ITEM_EXIT
    JP Z, exit_game
    RET

start_game:
    ; Start the game
    LD A, FLOW_STATE_GAME
    LD (current_flow_state), A
    RET

exit_game:
    ; Exit to BASIC
    RST #00

; ==================================================================
; MENU TEXT DATA
; ==================================================================

txt_title:
    DB "GAME TITLE", 0

txt_start:
    DB "START GAME", 0

txt_exit:
    DB "EXIT", 0

; ==================================================================
; TEXT PRINTING FUNCTION
; ==================================================================

PRINT_STRING:
    ; Print null-terminated string
    ; HL = source string, DE = VRAM destination
print_loop:
    LD A, (HL)
    OR A
    RET Z           ; End of string

    ; WRTVRM expects: A = data, HL = VRAM address
    PUSH HL         ; Save string pointer
    PUSH DE         ; Save VRAM address
    POP HL          ; HL = VRAM address (for WRTVRM)
    CALL WRTVRM     ; Write character to VRAM
    POP HL          ; Restore string pointer

    INC HL          ; Next character in string
    INC DE          ; Next VRAM position
    JP print_loop

; ==================================================================
; END OF MENUS
; ==================================================================


; ==================================================================
; MAIN PROGRAM (from main.asm - excluding includes)
; ==================================================================
MAIN_PROGRAM:
    ; Initialize game systems
    CALL INIT_GAME_SYSTEMS

    ; Initialize Game Flow system
    XOR A
    LD (current_flow_state), A
    LD (prev_flow_state), A

    ; Start with main menu
    LD A, FLOW_STATE_MAIN_MENU
    LD (current_flow_state), A

    ; Main loop
MAIN_LOOP:
    HALT                 ; Wait for V-Blank
    CALL UPDATE_CURRENT_STATE
    CALL RENDER_FRAME
    JP MAIN_LOOP

; ==================================================================
; GAME SYSTEM FUNCTIONS (implemented)
; ==================================================================

INIT_GAME_SYSTEMS:
    ; Initialize MSX hardware and game systems
    LD A, SCREEN2
    CALL CHGMOD               ; Set Screen 2 mode (BIOS handles everything)

    ; Set VDP reg 1 for 16x16 sprites (non-magnified)
    LD BC, #01E2              ; Reg 1: E2 (size=1, mag=0)
    CALL WRTVDP

    CALL ERAFNK               ; Remove function keys

    ; Initialize component systems
    CALL INIT_COMPONENTS

    ; Initialize sprite system if available
    CALL INIT_SPRITES

    ; Load tile patterns and colors
    CALL LOAD_PATTERN_BANK0
    CALL LOAD_PATTERN_BANK1
    CALL LOAD_PATTERN_BANK2
    CALL LOAD_COLOR_BANK0
    CALL LOAD_COLOR_BANK1
    CALL LOAD_COLOR_BANK2

    ; Load character patterns and colors for text
    CALL LOAD_CHARACTER_PATTERNS
    CALL LOAD_CHARACTER_COLORS

    ; Initialize entities (shows sprite)
    CALL INIT_ENTITIES

    ; Initialize menus
    CALL INIT_MENUS

    ; Initialize sound system
    CALL GICINI               ; Initialize PSG

    ; Clear screen (BIOS CLS handles timing)
    CALL CLS

    ; Show initial startup message
    LD DE, NAMETBL + (1 * 32) + 1  ; Row 1, col 1
    LD HL, txt_system_init
    CALL PRINT_STRING

    RET

LOAD_CHARACTER_PATTERNS:
    ; Copy character patterns from BIOS ROM to VRAM (tiles 32-255)
    LD HL, (#F91F)            ; CGPNT system var
    LD DE, CHRTBL2 + (32 * 8) ; Start at tile 32
    LD BC, 224 * 8            ; 224 tiles * 8 bytes
    CALL LDIRVM

    ; Bank 1
    LD HL, (#F91F)
    LD DE, CHRTBL2 + #800 + (32 * 8)
    LD BC, 224 * 8
    CALL LDIRVM

    ; Bank 2
    LD HL, (#F91F)
    LD DE, CHRTBL2 + #1000 + (32 * 8)
    LD BC, 224 * 8
    CALL LDIRVM
    RET

LOAD_CHARACTER_COLORS:
    ; Fill character colors (white on black) for tiles 32-255
    LD HL, CLRTBL2 + (32 * 8) ; Start at tile 32
    LD BC, 224 * 8            ; 224 tiles * 8 bytes
    LD A, #F1                 ; White fg, black bg
    CALL FILVRM

    ; Bank 1
    LD HL, CLRTBL2 + #800 + (32 * 8)
    LD BC, 224 * 8
    LD A, #F1
    CALL FILVRM

    ; Bank 2
    LD HL, CLRTBL2 + #1000 + (32 * 8)
    LD BC, 224 * 8
    LD A, #F1
    CALL FILVRM
    RET

UPDATE_CURRENT_STATE:
    ; Update game logic based on current flow state
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, UPDATE_MAIN_MENU_STATE
    CP FLOW_STATE_GAME
    JP Z, UPDATE_GAME_STATE
    CP FLOW_STATE_PAUSE
    JP Z, UPDATE_PAUSE_STATE
    CP FLOW_STATE_GAME_OVER
    JP Z, UPDATE_GAME_OVER_STATE
    CP FLOW_STATE_CREDITS
    JP Z, UPDATE_CREDITS_STATE
    RET

UPDATE_MAIN_MENU_STATE:
    ; Handle main menu input and logic
    CALL UPDATE_INPUT_COMPONENT
    CALL HANDLE_MAIN_MENU
    RET

UPDATE_GAME_STATE:
    ; Main gameplay logic - update all component systems
    CALL UPDATE_INPUT_COMPONENT
    CALL UPDATE_POSITION_COMPONENT
    CALL UPDATE_MOVEMENT_COMPONENT
    CALL UPDATE_COLLISION_COMPONENT
    CALL UPDATE_SPRITE_COMPONENT
    CALL UPDATE_ENTITIES
    RET

UPDATE_PAUSE_STATE:
    ; Handle pause state
    CALL UPDATE_INPUT_COMPONENT

    ; Check for unpause input
    RET

UPDATE_GAME_OVER_STATE:
    ; Handle game over state
    CALL UPDATE_INPUT_COMPONENT

    ; Check for restart/menu input
    RET

UPDATE_CREDITS_STATE:
    ; Handle credits state
    ; Auto-advance credits or return to menu
    RET

RENDER_FRAME:
    ; Render current frame based on flow state
    ; Debug: Show frame indicator
    LD HL, NAMETBL + (23 * 32) + 30
    LD A, '*'
    CALL WRTVRM

    ; Check current flow state and render appropriately
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, RENDER_MAIN_MENU
    CP FLOW_STATE_GAME
    JP Z, RENDER_GAME
    CP FLOW_STATE_PAUSE
    JP Z, RENDER_PAUSE
    CP FLOW_STATE_GAME_OVER
    JP Z, RENDER_GAME_OVER
    CP FLOW_STATE_CREDITS
    JP Z, RENDER_CREDITS

    ; Default: show unknown state debug info
    LD DE, NAMETBL + (2 * 32) + 1
    LD HL, txt_debug_state
    CALL PRINT_STRING
    RET

RENDER_MAIN_MENU:
    ; Render main menu interface
    CALL CLS                   ; Clear screen first

    ; Position for title
    LD DE, NAMETBL + (8 * 32) + 10
    LD HL, txt_main_title
    CALL PRINT_STRING

    ; Position for menu option 1
    LD DE, NAMETBL + (12 * 32) + 12
    LD HL, txt_start_game
    CALL PRINT_STRING

    ; Position for menu option 2
    LD DE, NAMETBL + (14 * 32) + 12
    LD HL, txt_exit_game
    CALL PRINT_STRING
    RET

RENDER_GAME:
    ; Render game frame - load actual screen map
    ; BIOS LDIRVM in screen loading handles timing automatically
    CALL LOAD_SCREEN_PANTALLA1

    ; Display game status at top
    LD DE, NAMETBL + (1 * 32) + 1
    LD HL, txt_game_mode
    CALL PRINT_STRING

    ; Update sprites
    CALL UPDATE_SPRITES_TO_VRAM
    RET

RENDER_PAUSE:
    ; Render pause overlay
    ; Position in center
    LD DE, NAMETBL + (12 * 32) + 14
    LD HL, txt_paused
    CALL PRINT_STRING
    RET

RENDER_GAME_OVER:
    ; Render game over screen
    CALL CLS                   ; Clear screen

    ; Position for game over message
    LD DE, NAMETBL + (10 * 32) + 12
    LD HL, txt_game_over
    CALL PRINT_STRING

    ; Position for instruction
    LD DE, NAMETBL + (14 * 32) + 8
    LD HL, txt_press_any_key
    CALL PRINT_STRING
    RET

RENDER_CREDITS:
    ; Render credits screen
    CALL CLS                   ; Clear screen

    ; Position for credits
    LD DE, NAMETBL + (8 * 32) + 8
    LD HL, txt_credits
    CALL PRINT_STRING
    RET

; Text strings for display
txt_system_init:    DB "MSX SYSTEM READY", 0
txt_debug_state:    DB "UNKNOWN STATE", 0
txt_main_title:     DB "MSX GAME ENGINE", 0
txt_start_game:     DB "1. START GAME", 0
txt_exit_game:      DB "2. EXIT", 0
txt_game_mode:      DB "GAME MODE", 0
txt_paused:         DB "PAUSED", 0
txt_game_over:      DB "GAME OVER", 0
txt_press_any_key:  DB "PRESS ANY KEY", 0
txt_credits:        DB "CREDITS: MIDEAS MSX", 0

    END                 ; End of assembl