;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; BASICENEMY - UNITED FILES ASM (ALL-IN-ONE)
;; Generated by MSX Retro Game IDE
;; Konami Cartridge ROM Format
;; Target: MSX1
;; Base Address: #4000 (Konami Standard)
;; Generated: 2025-09-14T18:50:36.251Z
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Memory Organization
    ORG #4000                ; Konami cartridge standard address

; ==================================================================
; KONAMI CARTRIDGE ROM HEADER
; ==================================================================
    DB "AB"              ; ROM signature
    DW INIT_KONAMI       ; Init address
    DW 0,0,0,0,0         ; Statement, Device, Text, Reserved

INIT_KONAMI:
    ; Konami cartridge initialization
    DI                   ; Disable interrupts during init

    ; Initialize stack for Konami cartridge
    LD SP, #F380

    ; Initialize RAM variables area (MSX Standard)
    ; Clear RAM from #C000 to #FFFF (project variables zone)
    LD HL, #C000
    LD DE, #C001
    LD BC, #3FFF         ; Clear 16KB of RAM
    LD (HL), 0
    LDIR

    ; Jump to main game (init functions are defined later)
    JP MAIN_GAME_START

; VDP initialization for Konami cartridge
INIT_VDP_KONAMI:
    ; Initialize VDP for Konami cartridge
    ; Setup screen mode 2
    RET

; Sound initialization for Konami cartridge
INIT_SOUND_KONAMI:
    ; Initialize sound system
    RET

; ==================================================================
; MSX SYSTEM CONSTANTS (INLINE)
; ==================================================================

; BIOS Addresses
CHGMOD  EQU #005F        ; Change screen mode
CLS     EQU #00C3        ; Clear screen
CHPUT   EQU #00A2        ; Character output
GTSTCK  EQU #00D5        ; Get joystick status
GTTRIG  EQU #00D8        ; Get trigger status
KILBUF  EQU #0156        ; Kill keyboard buffer

; VDP Addresses
VDPDR   EQU #0098        ; VDP Data Register
VDPSR   EQU #0099        ; VDP Status Register

; VRAM Layout (Screen 2)
PATTERNTBL  EQU #0000    ; Pattern table
COLORTBL    EQU #2000    ; Color table
NAMETBL     EQU #1800    ; Name table
SPRATR      EQU #1B00    ; Sprite attribute table
SPRPAT      EQU #3800    ; Sprite pattern table

; Game Constants
MAX_SPRITES     EQU 32
SCREEN_WIDTH    EQU 32
SCREEN_HEIGHT   EQU 24
TILE_SIZE       EQU 8


; ####################################################################
; #                                                                  #
; #                    RAM VARIABLES SECTION                        #
; #                                                                  #
; ####################################################################
; # IMPORTANT: This section defines VARIABLE ADDRESSES ONLY         #
; #            No actual data is stored in ROM                       #
; #            All variables are in MSX RAM area #C000-#FFFF         #
; ####################################################################

; ==================================================================
; RAM VARIABLE MAP - MSX CARTRIDGE STANDARD
; ==================================================================
; Memory Layout:
;   #C000-#C0FF : System Variables (256 bytes)
;   #C100-#C3FF : Game Variables (768 bytes)
;   #C400-#CFFF : Buffer Areas (3KB)
;   #D000-#FFFF : Free RAM (12KB)
; ==================================================================

; ------------------------------------------------------------------
; SYSTEM VARIABLES BLOCK (#C000-#C0FF)
; ------------------------------------------------------------------
input_state         EQU #C000   ; Current joystick/keyboard state
prev_input_state    EQU #C001   ; Previous input state for edge detection
vdp_status          EQU #C002   ; VDP status register cache
interrupt_flag      EQU #C003   ; Interrupt handling flag

; ------------------------------------------------------------------
; SPRITE SYSTEM VARIABLES (#C010-#C08F)
; ------------------------------------------------------------------
active_sprite_count EQU #C010   ; Number of sprites currently active
sprite_x_pos        EQU #C011   ; Sprite X positions (32 bytes: #C011-#C030)
sprite_y_pos        EQU #C031   ; Sprite Y positions (32 bytes: #C031-#C050)
sprite_pattern      EQU #C051   ; Sprite pattern IDs (32 bytes: #C051-#C070)
sprite_color        EQU #C071   ; Sprite colors (32 bytes: #C071-#C090)

; ------------------------------------------------------------------
; SCREEN & GRAPHICS VARIABLES (#C090-#C09F)
; ------------------------------------------------------------------
current_screen_id   EQU #C090   ; Currently displayed screen ID
screen_dirty_flag   EQU #C091   ; Flag: screen needs redraw (0=clean, 1=dirty)
scroll_x            EQU #C092   ; Horizontal scroll offset
scroll_y            EQU #C093   ; Vertical scroll offset

; ------------------------------------------------------------------
; GAME STATE VARIABLES (#C0A0-#C0BF)
; ------------------------------------------------------------------
frame_counter       EQU #C0A0   ; Frame counter (16-bit: #C0A0-#C0A1)
random_seed         EQU #C0A2   ; Random number generator seed (16-bit)
game_state          EQU #C0A4   ; Current game state (menu/game/pause/etc)
level_id            EQU #C0A5   ; Current level ID
lives_remaining     EQU #C0A6   ; Player lives
difficulty_level    EQU #C0A7   ; Game difficulty setting

; ------------------------------------------------------------------
; PLAYER VARIABLES (#C0C0-#C0DF)
; ------------------------------------------------------------------
player_x            EQU #C0C0   ; Player X position (16-bit: #C0C0-#C0C1)
player_y            EQU #C0C2   ; Player Y position (16-bit: #C0C2-#C0C3)
player_health       EQU #C0C4   ; Player health points
player_score        EQU #C0C5   ; Player score (16-bit: #C0C5-#C0C6)
player_power        EQU #C0C7   ; Player power level
player_direction    EQU #C0C8   ; Player facing direction

; ------------------------------------------------------------------
; TEMPORARY & CALCULATION VARIABLES (#C0E0-#C0FF)
; ------------------------------------------------------------------
temp_word_1         EQU #C0E0   ; Temporary 16-bit storage (#C0E0-#C0E1)
temp_word_2         EQU #C0E2   ; Temporary 16-bit storage (#C0E2-#C0E3)
temp_byte_1         EQU #C0E4   ; Temporary 8-bit storage
temp_byte_2         EQU #C0E5   ; Temporary 8-bit storage
temp_address        EQU #C0E6   ; Temporary address pointer (16-bit)
loop_counter        EQU #C0E8   ; General purpose loop counter

; ####################################################################
; #                    END OF VARIABLES SECTION                     #
; ####################################################################
; # Memory usage: System variables occupy #C000-#C0FF (256 bytes)   #
; # Remaining RAM: #C100-#FFFF (15.75KB available for game data)    #
; ####################################################################

; ==================================================================
; MAIN PROGRAM (KONAMI CARTRIDGE)
; ==================================================================

MAIN_GAME_START:
    ; Set screen mode for game
    LD A, 2              ; Screen 2 for MSX1
    CALL CHGMOD

    ; Clear screen
    CALL CLS

    ; Initialize game systems
    CALL INIT_GAME_SYSTEMS

    ; Initialize Game Flow system inline (avoid forward reference)
    XOR A
    LD (current_flow_state), A
    LD (prev_flow_state), A

    ; Start with main menu
    LD A, FLOW_STATE_MAIN_MENU
    LD (current_flow_state), A

    ; Main game loop
MAIN_LOOP:
    HALT                 ; Wait for V-Blank

    ; Update current game state
    CALL UPDATE_CURRENT_STATE

    ; Handle input
    CALL HANDLE_INPUT

    ; Update game systems
    CALL UPDATE_GAME_SYSTEMS

    ; Render frame
    CALL RENDER_FRAME

    ; Loop forever
    JP MAIN_LOOP


; ==================================================================
; GAME FLOW SYSTEM
; ==================================================================

; Game Flow State Constants
FLOW_STATE_MAIN_MENU    EQU 0
FLOW_STATE_GAME         EQU 1
FLOW_STATE_GAME_OVER    EQU 2

CHANGE_FLOW_STATE:
    ; Change Game Flow state
    ; A = new state
    LD (current_flow_state), A
    RET

; Game Flow Variables
current_flow_state:     DB 0
prev_flow_state:        DB 0

; ==================================================================
; GAME SYSTEMS (DYNAMIC GENERATION)
; Only systems needed for this project are included
; ==================================================================

INIT_GAME_SYSTEMS:
    ; Initialize systems dynamically based on project assets
    CALL INIT_INPUT_SYSTEM    ; Always needed
    CALL INIT_SPRITE_SYSTEM   ; Project has 1 sprites
    CALL INIT_TILE_SYSTEM     ; Project has 1 tiles
    CALL INIT_SCREEN_SYSTEM   ; Project has 1 screens
    CALL INIT_COLLISION_SYSTEM ; Project has collision layers
    RET

INIT_INPUT_SYSTEM:
    ; Initialize input handling
    XOR A
    LD (input_state), A
    LD (prev_input_state), A
    RET

INIT_SPRITE_SYSTEM:
    ; Initialize sprite system for 1 sprites
    ; NOTE: Individual sprite patterns are loaded by name
    ; Use SPRITE_[NAME]_F[FRAME]_C[COLOR]_LAYER labels generated by sprite assets
    ; Clear sprite attributes table
    LD HL, SPRATR
    LD DE, SPRATR+1
    LD BC, 127      ; Clear all 32 sprites × 4 bytes = 128 bytes
    LD (HL), #D1    ; Y=209 (off-screen position)
    LDIR
    ; Initialize sprite counter
    XOR A
    LD (active_sprite_count), A
    RET

INIT_TILE_SYSTEM:
    ; Initialize MSX Screen 2 tile system with 3 banks
    ; Load all 3 pattern banks to their VRAM locations
    CALL LOAD_PATTERN_BANK0       ; Bank 0 (Lines 0-7)
    CALL LOAD_PATTERN_BANK1       ; Bank 1 (Lines 8-15)
    CALL LOAD_PATTERN_BANK2       ; Bank 2 (Lines 16-23)
    ; Load all 3 color banks to their VRAM locations
    CALL LOAD_COLOR_BANK0         ; Bank 0 colors
    CALL LOAD_COLOR_BANK1         ; Bank 1 colors
    CALL LOAD_COLOR_BANK2         ; Bank 2 colors
    RET

; MSX Screen 2 Bank Loading Functions
LOAD_PATTERN_BANK0:
    ; Load pattern bank 0 to VRAM #0000
    LD HL, TILE_PATTERN_BANK0
    LD DE, VRAM_PATTERN_BANK0
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

LOAD_PATTERN_BANK1:
    ; Load pattern bank 1 to VRAM #0800
    LD HL, TILE_PATTERN_BANK1
    LD DE, VRAM_PATTERN_BANK1
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

LOAD_PATTERN_BANK2:
    ; Load pattern bank 2 to VRAM #1000
    LD HL, TILE_PATTERN_BANK2
    LD DE, VRAM_PATTERN_BANK2
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

LOAD_COLOR_BANK0:
    ; Load color bank 0 to VRAM #2000
    LD HL, TILE_COLOR_BANK0
    LD DE, VRAM_COLOR_BANK0
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

LOAD_COLOR_BANK1:
    ; Load color bank 1 to VRAM #2800
    LD HL, TILE_COLOR_BANK1
    LD DE, VRAM_COLOR_BANK1
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

LOAD_COLOR_BANK2:
    ; Load color bank 2 to VRAM #3000
    LD HL, TILE_COLOR_BANK2
    LD DE, VRAM_COLOR_BANK2
    LD BC, 256 * 8                ; Max 256 patterns × 8 bytes
    CALL COPY_TO_VRAM
    RET

INIT_SCREEN_SYSTEM:
    ; Initialize screen system for 1 screens
    ; Set current screen to first one
    XOR A
    LD (current_screen_id), A
    CALL LOAD_CURRENT_SCREEN
    RET

INIT_COLLISION_SYSTEM:
    ; Initialize collision detection system
    ; Load behavior maps for collision detection
    ; Setup collision detection variables
    RET

UPDATE_CURRENT_STATE:
    ; Update current game state
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, UPDATE_MAIN_MENU
    CP FLOW_STATE_GAME
    JP Z, UPDATE_GAME
    CP FLOW_STATE_GAME_OVER
    JP Z, UPDATE_GAME_OVER
    RET

UPDATE_MAIN_MENU:
    ; Update main menu logic
    ; Handle menu navigation
    RET

UPDATE_GAME:
    ; Update game logic
    CALL UPDATE_SPRITES       ; Update sprite system
    CALL UPDATE_COLLISIONS    ; Check collisions with behavior maps
    RET

UPDATE_GAME_OVER:
    ; Update game over logic
    ; Handle game over screen
    RET

HANDLE_INPUT:
    ; Handle player input
    CALL GTSTCK
    LD (input_state), A
    RET

UPDATE_GAME_SYSTEMS:
    ; Update only systems that exist in this project
    CALL UPDATE_SPRITES       ; Project has sprites
    CALL UPDATE_COLLISIONS    ; Project has collision layers
    RET

UPDATE_SPRITES:
    ; Update sprite positions and animations
    ; Sprite update logic here
    RET

UPDATE_COLLISIONS:
    ; Check for collisions between sprites and behavior maps
    ; Use BEHAVIOR_TABLE to access behavior data for collision detection
    ; Collision detection logic here
    RET

LOAD_CURRENT_SCREEN:
    ; Load screen based on current_screen_id
    LD A, (current_screen_id)
    ; Screen loading logic here
    RET

COPY_TO_VRAM:
    ; Copy BC bytes from HL to VRAM address DE
    ; Set VRAM write address
    LD A, E
    OUT (#99), A
    LD A, D
    OR #40
    OUT (#99), A
COPY_LOOP:
    LD A, (HL)
    OUT (#98), A
    INC HL
    DEC BC
    LD A, B
    OR C
    JR NZ, COPY_LOOP
    RET

RENDER_FRAME:
    ; Render current frame
    ; Frame rendering logic here
    RET

; ==================================================================
; END OF PROGRAM - MSX KONAMI CARTRIDGE
; ==================================================================
; Memory Layout Summary:
;   #4000-#BFFF : ROM Code & Data (32KB)
;   #C000-#FFFF : RAM Variables & Buffers (16KB)
;   Variables are defined with EQU addresses, not stored in ROM
; ==================================================================

    END                 ; End of assembly

; ==================================================================
; ASSET DATA (DYNAMIC GENERATION)
; Generated only for assets that exist in project
; ==================================================================

; ================================================================
; SCREEN LAYOUT DATA (MSX Screen 2 Compatible)
; ================================================================
; IMPORTANT: MSX Screen 2 uses 3 banks of 256 patterns each:
;   - Lines 0-7:   Use patterns from BANK0 (VRAM #0000/#2000)
;   - Lines 8-15:  Use patterns from BANK1 (VRAM #0800/#2800)
;   - Lines 16-23: Use patterns from BANK2 (VRAM #1000/#3000)
;
; The same pattern index (e.g., #05) can display different
; graphics depending on which screen line it appears on.
; ================================================================

SCREEN_COUNT    EQU 1

;; MAP: pantalla1 (32x24 tiles)
;; Total size: 768 bytes

SCREEN_PANTALLA1_WIDTH     EQU 32
SCREEN_PANTALLA1_HEIGHT    EQU 24
SCREEN_PANTALLA1_SIZE      EQU 768

SCREEN_PANTALLA1_LAYOUT:
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
SCREEN_TABLE:
    DW SCREEN_PANTALLA1_LAYOUT

; Behavior/Collision Data from Screen Editor (using Behavior ASM functionality)
BEHAVIOR_SCREEN_COUNT    EQU 1

;; BEHAVIOR MAP: pantalla1 (32x24 tiles)
;; Total size: 768 bytes (Map IDs 0-255)
;; Data format: HEX

BEHAVIOR_PANTALLA1_WIDTH     EQU 32
BEHAVIOR_PANTALLA1_HEIGHT    EQU 24
BEHAVIOR_PANTALLA1_SIZE      EQU 768

BEHAVIOR_PANTALLA1_DATA:
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10

;; End of Behavior Map Data for pantalla1
BEHAVIOR_TABLE:
    DW BEHAVIOR_PANTALLA1_DATA

; Sprite Data from Sprite Editor (using Sprite ASM functionality)
SPRITE_COUNT    EQU 1

; Sprite 0: bot1
SPRITE_BOT1_ID    EQU 0

;; Sprite: bot1
;; Total Frames: 2
;; Size: 16x16
;; Background Color (not exported as a layer): rgba(0,0,0,0)
;; Drawable Palette (Hex): C0=#000000, C1=#3EB847, C2=#FC584A, C3=#FFFFFF

SPRITE_BOT1_WIDTH     EQU 16
SPRITE_BOT1_HEIGHT    EQU 16
SPRITE_BOT1_FRAMES    EQU 2

;; ---- Sprite Frame: bot1_F0 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F0_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#7F,#B0,#CF,#B0,#8F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#BD
    DB #6F,#BD,#6F,#F0,#00,#00,#0C,#1C,#FC,#1C,#FC,#07,#C0,#07,#C0,#07

;; ---- End of Frame: bot1_F0 ----

;; ---- Sprite Frame: bot1_F1 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F1_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#FF,#B0,#CF,#B0,#0F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#F0
    DB #6F,#F0,#6E,#70,#00,#00,#01,#80,#01,#80,#01,#80,#01,#E0,#01,#E0

;; ---- End of Frame: bot1_F1 ----

; Sprite Pattern References
; bot1: SPRITE_BOT1_* (see individual frame/layer labels above)

; ================================================================
; MSX SCREEN 2 TILE BANK SYSTEM (3 banks of 256 patterns each)
; Bank 0: Lines 0-7   (VRAM Pattern: #0000, Color: #2000)
; Bank 1: Lines 8-15  (VRAM Pattern: #0800, Color: #2800)
; Bank 2: Lines 16-23 (VRAM Pattern: #1000, Color: #3000)
; ================================================================

TILE_COUNT      EQU 1
TILE_SIZE       EQU 8    ; Character block size
TILE_BYTES      EQU 8    ; Bytes per character block

TILE_BRICK1_ID    EQU 0

; ================================================================
; PATTERN DATA - BANK0 (Lines 0-7)
; VRAM Address: #0000
; Tiles in this bank: 1/256
; ================================================================
TILE_PATTERN_BANK0:
    ; Pattern data for BRICK1 (BANK0)
    DB #00,#7F,#7F,#7F,#00,#FB,#FB,#FB,#00,#BF,#BF,#BF,#00,#FD,#FD,#FD
    DB #00,#7F,#7F,#7F,#00,#FB,#FB,#FB,#00,#BF,#BF,#BF,#00,#FD,#FD,#FD

; ================================================================
; PATTERN DATA - BANK1 (Lines 8-15)
; VRAM Address: #0800
; Tiles in this bank: 0/256
; ================================================================
TILE_PATTERN_BANK1:

; ================================================================
; PATTERN DATA - BANK2 (Lines 16-23)
; VRAM Address: #1000
; Tiles in this bank: 0/256
; ================================================================
TILE_PATTERN_BANK2:

; ================================================================
; COLOR DATA - BANK0 (Lines 0-7)
; VRAM Address: #2000
; Tiles in this bank: 1/256
; ================================================================
TILE_COLOR_BANK0:
    ; Color data for BRICK1 (BANK0)
    DB #61,#61,#61,#61,#61,#61,#61,#91,#61,#B1,#61,#61,#61,#61,#61,#61
    DB #61,#61,#61,#61,#61,#61,#61,#61,#61,#61,#B1,#B1,#61,#61,#61,#61

; ================================================================
; COLOR DATA - BANK1 (Lines 8-15)
; VRAM Address: #2800
; Tiles in this bank: 0/256
; ================================================================
TILE_COLOR_BANK1:

; ================================================================
; COLOR DATA - BANK2 (Lines 16-23)
; VRAM Address: #3000
; Tiles in this bank: 0/256
; ================================================================
TILE_COLOR_BANK2:

; MSX Screen 2 Bank Loading Constants
VRAM_PATTERN_BANK0    EQU #0000
VRAM_COLOR_BANK0      EQU #2000
VRAM_PATTERN_BANK1    EQU #0800
VRAM_COLOR_BANK1      EQU #2800
VRAM_PATTERN_BANK2    EQU #1000
VRAM_COLOR_BANK2      EQU #3000

