; ==================================================================
; BASICENEMY - UNIFIED FILE
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
; ==================================================================

; ==================================================================
; MSX CARTRIDGE ROM HEADER
; File: header.asm
; Description: Standard MSX cartridge initialization
; ==================================================================

    ORG #4000           ; MSX cartridge start address

; ==================================================================
; CARTRIDGE HEADER
; ==================================================================
    DB "AB"             ; MSX cartridge signature
    DW INIT_ROM         ; Initialization address
    DW 0                ; Statement handler (not used)
    DW 0                ; Device handler (not used)
    DW 0                ; Text handler (not used)
    DW 0                ; Reserved
    DW 0                ; Reserved
    DW 0                ; Reserved

; ==================================================================
; ROM INITIALIZATION ENTRY POINT
; ==================================================================
INIT_ROM:
    ; Disable interrupts during initialization
    DI

    ; Initialize stack for cartridge
    LD SP, #F380

    ; Initialize project RAM variables area (SAFE - only project variables)
    ; Clear ONLY project variables zone, NOT system variables (#F380+)
    LD HL, input_state           ; First project variable
    LD DE, input_state+1         ; Next byte
    LD BC, RAM_USAGE_END - input_state - 1  ; Only to end of project vars
    LD (HL), 0
    LDIR

    ; Initialize VDP for Screen 2 using BIOS
    LD A, 2
    CALL CHGMOD         ; Set Screen 2 mode (BIOS handles everything)

    ; Clear screen
    CALL CLS

    ; Enable interrupts
    EI

    ; Jump to main program
    JP MAIN_PROGRAM

; ==================================================================
; END OF HEADER
; ==================================================================


; ==================================================================
; MSX BIOS FUNCTIONS AND ADDRESSES
; File: bios.asm
; Description: Standard MSX BIOS function definitions
; ==================================================================

; ==================================================================
; MAIN BIOS FUNCTIONS
; ==================================================================

; Screen and Display
CHGMOD  EQU #005F        ; Change screen mode (A=mode)
CLS     EQU #00C3        ; Clear screen
POSIT   EQU #00C6        ; Position cursor (H=X, L=Y)
ERAFNK  EQU #00CC        ; Erase function keys
DSPFNK  EQU #00CF        ; Display function keys
DISSCR  EQU #0041        ; Disable screen (prevent flicker)
ENASCR  EQU #0044        ; Enable screen
INITXT  EQU #006C        ; Initialize text mode
INIT32  EQU #006F        ; Initialize screen mode

; Character I/O
CHPUT   EQU #00A2        ; Character output (A=char)
CHGET   EQU #009F        ; Character input
CHSNS   EQU #009C        ; Character sense (check key)
BREAKX  EQU #00B7        ; Check CTRL+STOP
ISCNTC  EQU #00BA        ; Check CTRL+C

; String I/O
OUTDO   EQU #005A        ; String output (HL=string)

; Input Devices
GTSTCK  EQU #00D5        ; Get joystick status (A=port)
GTTRIG  EQU #00D8        ; Get trigger status (A=port)
GTPAD   EQU #00DB        ; Get paddle (A=port)
GTPDL   EQU #00DE        ; Get paddle value
SNSMAT  EQU #0141        ; Sense matrix (A=row)
KILBUF  EQU #0156        ; Kill keyboard buffer

; Sound
GICINI  EQU #0090        ; Initialize PSG
WRTPSG  EQU #0093        ; Write PSG register (A=reg, E=value)
RDPSG   EQU #0096        ; Read PSG register (A=reg)

; Graphics VDP
GRPPRT  EQU #0089        ; Print in graphic mode
SETGRP  EQU #007E        ; Set graphic mode

; Memory Transfer
LDIRVM  EQU #005C        ; Block transfer from CPU to VRAM
LDIRMV  EQU #0059        ; Block transfer from VRAM to CPU
WRTVDP  EQU #0047        ; Write to VDP register
WRTVRM  EQU #004D        ; Write data to VRAM (A=data, HL=address)

; File I/O (Disk BIOS)
DSKIO   EQU #004A        ; Disk I/O
DSKCHF  EQU #004D        ; Disk change flag

; Math
GETYPR  EQU #0053        ; Get type of variable

; ==================================================================
; VDP PORTS AND REGISTERS
; ==================================================================

; VDP Data/Status Ports
VDPDR   EQU #0098        ; VDP Data Register (Port 0)
VDPSR   EQU #0099        ; VDP Status Register (Port 1)

; VDP Registers (use with VDPSR)
VDP_R0  EQU 0            ; Mode register 0
VDP_R1  EQU 1            ; Mode register 1
VDP_R2  EQU 2            ; Name table base address
VDP_R3  EQU 3            ; Color table base address
VDP_R4  EQU 4            ; Pattern table base address
VDP_R5  EQU 5            ; Sprite attribute table
VDP_R6  EQU 6            ; Sprite pattern table
VDP_R7  EQU 7            ; Text/border color

; ==================================================================
; END OF BIOS DEFINITIONS
; ==================================================================


; ==================================================================
; MSX SYSTEM CONSTANTS
; File: constants.asm
; Description: MSX hardware constants and project-specific definitions
; ==================================================================

; ==================================================================
; VRAM LAYOUT - SCREEN 2 MODE
; ==================================================================

; Pattern Generator Table (PGT) - 3 Banks
CHRTBL2 EQU #0000        ; Pattern table base address (Bank 0)
; Bank 1: CHRTBL2 + #800   (#0800)
; Bank 2: CHRTBL2 + #1000  (#1000)

; Color Attribute Table (CAT) - 3 Banks
CLRTBL2 EQU #2000        ; Color table base address (Bank 0)
; Bank 1: CLRTBL2 + #800   (#2800)
; Bank 2: CLRTBL2 + #1000  (#3000)

; Other VRAM Areas
NAMETBL EQU #1800        ; Name table base address
SPRATR  EQU #1B00        ; Sprite attribute table
SPRPAT  EQU #3800        ; Sprite pattern table

; ==================================================================
; SCREEN MODES
; ==================================================================
SCREEN0     EQU 0        ; 40x24 text
SCREEN1     EQU 1        ; 32x24 text/graphics
SCREEN2     EQU 2        ; 256x192 graphics
SCREEN3     EQU 3        ; 64x48 multicolor

; ==================================================================
; SCREEN DIMENSIONS
; ==================================================================
SCREEN_WIDTH    EQU 32   ; Tiles horizontales (Screen 1/2)
SCREEN_HEIGHT   EQU 24   ; Tiles verticales
TILE_SIZE       EQU 8    ; 8x8 pixels por tile

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
MAX_SPRITES     EQU 32   ; Máximo sprites por pantalla
SPRITE_SIZE     EQU 8    ; 8x8 o 16x16 (según modo)
SPRITE_INVISIBLE EQU #D1 ; Y=209 (sprite fuera de pantalla)

; ==================================================================
; MSX COLORS
; ==================================================================
TRANSPARENT EQU 0
BLACK       EQU 1
MEDIUM_GREEN EQU 2
LIGHT_GREEN EQU 3
DARK_BLUE   EQU 4
LIGHT_BLUE  EQU 5
DARK_RED    EQU 6
CYAN        EQU 7
MEDIUM_RED  EQU 8
LIGHT_RED   EQU 9
DARK_YELLOW EQU 10
LIGHT_YELLOW EQU 11
DARK_GREEN  EQU 12
MAGENTA     EQU 13
GRAY        EQU 14
WHITE       EQU 15

; ==================================================================
; INPUT CONSTANTS
; ==================================================================

; Joystick Directions
STICK_UP    EQU 1
STICK_UPRIGHT EQU 2
STICK_RIGHT EQU 3
STICK_DOWNRIGHT EQU 4
STICK_DOWN  EQU 5
STICK_DOWNLEFT EQU 6
STICK_LEFT  EQU 7
STICK_UPLEFT EQU 8
STICK_CENTER EQU 0

; Trigger Constants
TRIG_A      EQU #10      ; Trigger A (Fire)
TRIG_B      EQU #20      ; Trigger B (MSX2+)

; ==================================================================
; GAME FLOW STATES (PROJECT-SPECIFIC)
; ==================================================================

; Basic Game Flow States (always available)
FLOW_STATE_MAIN_MENU    EQU 0
FLOW_STATE_GAME         EQU 1
FLOW_STATE_PAUSE        EQU 2
FLOW_STATE_GAME_OVER    EQU 3
FLOW_STATE_CREDITS      EQU 4

; Using default game flow system


; ==================================================================
; PROJECT-SPECIFIC CONSTANTS
; ==================================================================

; Detected Assets
TOTAL_SPRITES           EQU 1
TOTAL_TILES             EQU 1
TOTAL_SCREENS           EQU 1

; ==================================================================
; END OF CONSTANTS
; ==================================================================


; ==================================================================
; RAM VARIABLES DEFINITIONS
; File: variables.asm
; Description: Dynamic variable allocation using EQU addresses
; Generated based on project analysis
; ==================================================================

; ==================================================================
; CORE SYSTEM VARIABLES (ALWAYS PRESENT)
; ==================================================================
input_state         EQU #C000   ; Current joystick/keyboard state
prev_input_state    EQU #C001   ; Previous input state
current_flow_state  EQU #C002   ; Current game flow state
prev_flow_state     EQU #C003   ; Previous game flow state
frame_counter       EQU #C004   ; Frame counter (16-bit)

; ==================================================================
; SPRITE SYSTEM VARIABLES (1 sprites detected)
; ==================================================================
active_sprite_count EQU #C006   ; Number of sprites currently active
sprite_x_pos        EQU #C007   ; Sprite X positions (32 bytes)
sprite_y_pos        EQU #C027   ; Sprite Y positions (32 bytes)
sprite_pattern      EQU #C047   ; Sprite pattern IDs (32 bytes)
sprite_color        EQU #C067   ; Sprite colors (32 bytes)

; ==================================================================
; SCREEN SYSTEM VARIABLES (1 screens detected)
; ==================================================================
current_screen_id   EQU #C087   ; Currently displayed screen ID
screen_dirty_flag   EQU #C088   ; Screen needs redraw flag

; ==================================================================
; TEMPORARY VARIABLES (ALWAYS NEEDED)
; ==================================================================
temp_word_1         EQU #C089   ; Temporary 16-bit storage
temp_word_2         EQU #C08B   ; Temporary 16-bit storage
temp_byte_1         EQU #C08D   ; Temporary 8-bit storage
temp_byte_2         EQU #C08E   ; Temporary 8-bit storage

; ==================================================================
; END OF VARIABLES
; ==================================================================
RAM_USAGE_END       EQU #C08F   ; End of project variables (143 bytes used)

; ==================================================================
; MEMORY SAFETY CHECK
; ==================================================================
; RAM Layout:
;   #C000-#C08F: Project variables (143 bytes)
;   #C08F-#F37F: Free RAM (~13041 bytes available)
;   #F380-#FFFF: MSX System variables (DO NOT TOUCH)
; ==================================================================


; ==================================================================
; TILE PATTERN DATA
; File: patterns.asm
; Description: Tile pattern definitions for MSX Screen 2
; 1 tiles detected
; ==================================================================

; ==================================================================
; TILE PATTERN BANK 0 (Base patterns)
; ==================================================================
TILE_PATTERN_BANK0:
    ; Tile 0: brick1 (16x16px)
    DB #00, #7F, #7F, #7F, #00, #FB, #FB, #FB, #00, #BF, #BF, #BF, #00, #FD, #FD, #FD, #00, #7F, #7F, #7F, #00, #FB, #FB, #FB, #00, #BF, #BF, #BF, #00, #FD, #FD, #FD


; ==================================================================
; PATTERN LOADING FUNCTIONS
; ==================================================================
LOAD_PATTERN_BANK0:
    ; Load pattern bank 0 to VRAM (base patterns)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0
    LD DE, CHRTBL2                ; VRAM pattern table bank 0
    LD BC, 1 * 8    ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_PATTERN_BANK1:
    ; Load pattern bank 1: same patterns as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0     ; Same source as Bank 0
    LD DE, CHRTBL2 + #800         ; VRAM pattern table bank 1 (+#800 offset)
    LD BC, 1 * 8    ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_PATTERN_BANK2:
    ; Load pattern bank 2: same patterns as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_PATTERN_BANK0     ; Same source as Bank 0
    LD DE, CHRTBL2 + #1000        ; VRAM pattern table bank 2 (+#1000 offset)
    LD BC, 1 * 8    ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF PATTERN DATA
; ==================================================================


; ==================================================================
; TILE COLOR DATA
; File: colors.asm
; Description: Tile color definitions for MSX Screen 2
; 1 tiles detected
; ==================================================================

; ==================================================================
; TILE COLOR BANK 0 (Base colors)
; ==================================================================
TILE_COLOR_BANK0:
    ; Tile 0: brick1 colors (fg/bg pairs)
    DB #61, #61, #61, #61, #61, #61, #61, #91, #61, #B1, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #61, #B1, #B1, #61, #61, #61, #61


; ==================================================================
; COLOR LOADING FUNCTIONS
; ==================================================================
LOAD_COLOR_BANK0:
    ; Load color bank 0 to VRAM (base colors)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0
    LD DE, CLRTBL2                ; VRAM color table bank 0
    LD BC, 1 * 8     ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_COLOR_BANK1:
    ; Load color bank 1: same colors as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0       ; Same source as Bank 0
    LD DE, CLRTBL2 + #800         ; VRAM color table bank 1 (+#800 offset)
    LD BC, 1 * 8     ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

LOAD_COLOR_BANK2:
    ; Load color bank 2: same colors as bank 0 (MSX Screen 2 standard)
    ; BIOS LDIRVM handles timing automatically
    LD HL, TILE_COLOR_BANK0       ; Same source as Bank 0
    LD DE, CLRTBL2 + #1000        ; VRAM color table bank 2 (+#1000 offset)
    LD BC, 1 * 8     ; 1 patterns × 8 bytes
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF COLOR DATA
; ==================================================================


; ==================================================================
; SPRITE DATA
; File: sprites.asm
; Description: Sprite pattern and animation data
; 1 sprites detected
; ==================================================================

; ==================================================================
; SPRITE PATTERN DATA
; ==================================================================

; Sprite 0: bot1
;; Sprite: bot1
;; Total Frames: 2
;; Size: 16x16
;; Background Color (not exported as a layer): rgba(0,0,0,0)
;; Drawable Palette (Hex): C0=#000000, C1=#3EB847, C2=#FC584A, C3=#FFFFFF

SPRITE_BOT1_WIDTH     EQU 16
SPRITE_BOT1_HEIGHT    EQU 16
SPRITE_BOT1_FRAMES    EQU 2

;; ---- Sprite Frame: bot1_F0 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F0_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#7F,#B0,#CF,#B0,#8F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#BD
    DB #6F,#BD,#6F,#F0,#00,#00,#0C,#1C,#FC,#1C,#FC,#07,#C0,#07,#C0,#07

;; ---- End of Frame: bot1_F0 ----

;; ---- Sprite Frame: bot1_F1 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
BOT1_F1_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #1F,#E0,#FF,#B0,#CF,#B0,#0F,#F0,#07,#E0,#00,#00,#2F,#F0,#6F,#F0
    DB #6F,#F0,#6E,#70,#00,#00,#01,#80,#01,#80,#01,#80,#01,#E0,#01,#E0

;; ---- End of Frame: bot1_F1 ----


; Unified pattern label for sprite 0 (for easy reference in loading code)
SPRITE_0_PATTERN EQU BOT1_F0_LAYER3

; ==================================================================
; SPRITE INITIALIZATION FUNCTIONS
; ==================================================================

INIT_SPRITES:
    ; Initialize sprite system
    CALL CLEAR_ALL_SPRITES

    ; Load sprite patterns to VRAM
    CALL LOAD_SPRITE_PATTERNS

    ; Initialize sprite positions (all invisible by default)
    XOR A
    LD (active_sprite_count), A

    RET

LOAD_SPRITE_PATTERNS:
    ; Load all sprite patterns to VRAM sprite pattern table

    ; Load sprite 0: bot1 (BIOS LDIRVM handles timing)
    LD HL, SPRITE_0_PATTERN
    LD DE, SPRPAT + (0 * 32) ; Each 16x16 sprite = 32 bytes (4 patterns)
    LD BC, 32                       ; 16x16 sprite size
    CALL LDIRVM                     ; BIOS handles safe VRAM access
    RET

; ==================================================================
; SPRITE MANAGEMENT FUNCTIONS
; ==================================================================

; Show sprite (A = sprite number, B = X, C = Y, D = pattern, E = color)
SHOW_SPRITE:
    PUSH BC                       ; Preserve parameters
    PUSH DE

    ; Calculate sprite offset (A = sprite number)
    LD L, A                       ; L = sprite number
    LD H, 0                       ; HL = sprite number

    ; Set X position
    PUSH HL
    LD DE, sprite_x_pos
    ADD HL, DE                    ; HL points to sprite X position
    LD (HL), B                    ; Set X position
    POP HL

    ; Set Y position
    PUSH HL
    LD DE, sprite_y_pos
    ADD HL, DE                    ; HL points to sprite Y position
    LD (HL), C                    ; Set Y position
    POP HL

    ; Set pattern
    PUSH HL
    LD DE, sprite_pattern
    ADD HL, DE                    ; HL points to sprite pattern
    POP DE                        ; Restore original HL to DE
    PUSH DE                       ; Save it again
    LD (HL), D                    ; Set pattern number
    POP HL

    ; Set color
    LD DE, sprite_color
    ADD HL, DE                    ; HL points to sprite color
    POP DE                        ; Get original DE back
    LD (HL), E                    ; Set color

    POP BC                        ; Restore original parameters
    RET

; Clear all sprites (make them invisible)
CLEAR_ALL_SPRITES:
    LD HL, sprite_y_pos
    LD DE, sprite_y_pos+1
    LD BC, 31                     ; 32 sprites - 1
    LD (HL), SPRITE_INVISIBLE     ; Y=209 (invisible)
    LDIR
    RET

; Hide specific sprite (A = sprite number)
HIDE_SPRITE:
    LD HL, sprite_y_pos
    LD E, A
    LD D, 0
    ADD HL, DE                    ; HL points to sprite Y position
    LD (HL), SPRITE_INVISIBLE     ; Make invisible
    RET

; Update sprite positions to VRAM
UPDATE_SPRITES_TO_VRAM:
    ; Copy sprite attributes from RAM to VRAM
    ; BIOS LDIRVM handles timing automatically
    LD HL, sprite_y_pos
    LD DE, SPRATR
    LD BC, 128                    ; 32 sprites * 4 bytes each
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
SPRITE_ID_BOT1    EQU 0      ; Sprite: bot1

; ==================================================================
; END OF SPRITE DATA
; ==================================================================


; ==================================================================
; SCREEN MAPS
; File: screens.asm
; Description: Screen layout and map data
; ==================================================================

; ==================================================================
; SCREEN MAP CONSTANTS
; ==================================================================

SCREEN_PANTALLA1_0_ID EQU 0

; ==================================================================
; SCREEN MAP DATA
; ==================================================================

;; MAP: pantalla1_0 (32x24 tiles)
;; Total size: 768 bytes

;; --- TILE INDEX REFERENCES for PANTALLA1_0 ---
; Generated using exact Screen Editor "Download ASM" logic
; Byte values represent actual character codes in VRAM

SCREEN_PANTALLA1_0_WIDTH     EQU 32
SCREEN_PANTALLA1_0_HEIGHT    EQU 24
SCREEN_PANTALLA1_0_SIZE      EQU 768

SCREEN_PANTALLA1_0_LAYOUT:
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03,#02,#03
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01
    DB #00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01,#00,#01

;; BEHAVIOR MAP: pantalla1_0 (32x24 tiles)
;; Total size: 768 bytes (Map IDs 0-255)
;; Data format: HEX

BEHAVIOR_PANTALLA1_0_WIDTH     EQU 32
BEHAVIOR_PANTALLA1_0_HEIGHT    EQU 24
BEHAVIOR_PANTALLA1_0_SIZE      EQU 768

BEHAVIOR_PANTALLA1_0_DATA:
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
    DB #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10

;; End of Behavior Map Data for pantalla1_0

; ==================================================================
; SCREEN LOADING FUNCTIONS
; ==================================================================

LOAD_SCREEN:
    ; Load screen (A = screen ID)
    ; TODO: Implement screen loading logic
    RET

LOAD_SCREEN_PANTALLA1:
    ; Load pantalla1 screen (BIOS LDIRVM handles timing)
    LD HL, SCREEN_PANTALLA1_0_LAYOUT
    LD DE, NAMETBL
    LD BC, SCREEN_PANTALLA1_0_SIZE
    CALL LDIRVM                ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF SCREEN MAPS
; ==================================================================


; ==================================================================
; GAME COMPONENT SYSTEMS - MSX ECS ENGINE
; File: components.asm
; Description: Component systems based on Mideas React.js architecture
; Implements Position, Sprite, Movement, Collision, Input, and Behavior systems
; ==================================================================

; ==================================================================
; COMPONENT TYPE CONSTANTS (Based on ComponentDefinition analysis)
; ==================================================================

; Core Components (always present)
COMP_POSITION   EQU 0    ; Position component (x, y coordinates)
COMP_SPRITE     EQU 1    ; Sprite rendering component
COMP_MOVEMENT   EQU 2    ; Movement/velocity component
COMP_COLLISION  EQU 3    ; Collision detection component
COMP_INPUT      EQU 4    ; Input handling component
COMP_BEHAVIOR   EQU 5    ; AI/Logic behavior component
COMP_HEALTH     EQU 6    ; Health/damage component
COMP_ANIMATION  EQU 7    ; Animation state component

; Component flags for entity filtering
COMP_MASK_POSITION   EQU #01  ; Binary: 00000001
COMP_MASK_SPRITE     EQU #02  ; Binary: 00000010
COMP_MASK_MOVEMENT   EQU #04  ; Binary: 00000100
COMP_MASK_COLLISION  EQU #08  ; Binary: 00001000
COMP_MASK_INPUT      EQU #10  ; Binary: 00010000
COMP_MASK_BEHAVIOR   EQU #20  ; Binary: 00100000
COMP_MASK_HEALTH     EQU #40  ; Binary: 01000000
COMP_MASK_ANIMATION  EQU #80  ; Binary: 10000000

; ==================================================================
; COMPONENT DATA STRUCTURES (Entity-Component arrays)
; ==================================================================

; Position Component Data (32 entities max)
entity_x_pos        EQU sprite_x_pos      ; Reuse sprite positions
entity_y_pos        EQU sprite_y_pos      ; (32 bytes each)

; Movement Component Data
entity_vel_x        EQU temp_word_1       ; X velocity storage (signed 8-bit)
entity_vel_y        EQU temp_word_2       ; Y velocity storage (signed 8-bit)

; Component masks for each entity (which components are active)
entity_comp_masks   EQU temp_byte_1       ; Component flags per entity (32 bytes)

; Animation Component Data
entity_anim_frame   EQU temp_byte_2       ; Current animation frame (32 bytes)

; ==================================================================
; CORE ECS SYSTEM FUNCTIONS
; ==================================================================

INIT_COMPONENTS:
    ; Initialize all component systems (based on Mideas initialization)

    ; Clear all component masks
    LD HL, entity_comp_masks
    LD DE, entity_comp_masks+1
    LD BC, 31
    LD (HL), 0
    LDIR

    ; Initialize position system
    CALL INIT_POSITION_SYSTEM

    ; Initialize sprite system
    CALL INIT_SPRITE_SYSTEM

    ; Initialize movement system
    CALL INIT_MOVEMENT_SYSTEM

    ; Initialize collision system
    CALL INIT_COLLISION_SYSTEM

    ; Initialize input system
    CALL INIT_INPUT_SYSTEM

    ; Initialize behavior system
    CALL INIT_BEHAVIOR_SYSTEM

    RET

; ==================================================================
; POSITION COMPONENT SYSTEM (Based on SpriteEditor position handling)
; ==================================================================

INIT_POSITION_SYSTEM:
    ; Initialize position component system
    ; Clear all entity positions
    LD HL, entity_x_pos
    LD DE, entity_x_pos+1
    LD BC, 31
    LD (HL), 0
    LDIR

    LD HL, entity_y_pos
    LD DE, entity_y_pos+1
    LD BC, 31
    LD (HL), 0
    LDIR
    RET

UPDATE_POSITION_COMPONENT:
    ; Update positions based on velocities (Movement → Position)
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

position_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_POSITION     ; Check if has position component
    JR Z, position_next_entity ; Skip if no position component

    ; Apply velocity to position (if has movement component)
    LD A, (HL)
    AND COMP_MASK_MOVEMENT
    JR Z, position_next_entity ; Skip velocity if no movement

    ; TODO: Add velocity to position logic here
    ; entity_x_pos[entity] += entity_vel_x[entity]
    ; entity_y_pos[entity] += entity_vel_y[entity]

position_next_entity:
    INC HL                     ; Next entity
    DJNZ position_update_loop
    RET

; ==================================================================
; SPRITE COMPONENT SYSTEM (Based on SpriteEditor rendering)
; ==================================================================

INIT_SPRITE_SYSTEM:
    ; Initialize sprite rendering system
    ; Clear all sprite attributes
    CALL CLEAR_ALL_SPRITES
    RET

UPDATE_SPRITE_COMPONENT:
    ; Update sprite rendering based on entity positions
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks
    LD C, 0                    ; Entity index counter

sprite_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_SPRITE       ; Check if has sprite component
    JR Z, sprite_next_entity   ; Skip if no sprite component

    ; Render sprite at entity position
    PUSH BC
    PUSH HL

    ; Get entity position
    LD HL, entity_x_pos
    LD E, C                    ; Entity index
    LD D, 0
    ADD HL, DE                 ; HL points to entity X
    LD B, (HL)                 ; B = X position

    LD HL, entity_y_pos
    ADD HL, DE                 ; HL points to entity Y
    LD C, (HL)                 ; C = Y position

    ; Show sprite (A=sprite#, B=X, C=Y, D=pattern, E=color)
    LD A, E                    ; Sprite number = entity index
    LD D, 0                    ; Pattern 0 (TODO: get from entity data)
    LD E, 15                   ; Color white (TODO: get from entity data)
    CALL SHOW_SPRITE

    POP HL
    POP BC

sprite_next_entity:
    INC HL                     ; Next entity
    INC C                      ; Next entity index
    DJNZ sprite_update_loop

    ; Update all sprites to VRAM
    CALL UPDATE_SPRITES_TO_VRAM
    RET

; ==================================================================
; MOVEMENT COMPONENT SYSTEM (Based on movement physics)
; ==================================================================

INIT_MOVEMENT_SYSTEM:
    ; Initialize movement/physics system
    ; Clear velocities
    LD A, 0
    LD (entity_vel_x), A
    LD (entity_vel_y), A
    RET

UPDATE_MOVEMENT_COMPONENT:
    ; Update movement/physics for entities
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

movement_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_MOVEMENT     ; Check if has movement component
    JR Z, movement_next_entity ; Skip if no movement component

    ; Apply physics/movement logic here
    ; TODO: Apply gravity, friction, collision response, etc.

movement_next_entity:
    INC HL                     ; Next entity
    DJNZ movement_update_loop
    RET

; ==================================================================
; COLLISION COMPONENT SYSTEM (Based on ScreenEditor collision detection)
; ==================================================================

INIT_COLLISION_SYSTEM:
    ; Initialize collision detection system
    RET

UPDATE_COLLISION_COMPONENT:
    ; Check collisions between entities and environment
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

collision_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_COLLISION    ; Check if has collision component
    JR Z, collision_next_entity ; Skip if no collision component

    ; Perform collision detection
    ; TODO: Check against tiles, other entities, screen boundaries

collision_next_entity:
    INC HL                     ; Next entity
    DJNZ collision_update_loop
    RET

; ==================================================================
; INPUT COMPONENT SYSTEM (Based on input handling)
; ==================================================================

INIT_INPUT_SYSTEM:
    ; Initialize input handling system
    XOR A
    LD (input_state), A
    LD (prev_input_state), A
    RET

UPDATE_INPUT_COMPONENT:
    ; Update input handling for player entities
    ; Store previous input state
    LD A, (input_state)
    LD (prev_input_state), A

    ; Read current joystick state
    LD A, 0                    ; Joystick port 0
    CALL GTSTCK                ; Get joystick status (BIOS call)
    LD (input_state), A        ; Store current input state

    ; Process input for entities with input component
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

input_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_INPUT        ; Check if has input component
    JR Z, input_next_entity    ; Skip if no input component

    ; Apply input to entity movement/actions
    ; TODO: Convert joystick state to velocity/actions

input_next_entity:
    INC HL                     ; Next entity
    DJNZ input_update_loop
    RET

; ==================================================================
; BEHAVIOR COMPONENT SYSTEM (Based on BehaviorEditor logic)
; ==================================================================

INIT_BEHAVIOR_SYSTEM:
    ; Initialize AI/behavior system
    RET

UPDATE_BEHAVIOR_COMPONENT:
    ; Update AI/behavior logic for entities
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

behavior_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_BEHAVIOR     ; Check if has behavior component
    JR Z, behavior_next_entity ; Skip if no behavior component

    ; Execute behavior scripts/AI logic
    ; TODO: State machines, pathfinding, decision trees

behavior_next_entity:
    INC HL                     ; Next entity
    DJNZ behavior_update_loop
    RET

; ==================================================================
; ENTITY MANAGEMENT FUNCTIONS (Based on EntityTemplate system)
; ==================================================================

; Create entity with components (A = entity ID, B = component mask)
CREATE_ENTITY:
    ; Set component mask for entity
    LD HL, entity_comp_masks
    LD E, A                    ; Entity index
    LD D, 0
    ADD HL, DE                 ; HL points to entity mask
    LD (HL), B                 ; Set component mask

    ; Initialize component data based on mask
    BIT 0, B                   ; Check COMP_MASK_POSITION
    CALL NZ, INIT_ENTITY_POSITION

    BIT 1, B                   ; Check COMP_MASK_SPRITE
    CALL NZ, INIT_ENTITY_SPRITE

    ; TODO: Initialize other components based on mask bits

    RET

; Initialize position component for entity (A = entity ID)
INIT_ENTITY_POSITION:
    LD HL, entity_x_pos
    LD E, A
    LD D, 0
    ADD HL, DE
    LD (HL), 100               ; Default X position

    LD HL, entity_y_pos
    ADD HL, DE
    LD (HL), 100               ; Default Y position
    RET

; Initialize sprite component for entity (A = entity ID)
INIT_ENTITY_SPRITE:
    ; Set sprite as visible with default pattern
    LD HL, sprite_pattern
    LD E, A
    LD D, 0
    ADD HL, DE
    LD (HL), 0                 ; Pattern 0

    LD HL, sprite_color
    ADD HL, DE
    LD (HL), 15                ; White color
    RET

; ==================================================================
; END OF COMPONENT SYSTEMS
; ==================================================================


; ==================================================================
; GAME ENTITIES
; File: entities.asm
; Description: Game entity definitions and behavior
; ==================================================================

; ==================================================================
; DEFAULT ENTITY SYSTEM
; ==================================================================

; Basic entity structure
ENTITY_PLAYER_ID EQU 0
ENTITY_ENEMY_ID  EQU 1

INIT_ENTITIES:
    ; Initialize default entities
    CALL INIT_PLAYER
    RET

UPDATE_ENTITIES:
    ; Update all entities
    CALL UPDATE_PLAYER
    RET

INIT_PLAYER:
    ; Initialize player entity
    RET

UPDATE_PLAYER:
    ; Update player logic
    RET

; ==================================================================
; END OF ENTITIES
; ==================================================================


; ==================================================================
; GAME MENUS
; File: menus.asm
; Description: Menu systems and user interface with custom font support
; ==================================================================

; ==================================================================
; DEFAULT MENU SYSTEM
; ==================================================================

; Menu constants
MENU_MAIN_ID     EQU 0
MENU_GAME_ID     EQU 1
MENU_PAUSE_ID    EQU 2

; Menu states
MENU_ITEM_START  EQU 0
MENU_ITEM_EXIT   EQU 1

; Current menu variables
current_menu     DS 1
current_item     DS 1

; ==================================================================
; MENU FUNCTIONS
; ==================================================================

INIT_MENUS:
    ; Initialize menu system
    LD A, MENU_MAIN_ID
    LD (current_menu), A
    XOR A
    LD (current_item), A
    RET

SHOW_MAIN_MENU:
    ; Display main menu with custom font
    CALL CLS

    ; Make sure custom font is loaded
    CALL INIT_FONT_SYSTEM

    ; Print title using custom font
    LD HL, txt_title
    LD DE, NAMETBL + (5 * 32) + 10  ; Row 5, column 10
    CALL PRINT_STRING_SCREEN2        ; Use custom font print function

    ; Print menu options using custom font
    LD HL, txt_start
    LD DE, NAMETBL + (10 * 32) + 12
    CALL PRINT_STRING_SCREEN2

    LD HL, txt_exit
    LD DE, NAMETBL + (12 * 32) + 12
    CALL PRINT_STRING_SCREEN2

    RET

HANDLE_MAIN_MENU:
    ; Handle main menu input
    CALL GTSTCK     ; Get joystick input

    ; Check for up/down movement
    CP 1            ; Up
    JP Z, menu_up
    CP 5            ; Down
    JP Z, menu_down

    ; Check for selection (space or fire button)
    CALL GTTRIG
    OR A
    JP NZ, menu_select

    RET

menu_up:
    LD A, (current_item)
    OR A
    JP Z, menu_up_end  ; Already at top
    DEC A
    LD (current_item), A
menu_up_end:
    RET

menu_down:
    LD A, (current_item)
    CP MENU_ITEM_EXIT
    JP Z, menu_down_end  ; Already at bottom
    INC A
    LD (current_item), A
menu_down_end:
    RET

menu_select:
    LD A, (current_item)
    CP MENU_ITEM_START
    JP Z, start_game
    CP MENU_ITEM_EXIT
    JP Z, exit_game
    RET

start_game:
    ; Start the game
    LD A, MENU_GAME_ID
    LD (current_menu), A
    RET

exit_game:
    ; Exit to BASIC
    RST #00

; ==================================================================
; MENU TEXT DATA
; ==================================================================

txt_title:
    DB "GAME TITLE", 0

txt_start:
    DB "START GAME", 0

txt_exit:
    DB "EXIT", 0

; ==================================================================
; TEXT PRINTING FUNCTION
; ==================================================================

PRINT_STRING:
    ; Print null-terminated string
    ; HL = source string, DE = VRAM destination
print_loop:
    LD A, (HL)
    OR A
    RET Z           ; End of string

    ; WRTVRM expects: A = data, HL = VRAM address
    PUSH HL         ; Save string pointer
    PUSH DE         ; Save VRAM address
    POP HL          ; HL = VRAM address (for WRTVRM)
    CALL WRTVRM     ; Write character to VRAM
    POP HL          ; Restore string pointer

    INC HL          ; Next character in string
    INC DE          ; Next VRAM position
    JP print_loop

; ==================================================================
; END OF MENUS
; ==================================================================


; ==================================================================
; MAIN PROGRAM (from main.asm - excluding includes)
; ==================================================================
MAIN_PROGRAM:
    ; Initialize game systems
    CALL INIT_GAME_SYSTEMS

    ; Initialize Game Flow system
    XOR A
    LD (current_flow_state), A
    LD (prev_flow_state), A

    ; Start with main menu
    LD A, FLOW_STATE_MAIN_MENU
    LD (current_flow_state), A

    ; Main game loop
MAIN_LOOP:
    HALT                 ; Wait for V-Blank
    CALL UPDATE_CURRENT_STATE
    CALL RENDER_FRAME
    JP MAIN_LOOP

; ==================================================================
; GAME SYSTEM FUNCTIONS (implemented)
; ==================================================================

INIT_GAME_SYSTEMS:
    ; Initialize MSX hardware and game systems
    LD A, SCREEN2
    CALL CHGMOD               ; Set Screen 2 mode (BIOS handles everything)
    CALL ERAFNK               ; Remove function keys

    ; Initialize component systems
    CALL INIT_COMPONENTS

    ; Initialize sprite system if available
    CALL INIT_SPRITES

    ; Initialize sound system
    CALL GICINI               ; Initialize PSG

    ; Clear screen (BIOS CLS handles timing)
    CALL CLS

    ; Show initial startup message
    LD H, 1                    ; Row 1
    LD L, 1                    ; Column 1
    CALL POSIT

    LD HL, txt_system_init
    CALL OUTDO

    RET

UPDATE_CURRENT_STATE:
    ; Update game logic based on current flow state
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, UPDATE_MAIN_MENU_STATE
    CP FLOW_STATE_GAME
    JP Z, UPDATE_GAME_STATE
    CP FLOW_STATE_PAUSE
    JP Z, UPDATE_PAUSE_STATE
    CP FLOW_STATE_GAME_OVER
    JP Z, UPDATE_GAME_OVER_STATE
    CP FLOW_STATE_CREDITS
    JP Z, UPDATE_CREDITS_STATE
    RET

UPDATE_MAIN_MENU_STATE:
    ; Handle main menu input and logic
    CALL UPDATE_INPUT_COMPONENT

    ; Menu navigation logic would go here
    RET

UPDATE_GAME_STATE:
    ; Main gameplay logic - update all component systems
    CALL UPDATE_POSITION_COMPONENT
    CALL UPDATE_MOVEMENT_COMPONENT
    CALL UPDATE_COLLISION_COMPONENT
    CALL UPDATE_SPRITE_COMPONENT
    RET

UPDATE_PAUSE_STATE:
    ; Handle pause state
    CALL UPDATE_INPUT_COMPONENT

    ; Check for unpause input
    RET

UPDATE_GAME_OVER_STATE:
    ; Handle game over state
    CALL UPDATE_INPUT_COMPONENT

    ; Check for restart/menu input
    RET

UPDATE_CREDITS_STATE:
    ; Handle credits state
    ; Auto-advance credits or return to menu
    RET

RENDER_FRAME:
    ; Render current frame based on flow state
    ; Debug: Show frame indicator
    LD H, 23                   ; Bottom row
    LD L, 30                   ; Right side
    CALL POSIT
    LD A, '*'                  ; Frame indicator
    CALL CHPUT

    ; Check current flow state and render appropriately
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, RENDER_MAIN_MENU
    CP FLOW_STATE_GAME
    JP Z, RENDER_GAME
    CP FLOW_STATE_PAUSE
    JP Z, RENDER_PAUSE
    CP FLOW_STATE_GAME_OVER
    JP Z, RENDER_GAME_OVER
    CP FLOW_STATE_CREDITS
    JP Z, RENDER_CREDITS

    ; Default: show unknown state debug info
    LD H, 2
    LD L, 1
    CALL POSIT
    LD HL, txt_debug_state
    CALL OUTDO
    RET

RENDER_MAIN_MENU:
    ; Render main menu interface
    CALL CLS                   ; Clear screen first

    ; Position cursor for title
    LD H, 8                    ; Row 8
    LD L, 10                   ; Column 10
    CALL POSIT

    ; Display title
    LD HL, txt_main_title
    CALL OUTDO

    ; Position cursor for menu option 1
    LD H, 12                   ; Row 12
    LD L, 12                   ; Column 12
    CALL POSIT

    LD HL, txt_start_game
    CALL OUTDO

    ; Position cursor for menu option 2
    LD H, 14                   ; Row 14
    LD L, 12                   ; Column 12
    CALL POSIT

    LD HL, txt_exit_game
    CALL OUTDO
    RET

RENDER_GAME:
    ; Render game frame - load actual screen map
    ; BIOS LDIRVM in screen loading handles timing automatically
    CALL LOAD_SCREEN_PANTALLA1

    ; Display game status at top
    LD H, 1                    ; Row 1
    LD L, 1                    ; Column 1
    CALL POSIT

    LD HL, txt_game_mode
    CALL OUTDO
    RET

RENDER_PAUSE:
    ; Render pause overlay
    ; Position cursor in center
    LD H, 12                   ; Row 12 (center)
    LD L, 14                   ; Column 14 (center)
    CALL POSIT

    LD HL, txt_paused
    CALL OUTDO
    RET

RENDER_GAME_OVER:
    ; Render game over screen
    CALL CLS                   ; Clear screen

    ; Position cursor for game over message
    LD H, 10                   ; Row 10
    LD L, 12                   ; Column 12
    CALL POSIT

    LD HL, txt_game_over
    CALL OUTDO

    ; Position cursor for instruction
    LD H, 14                   ; Row 14
    LD L, 8                    ; Column 8
    CALL POSIT

    LD HL, txt_press_any_key
    CALL OUTDO
    RET

RENDER_CREDITS:
    ; Render credits screen
    CALL CLS                   ; Clear screen

    ; Position cursor for credits
    LD H, 8                    ; Row 8
    LD L, 8                    ; Column 8
    CALL POSIT

    LD HL, txt_credits
    CALL OUTDO
    RET

; Text strings for display
txt_system_init:    DB "MSX SYSTEM READY", 0
txt_debug_state:    DB "UNKNOWN STATE", 0
txt_main_title:     DB "MSX GAME ENGINE", 0
txt_start_game:     DB "1. START GAME", 0
txt_exit_game:      DB "2. EXIT", 0
txt_game_mode:      DB "GAME MODE", 0
txt_paused:         DB "PAUSED", 0
txt_game_over:      DB "GAME OVER", 0
txt_press_any_key:  DB "PRESS ANY KEY", 0
txt_credits:        DB "CREDITS: MIDEAS MSX", 0

    END                 ; End of assembly
