; ==================================================================
; SIMPLE_SPRITE(2) - UNIFIED FILE
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
; ==================================================================

; ==================================================================
; MSX CARTRIDGE ROM HEADER
; File: header.asm
; Description: Standard MSX cartridge initialization
; ==================================================================

    ORG #4000           ; MSX cartridge start address

; ==================================================================
; CARTRIDGE HEADER
; ==================================================================
    DB "AB"             ; MSX cartridge signature
    DW INIT_ROM         ; Initialization address
    DW 0                ; Statement handler (not used)
    DW 0                ; Device handler (not used)
    DW 0                ; Text handler (not used)
    DW 0                ; Reserved
    DW 0                ; Reserved
    DW 0                ; Reserved

; ==================================================================
; ROM INITIALIZATION ENTRY POINT
; ==================================================================
INIT_ROM:
    ; Initialize stack
    LD SP, #F380


    DI                           ; Disable interrupts during init
    ld a,#C9
    ld (HKEY),a
    EI

    ; Set up memory mapper (if any)
    ; This is a placeholder for future mapper initialization
    ; call setupROMRAMslots

    xor a       
    ld (CLIKSW),a ; Click switch off
    ; Change background colors:
    ld (BAKCLR),a 
    ld (BDRCLR),a
    call CHGCLR
   
    ld a,2      ; Change screen mode
    call CHGMOD

    ;; 16x16 sprites:
    ld bc,#e201  ;; write #e2 in VDP register #01 (activate sprites, generate interrupts, 16x16 sprites with no magnification)
    call WRTVDP

    ; init fill screen
    call FILLSCREEN

     call CheckIf60Hz
    ld (isComputer50HzOr60Hz),a

    ;init random seed
    call randomSeedUpdate


    ; Jump to main program
    JP MAIN_PROGRAM

; ==================================================================
; END OF HEADER
; ==================================================================


; ==================================================================
; MSX BIOS FUNCTIONS AND ADDRESSES
; File: bios.asm
; Description: Standard MSX BIOS function definitions
; ==================================================================

; ==================================================================
; MAIN BIOS FUNCTIONS
; ==================================================================

; Screen and Display
CHGMOD  EQU #005F        ; Change screen mode (A=mode)
CHGCLR  EQU #0062        ; Change colors
CLS     EQU #00C3        ; Clear screen
POSIT   EQU #00C6        ; Position cursor (H=X, L=Y)
ERAFNK  EQU #00CC        ; Erase function keys
DSPFNK  EQU #00CF        ; Display function keys
DISSCR  EQU #0041        ; Disable screen (prevent flicker)
ENASCR  EQU #0044        ; Enable screen
INITXT  EQU #006C        ; Initialize text mode
INIT32  EQU #006F        ; Initialize screen mode

; Character I/O
CHPUT   EQU #00A2        ; Character output (A=char)
CHGET   EQU #009F        ; Character input
CHSNS   EQU #009C        ; Character sense (check key)
BREAKX  EQU #00B7        ; Check CTRL+STOP
ISCNTC  EQU #00BA        ; Check CTRL+C

; String I/O
OUTDO   EQU #005A        ; String output (HL=string)

; Input Devices
GTSTCK  EQU #00D5        ; Get joystick status (A=port)
GTTRIG  EQU #00D8        ; Get trigger status (A=port)
GTPAD   EQU #00DB        ; Get paddle (A=port)
GTPDL   EQU #00DE        ; Get paddle value
SNSMAT  EQU #0141        ; Sense matrix (A=row)
KILBUF  EQU #0156        ; Kill keyboard buffer

; Sound
GICINI  EQU #0090        ; Initialize PSG
WRTPSG  EQU #0093        ; Write PSG register (A=reg, E=value)
RDPSG   EQU #0096        ; Read PSG register (A=reg)

; Graphics VDP
GRPPRT  EQU #0089        ; Print in graphic mode
SETGRP  EQU #007E        ; Set graphic mode

; Memory Transfer
LDIRVM  EQU #005C        ; Block transfer from CPU to VRAM
LDIRMV  EQU #0059        ; Block transfer from VRAM to CPU
WRTVDP  EQU #0047        ; Write to VDP register
WRTVRM  EQU #004D        ; Write data to VRAM (A=data, HL=address)

; File I/O (Disk BIOS)
DSKIO   EQU #004A        ; Disk I/O
DSKCHF  EQU #004D        ; Disk change flag

; Math
GETYPR  EQU #0053        ; Get type of variable

; ==================================================================
; VDP PORTS AND REGISTERS
; ==================================================================

; VDP Data/Status Ports
VDPDR   EQU #0098        ; VDP Data Register (Port 0)
VDPSR   EQU #0099        ; VDP Status Register (Port 1)

; VDP Registers (use with VDPSR)
VDP_R0  EQU 0            ; Mode register 0
VDP_R1  EQU 1            ; Mode register 1
VDP_R2  EQU 2            ; Name table base address
VDP_R3  EQU 3            ; Color table base address
VDP_R4  EQU 4            ; Pattern table base address
VDP_R5  EQU 5            ; Sprite attribute table
VDP_R6  EQU 6            ; Sprite pattern table
VDP_R7  EQU 7            ; Text/border color

; System Variables
HKEY    EQU #F3DB        ; Hook function key (system variable)
CLIKSW  EQU #F3DC        ; Key click switch
BAKCLR  EQU #F3E9        ; Background color
BDRCLR  EQU #F3EA        ; Border color
isComputer50HzOr60Hz EQU #F3EB  ; System frequency flag

; ==================================================================
; UTILITY FUNCTIONS
; ==================================================================

FILLSCREEN:
    ; Fill screen with default pattern
    CALL CLS
    RET

CheckIf60Hz:
    ; Check if system is 60Hz or 50Hz
    ; Return A=0 for 50Hz, A=1 for 60Hz
    LD A, 1                 ; Default to 60Hz
    RET

randomSeedUpdate:
    ; Update random seed
    ; Simple placeholder implementation
    RET

INIT_FONT_SYSTEM:
    ; Initialize custom font system
    ; For BasicEnemy, use default MSX font
    RET

PRINT_STRING_SCREEN2:
    ; Print string using custom font in Screen 2
    ; HL = string, DE = VRAM position
    ; For BasicEnemy, use basic character printing
    CALL PRINT_STRING
    RET

; ==================================================================
; END OF BIOS DEFINITIONS
; ==================================================================


; ==================================================================
; MSX SYSTEM CONSTANTS
; File: constants.asm
; Description: MSX hardware constants and project-specific definitions
; ==================================================================

; ==================================================================
; VRAM LAYOUT - SCREEN 2 MODE
; ==================================================================

; Pattern Generator Table (PGT) - 3 Banks
CHRTBL2 EQU #0000        ; Pattern table base address (Bank 0)
; Bank 1: CHRTBL2 + #800   (#0800)
; Bank 2: CHRTBL2 + #1000  (#1000)

; Color Attribute Table (CAT) - 3 Banks
CLRTBL2 EQU #2000        ; Color table base address (Bank 0)
; Bank 1: CLRTBL2 + #800   (#2800)
; Bank 2: CLRTBL2 + #1000  (#3000)

; Other VRAM Areas
NAMETBL EQU #1800        ; Name table base address
SPRATR  EQU #1B00        ; Sprite attribute table
SPRPAT  EQU #3800        ; Sprite pattern table

; ==================================================================
; SCREEN MODES
; ==================================================================
SCREEN0     EQU 0        ; 40x24 text
SCREEN1     EQU 1        ; 32x24 text/graphics
SCREEN2     EQU 2        ; 256x192 graphics
SCREEN3     EQU 3        ; 64x48 multicolor

; ==================================================================
; SCREEN DIMENSIONS (DYNAMIC BASED ON PROJECT TILES)
; ==================================================================

; No tiles detected - using MSX default character size
TILE_WIDTH      EQU 8    ; Default: 8x8 pixels per MSX character
TILE_HEIGHT     EQU 8    ; Default: 8x8 pixels per MSX character
SCREEN_TILES_X  EQU 32   ; Horizontal tiles (Screen 1/2)
SCREEN_TILES_Y  EQU 24   ; Vertical tiles
MSX_CHARS_PER_TILE_X EQU 1   ; 1 MSX character per tile
MSX_CHARS_PER_TILE_Y EQU 1   ; 1 MSX character per tile


; Legacy compatibility
SCREEN_WIDTH    EQU SCREEN_TILES_X
SCREEN_HEIGHT   EQU SCREEN_TILES_Y
TILE_SIZE       EQU 8    ; MSX character size (always 8x8)

; ==================================================================
; GAMEFLOW NODE TYPE CONSTANTS (Critical for Paridad)
; ==================================================================
NODE_TYPE_START        EQU 0    ; Start node (initial entry point)
NODE_TYPE_WORLDLINK    EQU 1    ; World link node (loads world map)
NODE_TYPE_SCREEN       EQU 2    ; Screen node (loads specific screen)
NODE_TYPE_MENU         EQU 3    ; Menu node (shows menu interface)
NODE_TYPE_UNKNOWN      EQU 255  ; Unknown/unsupported node type

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
MAX_SPRITES     EQU 32   ; Máximo sprites por pantalla
SPRITE_SIZE     EQU 8    ; 8x8 o 16x16 (según modo)
SPRITE_INVISIBLE EQU #D1 ; Y=209 (sprite fuera de pantalla)

; ==================================================================
; MSX COLORS
; ==================================================================
TRANSPARENT EQU 0
BLACK       EQU 1
MEDIUM_GREEN EQU 2
LIGHT_GREEN EQU 3
DARK_BLUE   EQU 4
LIGHT_BLUE  EQU 5
DARK_RED    EQU 6
CYAN        EQU 7
MEDIUM_RED  EQU 8
LIGHT_RED   EQU 9
DARK_YELLOW EQU 10
LIGHT_YELLOW EQU 11
DARK_GREEN  EQU 12
MAGENTA     EQU 13
GRAY        EQU 14
WHITE       EQU 15

; ==================================================================
; INPUT CONSTANTS
; ==================================================================

; Joystick Directions
STICK_UP    EQU 1
STICK_UPRIGHT EQU 2
STICK_RIGHT EQU 3
STICK_DOWNRIGHT EQU 4
STICK_DOWN  EQU 5
STICK_DOWNLEFT EQU 6
STICK_LEFT  EQU 7
STICK_UPLEFT EQU 8
STICK_CENTER EQU 0

; Trigger Constants
TRIG_A      EQU #10      ; Trigger A (Fire)
TRIG_B      EQU #20      ; Trigger B (MSX2+)

; ==================================================================
; GAME FLOW STATES (PROJECT-SPECIFIC)
; ==================================================================

; Basic Game Flow States (always available)
FLOW_STATE_MAIN_MENU    EQU 0
FLOW_STATE_GAME         EQU 1
FLOW_STATE_PAUSE        EQU 2
FLOW_STATE_GAME_OVER    EQU 3
FLOW_STATE_CREDITS      EQU 4

; Additional Game Flow States detected in project
; (Custom states would be added here if needed)


; ==================================================================
; PROJECT-SPECIFIC CONSTANTS
; ==================================================================

; Detected Assets
TOTAL_SPRITES           EQU 1
TOTAL_TILES             EQU 0
TOTAL_SCREENS           EQU 1

; ==================================================================
; END OF CONSTANTS
; ==================================================================


; ==================================================================
; RAM VARIABLES DEFINITIONS
; File: variables.asm
; Description: Dynamic variable allocation using EQU addresses
; Generated based on project analysis
; ==================================================================

; ==================================================================
; CORE SYSTEM VARIABLES (ALWAYS PRESENT)
; ==================================================================
input_state         EQU #C000   ; Current joystick/keyboard state
prev_input_state    EQU #C001   ; Previous input state
current_flow_state  EQU #C002   ; Current game flow state
prev_flow_state     EQU #C003   ; Previous game flow state
frame_counter       EQU #C004   ; Frame counter (16-bit)

; ==================================================================
; SPRITE SYSTEM VARIABLES (1 sprites detected)
; ==================================================================
active_sprite_count EQU #C006   ; Number of sprites currently active
sprite_x_pos        EQU #C007   ; Sprite X positions (1 bytes)
sprite_y_pos        EQU #C008   ; Sprite Y positions (1 bytes)
sprite_pattern      EQU #C009   ; Sprite pattern IDs (1 bytes)
sprite_color        EQU #C00A   ; Sprite colors (1 bytes)

; ==================================================================
; SCREEN SYSTEM VARIABLES (1 screens detected)
; ==================================================================
current_screen_id   EQU #C00B   ; Currently displayed screen ID
screen_dirty_flag   EQU #C00C   ; Screen needs redraw flag

; ==================================================================
; PLAYER SYSTEM VARIABLES (player entity detected)
; ==================================================================
player_x            EQU #C00D   ; Player X position (16-bit)
player_y            EQU #C00F   ; Player Y position (16-bit)
player_health       EQU #C011   ; Player health points
player_score        EQU #C012   ; Player score (16-bit)

; ==================================================================
; TEMPORARY VARIABLES (ALWAYS NEEDED)
; ==================================================================
temp_word_1         EQU #C014   ; Temporary 16-bit storage
temp_word_2         EQU #C016   ; Temporary 16-bit storage
temp_byte_1         EQU #C018   ; Temporary 8-bit storage
temp_byte_2         EQU #C019   ; Temporary 8-bit storage

; ==================================================================
; END OF VARIABLES
; ==================================================================
RAM_USAGE_END       EQU #C01A   ; End of project variables (26 bytes used)

; ==================================================================
; MEMORY SAFETY CHECK
; ==================================================================
; RAM Layout:
;   #C000-#C01A: Project variables (26 bytes)
;   #C01A-#F37F: Free RAM (~13158 bytes available)
;   #F380-#FFFF: MSX System variables (DO NOT TOUCH)
; ==================================================================


; ==================================================================
; PATTERN DATA (EMPTY - NO TILES DETECTED)
; File: patterns.asm
; ==================================================================

; No tiles detected in project - file generated as placeholder


; ==================================================================
; COLOR DATA (EMPTY - NO TILES DETECTED)
; File: colors.asm
; ==================================================================

; No tiles detected in project - file generated as placeholder


; ==================================================================
; SPRITE DATA
; File: sprites.asm
; Description: Sprite pattern and animation data
; 1 sprites detected
; ==================================================================

; ==================================================================
; SPRITE PATTERN DATA
; ==================================================================

; Sprite 0: cara1
;; Sprite: cara1
;; Total Frames: 1
;; Size: 16x16
;; Background Color (not exported as a layer): rgba(0,0,0,0)
;; Drawable Palette (Hex): C0=#000000, C1=#3EB847, C2=#FC584A, C3=#FFFFFF

SPRITE_CARA1_WIDTH     EQU 16
SPRITE_CARA1_HEIGHT    EQU 16
SPRITE_CARA1_FRAMES    EQU 1

;; ---- Sprite Frame: cara1_F0 ----
;; Size: 16x16
;; Layer 0 (Color: #000000) - SKIPPED (color not used or is background)
;; Layer 1 (Color: #3EB847) - SKIPPED (color not used or is background)
;; Layer 2 (Color: #FC584A) - SKIPPED (color not used or is background)
CARA1_F0_LAYER3: ; Brush Color Index 3 (Actual Color: #FFFFFF)
    DB #00,#00,#00,#00,#07,#E0,#3F,#FC,#77,#EE,#6B,#D6,#7F,#FE,#FD,#BF
    DB #7D,#BE,#7F,#FE,#79,#9E,#36,#6C,#0E,#70,#0F,#F0,#01,#80,#00,#00

;; ---- End of Frame: cara1_F0 ----


; Unified pattern label for sprite 0 (for easy reference in loading code)
SPRITE_0_PATTERN EQU CARA1_F0_LAYER3

; ==================================================================
; SPRITE INITIALIZATION FUNCTIONS
; ==================================================================

INIT_SPRITES:
    ; Initialize sprite system
    CALL CLEAR_ALL_SPRITES

    ; Load sprite patterns to VRAM
    CALL LOAD_SPRITE_PATTERNS

    ; Initialize sprite positions (all invisible by default)
    XOR A
    LD (active_sprite_count), A

    RET

LOAD_SPRITE_PATTERNS:
    ; Load all sprite patterns to VRAM sprite pattern table

    ; Load sprite 0: cara1 (BIOS LDIRVM handles timing)
    LD HL, SPRITE_0_PATTERN
    LD DE, SPRPAT + (0 * 32) ; Each 16x16 sprite = 32 bytes (4 patterns)
    LD BC, 32                       ; 16x16 sprite size
    CALL LDIRVM                     ; BIOS handles safe VRAM access
    RET

; ==================================================================
; SPRITE MANAGEMENT FUNCTIONS
; ==================================================================

; Show sprite (A = sprite number, B = X, C = Y, D = pattern, E = color)
SHOW_SPRITE:
    PUSH BC                       ; Preserve parameters
    PUSH DE

    ; Calculate sprite offset (A = sprite number)
    LD L, A                       ; L = sprite number
    LD H, 0                       ; HL = sprite number

    ; Set X position
    PUSH HL
    LD DE, sprite_x_pos
    ADD HL, DE                    ; HL points to sprite X position
    LD (HL), B                    ; Set X position
    POP HL

    ; Set Y position
    PUSH HL
    LD DE, sprite_y_pos
    ADD HL, DE                    ; HL points to sprite Y position
    LD (HL), C                    ; Set Y position
    POP HL

    ; Set pattern
    PUSH HL
    LD DE, sprite_pattern
    ADD HL, DE                    ; HL points to sprite pattern
    POP DE                        ; Restore original HL to DE
    PUSH DE                       ; Save it again
    LD (HL), D                    ; Set pattern number
    POP HL

    ; Set color
    LD DE, sprite_color
    ADD HL, DE                    ; HL points to sprite color
    POP DE                        ; Get original DE back
    LD (HL), E                    ; Set color

    POP BC                        ; Restore original parameters
    RET

; Clear all sprites (make them invisible)
CLEAR_ALL_SPRITES:
    LD HL, sprite_y_pos
    LD DE, sprite_y_pos+1
    LD BC, 0                     ; 1 sprites - 1
    LD (HL), SPRITE_INVISIBLE     ; Y=209 (invisible)
    LDIR
    RET

; Hide specific sprite (A = sprite number)
HIDE_SPRITE:
    LD HL, sprite_y_pos
    LD E, A
    LD D, 0
    ADD HL, DE                    ; HL points to sprite Y position
    LD (HL), SPRITE_INVISIBLE     ; Make invisible
    RET

; Update sprite positions to VRAM
UPDATE_SPRITES_TO_VRAM:
    ; Copy sprite attributes from RAM to VRAM
    ; BIOS LDIRVM handles timing automatically
    LD HL, sprite_y_pos
    LD DE, SPRATR
    LD BC, 4                    ; 1 sprites * 4 bytes each
    CALL LDIRVM                   ; BIOS handles safe VRAM access
    RET

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
SPRITE_ID_CARA1    EQU 0      ; Sprite: cara1

; ==================================================================
; END OF SPRITE DATA
; ==================================================================


; ==================================================================
; SCREEN MAPS
; File: screens.asm
; Description: Screen layout and map data
; ==================================================================

; ==================================================================
; SCREEN MAP CONSTANTS
; ==================================================================

SCREEN_SCREEN_1_VACIA_0_ID EQU 0

; ==================================================================
; SCREEN MAP DATA
; ==================================================================

;; MAP: screen_1_vacia_0 (32x24 tiles)
;; Total size: 768 bytes

;; --- TILE INDEX REFERENCES for SCREEN_1_VACIA_0 ---
; Generated using exact Screen Editor "Download ASM" logic
; Byte values represent actual character codes in VRAM

SCREEN_SCREEN_1_VACIA_0_WIDTH     EQU 32
SCREEN_SCREEN_1_VACIA_0_HEIGHT    EQU 24
SCREEN_SCREEN_1_VACIA_0_SIZE      EQU 768

SCREEN_SCREEN_1_VACIA_0_LAYOUT:
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
    DB #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF

;; BEHAVIOR MAP: screen_1_vacia_0 (32x24 tiles)
;; Total size: 768 bytes (Map IDs 0-255)
;; Data format: HEX

BEHAVIOR_SCREEN_1_VACIA_0_WIDTH     EQU 32
BEHAVIOR_SCREEN_1_VACIA_0_HEIGHT    EQU 24
BEHAVIOR_SCREEN_1_VACIA_0_SIZE      EQU 768

BEHAVIOR_SCREEN_1_VACIA_0_DATA:
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
    DB #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00

;; End of Behavior Map Data for screen_1_vacia_0

; ==================================================================
; SCREEN LOADING FUNCTIONS
; ==================================================================

LOAD_SCREEN:
    ; Load screen (A = screen ID)
    ; TODO: Implement screen loading logic
    RET

LOAD_SCREEN_SCREEN_1_VACIA:
    ; Load screen_1_vacia screen (BIOS LDIRVM handles timing)
    LD HL, SCREEN_SCREEN_1_VACIA_0_LAYOUT
    LD DE, NAMETBL
    LD BC, SCREEN_SCREEN_1_VACIA_0_SIZE
    CALL LDIRVM                ; BIOS handles safe VRAM access
    RET

; ==================================================================
; END OF SCREEN MAPS
; ==================================================================


; ==================================================================
; GAME COMPONENT SYSTEMS - MSX ECS ENGINE
; File: components.asm
; Description: Component systems based on Mideas React.js architecture
; Implements Position, Sprite, Movement, Collision, Input, and Behavior systems
; ==================================================================

; ==================================================================
; COMPONENT TYPE CONSTANTS (Based on ComponentDefinition analysis)
; ==================================================================

; Core Components (always present)
COMP_POSITION   EQU 0    ; Position component (x, y coordinates)
COMP_SPRITE     EQU 1    ; Sprite rendering component
COMP_MOVEMENT   EQU 2    ; Movement/velocity component
COMP_COLLISION  EQU 3    ; Collision detection component
COMP_INPUT      EQU 4    ; Input handling component
COMP_BEHAVIOR   EQU 5    ; AI/Logic behavior component
COMP_HEALTH     EQU 6    ; Health/damage component
COMP_ANIMATION  EQU 7    ; Animation state component

; Component flags for entity filtering
COMP_MASK_POSITION   EQU #01  ; Binary: 00000001
COMP_MASK_SPRITE     EQU #02  ; Binary: 00000010
COMP_MASK_MOVEMENT   EQU #04  ; Binary: 00000100
COMP_MASK_COLLISION  EQU #08  ; Binary: 00001000
COMP_MASK_INPUT      EQU #10  ; Binary: 00010000
COMP_MASK_BEHAVIOR   EQU #20  ; Binary: 00100000
COMP_MASK_HEALTH     EQU #40  ; Binary: 01000000
COMP_MASK_ANIMATION  EQU #80  ; Binary: 10000000

; ==================================================================
; COMPONENT DATA STRUCTURES (Entity-Component arrays)
; ==================================================================

; Position Component Data (32 entities max)
entity_x_pos        EQU sprite_x_pos      ; Reuse sprite positions
entity_y_pos        EQU sprite_y_pos      ; (32 bytes each)

; Movement Component Data
entity_vel_x        EQU temp_word_1       ; X velocity storage (signed 8-bit)
entity_vel_y        EQU temp_word_2       ; Y velocity storage (signed 8-bit)

; Component masks for each entity (which components are active)
entity_comp_masks   EQU temp_byte_1       ; Component flags per entity (32 bytes)

; Animation Component Data
entity_anim_frame   EQU temp_byte_2       ; Current animation frame (32 bytes)

; ==================================================================
; CORE ECS SYSTEM FUNCTIONS
; ==================================================================

INIT_COMPONENTS:
    ; Initialize all component systems (based on Mideas initialization)

    ; Clear all component masks
    LD HL, entity_comp_masks
    LD DE, entity_comp_masks+1
    LD BC, 31
    LD (HL), 0
    LDIR

    ; Initialize position system
    CALL INIT_POSITION_SYSTEM

    ; Initialize sprite system
    CALL INIT_SPRITE_SYSTEM

    ; Initialize movement system
    CALL INIT_MOVEMENT_SYSTEM

    ; Initialize collision system
    CALL INIT_COLLISION_SYSTEM

    ; Initialize input system
    CALL INIT_INPUT_SYSTEM

    ; Initialize behavior system
    CALL INIT_BEHAVIOR_SYSTEM

    RET

; ==================================================================
; POSITION COMPONENT SYSTEM (Based on SpriteEditor position handling)
; ==================================================================

INIT_POSITION_SYSTEM:
    ; Initialize position component system
    ; Clear all entity positions
    LD HL, entity_x_pos
    LD DE, entity_x_pos+1
    LD BC, 31
    LD (HL), 0
    LDIR

    LD HL, entity_y_pos
    LD DE, entity_y_pos+1
    LD BC, 31
    LD (HL), 0
    LDIR
    RET

UPDATE_POSITION_COMPONENT:
    ; Update positions based on velocities (Movement → Position)
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

position_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_POSITION     ; Check if has position component
    JR Z, position_next_entity ; Skip if no position component

    ; Apply velocity to position (if has movement component)
    LD A, (HL)
    AND COMP_MASK_MOVEMENT
    JR Z, position_next_entity ; Skip velocity if no movement

    ; TODO: Add velocity to position logic here
    ; entity_x_pos[entity] += entity_vel_x[entity]
    ; entity_y_pos[entity] += entity_vel_y[entity]

position_next_entity:
    INC HL                     ; Next entity
    DJNZ position_update_loop
    RET

; ==================================================================
; SPRITE COMPONENT SYSTEM (Based on SpriteEditor rendering)
; ==================================================================

INIT_SPRITE_SYSTEM:
    ; Initialize sprite rendering system
    ; Clear all sprite attributes
    CALL CLEAR_ALL_SPRITES
    RET

UPDATE_SPRITE_COMPONENT:
    ; Update sprite rendering based on entity positions
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks
    LD C, 0                    ; Entity index counter

sprite_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_SPRITE       ; Check if has sprite component
    JR Z, sprite_next_entity   ; Skip if no sprite component

    ; Render sprite at entity position
    PUSH BC
    PUSH HL

    ; Get entity position
    LD HL, entity_x_pos
    LD E, C                    ; Entity index
    LD D, 0
    ADD HL, DE                 ; HL points to entity X
    LD B, (HL)                 ; B = X position

    LD HL, entity_y_pos
    ADD HL, DE                 ; HL points to entity Y
    LD C, (HL)                 ; C = Y position

    ; Show sprite (A=sprite#, B=X, C=Y, D=pattern, E=color)
    LD A, E                    ; Sprite number = entity index
    LD D, 0                    ; Pattern 0 (TODO: get from entity data)
    LD E, 15                   ; Color white (TODO: get from entity data)
    CALL SHOW_SPRITE

    POP HL
    POP BC

sprite_next_entity:
    INC HL                     ; Next entity
    INC C                      ; Next entity index
    DJNZ sprite_update_loop

    ; Update all sprites to VRAM
    CALL UPDATE_SPRITES_TO_VRAM
    RET

; ==================================================================
; MOVEMENT COMPONENT SYSTEM (Based on movement physics)
; ==================================================================

INIT_MOVEMENT_SYSTEM:
    ; Initialize movement/physics system
    ; Clear velocities
    LD A, 0
    LD (entity_vel_x), A
    LD (entity_vel_y), A
    RET

UPDATE_MOVEMENT_COMPONENT:
    ; Update movement/physics for entities
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

movement_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_MOVEMENT     ; Check if has movement component
    JR Z, movement_next_entity ; Skip if no movement component

    ; Apply physics/movement logic here
    ; TODO: Apply gravity, friction, collision response, etc.

movement_next_entity:
    INC HL                     ; Next entity
    DJNZ movement_update_loop
    RET

; ==================================================================
; COLLISION COMPONENT SYSTEM (Based on ScreenEditor collision detection)
; ==================================================================

INIT_COLLISION_SYSTEM:
    ; Initialize collision detection system
    RET

UPDATE_COLLISION_COMPONENT:
    ; Check collisions between entities and environment
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks
    LD C, 0                    ; Entity index

collision_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_COLLISION    ; Check if has collision component
    JR Z, collision_next_entity ; Skip if no collision component

    ; Perform collision detection for this entity
    PUSH BC
    PUSH HL

    ; Get entity position
    LD HL, entity_x_pos
    LD E, C                    ; Entity index
    LD D, 0
    ADD HL, DE                 ; HL points to entity X
    LD A, (HL)                 ; A = X position

    LD HL, entity_y_pos
    ADD HL, DE                 ; HL points to entity Y
    LD B, (HL)                 ; B = Y position

    ; Check screen boundaries (256x192 with 16x16 sprites)
    ; Left boundary
    CP 0
    JR Z, collision_boundary_hit

    ; Right boundary (256 - 16 = 240)
    CP 240
    JR NC, collision_boundary_hit

    ; Top boundary
    LD A, B
    CP 0
    JR Z, collision_boundary_hit

    ; Bottom boundary (192 - 16 = 176)
    CP 176
    JR NC, collision_boundary_hit

    ; Check tile collision (if screen maps exist)
    CALL CHECK_TILE_COLLISION

    ; Check entity-to-entity collision
    CALL CHECK_ENTITY_COLLISION

    JR collision_check_complete

collision_boundary_hit:
    ; Handle boundary collision
    CALL HANDLE_BOUNDARY_COLLISION

collision_check_complete:
    POP HL
    POP BC

collision_next_entity:
    INC HL                     ; Next entity
    INC C                      ; Next entity index
    DJNZ collision_update_loop
    RET

; ==================================================================
; COLLISION HELPER FUNCTIONS (Critical for Gameplay Parity)
; ==================================================================

CHECK_TILE_COLLISION:
    ; Check collision with background tiles
    ; A = X position, B = Y position
    ; Convert pixel position to tile coordinates
    PUSH AF
    PUSH BC

    ; DYNAMIC TILE SIZE CONVERSION
    ; TODO: This should be calculated from actual screen map tile sizes
    ; For now, detect most common tile size in project

    ; No tiles detected - using default 16x16
    ; Convert X to tile column (divide by 16)


    ; Default 16px tiles (4 shifts)
    SRL A                      ; A = X / 2
    SRL A                      ; A = X / 4
    SRL A                      ; A = X / 8
    SRL A                      ; A = X / 16
    LD C, A                    ; C = tile column


    ; Default 16px tiles (4 shifts)
    LD A, B
    SRL A                      ; A = Y / 2
    SRL A                      ; A = Y / 4
    SRL A                      ; A = Y / 8
    SRL A                      ; A = Y / 16
    LD B, A                    ; B = tile row

    ; Check if position is within valid tile map
    LD A, C
    CP 16                      ; Screen width in tiles
    JR NC, no_tile_collision
    LD A, B
    CP 12                      ; Screen height in tiles
    JR NC, no_tile_collision

    ; Get tile at position (simplified - would read from behavior map)
    ; For now, assume all non-zero tiles are solid
    ; This would read from the behavior map generated from screen data
    CALL GET_BEHAVIOR_TILE     ; Returns A = behavior value
    OR A
    JR Z, no_tile_collision    ; 0 = passable

    ; Collision detected - handle it
    CALL HANDLE_TILE_COLLISION

no_tile_collision:
    POP BC
    POP AF
    RET

CHECK_ENTITY_COLLISION:
    ; Check collision with other entities
    ; A = current entity X, B = current entity Y, C = current entity index
    PUSH BC
    PUSH AF

    ; Loop through all other entities
    LD HL, entity_comp_masks
    LD E, 0                    ; Other entity index

entity_collision_loop:
    LD A, E
    CP C                       ; Skip self
    JR Z, next_entity_collision

    ; Check if other entity has collision component
    LD A, (HL)
    AND COMP_MASK_COLLISION
    JR Z, next_entity_collision

    ; Get other entity position
    PUSH HL
    PUSH DE

    LD HL, entity_x_pos
    LD D, 0
    ADD HL, DE                 ; HL points to other entity X
    LD D, (HL)                 ; D = other X

    LD HL, entity_y_pos
    ADD HL, DE                 ; HL points to other entity Y
    LD E, (HL)                 ; E = other Y

    ; Check if entities overlap (16x16 sprites)
    ; Current entity: A = X, B = Y
    ; Other entity: D = X, E = Y

    ; X overlap check: |X1 - X2| < 16
    LD H, A                    ; H = current X
    LD A, D                    ; A = other X
    SUB H                      ; A = other X - current X
    JR NC, x_diff_positive     ; Jump if positive
    NEG                        ; Make positive
x_diff_positive:
    CP 16                      ; Check if < 16
    JR NC, no_entity_collision ; No X overlap

    ; Y overlap check: |Y1 - Y2| < 16
    LD A, E                    ; A = other Y
    SUB B                      ; A = other Y - current Y
    JR NC, y_diff_positive     ; Jump if positive
    NEG                        ; Make positive
y_diff_positive:
    CP 16                      ; Check if < 16
    JR NC, no_entity_collision ; No Y overlap

    ; Collision detected!
    CALL HANDLE_ENTITY_COLLISION

no_entity_collision:
    POP DE
    POP HL

next_entity_collision:
    INC HL                     ; Next entity mask
    INC E                      ; Next entity index
    LD A, E
    CP 32                      ; Check all 32 entities
    JR NZ, entity_collision_loop

    POP AF
    POP BC
    RET

HANDLE_BOUNDARY_COLLISION:
    ; Handle collision with screen boundaries
    ; Stop movement in the collision direction
    LD A, 0
    LD (entity_vel_x), A       ; Stop X movement
    LD (entity_vel_y), A       ; Stop Y movement
    RET

HANDLE_TILE_COLLISION:
    ; Handle collision with solid tiles
    ; Prevent movement into the tile
    LD A, 0
    LD (entity_vel_x), A       ; Stop X movement
    LD (entity_vel_y), A       ; Stop Y movement
    RET

HANDLE_ENTITY_COLLISION:
    ; Handle collision between entities
    ; Implementation depends on game logic (damage, bouncing, etc.)
    RET

GET_BEHAVIOR_TILE:
    ; Get behavior value for tile at (B, C)
    ; Returns A = behavior value (0=passable, 1=solid, etc.)
    ; This would read from the behavior map data
    ; For now, return 0 (all passable)
    LD A, 0
    RET

; ==================================================================
; INPUT COMPONENT SYSTEM (Based on input handling)
; ==================================================================

INIT_INPUT_SYSTEM:
    ; Initialize input handling system
    XOR A
    LD (input_state), A
    LD (prev_input_state), A
    RET

UPDATE_INPUT_COMPONENT:
    ; Update input handling for player entities
    ; Store previous input state for edge detection
    LD A, (input_state)
    LD (prev_input_state), A

    ; Read current joystick state
    LD A, 0                    ; Joystick port 0
    CALL GTSTCK                ; Get joystick status (BIOS call)
    LD (input_state), A        ; Store current input state

    ; Process input for entities with input component
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks
    LD C, 0                    ; Entity index

input_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_INPUT        ; Check if has input component
    JR Z, input_next_entity    ; Skip if no input component

    ; Apply input to entity movement (real implementation)
    PUSH BC
    PUSH HL

    ; Convert joystick input to velocity
    LD A, (input_state)
    LD B, 0                    ; Default X velocity
    LD C, 0                    ; Default Y velocity

    ; Check directional input
    CP STICK_UP
    JR Z, input_move_up
    CP STICK_DOWN
    JR Z, input_move_down
    CP STICK_LEFT
    JR Z, input_move_left
    CP STICK_RIGHT
    JR Z, input_move_right
    CP STICK_UPRIGHT
    JR Z, input_move_upright
    CP STICK_UPLEFT
    JR Z, input_move_upleft
    CP STICK_DOWNRIGHT
    JR Z, input_move_downright
    CP STICK_DOWNLEFT
    JR Z, input_move_downleft
    JR input_apply_velocity

input_move_up:
    LD C, -2                   ; Negative Y velocity (up)
    JR input_apply_velocity

input_move_down:
    LD C, 2                    ; Positive Y velocity (down)
    JR input_apply_velocity

input_move_left:
    LD B, -2                   ; Negative X velocity (left)
    JR input_apply_velocity

input_move_right:
    LD B, 2                    ; Positive X velocity (right)
    JR input_apply_velocity

input_move_upright:
    LD B, 1                    ; Diagonal movement (slower)
    LD C, -1
    JR input_apply_velocity

input_move_upleft:
    LD B, -1
    LD C, -1
    JR input_apply_velocity

input_move_downright:
    LD B, 1
    LD C, 1
    JR input_apply_velocity

input_move_downleft:
    LD B, -1
    LD C, 1

input_apply_velocity:
    ; Apply calculated velocity to entity
    ; Store X velocity (entity_vel_x is temp storage for now)
    LD A, B
    LD (entity_vel_x), A       ; Store calculated X velocity

    ; Store Y velocity
    LD A, C
    LD (entity_vel_y), A       ; Store calculated Y velocity

    POP HL
    POP BC

input_next_entity:
    INC HL                     ; Next entity
    INC C                      ; Next entity index
    DJNZ input_update_loop
    RET

; ==================================================================
; BEHAVIOR COMPONENT SYSTEM (Based on BehaviorEditor logic)
; ==================================================================

INIT_BEHAVIOR_SYSTEM:
    ; Initialize AI/behavior system
    RET

UPDATE_BEHAVIOR_COMPONENT:
    ; Update AI/behavior logic for entities
    LD B, 32                   ; Loop through all entities
    LD HL, entity_comp_masks   ; Check component masks

behavior_update_loop:
    LD A, (HL)                 ; Get entity component mask
    AND COMP_MASK_BEHAVIOR     ; Check if has behavior component
    JR Z, behavior_next_entity ; Skip if no behavior component

    ; Execute behavior scripts/AI logic
    ; TODO: State machines, pathfinding, decision trees

behavior_next_entity:
    INC HL                     ; Next entity
    DJNZ behavior_update_loop
    RET

; ==================================================================
; ENTITY MANAGEMENT FUNCTIONS (Based on EntityTemplate system)
; ==================================================================

; Create entity with components (A = entity ID, B = component mask)
CREATE_ENTITY:
    ; Set component mask for entity
    LD HL, entity_comp_masks
    LD E, A                    ; Entity index
    LD D, 0
    ADD HL, DE                 ; HL points to entity mask
    LD (HL), B                 ; Set component mask

    ; Initialize component data based on mask
    BIT 0, B                   ; Check COMP_MASK_POSITION
    CALL NZ, INIT_ENTITY_POSITION

    BIT 1, B                   ; Check COMP_MASK_SPRITE
    CALL NZ, INIT_ENTITY_SPRITE

    ; TODO: Initialize other components based on mask bits

    RET

; Initialize position component for entity (A = entity ID)
INIT_ENTITY_POSITION:
    LD HL, entity_x_pos
    LD E, A
    LD D, 0
    ADD HL, DE
    LD (HL), 100               ; Default X position

    LD HL, entity_y_pos
    ADD HL, DE
    LD (HL), 100               ; Default Y position
    RET

; Initialize sprite component for entity (A = entity ID)
INIT_ENTITY_SPRITE:
    ; Set sprite as visible with default pattern
    LD HL, sprite_pattern
    LD E, A
    LD D, 0
    ADD HL, DE
    LD (HL), 0                 ; Pattern 0

    LD HL, sprite_color
    ADD HL, DE
    LD (HL), 15                ; White color
    RET

; ==================================================================
; END OF COMPONENT SYSTEMS
; ==================================================================


; ==================================================================
; GAME ENTITIES
; File: entities.asm
; Description: Game entity definitions and behavior
; ==================================================================

; ==================================================================
; DEFAULT ENTITY SYSTEM
; ==================================================================

; Basic entity structure
ENTITY_PLAYER_ID EQU 0
ENTITY_ENEMY_ID  EQU 1

INIT_ENTITIES:
    ; Initialize default entities
    CALL INIT_PLAYER
    RET

UPDATE_ENTITIES:
    ; Update all entities
    CALL UPDATE_PLAYER
    RET

INIT_PLAYER:
    ; Initialize player entity
    RET

UPDATE_PLAYER:
    ; Update player logic
    RET

; ==================================================================
; END OF ENTITIES
; ==================================================================


; ==================================================================
; GAME MENUS
; File: menus.asm
; Description: Menu systems and user interface with custom font support
; ==================================================================

; ==================================================================
; DEFAULT MENU SYSTEM
; ==================================================================

; Menu constants
MENU_MAIN_ID     EQU 0
MENU_GAME_ID     EQU 1
MENU_PAUSE_ID    EQU 2

; Menu states
MENU_ITEM_START  EQU 0
MENU_ITEM_EXIT   EQU 1

; Current menu variables
current_menu     DS 1
current_item     DS 1

; ==================================================================
; MENU FUNCTIONS
; ==================================================================

INIT_MENUS:
    ; Initialize menu system
    LD A, MENU_MAIN_ID
    LD (current_menu), A
    XOR A
    LD (current_item), A
    RET

SHOW_MAIN_MENU:
    ; Display main menu with custom font
    CALL CLS

    ; Make sure custom font is loaded
    CALL INIT_FONT_SYSTEM

    ; Print title using custom font
    LD HL, txt_title
    LD DE, NAMETBL + (5 * 32) + 10  ; Row 5, column 10
    CALL PRINT_STRING_SCREEN2        ; Use custom font print function

    ; Print menu options using custom font
    LD HL, txt_start
    LD DE, NAMETBL + (10 * 32) + 12
    CALL PRINT_STRING_SCREEN2

    LD HL, txt_exit
    LD DE, NAMETBL + (12 * 32) + 12
    CALL PRINT_STRING_SCREEN2

    RET

HANDLE_MAIN_MENU:
    ; Handle main menu input
    CALL GTSTCK     ; Get joystick input

    ; Check for up/down movement
    CP 1            ; Up
    JP Z, menu_up
    CP 5            ; Down
    JP Z, menu_down

    ; Check for selection (space or fire button)
    CALL GTTRIG
    OR A
    JP NZ, menu_select

    RET

menu_up:
    LD A, (current_item)
    OR A
    JP Z, menu_up_end  ; Already at top
    DEC A
    LD (current_item), A
menu_up_end:
    RET

menu_down:
    LD A, (current_item)
    CP MENU_ITEM_EXIT
    JP Z, menu_down_end  ; Already at bottom
    INC A
    LD (current_item), A
menu_down_end:
    RET

menu_select:
    LD A, (current_item)
    CP MENU_ITEM_START
    JP Z, start_game
    CP MENU_ITEM_EXIT
    JP Z, exit_game
    RET

start_game:
    ; Start the game
    LD A, MENU_GAME_ID
    LD (current_menu), A
    RET

exit_game:
    ; Exit to BASIC
    RST #00

; ==================================================================
; MENU TEXT DATA
; ==================================================================

txt_title:
    DB "GAME TITLE", 0

txt_start:
    DB "START GAME", 0

txt_exit:
    DB "EXIT", 0

; ==================================================================
; TEXT PRINTING FUNCTION
; ==================================================================

PRINT_STRING:
    ; Print null-terminated string
    ; HL = source string, DE = VRAM destination
print_loop:
    LD A, (HL)
    OR A
    RET Z           ; End of string

    ; WRTVRM expects: A = data, HL = VRAM address
    PUSH HL         ; Save string pointer
    PUSH DE         ; Save VRAM address
    POP HL          ; HL = VRAM address (for WRTVRM)
    CALL WRTVRM     ; Write character to VRAM
    POP HL          ; Restore string pointer

    INC HL          ; Next character in string
    INC DE          ; Next VRAM position
    JP print_loop

; ==================================================================
; END OF MENUS
; ==================================================================


; ==================================================================
; MAIN PROGRAM (from main.asm - excluding includes)
; ==================================================================
MAIN_PROGRAM:
    ; Initialize game systems
    CALL INIT_GAME_SYSTEMS

    ; Initialize Game Flow system
    XOR A
    LD (current_flow_state), A
    LD (prev_flow_state), A

    ; Start with main menu
    LD A, FLOW_STATE_MAIN_MENU
    LD (current_flow_state), A

    ; Main game loop
MAIN_LOOP:
    HALT                 ; Wait for V-Blank
    CALL UPDATE_CURRENT_STATE
    CALL RENDER_FRAME
    JP MAIN_LOOP

; ==================================================================
; GAME SYSTEM FUNCTIONS (implemented)
; ==================================================================

INIT_GAME_SYSTEMS:
    ; Initialize component systems
    CALL INIT_COMPONENTS

    ; Initialize sprite system and load patterns
    CALL INIT_SPRITES
    CALL LOAD_SPRITE_PATTERNS  ; Load sprite patterns to VRAM

    ; Load pattern and color data
    CALL LOAD_PATTERN_BANK0
    CALL LOAD_PATTERN_BANK1
    CALL LOAD_PATTERN_BANK2
    CALL LOAD_COLOR_BANK0
    CALL LOAD_COLOR_BANK1
    CALL LOAD_COLOR_BANK2

    ; Initialize game entities with real positions from JSON
    CALL INIT_ENTITIES

    ; Initialize sound system
    CALL GICINI               ; Initialize PSG

    ; Clear screen (BIOS CLS handles timing)
    CALL FILLSCREEN

    ; Load the first game screen
    CALL LOAD_GAME_SCREEN

    ; No startup message needed for pure game projects

    RET

UPDATE_CURRENT_STATE:
    ; Update game logic based on current flow state
    ; Store previous state for transition detection
    LD A, (current_flow_state)
    LD (prev_flow_state), A

    ; Update input first (needed by all states)
    CALL UPDATE_INPUT_COMPONENT

    ; Branch to appropriate state handler
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, UPDATE_MAIN_MENU_STATE
    CP FLOW_STATE_GAME
    JP Z, UPDATE_GAME_STATE
    CP FLOW_STATE_PAUSE
    JP Z, UPDATE_PAUSE_STATE
    CP FLOW_STATE_GAME_OVER
    JP Z, UPDATE_GAME_OVER_STATE
    CP FLOW_STATE_CREDITS
    JP Z, UPDATE_CREDITS_STATE
    RET

UPDATE_MAIN_MENU_STATE:
    ; Handle main menu input and logic
    ; Check for joystick input to navigate menu
    LD A, (input_state)
    CP STICK_DOWN
    CALL Z, MENU_CURSOR_DOWN
    CP STICK_UP
    CALL Z, MENU_CURSOR_UP

    ; Check for selection (trigger or space)
    LD A, 0                     ; Trigger port 0
    CALL GTTRIG
    OR A
    JP NZ, MENU_SELECT_OPTION

    ; Check for START key to begin game directly
    LD A, (input_state)
    CP STICK_CENTER
    RET NZ
    LD A, 0
    CALL GTTRIG
    OR A
    JP NZ, START_GAME_FROM_MENU
    RET

UPDATE_GAME_STATE:
    ; Main gameplay logic - update all component systems in correct order
    CALL UPDATE_INPUT_COMPONENT     ; Read input
    CALL UPDATE_BEHAVIOR_COMPONENT  ; AI/Logic decisions
    CALL UPDATE_MOVEMENT_COMPONENT  ; Apply physics/movement
    CALL UPDATE_POSITION_COMPONENT  ; Update positions
    CALL UPDATE_COLLISION_COMPONENT ; Check collisions
    CALL UPDATE_SPRITE_COMPONENT    ; Update sprite rendering

    ; Check for pause input (SELECT key or P)
    LD A, (input_state)
    CP STICK_CENTER                ; Center + trigger = pause
    RET NZ
    LD A, 0
    CALL GTTRIG
    OR A
    JP NZ, PAUSE_GAME

    ; Check for game over conditions
    CALL CHECK_GAME_OVER_CONDITIONS
    RET

UPDATE_PAUSE_STATE:
    ; Handle pause state - minimal updates
    ; Check for unpause input (same as pause)
    LD A, (input_state)
    CP STICK_CENTER
    RET NZ
    LD A, 0
    CALL GTTRIG
    OR A
    JP NZ, UNPAUSE_GAME
    RET

UPDATE_GAME_OVER_STATE:
    ; Handle game over state
    ; Auto-advance to menu after delay or on input
    LD A, (frame_counter)
    AND #3F                         ; Check every 64 frames (~1 second)
    RET NZ

    ; Check for any input to return to menu
    LD A, 0
    CALL GTTRIG
    OR A
    JP NZ, RETURN_TO_MENU

    ; Auto-return after timeout
    LD HL, (frame_counter)
    LD DE, 300                      ; ~5 seconds at 60fps
    OR A
    SBC HL, DE
    JP NC, RETURN_TO_MENU
    RET

UPDATE_CREDITS_STATE:
    ; Handle credits state - auto-advance
    LD A, (frame_counter)
    AND #1F                         ; Check every 32 frames
    RET NZ

    ; Auto-return to menu after credits
    LD HL, (frame_counter)
    LD DE, 600                      ; ~10 seconds
    OR A
    SBC HL, DE
    JP NC, RETURN_TO_MENU
    RET

; ==================================================================
; GAME FLOW TRANSITION FUNCTIONS (Critical for Parity)
; ==================================================================

START_GAME_FROM_MENU:
    ; Transition: Main Menu → Game
    LD A, FLOW_STATE_GAME
    LD (current_flow_state), A

    ; Initialize game state
    CALL INIT_GAME_ENTITIES
    CALL RESET_GAME_VARIABLES

    ; Clear screen and load game screen
    CALL CLS
    CALL LOAD_GAME_SCREEN
    RET

PAUSE_GAME:
    ; Transition: Game → Pause
    LD A, FLOW_STATE_PAUSE
    LD (current_flow_state), A

    ; Save game state (already in RAM variables)
    ; Show pause overlay
    CALL SHOW_PAUSE_OVERLAY
    RET

UNPAUSE_GAME:
    ; Transition: Pause → Game
    LD A, FLOW_STATE_GAME
    LD (current_flow_state), A

    ; Restore game display
    CALL CLEAR_PAUSE_OVERLAY
    RET

GAME_OVER:
    ; Transition: Game → Game Over
    LD A, FLOW_STATE_GAME_OVER
    LD (current_flow_state), A

    ; Reset frame counter for timeout
    LD HL, 0
    LD (frame_counter), HL

    ; Show game over screen
    CALL SHOW_GAME_OVER_SCREEN
    RET

RETURN_TO_MENU:
    ; Pure game - restart game instead of menu
    LD A, FLOW_STATE_GAME
    LD (current_flow_state), A

    ; Reset all game state and restart
    CALL RESET_ALL_GAME_STATE
    CALL INIT_GAME_ENTITIES
    CALL LOAD_GAME_SCREEN
    RET

; ==================================================================
; STATE HELPER FUNCTIONS
; ==================================================================

MENU_CURSOR_DOWN:
    ; Move menu cursor down (cycle through options)
    RET

MENU_CURSOR_UP:
    ; Move menu cursor up (cycle through options)
    RET

MENU_SELECT_OPTION:
    ; Select current menu option
    JP START_GAME_FROM_MENU

CHECK_GAME_OVER_CONDITIONS:
    ; Check if player is dead, enemies cleared, etc.
    ; Implementation depends on specific game logic
    RET

INIT_GAME_ENTITIES:
    ; Initialize all game entities for new game
    CALL INIT_ENTITIES
    CALL INIT_SPRITES
    RET

RESET_GAME_VARIABLES:
    ; Reset score, health, etc.
    XOR A
    LD (player_health), A
    LD HL, 0
    LD (player_score), HL
    RET

RESET_ALL_GAME_STATE:
    ; Complete reset for return to menu
    CALL CLEAR_ALL_SPRITES
    CALL RESET_GAME_VARIABLES
    RET

LOAD_GAME_SCREEN:
    ; Load game screen based on GameFlow execution path
    ; This follows the exact same flow as Play mode for PARIDAD

    ; GameFlow detected - follow node execution path
    ; Start node: gf_start_1758379036872
    ; Nodes: 2 total
    ; Node 0: gf_start_1758379036872 (Start) 
    ; Node 1: gfn_1758379328617 (WorldLink) 

    ; Execute first GameFlow transition (matches Play mode behavior)
    CALL EXECUTE_GAMEFLOW_START
    RET

; ==================================================================
; GAMEFLOW EXECUTION FUNCTIONS (Critical for Paridad)
; ==================================================================

EXECUTE_GAMEFLOW_START:

    ; Execute the GameFlow start node exactly as Play mode does
    ; Start node ID: gf_start_1758379036872

    ; Find and execute start node
    LD HL, gameflow_node_gf_start_1758379036872
    CALL EXECUTE_GAMEFLOW_NODE
    RET

EXECUTE_GAMEFLOW_NODE:
    ; Execute a single GameFlow node (matches Play mode execution)
    ; HL = pointer to node data structure

    ; Get node type and execute appropriate handler
    LD A, (HL)                    ; Load node type
    CP NODE_TYPE_START
    JP Z, EXECUTE_START_NODE
    CP NODE_TYPE_WORLDLINK
    JP Z, EXECUTE_WORLD_LINK_NODE
    CP NODE_TYPE_SCREEN
    JP Z, EXECUTE_SCREEN_NODE
    CP NODE_TYPE_MENU
    JP Z, EXECUTE_MENU_NODE

    ; Unknown node type - skip
    RET

EXECUTE_START_NODE:
    ; Start node - typically just transitions to next node
    ; Find next connected node and execute it
    CALL FIND_NEXT_GAMEFLOW_NODE
    JP EXECUTE_GAMEFLOW_NODE

EXECUTE_WORLD_LINK_NODE:
    ; World link node - load the referenced world map


    RET

EXECUTE_SCREEN_NODE:
    ; Screen node - load the specific screen
    ; Extract screen reference from node data
    CALL LOAD_REFERENCED_SCREEN
    RET

EXECUTE_MENU_NODE:
    ; Menu node - show menu interface
    CALL SHOW_MENU_INTERFACE
    RET

LOAD_DEFAULT_SCREEN:
    ; Fallback: load first available screen

    CALL LOAD_SCREEN_SCREEN_1_VACIA
    RET

FIND_NEXT_GAMEFLOW_NODE:
    ; Find the next node in GameFlow connections
    ; Implementation depends on connection data structure
    ; For now, use first connection if available
    RET

LOAD_REFERENCED_SCREEN:
    ; Load screen referenced by current node
    ; Implementation needs node data parsing
    CALL LOAD_DEFAULT_SCREEN
    RET

SHOW_MENU_INTERFACE:
    ; Show menu defined in GameFlow node
    ; Implementation needs menu data parsing
    RET

SHOW_NO_CONTENT_MESSAGE:
    ; Show message when no content is available
    RET

; ==================================================================
; GAMEFLOW NODE DATA STRUCTURES
; ==================================================================


; Node: gf_start_1758379036872 (Start)
gameflow_node_gf_start_1758379036872:
    DB NODE_TYPE_START
    DW 0
    ; Additional node data would go here


; Node: gfn_1758379328617 (WorldLink)
gameflow_node_gfn_1758379328617:
    DB NODE_TYPE_WORLDLINK
    DW 0
    ; Additional node data would go here


SHOW_PAUSE_OVERLAY:
    ; Pure game - no pause overlay needed
    RET

CLEAR_PAUSE_OVERLAY:
    ; Clear pause overlay by redrawing that area
    ; Simple implementation: reload game screen
    CALL LOAD_GAME_SCREEN
    RET

SHOW_GAME_OVER_SCREEN:
    ; Pure game - no game over screen needed
    ; Just restart the game automatically
    RET

RENDER_FRAME:
    ; Render current frame based on flow state
    ; Optimized rendering with V-Blank synchronization

    ; Increment frame counter for timing
    LD HL, (frame_counter)
    INC HL
    LD (frame_counter), HL

    ; Check current flow state and render appropriately
    LD A, (current_flow_state)
    CP FLOW_STATE_MAIN_MENU
    JP Z, RENDER_MAIN_MENU
    CP FLOW_STATE_GAME
    JP Z, RENDER_GAME
    CP FLOW_STATE_PAUSE
    JP Z, RENDER_PAUSE
    CP FLOW_STATE_GAME_OVER
    JP Z, RENDER_GAME_OVER
    CP FLOW_STATE_CREDITS
    JP Z, RENDER_CREDITS

    ; Default: unknown state - just continue
    RET

RENDER_MAIN_MENU:
    ; Pure game - no menu, go directly to game
    LD A, FLOW_STATE_GAME
    LD (current_flow_state), A
    CALL INIT_GAME_ENTITIES
    CALL LOAD_GAME_SCREEN
    RET

RENDER_GAME:
    ; Render game frame with optimized sprite updates
    ; Only update sprites that have moved (optimization)

    ; Update sprite positions in VRAM only when needed
    ; This is much more efficient than reloading entire screen
    CALL UPDATE_SPRITES_TO_VRAM

    ; Pure game rendering - no UI text needed
    ; Game state is entirely visual through sprites and background
    RET

RENDER_PAUSE:
    ; Pure game - no pause text needed
    ; Game is paused but visually identical
    RET

RENDER_GAME_OVER:
    ; Pure game - return to game after brief pause
    ; No text needed - just restart game
    CALL RETURN_TO_MENU
    RET

RENDER_CREDITS:
    ; Pure game - no credits needed
    CALL RETURN_TO_MENU
    RET

; Pure game - no text strings needed for SIMPLE_SPRITE(2)
; All communication is through visual gameplay elements

    END                 ; End of assembly
