/**
 * @fileoverview MSX Main.asm Generator
 * Generates main.asm file with proper includes and project structure
 */

import { ProjectAsset, ComponentDefinition, EntityTemplate, Sprite, Tile, ScreenMap } from '../types';
import { analyzeProject, ProjectAnalysis } from './asmTemplateGenerator';
import * as ECSGen from './msxECSGenerators';

/**
 * MSX Project configuration
 */
export interface MSXProjectConfig {
  projectName: string;
  targetMSX: 'MSX1' | 'MSX2' | 'MSX2+';
  baseAddress: number;
  cartridgeType: 'ROM' | 'MEGAROM' | 'DISK';
  includeStateSystem: boolean;
  includeBIOS: boolean;
  generateBinaryFiles: boolean;
}

/**
 * Default MSX project configuration
 */
export const DEFAULT_MSX_CONFIG: MSXProjectConfig = {
  projectName: 'MSX_Game',
  targetMSX: 'MSX1',
  baseAddress: 0x8000,
  cartridgeType: 'ROM',
  includeStateSystem: true,
  includeBIOS: true,
  generateBinaryFiles: true
};

/**
 * Generate main.asm file with proper includes
 */
export function generateMainASM(
  projectName: string,
  assets: ProjectAsset[],
  config: MSXProjectConfig = DEFAULT_MSX_CONFIG
): string {
  const analysis = analyzeProject(projectName, assets);
  const sanitizedName = projectName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  
  let code = '';
  
  // Header
  code += `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n`;
  code += `;; ${projectName.toUpperCase()} - MSX GAME MAIN FILE\n`;
  code += `;; Generated by MSX Retro Game IDE\n`;
  code += `;; Target: ${config.targetMSX}\n`;
  code += `;; Base Address: #${config.baseAddress.toString(16).toUpperCase()}\n`;
  code += `;; Generated: ${new Date().toISOString()}\n`;
  code += `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n`;
  
  // Memory organization
  code += `; Memory Organization\n`;
  code += `    ORG #${config.baseAddress.toString(16).toUpperCase()}\n\n`;
  
  // ROM Header (if cartridge)
  if (config.cartridgeType === 'ROM' || config.cartridgeType === 'MEGAROM') {
    code += generateROMHeader(projectName, config);
  }
  
  // Include system files
  code += `; ==================================================================\n`;
  code += `; SYSTEM INCLUDES\n`;
  code += `; ==================================================================\n`;
  code += `INCLUDE "system/constants.asm"     ; MSX system constants\n`;
  
  if (config.includeBIOS) {
    code += `INCLUDE "system/bios.asm"          ; BIOS function definitions\n`;
  }
  
  if (config.includeStateSystem) {
    code += `INCLUDE "system/state_machine.asm" ; Game state management\n`;
  }
  
  code += `INCLUDE "system/utils.asm"         ; Utility functions\n\n`;
  
  // Include asset files based on project content
  code += generateAssetIncludes(analysis);
  
  // Include game logic files
  code += generateGameLogicIncludes(analysis, sanitizedName);
  
  // Main program entry point
  code += generateMainProgram(analysis, config);
  
  // Asset data sections
  code += generateAssetDataSections(analysis);
  
  // Game initialization
  code += generateInitializationCode(analysis, config);
  
  // Main game loop
  code += generateMainLoop(analysis, config);
  
  // Footer
  code += `; ==================================================================\n`;
  code += `; END OF ${projectName.toUpperCase()}\n`;
  code += `; ==================================================================\n`;
  
  return code;
}

/**
 * Generate ROM header for cartridge games
 */
function generateROMHeader(projectName: string, config: MSXProjectConfig): string {
  return `; ==================================================================
; ROM HEADER
; ==================================================================
    DB "AB"              ; ROM signature
    DW INIT_GAME         ; Init address
    DW 0,0,0,0,0         ; Statement, Device, Text, Reserved

INIT_GAME:
    ; ROM cartridge initialization
    DI                   ; Disable interrupts during init
    
    ; Initialize stack
    LD SP, #F380
    
    ; Clear work RAM
    LD HL, #C000
    LD DE, #C001
    LD BC, #3FFF
    LD (HL), 0
    LDIR
    
    ; Jump to main program
    JP MAIN_PROGRAM

`;
}

/**
 * Generate asset include statements
 */
function generateAssetIncludes(analysis: ProjectAnalysis): string {
  let code = `; ==================================================================\n`;
  code += `; ASSET INCLUDES\n`;
  code += `; ==================================================================\n`;
  
  if (analysis.tiles.length > 0) {
    code += `INCLUDE "assets/tiles.asm"         ; Tile pattern and color data\n`;
  }
  
  if (analysis.sprites.length > 0) {
    code += `INCLUDE "assets/sprites.asm"       ; Sprite pattern data\n`;
  }
  
  if (analysis.screenMaps.length > 0) {
    code += `INCLUDE "assets/screens.asm"       ; Screen map layouts\n`;
  }
  
  if (analysis.hasECS) {
    code += `INCLUDE "assets/entities.asm"      ; Entity and component data\n`;
  }
  
  code += `INCLUDE "assets/palettes.asm"      ; Color palette data\n\n`;
  
  return code;
}

/**
 * Generate game logic include statements
 */
function generateGameLogicIncludes(analysis: ProjectAnalysis, projectName: string): string {
  let code = `; ==================================================================\n`;
  code += `; HOOK SYSTEM INCLUDES\n`;
  code += `; ==================================================================\n`;
  
  // Core Hook system - MUST be included first
  code += `INCLUDE "hook/hook_core.asm"       ; Hook system dispatcher\n`;
  code += `INCLUDE "hook/hook_systems.asm"    ; Hook system implementations\n`;
  
  code += `; ==================================================================\n`;
  code += `; GAME LOGIC INCLUDES\n`;
  code += `; ==================================================================\n`;
  
  code += `INCLUDE "game/input.asm"           ; Input handling\n`;
  code += `INCLUDE "game/graphics.asm"        ; Graphics routines\n`;
  
  if (analysis.hasCollisions) {
    code += `INCLUDE "game/collision.asm"       ; Collision detection\n`;
  }
  
  if (analysis.hasSprites) {
    code += `INCLUDE "game/sprites.asm"         ; Sprite management\n`;
  }
  
  if (analysis.hasECS) {
    code += `INCLUDE "game/ecs.asm"             ; Entity Component System\n`;
  }
  
  if (analysis.hasMenuSystem) {
    code += `INCLUDE "game/menu.asm"            ; Menu system (Hook-compatible)\n`;
  }
  
  if (analysis.customStates.length > 0) {
    code += `INCLUDE "game/custom_states.asm"   ; Custom game states\n`;
  }
  
  code += `INCLUDE "game/${projectName}_logic.asm" ; Project-specific logic\n\n`;
  
  return code;
}

/**
 * Generate main program structure
 */
function generateMainProgram(analysis: ProjectAnalysis, config: MSXProjectConfig): string {
  return `; ==================================================================
; MAIN PROGRAM ENTRY POINT - HOOK SYSTEM ARCHITECTURE
; ==================================================================

MAIN_PROGRAM:
    di                          ; Disable interrupts
    
    ; Initialize stack
    ld sp, #F380
    
    ; Clear work RAM
    ld hl, #C000
    ld de, #C001
    ld bc, #3FFF
    ld (hl), 0
    ldir
    
    ; Initialize Hook system first
    call INIT_HOOK_SYSTEM
    
    ; System initialization through Hook calls
    call HOOK_INIT_MSX_HARDWARE
    call HOOK_INIT_MEMORY
    call HOOK_LOAD_ASSETS
    
    ; Start with initial system based on project
    ld a, ${analysis.hasMenuSystem ? 'HOOK_MENU_SYSTEM' : 'HOOK_GAME_SYSTEM'}
    call HOOK_ACTIVATE_SYSTEM
    
    ; Enable interrupts and start Hook main loop
    ei
    jp HOOK_MAIN_LOOP

`;
}

/**
 * Generate asset data sections references
 */
function generateAssetDataSections(analysis: ProjectAnalysis): string {
  let code = `; ==================================================================\n`;
  code += `; ASSET DATA REFERENCES\n`;
  code += `; ==================================================================\n`;
  
  if (analysis.tiles.length > 0) {
    code += `; Tile data will be included from tiles.asm\n`;
    code += `; - TILE_PATTERNS: Pattern data for ${analysis.tiles.length} tiles\n`;
    code += `; - TILE_COLORS: Color attribute data\n`;
  }
  
  if (analysis.sprites.length > 0) {
    code += `; Sprite data will be included from sprites.asm\n`;
    code += `; - SPRITE_PATTERNS: Pattern data for ${analysis.sprites.length} sprites\n`;
    if (analysis.hasAnimations) {
      code += `; - SPRITE_ANIMATIONS: Animation frame data\n`;
    }
  }
  
  if (analysis.screenMaps.length > 0) {
    code += `; Screen map data will be included from screens.asm\n`;
    code += `; - SCREEN_LAYOUTS: Layout data for ${analysis.screenMaps.length} screens\n`;
  }
  
  code += `\n`;
  return code;
}

/**
 * Generate initialization code
 */
function generateInitializationCode(analysis: ProjectAnalysis, config: MSXProjectConfig): string {
  return `; ==================================================================
; INITIALIZATION ROUTINES
; ==================================================================

INIT_MSX_SYSTEM:
    ; Set screen mode based on target
    LD A, ${config.targetMSX === 'MSX1' ? '2' : '4'}
    CALL CHGMOD          ; Change to screen mode
    RET

INIT_GRAPHICS_MODE:
    ; Initialize graphics for game
    CALL CLS             ; Clear screen
    RET

INIT_INTERRUPTS:
    ; Setup interrupt handling
    DI
    ; Interrupt setup code here
    EI
    RET

INIT_INPUT_SYSTEM:
    ; Initialize input handling
    XOR A
    LD (input_state), A
    LD (prev_input_state), A
    RET

${analysis.hasCollisions ? `INIT_COLLISION_SYSTEM:
    ; Initialize collision detection system
    ; Setup collision maps and detection routines
    RET

` : ''}START_GAME:
    ; Game-specific startup sequence
${config.includeStateSystem ? '    LD A, STATE_MENU\n    CALL CHANGE_GAME_STATE\n' : '    CALL INIT_GAME_STATE\n'}    RET

`;
}

/**
 * Generate main game loop (if not using state machine)
 */
function generateMainLoop(analysis: ProjectAnalysis, config: MSXProjectConfig): string {
  return `; ==================================================================
; HOOK MAIN LOOP - Dynamic System Execution
; ==================================================================

HOOK_MAIN_LOOP:
    halt                        ; Wait for V-Blank interrupt
    
    ; Execute current active system through Hook dispatcher
    call HOOK_EXECUTE_CURRENT_SYSTEM
    
    ; Check for system transitions
    call HOOK_CHECK_SYSTEM_CHANGE
    
    ; Loop forever - Hook system handles everything
    jp HOOK_MAIN_LOOP

; ==================================================================
; HOOK SYSTEM CONSTANTS
; ==================================================================

; System IDs for Hook dispatcher
HOOK_MENU_SYSTEM     equ 0      ; Menu system
HOOK_GAME_SYSTEM     equ 1      ; Main game system
HOOK_PAUSE_SYSTEM    equ 2      ; Pause overlay system
HOOK_TRANSITION_SYS  equ 3      ; Screen transition system

; Hook system state
current_hook_system: db HOOK_MENU_SYSTEM

`;
}

/**
 * Generate asset loading stub functions
 */
export function generateAssetLoadingStubs(analysis: ProjectAnalysis): string {
  let code = `; ==================================================================\n`;
  code += `; ASSET LOADING STUB FUNCTIONS\n`;
  code += `; These will be replaced with actual binary loading code\n`;
  code += `; ==================================================================\n\n`;
  
  code += `LOAD_PALETTES:\n`;
  code += `    ; Load color palettes from binary files\n`;
  code += `    RET\n\n`;
  
  if (analysis.tiles.length > 0) {
    code += `LOAD_TILES:\n`;
    code += `    ; Load tile patterns from bin/tiles/\n`;
    code += `    ; CALL LOAD_BINARY_FILE("tiles.bin", TILE_PATTERNS)\n`;
    code += `    RET\n\n`;
  }
  
  if (analysis.sprites.length > 0) {
    code += `LOAD_SPRITES:\n`;
    code += `    ; Load sprite patterns from bin/sprites/\n`;
    code += `    ; CALL LOAD_BINARY_FILE("sprites.bin", SPRITE_PATTERNS)\n`;
    code += `    RET\n\n`;
  }
  
  if (analysis.screenMaps.length > 0) {
    code += `LOAD_SCREEN_MAPS:\n`;
    code += `    ; Load screen layouts from bin/screens/\n`;
    code += `    ; CALL LOAD_BINARY_FILE("screens.bin", SCREEN_LAYOUTS)\n`;
    code += `    RET\n\n`;
  }
  
  return code;
}

/**
 * Generate professional ECS MSX project structure
 */
export function generateMSXProjectFiles(
  projectName: string,
  assets: ProjectAsset[],
  config: MSXProjectConfig = DEFAULT_MSX_CONFIG
): { [filename: string]: string } {
  const analysis = analyzeProject(projectName, assets);
  const sanitizedName = projectName.toLowerCase().replace(/[^a-z0-9]/g, '_');
  
  const files: { [filename: string]: string } = {};
  
  // Source files
  files['src/main.asm'] = ECSGen.generateProfessionalMainASM(projectName, analysis, config);
  files['src/constants.asm'] = generateConstantsFile(config);
  files['src/macros.asm'] = ECSGen.generateMacrosFile(analysis);
  
  // HOOK SYSTEM FILES - Core dynamic system dispatcher
  files['src/hook/hook_core.asm'] = ECSGen.generateHookCore();
  files['src/hook/hook_systems.asm'] = ECSGen.generateHookSystems(analysis);
  
  // ECS System files (if ECS detected)
  if (analysis.hasECS) {
    files['src/ecs/entity_manager.asm'] = ECSGen.generateEntityManagerASM(analysis);
    files['src/ecs/component_types.asm'] = ECSGen.generateComponentTypesASM(analysis);
    files['src/ecs/system_renderer.asm'] = ECSGen.generateRendererSystemASM(analysis);
    files['src/ecs/system_input.asm'] = ECSGen.generateInputSystemASM(analysis);
    files['src/ecs/system_physics.asm'] = ECSGen.generatePhysicsSystemASM(analysis);
    files['src/ecs/system_collision.asm'] = ECSGen.generateCollisionSystemASM(analysis);
  }
  
  // Core system files
  files['src/core/memory.asm'] = ECSGen.generateMemoryManagerASM(analysis);
  files['src/core/scheduler.asm'] = ECSGen.generateSchedulerASM(analysis);
  
  // Screen files
  files['src/screens/screen_game.asm'] = ECSGen.generateGameScreenASM(analysis);
  files['src/screens/screen_menu.asm'] = ECSGen.generateMenuScreenASM(analysis);
  
  // Asset definition files
  if (analysis.screenMaps.length > 0) {
    files['assets/maps/level1_entities.csv'] = ECSGen.generateEntitiesCSV(analysis);
  }
  
  // Include files
  files['include/glass_helpers.inc'] = ECSGen.generateGlassHelpersInc();
  
  // Tools
  files['tools/png2msx.py'] = ECSGen.generatePNG2MSXTool();
  files['tools/csv_entities_parser.py'] = ECSGen.generateCSVParserTool();
  
  // Documentation
  files['docs/ecs_design.md'] = ECSGen.generateECSDesignDoc(analysis);
  files['docs/memory_layout.txt'] = ECSGen.generateMemoryLayoutDoc(analysis);
  
  // Build system
  files['glass.cfg'] = ECSGen.generateGlassConfig(sanitizedName);
  files['Makefile'] = ECSGen.generateProfessionalMakefile(sanitizedName, analysis);
  files['README.md'] = ECSGen.generateREADME(projectName, analysis);
  
  return files;
}

/**
 * Generate constants file
 */
function generateConstantsFile(config: MSXProjectConfig): string {
  return `; MSX System Constants
; Generated for ${config.targetMSX} target

; BIOS addresses
CHGMOD  EQU #005F    ; Change screen mode
CLS     EQU #00C3    ; Clear screen
CHPUT   EQU #00A2    ; Character output
GTSTCK  EQU #00D5    ; Get joystick status
GTTRIG  EQU #00D8    ; Get trigger status

; VRAM addresses
NAMETBL EQU #1800    ; Name table
PATTERNTBL EQU #0000 ; Pattern table
COLORTBL EQU #2000   ; Color table
SPRATR  EQU #1B00    ; Sprite attribute table
SPRPAT  EQU #3800    ; Sprite pattern table

; System variables
TIMI    EQU #FC9A    ; Timer interrupt hook

; Game constants
MAX_SPRITES     EQU 32
MAX_ENTITIES    EQU 64
SCREEN_WIDTH    EQU 32
SCREEN_HEIGHT   EQU 24
`;
}

/**
 * Generate build script
 */
function generateBuildScript(projectName: string): string {
  return `@echo off
echo Building ${projectName.toUpperCase()} for MSX...

REM Assemble main file
sjasm main.asm ${projectName}.rom

if exist ${projectName}.rom (
    echo Build successful: ${projectName}.rom created
) else (
    echo Build failed!
)

pause
`;
}

/**
 * Generate Makefile
 */
function generateMakefile(projectName: string): string {
  return `# Makefile for ${projectName.toUpperCase()}
# Generated by MSX Retro Game IDE

ASM = sjasm
TARGET = ${projectName}.rom
MAIN_SRC = main.asm

all: $(TARGET)

$(TARGET): $(MAIN_SRC)
	$(ASM) $(MAIN_SRC) $(TARGET)

clean:
	rm -f $(TARGET) *.sym *.map

.PHONY: all clean
`;
}