"use strict";
/**
 * @fileoverview Unified Generator - All-in-one combined file
 * Generates unitedFiles.asm combining all modular files into one
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateUnifiedFile = generateUnifiedFile;
const bankPacker_1 = require("../utils/bankPacker");
/**
 * Convert routine name to lowercase (for labels, CALL, JP, JR targets)
 */
function toRoutineLabel(name) {
    return name.toLowerCase();
}
/**
 * Generate unified file (unitedFiles.asm) - optional all-in-one file
 *
 * @param files - All generated ASM files
 * @param projectName - Name of the project
 * @param analysis - Project analysis with assets and configuration
 * @param config - ROM mode/mapper configuration
 * @returns ASM code string with all files combined
 */
function generateUnifiedFile(files, projectName, analysis, config = {
    romMode: 'auto',
    targetFormat: 'konami',
    autoMegaROM: true
}) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _j, _k;
    // Check what features are needed
    const hasMenus = (_b = (_a = analysis.gameFlow) === null || _a === void 0 ? void 0 : _a.nodes) === null || _b === void 0 ? void 0 : _b.some(node => node.type === 'SubMenu');
    const hasText = (_c = analysis.screenMaps) === null || _c === void 0 ? void 0 : _c.some(screen => { var _a, _b; return ((_a = screen.layers) === null || _a === void 0 ? void 0 : _a.text) || ((_b = screen.textElements) === null || _b === void 0 ? void 0 : _b.length) > 0; });
    const hasHud = (_d = analysis.screenMaps) === null || _d === void 0 ? void 0 : _d.some(screen => { var _a; return ((_a = screen.hudConfiguration) === null || _a === void 0 ? void 0 : _a.elements) && screen.hudConfiguration.elements.length > 0; });
    const needsFont = hasMenus || hasText || hasHud;
    const bankPackReport = (0, bankPacker_1.buildBankPackReport)(files);
    const bankPackComments = (0, bankPacker_1.formatBankPackReportAsAsmComments)(bankPackReport);
    return `; ==================================================================
; ${projectName.toUpperCase()} - UNIFIED FILE
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
;
; OPTIMIZED: Only includes necessary code for this project
; Tiles: ${((_e = analysis.tiles) === null || _e === void 0 ? void 0 : _e.length) || 0}
; Sprites: ${((_f = analysis.sprites) === null || _f === void 0 ? void 0 : _f.length) || 0}
; Screens: ${((_g = analysis.screenMaps) === null || _g === void 0 ? void 0 : _g.length) || 0}
; Entities: ${((_h = analysis.entities) === null || _h === void 0 ? void 0 : _h.length) || 0}
; Menus: ${hasMenus ? 'Yes' : 'No'}
; HUD: ${hasHud ? 'Yes' : 'No'}
; State Machines: ${((_j = analysis.stateMachines) === null || _j === void 0 ? void 0 : _j.length) || 0}
; ROM Mode: ${config.romMode}
; Mapper Target: ${config.targetFormat}
; Auto MegaROM: ${config.autoMegaROM ? 'Yes' : 'No'}
; ==================================================================
${bankPackComments}

; CRITICAL: header.asm with ORG #4000 and "AB" signature MUST be first
; for the ROM to work correctly. EQUs can go after ORG.
${files['header.asm']}

${files['bios.asm']}

${files['constants.asm']}

${files['variables.asm']}

${files['mapper.asm']}

${files['interrupt.asm']}

${analysis.tiles && analysis.tiles.length > 0 ? files['patterns.asm'] : '; [patterns.asm skipped - no tiles]\n'}

${analysis.tiles && analysis.tiles.length > 0 ? files['colors.asm'] : '; [colors.asm skipped - no tiles]\n'}

${files['sprites.asm']}

${analysis.screenMaps && analysis.screenMaps.length > 0 ? files['screens.asm'] : '; [screens.asm skipped - no screens]\n'}

${files['components.asm']}

${analysis.entities && analysis.entities.length > 0 ? files['entities.asm'] : '; [entities.asm skipped - no entities]\n'}

${hasMenus ? files['menus.asm'] : '; [menus.asm skipped - no menus]\n'}

${needsFont ? files['font.asm'] : '; [font.asm skipped - no text/menus]\n'}

${hasHud ? files['hud.asm'] : '; [hud.asm skipped - no HUD elements]\n'}

${files['sound.asm']}

${files['scroll.asm']}

${files['animtiles.asm']}

${files['particles.asm']}

${files['statemachine.asm'] && files['statemachine.asm'].trim() !== '; No State Machines' ? files['statemachine.asm'] : '; [statemachine.asm skipped - no state machines]\n'}

${analysis.gameFlow ? files['gameflow.asm'] : '; [gameflow.asm skipped - no GameFlow]\n'}

${((_k = analysis.worldmaps) === null || _k === void 0 ? void 0 : _k.length) > 0 ? files['worlds.asm'] : '; [worlds.asm skipped - no WorldMaps]\n'}

; ==================================================================
; GAME SYSTEM FUNCTIONS
; ==================================================================
; NOTE: The main game loop and execution flow are handled exclusively
; by GameFlow (see gameflow.asm section above).
; This section only contains shared initialization and utility functions.
; ==================================================================

init_game_systems:
    call DISSCR               ; Disable screen while loading VRAM assets
${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize component systems (entities detected)
    call init_components
` : `    ; No entities - skipping component system initialization
`}
${analysis.tiles && analysis.tiles.length > 0 ? `    ; Load pattern and color data (tiles detected)
    call load_pattern_bank0
    call load_pattern_bank1
    call load_pattern_bank2
    call load_color_bank0
    call load_color_bank1
    call load_color_bank2
` : `    ; No tiles detected - skipping pattern/color loading
`}
${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize game entities with real positions from JSON
    call init_entities
` : `    ; No entities to initialize
`}
    ; Initialize sound system
    call GICINI               ; Initialize PSG

${analysis.screenMaps && analysis.screenMaps.length > 0 ? `    ; Load the first game screen
    call load_game_screen
` : `    ; No screens - skip screen loading
`}
${needsFont ? `    ; Initialize font system
    call init_font_system
` : `    ; No text/menus - skip font initialization
`}${hasHud ? `    ; HUD dirty flag - will be rendered after screen loading (by GameFlow WorldLink)
    ld a, 1
    ld (hud_dirty_flag), a
` : ``}    call ENASCR               ; Re-enable screen after VRAM updates
    ret

; ==================================================================
; SCREEN LOADING STUB (for compatibility)
; ==================================================================
; NOTE: With GameFlow system, screen loading is handled by GameFlow nodes
; via load_world_X -> load_screen_X. This stub exists for backward
; compatibility with init_game_systems references.
load_game_screen:
    ret

    end                 ; End of assembly
`;
}
