#!/usr/bin/env node
/**
 * The deferred boss path swap, on the emulator.
 *
 * The static contract (check_msx2_boss_path_phase_switch.mjs) proves the ASM was
 * emitted. This proves the boss actually behaves: it walks its route, an attack
 * phase asks for a different one mid-lap, and the swap lands on the anchor the
 * first route started from instead of wherever the HP happened to run out.
 *
 * Nothing here is hardcoded from a previous run. The boss's state lives in a
 * per-instance block whose field offsets depend on which subsystems the project
 * uses, so both the block address and every offset are read back out of the
 * build: the .sym for the addresses, the emitted `bitmap_boss_state_save` for
 * the order of the fields inside it. Sampling the named boss_* variables
 * instead would read whichever of the two boss slots was updated last.
 *
 * Usage:
 *   node scripts/build_msx2_boss_path_phase_switch_smoke.mjs
 *   python -B scripts/build_mideas_unified_rom.py --json test/msx2-boss/fixture_path_phase_switch.json --rom-mode megarom
 *   node scripts/check_msx2_boss_path_phase_switch_openmsx.mjs
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const BUILD = join(root, 'server', 'temp', 'Boss Path Phase Switch Smoke_unified');
const TCL = join(root, 'test', 'msx2-boss', 'path_phase_switch.tcl');
const LOG = join(root, 'test', 'msx2-boss', 'path_phase_switch.txt');

for (const file of [`${BUILD}.rom`, `${BUILD}.sym`, `${BUILD}.asm`]) {
  if (!existsSync(file)) {
    throw new Error(`Missing ${file}. Build the fixture ROM first (see the header of this file).`);
  }
}
const sym = readFileSync(`${BUILD}.sym`, 'utf8');
const asm = readFileSync(`${BUILD}.asm`, 'utf8');

const symbol = label => {
  const match = new RegExp(`^\\s*${label}:\\s+equ\\s+([0-9A-Fa-f]+)H\\s*$`, 'm').exec(sym);
  if (!match) throw new Error(`Symbol ${label} not found in the build`);
  return parseInt(match[1], 16);
};

/**
 * Byte offsets inside one instance block, taken from the copy routine itself:
 * bytes first in order, then the words, which is how stateCopyAsm emits them.
 */
const stateOffsets = () => {
  const start = asm.indexOf('\nbitmap_boss_state_save:');
  if (start < 0) throw new Error('bitmap_boss_state_save not found in the emitted ASM');
  const body = asm.slice(start, asm.indexOf('\n    ret', start));
  const bytes = [...body.matchAll(/ld a, \((boss_\w+)\)/g)].map(m => m[1]).slice(1);   // [0] is boss_slot
  const words = [...body.matchAll(/ld hl, \((boss_\w+)\)/g)].map(m => m[1]);
  const offsets = {};
  bytes.forEach((name, index) => { offsets[name] = index; });
  words.forEach((name, index) => { offsets[name] = bytes.length + index * 2; });
  return { offsets, size: bytes.length + words.length * 2 };
};

const { offsets, size } = stateOffsets();
const declaredSize = symbol('BOSS_INSTANCE_STATE_BYTES');
if (declaredSize !== size) {
  throw new Error(
    `The instance block is declared ${declaredSize} bytes but ${size} are copied into it. `
    + 'Slot 1 would start inside slot 0 and the two bosses would corrupt each other.',
  );
}
const base = symbol('boss_instance_state');
const at = field => {
  if (offsets[field] === undefined) throw new Error(`${field} is not part of the per-instance state`);
  return `0x${(base + offsets[field]).toString(16).toUpperCase()}`;
};

// 30 HP, phase 2 at 50%: 10 is comfortably inside it and still alive.
const POKE_HP = 10;
writeFileSync(TCL, `# GENERATED by scripts/check_msx2_boss_path_phase_switch_openmsx.mjs -- do not hand-edit.
# Addresses come from the build being probed; every one of them moves when the
# project turns another boss subsystem on or off.
set log_path "${LOG.replace(/\\/g, '/')}"
set f [open $log_path "w"]
proc logline {msg} { global f; puts $f $msg; flush $f }
proc mem8 {addr} { return [debug read memory $addr] }
set throttle off

set ACTIVE ${at('boss_active')}
set X ${at('boss_x')}
set Y ${at('boss_y')}
set HP ${at('boss_hp')}
set IDX ${at('boss_path_idx')}
set PENDING ${at('boss_path_pending')}
set HPLIVE 0x${symbol('boss_hp').toString(16).toUpperCase()}
set INTRO 0x${symbol('boss_intro_state').toString(16).toUpperCase()}

set frame 0
set pokeFrame -1 ; set pokeX -1 ; set pokeY -1
set swapFrame -1 ; set swapX -1 ; set swapY -1
set bxmin 255 ; set bxmax 0 ; set bymin 255 ; set bymax 0
set sxmin 255 ; set sxmax 0 ; set symin 255 ; set symax 0

proc watch {} {
    global frame ACTIVE X Y IDX swapFrame swapX swapY
    global bxmin bxmax bymin bymax sxmin sxmax symin symax
    incr frame
    if {[mem8 $ACTIVE] == 1} {
        set x [mem8 $X]
        set y [mem8 $Y]
        set p [mem8 $IDX]
        if {$p == 1} {
            if {$x < $bxmin} { set bxmin $x }
            if {$x > $bxmax} { set bxmax $x }
            if {$y < $bymin} { set bymin $y }
            if {$y > $bymax} { set bymax $y }
        } elseif {$p == 2} {
            if {$swapFrame < 0} { set swapFrame $frame ; set swapX $x ; set swapY $y }
            if {$x < $sxmin} { set sxmin $x }
            if {$x > $sxmax} { set sxmax $x }
            if {$y < $symin} { set symin $y }
            if {$y > $symax} { set symax $y }
        }
    }
    after frame watch
}

foreach t {6 8 10} {
    after time $t "keymatrixdown 8 0x01"
    after time [expr {$t + 0.5}] "keymatrixup 8 0x01"
}
after time 12 {
    # Skip the Room Lock entry sequence. The boss body does not update until it
    # has run, and this fixture's legacy chain intro parks on its "walk the
    # player to the centre" step -- which has nothing to do with routes.
    debug write memory $INTRO 0
}
after time 13 {
    watch
    logline "START x=[mem8 $X] y=[mem8 $Y] hp=[mem8 $HP] path=[mem8 $IDX]"
}
after time 26 {
    global frame pokeFrame pokeX pokeY
    set pokeFrame $frame
    set pokeX [mem8 $X]
    set pokeY [mem8 $Y]
    debug write memory $HP ${POKE_HP}
    debug write memory $HPLIVE ${POKE_HP}
    logline "POKE hp=${POKE_HP} frame=$pokeFrame x=$pokeX y=$pokeY path=[mem8 $IDX]"
}
after time 27 { logline "AFTER1S path=[mem8 $IDX] pending=[mem8 $PENDING] x=[mem8 $X] y=[mem8 $Y]" }
after time 60 {
    global pokeFrame pokeX pokeY swapFrame swapX swapY
    global bxmin bxmax bymin bymax sxmin sxmax symin symax
    logline "BOX x $bxmin $bxmax y $bymin $bymax"
    logline "SWEEP x $sxmin $sxmax y $symin $symax"
    logline "POKED frame $pokeFrame at $pokeX $pokeY"
    logline "SWAPPED frame $swapFrame at $swapX $swapY"
    logline "FINAL path=[mem8 $IDX] pending=[mem8 $PENDING] hp=[mem8 $HP]"
    after time 1 { exit }
}
`);

rmSync(LOG, { force: true });
execFileSync('python', [
  '-B', join(root, 'scripts', 'open_openmsx.py'),
  '--rom', `${BUILD}.rom`,
  // Without the mapper the ROM boots into nonsense and every reading below is
  // a convincing-looking lie.
  '--romtype', 'KonamiSCC',
  '--script', TCL,
  '--wait',
], { cwd: root, stdio: 'ignore' });

if (!existsSync(LOG)) throw new Error('The probe produced no log: OpenMSX did not run the script.');
const log = readFileSync(LOG, 'utf8');
const line = prefix => (new RegExp(`^${prefix} (.*)$`, 'm').exec(log) || [])[1] || '';
const nums = prefix => line(prefix).split(/[^\d-]+/).filter(Boolean).map(Number);

const [bxmin, bxmax, bymin, bymax] = nums('BOX');
const [sxmin, sxmax, symin, symax] = nums('SWEEP');
const [pokeFrame, pokeX, pokeY] = nums('POKED frame');
const [swapFrame, swapX, swapY] = nums('SWAPPED frame');

// What the fixture drew, in relative pixels. X is baked to even steps.
const BOX_SPAN = { x: 60, y: 40 };
const SWEEP_SPAN = { x: 92, y: 24 };
const BODY = 64;
const near = (value, target, slack = 2) => Math.abs(value - target) <= slack;

const checks = [
  ['The boss actually walks its route (a static boss would prove nothing below)',
    Number.isFinite(bxmax) && near(bxmax - bxmin, BOX_SPAN.x) && near(bymax - bymin, BOX_SPAN.y)],

  ['The phase change is not applied on the spot: the boss keeps walking its lap',
    swapFrame > pokeFrame + 30],

  ['The route was mid-lap when the phase changed, so this is the case that used to break',
    !near(pokeX, bxmin, 4) || !near(pokeY, bymin, 4)],

  ['The swap lands on the anchor the FIRST route started from, not where the HP ran out',
    near(swapX, bxmin) && near(swapY, bymin)],

  ['The second route is therefore the shape that was drawn',
    near(sxmax - sxmin, SWEEP_SPAN.x) && near(symax - symin, SWEEP_SPAN.y)],

  ['Both routes share their anchor corner',
    near(sxmin, bxmin) && near(symin, bymin)],

  ['The body never leaves the room',
    sxmin >= 0 && symin >= 0 && sxmax + BODY <= 256 && symax + BODY <= 168
    && bxmin >= 0 && bymin >= 0 && bxmax + BODY <= 256 && bymax + BODY <= 168],
];

console.log(log.trim());
console.log('');
let failed = 0;
for (const [name, ok] of checks) {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}`);
  if (!ok) failed++;
}
console.log(`\n${checks.length - failed}/${checks.length} checks passed`);
process.exit(failed ? 1 : 0);
