import React from 'react';
import { Button } from '../common/Button';

interface MsxEmulatorHelpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const MsxEmulatorHelpModal: React.FC<MsxEmulatorHelpModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 animate-fadeIn p-4"
      onClick={onClose}
      role="dialog"
      aria-modal="true"
      aria-labelledby="msxEmulatorHelpTitle"
    >
      <div
        className="bg-msx-panelbg p-6 rounded-lg shadow-xl w-full max-w-2xl animate-slideIn pixel-font flex flex-col max-h-[85vh]"
        onClick={(e) => e.stopPropagation()}
      >
        <h2 id="msxEmulatorHelpTitle" className="text-lg text-msx-highlight mb-4">
          MSX Emulator — Setup Guide
        </h2>

        <div className="overflow-y-auto flex-grow space-y-5 text-sm font-sans pr-1">

          {/* Section: What is OpenMSX */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">What is OpenMSX?</h3>
            <p className="text-msx-textprimary leading-relaxed">
              <strong>OpenMSX</strong> is the most accurate and widely used <strong>free MSX emulator</strong>.
              It runs on Windows, macOS and Linux and can load .ROM files generated by Mideas directly.
              Mideas uses OpenMSX to launch and test your compiled games with one click.
            </p>
          </section>

          {/* Section: Download */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">Step 1 — Download OpenMSX</h3>
            <p className="text-msx-textprimary leading-relaxed mb-2">
              Go to the official OpenMSX website and download the installer for your platform:
            </p>
            <a
              href="https://openmsx.org/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-msx-highlight underline hover:opacity-80 block"
            >
              https://openmsx.org/ — Official homepage
            </a>
            <a
              href="https://github.com/openMSX/openMSX/releases"
              target="_blank"
              rel="noopener noreferrer"
              className="text-msx-highlight underline hover:opacity-80 block mt-1"
            >
              https://github.com/openMSX/openMSX/releases — GitHub Releases
            </a>
          </section>

          {/* Section: Install by platform */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">Step 2 — Install</h3>
            <div className="space-y-3">

              <div className="bg-msx-bgcolor rounded p-3">
                <p className="text-msx-accent text-xs font-bold mb-1">Windows</p>
                <ol className="text-msx-textprimary text-xs space-y-1 ml-3 list-decimal list-inside">
                  <li>Download the <code className="bg-msx-panelbg px-1 rounded">.msi</code> installer</li>
                  <li>Double-click the installer and follow the steps (about 3 clicks)</li>
                  <li>OpenMSX will be installed and ready to use</li>
                </ol>
              </div>

              <div className="bg-msx-bgcolor rounded p-3">
                <p className="text-msx-accent text-xs font-bold mb-1">macOS</p>
                <ol className="text-msx-textprimary text-xs space-y-1 ml-3 list-decimal list-inside">
                  <li>Download the <code className="bg-msx-panelbg px-1 rounded">.dmg</code> file</li>
                  <li>Open the .dmg and drag OpenMSX to your Applications folder</li>
                  <li>OpenMSX has a built-in GUI on macOS</li>
                </ol>
              </div>

              <div className="bg-msx-bgcolor rounded p-3">
                <p className="text-msx-accent text-xs font-bold mb-1">Linux (Debian/Ubuntu)</p>
                <pre className="text-msx-textprimary text-xs font-mono mt-1">
{`sudo apt install openmsx-catapult`}
                </pre>
                <p className="text-msx-textsecondary text-xs mt-1">
                  APT will install OpenMSX and all required dependencies automatically.
                </p>
                <p className="text-msx-textsecondary text-xs mt-1">
                  Alternatively, install via{' '}
                  <a
                    href="https://flathub.org/en/apps/org.openmsx.openMSX"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-msx-highlight underline"
                  >
                    Flathub
                  </a>.
                </p>
              </div>
            </div>
          </section>

          {/* Section: First run */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">Step 3 — First Run &amp; C-BIOS</h3>
            <p className="text-msx-textprimary leading-relaxed mb-2">
              OpenMSX comes with <strong>C-BIOS</strong>, a free open source BIOS replacement that lets you run
              cartridge ROM games immediately — <em>no additional files needed</em> for Mideas-generated ROMs.
            </p>
            <div className="bg-msx-highlight bg-opacity-10 border border-msx-highlight rounded p-2 text-xs text-msx-textprimary">
              Mideas exports ROMs as cartridge images (.rom) compatible with C-BIOS out of the box.
            </div>
            <p className="text-msx-textsecondary text-xs mt-2">
              For full MSX machine emulation (disk-based games, BASIC), you will need real MSX BIOS ROM files.
              Check the{' '}
              <a
                href="https://openmsx.org/manual/setup.html"
                target="_blank"
                rel="noopener noreferrer"
                className="text-msx-highlight underline"
              >
                OpenMSX Setup Guide
              </a>{' '}
              for instructions on obtaining system ROMs legally.
            </p>
          </section>

          {/* Section: Mideas integration */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">Integration with Mideas</h3>
            <p className="text-msx-textprimary leading-relaxed mb-1">
              Once OpenMSX is installed, Mideas can launch it automatically after compiling your ROM.
              Use the <strong>Build &amp; Run</strong> button in the Export Z80 Code window:
            </p>
            <ol className="text-msx-textsecondary text-xs space-y-1 ml-3 list-decimal list-inside">
              <li>Go to <strong>File → Export Z80 Code</strong></li>
              <li>Click <strong>Build &amp; Run</strong></li>
              <li>Mideas compiles the ROM and opens it in OpenMSX automatically</li>
            </ol>
            <p className="text-msx-textsecondary text-xs mt-2">
              Make sure <code className="bg-msx-bgcolor px-1 rounded">openmsx</code> is in your system PATH,
              or configure the path in <code className="bg-msx-bgcolor px-1 rounded">server/server.js</code>.
            </p>
          </section>

          {/* Section: Links */}
          <section>
            <h3 className="text-msx-accent font-bold mb-1">Useful Links</h3>
            <div className="space-y-1">
              <a
                href="https://openmsx.org/manual/user.html"
                target="_blank"
                rel="noopener noreferrer"
                className="text-msx-highlight underline hover:opacity-80 block text-xs"
              >
                OpenMSX User's Manual
              </a>
              <a
                href="https://openmsx.org/manual/faq.html"
                target="_blank"
                rel="noopener noreferrer"
                className="text-msx-highlight underline hover:opacity-80 block text-xs"
              >
                OpenMSX FAQ
              </a>
              <a
                href="https://www.msx.org/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-msx-highlight underline hover:opacity-80 block text-xs"
              >
                MSX Resource Center — msx.org
              </a>
            </div>
          </section>

        </div>

        <div className="flex justify-end mt-4 pt-3 border-t border-msx-border">
          <Button onClick={onClose} variant="primary" size="md">
            Close
          </Button>
        </div>
      </div>
    </div>
  );
};
