; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SPRITES                   EQU 1
RESOURCE_GROUP_PATTERNS                  EQU 2
RESOURCE_GROUP_COLORS                    EQU 3
RESOURCE_GROUP_SCREENS                   EQU 4
RESOURCE_GROUP_SOUND                     EQU 5

RESOURCE_TYPE_SPRITE_PATTERNS            EQU 1
RESOURCE_TYPE_TILE_PATTERNS              EQU 2
RESOURCE_TYPE_TILE_COLORS                EQU 3
RESOURCE_TYPE_SCREEN_LAYOUT              EQU 4
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 5
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 6
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 7
RESOURCE_TYPE_SCREEN_DATA                EQU 8
RESOURCE_TYPE_MUSIC_TRACK                EQU 9

RESOURCE_TABLE_COUNT EQU 112

resource_table:
    ; HERO_LEFT_0_F0_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9F8D
    dw 32
    ; HERO_LEFT_0_F0_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9FAD
    dw 32
    ; HERO_LEFT_0_F1_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9FCD
    dw 32
    ; HERO_LEFT_0_F1_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #9F68
    dw 32
    ; HERO_LEFT_0_F2_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #9F88
    dw 32
    ; HERO_LEFT_0_F2_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F2_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #9FA8
    dw 32
    ; HERO_LEFT_0_F3_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 17
    dw #9FC8
    dw 32
    ; HERO_LEFT_0_F3_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F3_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F68
    dw 32
    ; BIRD_1_F0_LAYER1
    db RESOURCE_ID_BIRD_1_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9F88
    dw 32
    ; BIRD_1_F1_LAYER1
    db RESOURCE_ID_BIRD_1_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9FA8
    dw 32
    ; BIRD_1_F2_LAYER1
    db RESOURCE_ID_BIRD_1_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 18
    dw #9FC8
    dw 32
    ; BIRD_1_F3_LAYER1
    db RESOURCE_ID_BIRD_1_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #9F48
    dw 32
    ; BOT1_2_F0_LAYER1
    db RESOURCE_ID_BOT1_2_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #9F68
    dw 32
    ; BOT2_RIGHT_3_F0_LAYER0
    db RESOURCE_ID_BOT2_RIGHT_3_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #9F88
    dw 32
    ; BOT2_RIGHT_3_F1_LAYER0
    db RESOURCE_ID_BOT2_RIGHT_3_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #9FA8
    dw 32
    ; HERO_DEAD_4_F0_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 19
    dw #9FC8
    dw 32
    ; HERO_DEAD_4_F1_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8D48
    dw 32
    ; HERO_DEAD_4_F2_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8D68
    dw 32
    ; HERO_DEAD_4_F3_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8D88
    dw 32
    ; HERO_DEAD_4_F4_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F4_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8DA8
    dw 32
    ; HERO_DEAD_4_F5_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F5_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8DC8
    dw 32
    ; HERO_DEAD_4_F6_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F6_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8DE8
    dw 32
    ; HERO_DEAD_4_F7_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F7_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8E08
    dw 32
    ; HERO_DEAD_4_F8_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F8_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8E28
    dw 32
    ; HERO_DEAD_4_F9_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F9_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8E48
    dw 32
    ; HERO_DEAD_4_F10_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F10_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8E68
    dw 32
    ; HERO_DEAD_4_F11_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F11_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8E88
    dw 32
    ; HERO_DEAD_4_F12_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F12_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8EA8
    dw 32
    ; HERO_DEAD_4_F13_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F13_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8EC8
    dw 32
    ; NEW_SPRITE_5_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_5_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #9F4D
    dw 64
    ; GEMA1_6_F0_LAYER2
    db RESOURCE_ID_GEMA1_6_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8EE8
    dw 32
    ; GEMA1_6_F1_LAYER2
    db RESOURCE_ID_GEMA1_6_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8F08
    dw 32
    ; BOX_7_F0_LAYER1
    db RESOURCE_ID_BOX_7_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8F28
    dw 32
    ; FIRE_8_F0_LAYER1
    db RESOURCE_ID_FIRE_8_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8F48
    dw 32
    ; FIRE_8_F1_LAYER1
    db RESOURCE_ID_FIRE_8_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8F68
    dw 32
    ; FIRE2_LEFT_9_F0_LAYER1
    db RESOURCE_ID_FIRE2_LEFT_9_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8F88
    dw 32
    ; FIRE2_LEFT_9_F1_LAYER1
    db RESOURCE_ID_FIRE2_LEFT_9_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8FA8
    dw 32
    ; FIRE2_LEFT_9_F2_LAYER1
    db RESOURCE_ID_FIRE2_LEFT_9_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8FC8
    dw 32
    ; FIRE2_LEFT_9_F3_LAYER1
    db RESOURCE_ID_FIRE2_LEFT_9_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #8FE8
    dw 32
    ; FIRE2_LEFT_9_F4_LAYER1
    db RESOURCE_ID_FIRE2_LEFT_9_F4_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9008
    dw 32
    ; NEW_SPRITE_1_10_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_1_10_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9028
    dw 32
    ; NEW_SPRITE_1_10_F0_LAYER3
    db RESOURCE_ID_NEW_SPRITE_1_10_F0_LAYER3, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9048
    dw 32
    ; HERO_RIGHT_11_F0_LAYER1
    db RESOURCE_ID_HERO_RIGHT_11_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9068
    dw 32
    ; HERO_RIGHT_11_F0_LAYER2
    db RESOURCE_ID_HERO_RIGHT_11_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9088
    dw 32
    ; HERO_RIGHT_11_F1_LAYER1
    db RESOURCE_ID_HERO_RIGHT_11_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #90A8
    dw 32
    ; HERO_RIGHT_11_F1_LAYER2
    db RESOURCE_ID_HERO_RIGHT_11_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #90C8
    dw 32
    ; HERO_RIGHT_11_F2_LAYER1
    db RESOURCE_ID_HERO_RIGHT_11_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #90E8
    dw 32
    ; HERO_RIGHT_11_F2_LAYER2
    db RESOURCE_ID_HERO_RIGHT_11_F2_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9108
    dw 32
    ; HERO_RIGHT_11_F3_LAYER1
    db RESOURCE_ID_HERO_RIGHT_11_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9128
    dw 32
    ; HERO_RIGHT_11_F3_LAYER2
    db RESOURCE_ID_HERO_RIGHT_11_F3_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9148
    dw 32
    ; BOT2_LEFT_12_F0_LAYER0
    db RESOURCE_ID_BOT2_LEFT_12_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9168
    dw 32
    ; BOT2_LEFT_12_F1_LAYER0
    db RESOURCE_ID_BOT2_LEFT_12_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9188
    dw 32
    ; FIRE2_RIGHT_13_F0_LAYER1
    db RESOURCE_ID_FIRE2_RIGHT_13_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #91A8
    dw 32
    ; FIRE2_RIGHT_13_F1_LAYER1
    db RESOURCE_ID_FIRE2_RIGHT_13_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #91C8
    dw 32
    ; FIRE2_RIGHT_13_F2_LAYER1
    db RESOURCE_ID_FIRE2_RIGHT_13_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #91E8
    dw 32
    ; FIRE2_RIGHT_13_F3_LAYER1
    db RESOURCE_ID_FIRE2_RIGHT_13_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9208
    dw 32
    ; FIRE2_RIGHT_13_F4_LAYER1
    db RESOURCE_ID_FIRE2_RIGHT_13_F4_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9228
    dw 32
    ; SPRITE_PLACEHOLDER_PATTERN
    db RESOURCE_ID_SPRITE_PLACEHOLDER_PATTERN, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 20
    dw #9248
    dw 32
    ; tile_pattern_bank0
    db RESOURCE_ID_TILE_PATTERN_BANK0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 17
    dw #9E00
    dw 360
    ; tilebank_pattern_data_0
    db RESOURCE_ID_TILEBANK_PATTERN_DATA_0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 19
    dw #9E00
    dw 328
    ; tile_color_bank0
    db RESOURCE_ID_TILE_COLOR_BANK0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 18
    dw #9E00
    dw 360
    ; tilebank_color_data_0
    db RESOURCE_ID_TILEBANK_COLOR_DATA_0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 20
    dw #8C00
    dw 328
    ; SCREEN_PAN1_0_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #874D
    dw 768
    ; SCREEN_PAN1_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #8A4D
    dw 768
    ; SCREEN_PAN1_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FED
    dw 1
    ; BEHAVIOR_PAN1_0_DATA
    db RESOURCE_ID_BEHAVIOR_PAN1_0_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 16
    dw #8D4D
    dw 768
    ; SCREEN_PAN1_0_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #904D
    dw 768
    ; SCREEN_PAN1_0_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #934D
    dw 768
    ; SCREEN_PAN1_0_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN1_0_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 16
    dw #964D
    dw 768
    ; SCREEN_PAN2_1_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #994D
    dw 768
    ; SCREEN_PAN2_1_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 16
    dw #9C4D
    dw 768
    ; SCREEN_PAN2_1_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FEE
    dw 1
    ; BEHAVIOR_PAN2_1_DATA
    db RESOURCE_ID_BEHAVIOR_PAN2_1_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #8000
    dw 768
    ; SCREEN_PAN2_1_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN2_1_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #8300
    dw 768
    ; SCREEN_PAN2_1_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN2_1_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #8600
    dw 768
    ; SCREEN_PAN2_1_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN2_1_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #8900
    dw 768
    ; SCREEN_PAN3_2_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_2_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8C00
    dw 768
    ; SCREEN_PAN3_2_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_2_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 17
    dw #8F00
    dw 768
    ; SCREEN_PAN3_2_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN3_2_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FEF
    dw 1
    ; BEHAVIOR_PAN3_2_DATA
    db RESOURCE_ID_BEHAVIOR_PAN3_2_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 17
    dw #9200
    dw 768
    ; SCREEN_PAN3_2_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN3_2_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #9500
    dw 768
    ; SCREEN_PAN3_2_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN3_2_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #9800
    dw 768
    ; SCREEN_PAN3_2_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN3_2_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 17
    dw #9B00
    dw 768
    ; SCREEN_PAN4_3_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_3_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8000
    dw 768
    ; SCREEN_PAN4_3_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_3_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #8300
    dw 768
    ; SCREEN_PAN4_3_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN4_3_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF0
    dw 1
    ; BEHAVIOR_PAN4_3_DATA
    db RESOURCE_ID_BEHAVIOR_PAN4_3_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 18
    dw #8600
    dw 768
    ; SCREEN_PAN4_3_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN4_3_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 18
    dw #8900
    dw 768
    ; SCREEN_PAN4_3_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN4_3_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 18
    dw #8C00
    dw 768
    ; SCREEN_PAN4_3_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN4_3_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 18
    dw #8F00
    dw 768
    ; SCREEN_PAN5_4_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_4_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #9200
    dw 768
    ; SCREEN_PAN5_4_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_4_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 18
    dw #9500
    dw 768
    ; SCREEN_PAN5_4_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN5_4_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF1
    dw 1
    ; BEHAVIOR_PAN5_4_DATA
    db RESOURCE_ID_BEHAVIOR_PAN5_4_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 18
    dw #9800
    dw 768
    ; SCREEN_PAN5_4_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN5_4_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 18
    dw #9B00
    dw 768
    ; SCREEN_PAN5_4_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN5_4_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 19
    dw #8000
    dw 768
    ; SCREEN_PAN5_4_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN5_4_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 19
    dw #8300
    dw 768
    ; SCREEN_PAN62_5_LAYOUT
    db RESOURCE_ID_SCREEN_PAN62_5_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 19
    dw #8600
    dw 768
    ; SCREEN_PAN62_5_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN62_5_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 19
    dw #8900
    dw 768
    ; SCREEN_PAN62_5_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN62_5_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF2
    dw 1
    ; BEHAVIOR_PAN62_5_DATA
    db RESOURCE_ID_BEHAVIOR_PAN62_5_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 19
    dw #8C00
    dw 768
    ; SCREEN_PAN62_5_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN62_5_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 19
    dw #8F00
    dw 768
    ; SCREEN_PAN62_5_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN62_5_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 19
    dw #9200
    dw 768
    ; SCREEN_PAN62_5_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN62_5_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 19
    dw #9500
    dw 768
    ; SCREEN_PAN7_6_LAYOUT
    db RESOURCE_ID_SCREEN_PAN7_6_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 19
    dw #9800
    dw 768
    ; SCREEN_PAN7_6_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN7_6_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 19
    dw #9B00
    dw 768
    ; SCREEN_PAN7_6_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN7_6_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 16
    dw #9FF3
    dw 1
    ; BEHAVIOR_PAN7_6_DATA
    db RESOURCE_ID_BEHAVIOR_PAN7_6_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 20
    dw #8000
    dw 768
    ; SCREEN_PAN7_6_INTERACTION_TYPE_MAP
    db RESOURCE_ID_SCREEN_PAN7_6_INTERACTION_TYPE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 20
    dw #8300
    dw 768
    ; SCREEN_PAN7_6_INTERACTION_VALUE_MAP
    db RESOURCE_ID_SCREEN_PAN7_6_INTERACTION_VALUE_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 20
    dw #8600
    dw 768
    ; SCREEN_PAN7_6_INTERACTION_TARGET_MAP
    db RESOURCE_ID_SCREEN_PAN7_6_INTERACTION_TARGET_MAP, RESOURCE_TYPE_SCREEN_DATA, RESOURCE_GROUP_SCREENS, 20
    dw #8900
    dw 768
    ; music_track_0_Oda1_data
    db RESOURCE_ID_MUSIC_TRACK_0_ODA1_DATA, RESOURCE_TYPE_MUSIC_TRACK, RESOURCE_GROUP_SOUND, 16
    dw #8000
    dw 1869
