; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SCREENS                   EQU 1

RESOURCE_TYPE_SCREEN_LAYOUT              EQU 1
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 2
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 3
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 4

RESOURCE_TABLE_COUNT EQU 4

resource_table:
    ; SCREEN_SCREEN1_0_LAYOUT
    db RESOURCE_ID_SCREEN_SCREEN1_0_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8000
    dw 768
    ; SCREEN_SCREEN1_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_SCREEN1_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8300
    dw 768
    ; SCREEN_SCREEN1_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_SCREEN1_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #8900
    dw 1
    ; BEHAVIOR_SCREEN1_0_DATA
    db RESOURCE_ID_BEHAVIOR_SCREEN1_0_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 14
    dw #8600
    dw 768
