/**
 * @fileoverview Game Flow Generator - GameFlow state machine
 * Generates GameFlow state machine from GameFlow graph for ASM
 */

import { ProjectAnalysis } from '../../asmTemplateGenerator';

/**
 * Convert routine name to lowercase (for labels, CALL, JP, JR targets)
 */
function toRoutineLabel(name: string): string {
  return name.toLowerCase();
}

/**
 * Get the load_screen_X routine name for a screen
 * Must match the naming convention in screensGenerator.ts
 * Format: load_screen_SCREENNAME_IDSUFFIX
 */
function getScreenLoadRoutineName(screen: { name?: string; id?: string }): string {
  const screenName = (screen.name || 'DEFAULT').toUpperCase().replace(/[^A-Z0-9]/g, '_');
  const screenIdSuffix = screen.id ? `_${screen.id.replace(/[^a-zA-Z0-9]/g, '_').slice(-12)}` : '';
  return `load_screen_${screenName.toLowerCase()}${screenIdSuffix.toLowerCase()}`;
}

/**
 * Get node type constant name (e.g., "Start" -> "NODE_TYPE_START")
 */
function getNodeTypeConstant(nodeType: string): string {
  return `NODE_TYPE_${nodeType
    .replace(/([a-z])([A-Z])/g, '$1_$2') // Add underscore between camelCase words
    .toUpperCase()
    }`;
}

/**
 * Generate complete GameFlow file (gameflow.asm)
 * Creates GameFlow state machine with execution functions and node handlers
 *
 * @param analysis - Project analysis with GameFlow data
 * @returns ASM code string with complete GameFlow system
 */
export function generateGameFlowFile(analysis: ProjectAnalysis): string {
  // If no GameFlow, return minimal stub
  if (!analysis.gameFlow) {
    return `; ==================================================================
; GAMEFLOW SYSTEM
; File: gameflow.asm
; Description: GameFlow state machine (No GameFlow detected)
; ==================================================================

; No GameFlow defined - using default screen loading

load_game_screen:
    ; Load first available screen
${analysis.screenMaps && analysis.screenMaps.length > 0 ? `    call ${getScreenLoadRoutineName(analysis.screenMaps[0])}` : `    ; No screens available`}
    ret

execute_gameflow_start:
    ; No GameFlow - fallback
    ret

; ==================================================================
; END OF GAMEFLOW
; ==================================================================
`;
  }

  const gameFlow = analysis.gameFlow;

  let code = `; ==================================================================
; GAMEFLOW SYSTEM
; File: gameflow.asm
; Description: GameFlow state machine and execution functions
; Generated by Mideas MSX Generator
; ==================================================================
;
; GameFlow: ${gameFlow.name || 'Unknown'}
; Nodes: ${gameFlow.nodes?.length || 0}
; Connections: ${gameFlow.connections?.length || 0}
; Start Node: ${gameFlow.startNodeId || 'none'}
; ==================================================================

; ==================================================================
; GAMEFLOW MAIN FUNCTIONS
; ==================================================================

load_game_screen:
    ; Load game screen based on GameFlow execution path
    ; This follows the exact same flow as Play mode for PARIDAD

    ; GameFlow detected - follow node execution path
    ; Start node: ${gameFlow.startNodeId || 'unknown'}
    ; Nodes: ${gameFlow.nodes?.length || 0} total
${gameFlow.nodes && gameFlow.nodes.length > 0 ?
      gameFlow.nodes.map((node, i) =>
        `    ; Node ${i}: ${node.id} (${node.type || 'unknown'}) ${(node as any).data?.worldMapId ? `-> World: ${(node as any).data.worldMapId}` : ''}`
      ).join('\n') : '    ; No nodes in GameFlow'}

    ; Execute first GameFlow transition (matches Play mode behavior)
    call execute_gameflow_start
    ret

execute_gameflow_start:
    ; Execute the GameFlow start node exactly as Play mode does
    ; Start node ID: ${gameFlow.startNodeId || 'none'}
${gameFlow.startNodeId ? `
    ; Find and execute start node
    ld hl, gameflow_node_${gameFlow.startNodeId.replace(/[^a-zA-Z0-9]/g, '_')}
    call execute_gameflow_node` : `
    ; No start node defined - execute first available node
${gameFlow.nodes && gameFlow.nodes.length > 0 ? `
    ld hl, gameflow_node_${gameFlow.nodes[0].id.replace(/[^a-zA-Z0-9]/g, '_')}
    call execute_gameflow_node` : `
    ; No nodes available - load default screen
    call load_default_screen`}`}
    ret

execute_gameflow_node:
    ; Execute a single GameFlow node (matches Play mode execution)
    ; HL = pointer to node routine (starts with type byte)

    ; Read node type byte and advance HL to actual code
    ld a, (hl)                    ; Load node type byte
    inc hl                        ; HL now points to actual code
    push hl                       ; Save code address for later
${gameFlow.nodes && gameFlow.nodes.length > 0 ?
      // Get unique node types used in this project
      Array.from(new Set(gameFlow.nodes.map((n: any) => n.type)))
        .filter((type: any) => type) // Remove undefined/null
        .map((nodeType: any, index: number) => {
          // Map node type to constant name - simple camelCase to UPPER_SNAKE_CASE
          const constantName = `NODE_TYPE_${nodeType
            .replace(/([a-z])([A-Z])/g, '$1_$2') // Add underscore between camelCase words
            .toUpperCase()
            }`;
          const handlerName = `execute_${nodeType.toLowerCase()}_node`;
          return `
    cp ${constantName}
    jp z, ${handlerName}`;
        }).join('') : ''}

    ; Unknown node type - clean stack and return
    pop hl
    ret


${gameFlow.nodes && gameFlow.nodes.length > 0 ?
      // Get unique node types used in this project
      Array.from(new Set(gameFlow.nodes.map((n: any) => n.type)))
        .filter((type: any) => type) // Remove undefined/null
        .map((nodeType: any) => {
          const handlerName = `execute_${nodeType.toLowerCase()}_node`;

          // Generate handler based on node type
          switch (nodeType) {
            case 'Start':
              return `execute_start_node:
    ; Start node - typically just transitions to next node
    pop hl                ; Recover node address from stack
    ; Find next connected node and execute it
    call find_next_gameflow_node
    ; Check if next node was found (HL != 0)
    ld a, h
    or l
    ret z                 ; No next node found, return
    jp execute_gameflow_node
`;

            case 'WorldLink':
              return `execute_worldlink_node:
    ; World link node - load world and return to game loop
    pop hl                ; Recover node address from stack
    ; Each WorldLink node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'Screen':
              return `execute_screen_node:
    ; Screen node - load the specific screen
    pop hl                ; Recover node address from stack
    ; Extract screen reference from node data
    call load_referenced_screen
    ret
`;

            case 'SubMenu':
              return `execute_submenu_node:
    ; Menu node - show menu interface
    pop hl                ; Recover node address from stack
    call show_menu_interface
    ret
`;

            case 'Text':
              return `execute_text_node:
    ; Text node - show text interface
    pop hl                ; Recover node address from stack
    ; Each Text node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'Transition':
              return `execute_transition_node:
    ; Transition node - execute transition effect
    pop hl                ; Recover node address from stack
    ; Each Transition node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'Restart':
              return `execute_restart_node:
    ; Restart node - restart the game
    pop hl                ; Clean stack before restarting
    jp init_rom
`;

            case 'Group':
              return `execute_group_node:
    ; Group node - nested GameFlow
    pop hl                ; Recover node address from stack
    ; Each Group node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'End':
              return `execute_end_node:
    ; End node - show end screen
    pop hl                ; Recover node address from stack
    call show_end_screen
    ret
`;

            case 'Waypoint':
              return `execute_waypoint_node:
    ; Waypoint node - routing node
    pop hl                ; Recover node address from stack
    ; Each Waypoint node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'IfThenElse':
              return `execute_ifthenelse_node:
    ; IfThenElse node - conditional branching
    pop hl                ; Recover node address from stack
    ; Each IfThenElse node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            case 'Globals':
              return `execute_globals_node:
    ; Globals node - set global variables
    pop hl                ; Recover node address from stack
    ; Each Globals node has its own implementation below
    ; This stub should never be called directly
    ret
`;

            default:
              return `execute_${nodeType.toLowerCase()}_node:
    ; ${nodeType} node - not yet implemented
    pop hl                ; Recover node address from stack
    ret
`;
          }
        }).join('\n') : ''}

load_default_screen:
    ; Fallback: load first available screen
${analysis.screenMaps && analysis.screenMaps.length > 0 ? `
    call ${getScreenLoadRoutineName(analysis.screenMaps[0])}` : `
    ; No screens available - show placeholder
    call show_no_content_message`}
    ret

find_next_gameflow_node:
    ; Find the next node in GameFlow connections
    ; Input: HL = current node address
    ; Output: HL = next node address or 0 if not found
    push de
    push bc
    ld de, gameflow_connection_table
.find_loop:
    ld a, (de)        ; Load low byte of 'from' address
    inc de
    ld c, a
    ld a, (de)        ; Load high byte of 'from' address
    inc de
    ld b, a
    or c              ; Check if end of table (0, 0)
    jr z, .not_found
    
    ; Compare with current node (HL)
    ld a, l
    cp c
    jr nz, .skip_entry
    ld a, h
    cp b
    jr nz, .skip_entry
    
    ; Match found - load 'to' address into HL
    ld a, (de)
    ld l, a
    inc de
    ld a, (de)
    ld h, a
    pop bc
    pop de
    ret
    
.skip_entry:
    inc de            ; Skip 'to' low byte
    inc de            ; Skip 'to' high byte
    jr .find_loop
    
.not_found:
    ld hl, 0          ; Return 0 (no next node)
    pop bc
    pop de
    ret

; GameFlow Connection Table (from -> to)
gameflow_connection_table:
${gameFlow.connections && gameFlow.connections.length > 0 ?
      gameFlow.connections.map((conn: any) => {
        const fromNodeId = conn.from?.nodeId || conn.from;
        const toNodeId = conn.to?.nodeId || conn.to;
        if (!fromNodeId || !toNodeId) return '';
        const fromLabel = `gameflow_node_${String(fromNodeId).replace(/[^a-zA-Z0-9]/g, '_')}`;
        const toLabel = `gameflow_node_${String(toNodeId).replace(/[^a-zA-Z0-9]/g, '_')}`;
        return `    dw ${fromLabel}, ${toLabel}  ; ${fromNodeId} -> ${toNodeId}`;
      }).filter((s: string) => s).join('\n') :
      '    ; No connections defined'}
    dw 0, 0           ; End of table marker

load_referenced_screen:
    ; Load screen referenced by current node
    ; Implementation needs node data parsing
    call load_default_screen
    ret

show_menu_interface:
    ; Show menu defined in GameFlow node
    ; Implementation needs menu data parsing
    ret

show_no_content_message:
    ; Show message when no content is available
    ret

show_end_screen:
    ; Show end screen (Game Over, Victory, etc)
    ; Implementation needs end screen rendering
    ret

; ==================================================================
; GAMEFLOW NODE DATA STRUCTURES (Generated State Machine)
; ==================================================================

`;

  // Generate handler routines for each node
  if (gameFlow.nodes && gameFlow.nodes.length > 0) {
    gameFlow.nodes.forEach((node: any) => {
      const nodeLabel = `gameflow_node_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}`;

      switch (node.type) {
        case 'Start':
          // Find connection from Start node
          const startConnection = gameFlow.connections?.find(
            (c: any) => c.from?.nodeId === node.id || c.from === node.id
          );

          if (startConnection) {
            const nextNodeId = startConnection.to?.nodeId || startConnection.to;
            const nextNodeLabel = `gameflow_node_${nextNodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
            code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Start Node - transition to first connected node
    ld hl, ${nextNodeLabel}
    jp execute_gameflow_node
`;
          } else {
            code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Start Node - no connections, fallback to main program
    ret
`;
          }
          break;

        case 'WorldLink':
          const worldAssetId = node.worldAssetId;
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; WorldLink Node - Load world: ${worldAssetId || 'Unknown'}
    call ${toRoutineLabel('load_world_' + (worldAssetId || 'default'))}
    ; Set game flow state and update sprites to VRAM
    ld a, FLOW_STATE_GAME
    ld (current_flow_state), a
    call update_sprites_to_vram   ; Copy sprite attributes to VRAM
    ret                           ; Return to caller (game loop will handle main_loop)
`;
          break;

        case 'SubMenu':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; SubMenu Node - "${node.title || 'Menu'}"
    call init_font_system
    call ${toRoutineLabel('show_menu_' + node.id)}
    ; Wait for menu selection and transition to next node
    ret
`;
          break;

        case 'Text':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Text Node - "${node.title || 'Text'}"
    call init_font_system
    call ${toRoutineLabel('show_text_' + node.id)}
    ; Wait for user input, then transition to next node
    ret
`;
          break;

        case 'Transition':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Transition Node - Effect: ${node.effect || 'default'}
    call ${toRoutineLabel('transition_effect_' + node.id)}
    ret
`;
          break;

        case 'Group':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Group Node - Nested GameFlow
    ; Load GameFlow: ${node.gameFlowAssetId || 'Unknown'}
    call ${toRoutineLabel('init_gameflow_' + (node.gameFlowAssetId || 'default'))}
    ret
`;
          break;

        case 'End':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; End Node - ${node.endType || 'Game Over'}
    call show_end_screen
    ; Halt or return to main menu
    ret
`;
          break;

        case 'Restart':
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Restart Node
    jp init_rom  ; Restart entire game
`;
          break;

        case 'Waypoint':
          // Waypoint is just a routing node
          const waypointConnection = gameFlow.connections?.find(
            (c: any) => c.from?.nodeId === node.id || c.from === node.id
          );

          if (waypointConnection) {
            const nextNodeId = waypointConnection.to?.nodeId || waypointConnection.to;
            const nextNodeLabel = `gameflow_node_${nextNodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
            code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Waypoint - route to next node
    ld hl, ${nextNodeLabel}
    jp execute_gameflow_node
`;
          }
          break;

        case 'IfThenElse':
          // Find THEN and ELSE connections (using sourceId to differentiate)
          const thenConnection = gameFlow.connections?.find(
            (c: any) => (c.from?.nodeId === node.id || c.from === node.id) &&
              (c.from?.sourceId === 'then' || !c.from?.sourceId) // Default to THEN if no sourceId
          );
          const elseConnection = gameFlow.connections?.find(
            (c: any) => (c.from?.nodeId === node.id || c.from === node.id) &&
              c.from?.sourceId === 'else'
          );

          const thenNodeId = thenConnection ? (thenConnection.to?.nodeId || thenConnection.to) : null;
          const elseNodeId = elseConnection ? (elseConnection.to?.nodeId || elseConnection.to) : null;

          const thenLabel = thenNodeId ? `gameflow_node_${thenNodeId.replace(/[^a-zA-Z0-9]/g, '_')}` : null;
          const elseLabel = elseNodeId ? `gameflow_node_${elseNodeId.replace(/[^a-zA-Z0-9]/g, '_')}` : null;

          // Generate variable name using snake_case conversion
          const variableName = `global_var_${(node.variableName || 'Goal').replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')}`;

          // Generate compare value - check if it's a number or a named constant
          let compareConstant = '';
          const compareValue = node.compareValue || 'Completed';

          // Check if compareValue is a number
          if (!isNaN(Number(compareValue))) {
            // It's a numeric value - use directly
            compareConstant = compareValue;
          } else {
            // It's a named constant - generate constant name
            const compareValueUpper = compareValue.toUpperCase().replace(/\s+/g, '_');
            const varNameUpper = (node.variableName || 'Goal').toUpperCase().replace(/([A-Z])/g, '_$1').replace(/^_/, '');

            // Handle boolean values
            if (compareValue === 'True' || compareValue === 'False') {
              compareConstant = `BOOL_${compareValueUpper}`;
            } else {
              compareConstant = `${varNameUpper}_${compareValueUpper}`;
            }
          }

          // Generate comparison operator (default to ==)
          const operator = node.operator || '==';

          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; IfThenElse Node - Compare ${node.variableName || 'Goal'} ${operator} ${node.compareValue || 'Completed'}
    ld a, (${variableName})     ; Load global variable ${node.variableName || 'Goal'}
    cp ${compareConstant}        ; Compare with ${node.compareValue || 'Completed'}
`;

          // Generate conditional jump based on operator
          if (operator === '==') {
            if (thenLabel) {
              code += `    jp z, ${thenLabel}       ; If equal, jump to THEN branch\n`;
            }
            if (elseLabel) {
              code += `    jp ${elseLabel}          ; Otherwise, jump to ELSE branch\n`;
            } else {
              code += `    ret                      ; No ELSE branch, return\n`;
            }
          } else if (operator === '!=') {
            if (thenLabel) {
              code += `    jp nz, ${thenLabel}      ; If not equal, jump to THEN branch\n`;
            }
            if (elseLabel) {
              code += `    jp ${elseLabel}          ; Otherwise, jump to ELSE branch\n`;
            } else {
              code += `    ret                      ; No ELSE branch, return\n`;
            }
          } else if (operator === '>') {
            // For >, use carry flag (CP sets carry if A < operand)
            if (elseLabel) {
              code += `    jp c, ${elseLabel}       ; If A < value (carry set), ELSE\n`;
            }
            if (thenLabel) {
              code += `    jp z, ${elseLabel || 'if_then_else_skip'}       ; If A == value (zero set), ELSE\n`;
              code += `    jp ${thenLabel}          ; Otherwise A > value, THEN\n`;
            }
          } else if (operator === '<') {
            if (thenLabel) {
              code += `    jp c, ${thenLabel}       ; If A < value (carry set), THEN\n`;
            }
            if (elseLabel) {
              code += `    jp ${elseLabel}          ; Otherwise, ELSE\n`;
            }
          } else if (operator === '>=') {
            if (elseLabel) {
              code += `    jp c, ${elseLabel}       ; If A < value (carry set), ELSE\n`;
            }
            if (thenLabel) {
              code += `    jp ${thenLabel}          ; Otherwise A >= value, THEN\n`;
            }
          } else if (operator === '<=') {
            if (thenLabel) {
              code += `    jp z, ${thenLabel}       ; If A == value, THEN\n`;
              code += `    jp c, ${thenLabel}       ; If A < value, THEN\n`;
            }
            if (elseLabel) {
              code += `    jp ${elseLabel}          ; Otherwise A > value, ELSE\n`;
            }
          }

          if (!thenLabel && !elseLabel) {
            code += `    ret                      ; No connections, return\n`;
          }
          code += `if_then_else_skip:\n    ret\n`;
          break;

        case 'Globals':
          // Globals node sets global variables and transitions to next node
          const globalsConnection = gameFlow.connections?.find(
            (c: any) => c.from?.nodeId === node.id || c.from === node.id
          );

          // First, collect all VALID variable assignments
          const validAssignments: Array<{ varName: string, asmVarName: string, valueExpression: string, originalValue: any }> = [];

          if (node.variables && Array.isArray(node.variables)) {
            node.variables.forEach((varAssignment: any) => {
              const varName = varAssignment.variableName || 'unknown';
              const varValue = varAssignment.value !== undefined ? varAssignment.value : 0;

              // Convert variable name to ASM label (snake_case)
              const asmVarName = `global_var_${varName.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')}`;

              // Check if this variable exists in analysis.globalVariables
              const variableExists = analysis.globalVariables?.some(
                (v: any) => v.asmName === asmVarName || v.name === varName
              );

              if (!variableExists) {
                // Variable not defined - skip silently
                console.warn(`Globals node: Variable "${varName}" (${asmVarName}) not defined in analysis.globalVariables, skipping`);
                return;
              }

              // Determine the value expression
              let valueExpression = '';

              // Handle boolean values FIRST (before any other checks)
              if (typeof varValue === 'boolean') {
                valueExpression = varValue ? '1' : '0';
              } else if (varValue === 'true' || varValue === 'True') {
                valueExpression = '1';
              } else if (varValue === 'false' || varValue === 'False') {
                valueExpression = '0';
              } else if (typeof varValue === 'number') {
                // It's already a number
                valueExpression = String(varValue);
              } else if (typeof varValue === 'string' && !isNaN(Number(varValue)) && varValue.trim() !== '') {
                // String that represents a valid number
                valueExpression = varValue;
              } else if (typeof varValue === 'string') {
                // It's a named constant - generate constant name
                const valueUpper = varValue.toUpperCase().replace(/\s+/g, '_');
                const varNameUpper = varName.toUpperCase().replace(/([A-Z])/g, '_$1').replace(/^_/, '');
                valueExpression = `${varNameUpper}_${valueUpper}`;
              } else {
                // Default fallback
                valueExpression = '0';
              }

              validAssignments.push({ varName, asmVarName, valueExpression, originalValue: varValue });
            });
          }

          // Generate the node code
          code += `
${nodeLabel}:
    db ${getNodeTypeConstant(node.type)}       ; Node type identifier
    ; Globals Node - Set global variables
`;

          // Only generate assignment code if there are valid variables
          if (validAssignments.length > 0) {
            validAssignments.forEach(assignment => {
              code += `    ld a, ${assignment.valueExpression}         ; Set ${assignment.varName} = ${assignment.originalValue}\n`;
              code += `    ld (${assignment.asmVarName}), a\n`;
            });
          } else {
            code += `    ; No valid global variables to set (all skipped or undefined)\n`;
          }

          // Transition to next node
          if (globalsConnection) {
            const nextNodeId = globalsConnection.to?.nodeId || globalsConnection.to;
            const nextNodeLabel = `gameflow_node_${nextNodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
            code += `    jp ${nextNodeLabel}          ; Continue to next node\n`;
          } else {
            code += `    ret                      ; No connections, return\n`;
          }
          break;

        default:
          code += `
${nodeLabel}:
    ; ${node.type} Node (not yet implemented)
    ; Node ID: ${node.id}
    ret
`;
      }
    });
  }

  code += `
; End of GameFlow State Machine

; ==================================================================
; END OF GAMEFLOW
; ==================================================================
`;

  return code;
}

/**
 * Legacy function for compatibility - generates only the state machine nodes
 * @deprecated Use generateGameFlowFile instead
 */
export function generateGameFlowStateMachine(gameFlow: any, analysis: ProjectAnalysis): string {
  if (!gameFlow) return '; No GameFlow\n';

  let code = `
; GameFlow: ${gameFlow.name || 'Unknown'}
; Nodes: ${gameFlow.nodes?.length || 0}
; Connections: ${gameFlow.connections?.length || 0}

`;

  // Generate handler routines for each node
  if (gameFlow.nodes && gameFlow.nodes.length > 0) {
    gameFlow.nodes.forEach((node: any) => {
      const nodeLabel = `gameflow_node_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}`;

      switch (node.type) {
        case 'Start':
          const startConnection = gameFlow.connections?.find(
            (c: any) => c.from?.nodeId === node.id || c.from === node.id
          );

          if (startConnection) {
            const nextNodeId = startConnection.to?.nodeId || startConnection.to;
            const nextNodeLabel = `gameflow_node_${nextNodeId.replace(/[^a-zA-Z0-9]/g, '_')}`;
            code += `
${nodeLabel}:
    ; Start Node - transition to first connected node
    ld hl, ${nextNodeLabel}
    jp execute_gameflow_node
`;
          } else {
            code += `
${nodeLabel}:
    ; Start Node - no connections, fallback to main program
    ret
`;
          }
          break;

        case 'WorldLink':
          const worldAssetId = node.worldAssetId;
          code += `
${nodeLabel}:
    ; WorldLink Node - Load world: ${worldAssetId || 'Unknown'}
    call ${toRoutineLabel('load_world_' + (worldAssetId || 'default'))}
    ; CRITICAL: Set game flow state and update sprites to VRAM
    ld a, FLOW_STATE_GAME
    ld (current_flow_state), a
    call update_sprites_to_vram   ; Copy sprite attributes to VRAM

    jp main_loop
`;
          break;

        case 'Restart':
          code += `
${nodeLabel}:
    ; Restart Node
    jp init_rom  ; Restart entire game
`;
          break;

        default:
          code += `
${nodeLabel}:
    ; ${node.type} Node
    ret
`;
      }
    });
  }

  code += `
; End of GameFlow State Machine
`;

  return code;
}

