/**
 * @fileoverview Sprites Generator - Sprite pattern and animation data
 * Generates sprites.asm with sprite definitions and management functions
 */

import { ProjectAnalysis } from '../../asmTemplateGenerator';
import { generateSpriteASMCode } from '../../../components/utils/spriteUtils';

/**
 * Generate sprite data file (sprites.asm)
 *
 * @param analysis - Project analysis with sprite assets
 * @returns ASM code string with sprite data and functions
 */
export function generateSpritesFile(analysis: ProjectAnalysis): string {
  if (!analysis.sprites || analysis.sprites.length === 0) {
    return `; ==================================================================
; SPRITE DATA (EMPTY - NO SPRITES DETECTED)
; File: sprites.asm
; ==================================================================

; No sprites detected in project - file generated as placeholder

; ==================================================================
; SPRITE UTILITY FUNCTIONS (Available for future use)
; ==================================================================

; Clear all sprites (make them invisible)
clear_all_sprites:
    ld hl, sprite_y_pos
    ld de, sprite_y_pos+1
    ld bc, ${Math.max(0, (analysis.sprites?.length || 1) - 1)}                     ; ${analysis.sprites?.length || 1} sprites - 1
    ld (hl), SPRITE_INVISIBLE     ; Y=209 (invisible)
    ldir
    ret

; Hide specific sprite (A = sprite number)
hide_sprite:
    ld hl, sprite_y_pos
    ld e, a
    ld d, 0
    add hl, de                    ; HL points to sprite Y position
    ld (hl), SPRITE_INVISIBLE     ; Make invisible
    ret

; ==================================================================
; END OF SPRITE DATA
; ==================================================================
`;
  }

  let code = `; ==================================================================
; SPRITE DATA
; File: sprites.asm
; Description: Sprite pattern and animation data
; ${analysis.sprites?.length || 0} sprites detected
; ==================================================================

; ==================================================================
; SPRITE PATTERN DATA
; ==================================================================
`;

  // Generate sprite patterns using the EXACT same function as Sprite Editor "Download ASM"
  analysis.sprites.forEach((sprite, index) => {
    const safeSpriteName = sprite.name.replace(/[^a-zA-Z0-9_]/g, '_').toUpperCase();
    const spriteASM = generateSpriteASMCode(sprite, 'hex');

    // Find the first layer that was actually generated by scanning the ASM output
    let firstLayerFound = -1;
    for (let layerIndex = 0; layerIndex < 4; layerIndex++) {
      const layerLabel = `${safeSpriteName}_F0_LAYER${layerIndex}:`;
      if (spriteASM.includes(layerLabel)) {
        firstLayerFound = layerIndex;
        break;
      }
    }

    code += `
; Sprite ${index}: ${sprite.name}
${spriteASM}`;

    if (firstLayerFound >= 0) {
      code += `
; Unified pattern label for sprite ${index} (for easy reference in loading code)
SPRITE_${index}_PATTERN EQU ${safeSpriteName}_F0_LAYER${firstLayerFound}
`;
    } else {
      code += `
; WARNING: No valid pattern layers found for sprite ${index}: ${sprite.name}
; Creating placeholder pattern label
SPRITE_${index}_PATTERN:
    DB 0, 0, 0, 0, 0, 0, 0, 0  ; 8 bytes of empty pattern data
`;
    }
  });

  code += `
; ==================================================================
; SPRITE INITIALIZATION FUNCTIONS
; ==================================================================

init_sprites:
    ; Initialize sprite system
    call clear_all_sprites

    ; Load sprite patterns to VRAM
    call load_sprite_patterns

    ; Initialize sprite positions (all invisible by default)
    xor a
    ld (active_sprite_count), a

    ret

load_sprite_patterns:
    ; Load all sprite patterns to VRAM sprite pattern table
`;

  // Generate pattern loading for each sprite
  analysis.sprites.forEach((sprite, index) => {
    code += `
    ; Load sprite ${index}: ${sprite.name} (BIOS LDIRVM handles timing)
    ld hl, SPRITE_${index}_PATTERN
    ld de, SPRPAT + (${index} * 32) ; Each 16x16 sprite = 32 bytes (4 patterns)
    ld bc, 32                       ; 16x16 sprite size
    call LDIRVM                     ; BIOS handles safe VRAM access
`;
  });

  code += `    ret

; ==================================================================
; SPRITE MANAGEMENT FUNCTIONS
; ==================================================================

; Show sprite (A = sprite number, B = X, C = Y, D = pattern, E = color)
show_sprite:
    push bc                       ; Preserve parameters
    push de

    ; Calculate sprite offset (A = sprite number)
    ld l, a                       ; L = sprite number
    ld h, 0                       ; HL = sprite number

    ; Set X position
    push hl
    ld de, sprite_x_pos
    add hl, de                    ; HL points to sprite X position
    ld (hl), b                    ; Set X position
    pop hl

    ; Set Y position
    push hl
    ld de, sprite_y_pos
    add hl, de                    ; HL points to sprite Y position
    ld (hl), c                    ; Set Y position
    pop hl

    ; Set pattern
    push hl
    ld de, sprite_pattern
    add hl, de                    ; HL points to sprite pattern
    pop de                        ; Restore original HL to DE
    push de                       ; Save it again
    ld (hl), d                    ; Set pattern number
    pop hl

    ; Set color
    ld de, sprite_color
    add hl, de                    ; HL points to sprite color
    pop de                        ; Get original DE back
    ld (hl), e                    ; Set color

    pop bc                        ; Restore original parameters
    ret

; Clear all sprites (make them invisible)
clear_all_sprites:
    ld hl, sprite_y_pos
    ld de, sprite_y_pos+1
    ld bc, ${Math.max(0, (analysis.sprites?.length || 1) - 1)}                     ; ${analysis.sprites?.length || 1} sprites - 1
    ld (hl), SPRITE_INVISIBLE     ; Y=209 (invisible)
    ldir
    ret

; Hide specific sprite (A = sprite number)
hide_sprite:
    ld hl, sprite_y_pos
    ld e, a
    ld d, 0
    add hl, de                    ; HL points to sprite Y position
    ld (hl), SPRITE_INVISIBLE     ; Make invisible
    ret

; Update sprite positions to VRAM
update_sprites_to_vram:
    ; Copy sprite attributes from RAM to VRAM
    ; BIOS LDIRVM handles timing automatically
    ld hl, sprite_y_pos
    ld de, SPRATR
    ld bc, ${(analysis.sprites?.length || 1) * 4}                    ; ${analysis.sprites?.length || 1} sprites * 4 bytes each
    call LDIRVM                   ; BIOS handles safe VRAM access
    ret

; ==================================================================
; SPRITE CONSTANTS
; ==================================================================
`;

  // Generate sprite ID constants
  analysis.sprites.forEach((sprite, index) => {
    const spriteName = sprite.name.toUpperCase().replace(/[^A-Z0-9_]/g, '_');
    code += `SPRITE_ID_${spriteName}    EQU ${index}      ; Sprite: ${sprite.name}\n`;
  });

  code += `
; ==================================================================
; END OF SPRITE DATA
; ==================================================================
`;

  return code;
}
