/**
 * @fileoverview Unified Generator - All-in-one combined file
 * Generates unitedFiles.asm combining all modular files into one
 */

import { ProjectAnalysis } from '../../asmTemplateGenerator';
import { buildBankPackReport, formatBankPackReportAsAsmComments } from '../utils/bankPacker';
import type { ExecutionPlan } from '../types/executionTypes';
import { buildPage0Plan, hasPage0DataGroups, page0NeedsZx0Decoder } from './page0Generator';
import { getFontRawData } from './fontGenerator';
import { getZx0DecoderAsm } from './zx0Utils';

/**
 * Convert routine name to lowercase (for labels, CALL, JP, JR targets)
 */
function toRoutineLabel(name: string): string {
    return name.toLowerCase();
}

function formatExecutionPlanComments(executionPlan: ExecutionPlan): string {
    const irqTasks = executionPlan.tasks.length > 0
        ? executionPlan.tasks.map((task) => `; IRQ Task: slot ${task.slot} -> ${task.routineLabel} (${task.responsibility}, every ${task.period} frame${task.period === 1 ? '' : 's'})`).join('\n')
        : '; IRQ Task: none';
    const mainlineWork = executionPlan.mainline.length > 0
        ? executionPlan.mainline.map((item) => `; Mainline: ${item.phase} -> ${item.routineLabel} (${item.responsibility})`).join('\n')
        : '; Mainline: none';
    const warnings = executionPlan.diagnostics.warnings.length > 0
        ? executionPlan.diagnostics.warnings.map((warning) => `; Warning: ${warning}`).join('\n')
        : '; Warning: none';

    return `; Engine Execution Mode: ${executionPlan.mode}\n${irqTasks}\n${mainlineWork}\n${warnings}\n`;
}

/**
 * Interface for generated ASM files
 */
export interface GeneratedASMFiles {
    'page0.asm': string;
    'bios.asm': string;
    'constants.asm': string;
    'variables.asm': string;
    'mapper.asm': string;
    'interrupt.asm': string;
    'header.asm': string;
    'components.asm': string;
    'entities.asm': string;
    'screens.asm': string;
    'patterns.asm': string;
    'colors.asm': string;
    'sprites.asm': string;
    'font.asm': string;
    'hud.asm': string;
    'menus.asm': string;
    'sound.asm': string;
    'scroll.asm': string;
    'animtiles.asm': string;
    'statemachine.asm': string;
    'gameflow.asm': string;
    'worlds.asm': string;
    'main.asm': string;
    'unitedFiles.asm'?: string;
}

export type UnifiedMapperFormat = 'konami' | 'ascii8' | 'ascii16';
export type UnifiedRomMode = 'auto' | 'simple32k' | 'plain48k' | 'megarom';

export interface UnifiedGenerationConfig {
    romMode: UnifiedRomMode;
    targetFormat: UnifiedMapperFormat;
    autoMegaROM: boolean;
}

/**
 * Generate unified file (unitedFiles.asm) - optional all-in-one file
 *
 * @param files - All generated ASM files
 * @param projectName - Name of the project
 * @param analysis - Project analysis with assets and configuration
 * @param config - ROM mode/mapper configuration
 * @returns ASM code string with all files combined
 */
export function generateUnifiedFile(
    files: GeneratedASMFiles,
    projectName: string,
    analysis: ProjectAnalysis,
    executionPlan: ExecutionPlan,
    config: UnifiedGenerationConfig = {
        romMode: 'simple32k',
        targetFormat: 'konami',
        autoMegaROM: false
    }
): string {
    // Check what features are needed
    const hasPresentationScreenNode = analysis.gameFlow?.nodes?.some(node => node.type === 'PresentationScreen');
    const hasMenus = analysis.gameFlow?.nodes?.some(node => node.type === 'SubMenu');
    const hasText = analysis.screenMaps?.some(screen =>
        (screen.layers as any)?.text || (screen as any).textElements?.length > 0
    );
    const hasHud = analysis.screenMaps?.some(screen =>
        screen.hudConfiguration?.elements && screen.hudConfiguration.elements.length > 0
    );
    const needsFont = hasMenus || hasText || hasHud;
    const fontInPage0 = config.romMode === 'plain48k' && !!needsFont;
    const fontRawData = fontInPage0 ? getFontRawData(analysis) : undefined;
    const page0Plan = buildPage0Plan(analysis, config.romMode, fontRawData);
    const hasPage0Data = hasPage0DataGroups(analysis, config.romMode, fontRawData);
    const bankPackReport = buildBankPackReport(files as unknown as Record<string, string>);
    const bankPackComments = formatBankPackReportAsAsmComments(bankPackReport);
    const executionPlanComments = formatExecutionPlanComments(executionPlan);
    const needsZx0Decoder = page0NeedsZx0Decoder(analysis, config.romMode, fontRawData);

    return `; ==================================================================
; ${projectName.toUpperCase()} - UNIFIED FILE
; File: unitedFiles.asm
; Description: All-in-one file combining all modular files
; Generated by Mideas MSX Modular Generator
;
; OPTIMIZED: Only includes necessary code for this project
; Tiles: ${analysis.tiles?.length || 0}
; Sprites: ${analysis.sprites?.length || 0}
; Screens: ${analysis.screenMaps?.length || 0}
; Entities: ${analysis.entities?.length || 0}
; Menus: ${hasMenus ? 'Yes' : 'No'}
; HUD: ${hasHud ? 'Yes' : 'No'}
; State Machines: ${analysis.stateMachines?.length || 0}
; ROM Mode: ${config.romMode}
; Mapper Target: ${config.targetFormat}
; Auto MegaROM: ${config.autoMegaROM ? 'Yes' : 'No'}
${executionPlanComments}; ==================================================================
${config.romMode === 'plain48k' ? `; Linear48K Page0 Data: ${hasPage0Data ? 'Yes' : 'No'}\n; Page0 Used Bytes: ${page0Plan.usedBytes}\n; Page0 Remaining Bytes: ${page0Plan.remainingBytes}\n; EXPERIMENTAL: linear 48K page-0 data groups currently start with Presentation Screen.\n` : ''}${bankPackComments}

${config.romMode === 'plain48k' ? `; ==================================================================
; LINEAR 48K PAGE 0 SCAFFOLD
; ==================================================================
    org #0000
${files['page0.asm']}
    ds #4000 - $

` : ''}
; CRITICAL: header.asm with ORG #4000 and "AB" signature MUST be first
; for the ROM to work correctly after the optional page-0 scaffold.
${files['header.asm']}

${needsZx0Decoder ? `; ZX0 decoder required by page-0 compressed cold data.
${getZx0DecoderAsm()}

` : ''}

${files['bios.asm']}

${files['constants.asm']}

${files['variables.asm']}

${files['mapper.asm']}

${files['interrupt.asm']}

${analysis.tiles && analysis.tiles.length > 0 ? files['patterns.asm'] : '; [patterns.asm skipped - no tiles]\n'}

${analysis.tiles && analysis.tiles.length > 0 ? files['colors.asm'] : '; [colors.asm skipped - no tiles]\n'}

${files['sprites.asm']}

${analysis.screenMaps && analysis.screenMaps.length > 0 || hasPresentationScreenNode ? files['screens.asm'] : '; [screens.asm skipped - no screens]\n'}

${files['components.asm']}

${analysis.entities && analysis.entities.length > 0 ? files['entities.asm'] : '; [entities.asm skipped - no entities]\n'}

${hasMenus ? files['menus.asm'] : '; [menus.asm skipped - no menus]\n'}

${needsFont ? files['font.asm'] : `; [font.asm skipped - no text/menus]
init_font_system:
    ret

`}

${hasHud ? files['hud.asm'] : '; [hud.asm skipped - no HUD elements]\n'}

${files['sound.asm']}

${files['scroll.asm']}

${files['animtiles.asm']}

${files['statemachine.asm'] && files['statemachine.asm'].trim() !== '; No State Machines' ? files['statemachine.asm'] : '; [statemachine.asm skipped - no state machines]\n'}

${analysis.gameFlow ? files['gameflow.asm'] : '; [gameflow.asm skipped - no GameFlow]\n'}

${files['worlds.asm']}

; ==================================================================
; GAME SYSTEM FUNCTIONS
; ==================================================================
; NOTE: The main game loop and execution flow are handled exclusively
; by GameFlow (see gameflow.asm section above).
; This section only contains shared initialization and utility functions.
; ==================================================================

;-----------------------------------------------
; Capture the normal expanded slot used by each page.
init_page0_runtime_state:
    in a, (#A8)
    ld (slot_primary_normal), a
    ld e, a
    ld a, e
    and #03
    call GETSLOT
    ld (page0_bios_slot), a
    ld a, e
    rrca
    rrca
    and #03
    call GETSLOT
    ld (ROM_slot), a
    ld a, e
    rrca
    rrca
    rrca
    rrca
    and #03
    call GETSLOT
    ld (page2_normal_slot), a
    ld a, e
    rlca
    rlca
    and #03
    call GETSLOT
    ld (page3_normal_slot), a
    ret

;-----------------------------------------------
; Map page 0 to the expanded slot passed in A while restoring page 3 afterwards.
; input:
;   a: expanded slot for page 0 target
; output:
;   page 0 remapped
;   page 3 restored to its normal RAM slot
;   interrupts remain disabled on return
page0_map_expanded_slot:
    ld c, a
    ld a, (slot_primary_normal)
    ; Keep pages 1-3 exactly as they were; only replace page 0 primary slot bits.
    and #FC
    ld b, a
    ld a, c
    and #03
    or b
    di
    out (#A8), a

    ld a, c
    and #80
    ret z
    ld a, c
    and #0C
    rrca
    rrca
    ld b, a
    ld a, (ROM_slot)
    and #0C
    or b
    ld b, a
    ld a, (page2_normal_slot)
    and #0C
    rlca
    rlca
    or b
    ld b, a
    ld a, (page3_normal_slot)
    and #0C
    rlca
    rlca
    rlca
    rlca
    or b
    ld (#FFFF), a
    ret

;-----------------------------------------------
; Switch page 0 to the cartridge ROM slot while keeping page 3 in RAM.
page0_map_game_rom:
    ; IRQs must stay disabled while BIOS page 0 is hidden, otherwise IM1 jumps to #0038
    ; inside cartridge data/ZX0 blobs and execution derails.
    di
    ld a, (ROM_slot)
    jp page0_map_expanded_slot

;-----------------------------------------------
; Restore the normal BIOS-ROM-ROM-RAM slot layout after a page-0 copy.
page0_restore_bios_rom:
    ld a, (page0_bios_slot)
    call page0_map_expanded_slot
    ei
    ret

;-----------------------------------------------
; Copy one chunk from page 0 ROM into the RAM transfer buffer.
; input:
;   hl: source in page 0
;   bc: chunk size (1..256)
; output:
;   hl: source advanced by chunk size
page0_copy_chunk_to_buffer:
    call page0_map_game_rom
    ld de, page0_transfer_buffer
    ldir
    jp page0_restore_bios_rom

;-----------------------------------------------
; Decompress ZX0 data stored in page 0 into a RAM destination.
; input:
;   hl: compressed source in page 0
;   de: destination in RAM
page0_decompress_to_ram:
    ; page0_map_game_rom uses E/C/B as scratch while rebuilding slot registers.
    ; Preserve DE so dzx0_standard receives the caller's RAM destination intact.
    push de
    call page0_map_game_rom
    pop de
    call dzx0_standard
    jp page0_restore_bios_rom

;-----------------------------------------------
; Copy cold data from page 0 ROM to VRAM using a RAM buffer.
; input:
;   hl: source in page 0
;   de: destination VRAM
;   bc: byte count
page0_copy_to_vram:
    ld a, b
    or c
    ret z
.page0_copy_loop:
    push bc
    ld a, b
    or a
    jr z, .page0_copy_final_chunk
    ld bc, #0100
    jr .page0_copy_chunk_ready
.page0_copy_final_chunk:
    ; Final chunk keeps the original BC (1..255 bytes).
.page0_copy_chunk_ready:
    push bc
    push de
    call page0_copy_chunk_to_buffer
    pop de
    pop bc
    push hl
    push bc
    ld hl, page0_transfer_buffer
    call FAST_LDIRVM
    pop bc
    pop hl
    ex de, hl
    add hl, bc
    ex de, hl
    pop bc
    ld a, b
    or a
    jr z, .page0_copy_done
    dec b
    ld a, b
    or c
    jp nz, .page0_copy_loop
.page0_copy_done:
    ret

init_game_systems:
    call DISSCR               ; Disable screen while loading VRAM assets
${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize component systems (entities detected)
    call init_components
` : `    ; No entities - skipping component system initialization
`}
${analysis.tiles && analysis.tiles.length > 0 ? `    ; Load pattern and color data (tiles detected)
    call load_pattern_bank0
    call load_pattern_bank1
    call load_pattern_bank2
    call load_color_bank0
    call load_color_bank1
    call load_color_bank2
` : `    ; No tiles detected - skipping pattern/color loading
`}
    ; Initialize animated tile runtime (safe no-op if no animated groups)
    call init_animated_tiles

${analysis.entities && analysis.entities.length > 0 ? `    ; Initialize game entities with real positions from JSON
    call init_entities
` : `    ; No entities to initialize
`}
${analysis.screenMaps && analysis.screenMaps.length > 0 ? `    ; Load the first game screen
    call load_game_screen
    call rebuild_used_entity_list
` : `    ; No screens - skip screen loading
`}
${needsFont ? `    ; Initialize font system
    call init_font_system
` : `    ; No text/menus - skip font initialization
`}${hasHud ? `    ; HUD dirty flag - will be rendered after screen loading (by GameFlow WorldLink)
    ld a, 1
    ld (hud_dirty_flag), a
` : ``}    call ENASCR               ; Re-enable screen after VRAM updates
    ret

; ==================================================================
; SCREEN LOADING STUB (for compatibility)
; ==================================================================
; NOTE: With GameFlow system, screen loading is handled by GameFlow nodes
; via load_world_X -> load_screen_X. This stub exists for backward
; compatibility with init_game_systems references.
load_game_screen:
    ret

${config.romMode === 'plain48k' ? `    ds #C000 - $        ; Pad linear 48K ROM to 49152 bytes

` : ''}    end                 ; End of assembly
`;
}
