/**
 * @fileoverview World Generator - WorldMap structure and loading functions
 * Generates worlds.asm with world map data and screen loading functions
 */

import { ProjectAnalysis } from '../../asmTemplateGenerator';

/**
 * Convert name to valid ASM label (lowercase)
 */
function toRoutineLabel(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

/**
 * Convert name to valid ASM constant (uppercase)
 */
function toConstantName(name: string): string {
  return name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
}

/**
 * Generate worlds file with world map data and loading functions (worlds.asm)
 *
 * WorldMap structure:
 * - nodes: Array of screen nodes with screenAssetId
 * - connections: Array of connections between screens (for transitions)
 * - startScreenNodeId: ID of the initial screen node
 *
 * @param analysis - Project analysis with world maps and screens
 * @returns ASM code string with world map data and loading functions
 */
export function generateWorldsFile(analysis: ProjectAnalysis): string {
  // Check if we have world maps in the analysis
  const worldMaps = (analysis as any).worldmaps || [];

  // Skip world system if no worlds in project
  if (worldMaps.length === 0) {
    return `; ==================================================================
; WORLD MAPS (SKIPPED - NO WORLDS DETECTED)
; File: worlds.asm
; ==================================================================

; No worlds detected in project - world system not needed

; Minimal stub functions for compatibility
load_world_default:
    ret

; ==================================================================
; END OF WORLDS (MINIMAL VERSION)
; ==================================================================
`;
  }

  let code = `; ==================================================================
; WORLD MAPS
; File: worlds.asm
; Description: World map structures and screen loading functions
; Generated by Mideas MSX Generator
; ==================================================================

`;

  // Generate constants for each world
  code += `; ==================================================================
; WORLD MAP CONSTANTS
; ==================================================================

`;

  worldMaps.forEach((world: any, index: number) => {
    const worldName = toConstantName(world.name || `world_${index}`);
    const worldId = world.id || `world_${index}`;

    code += `; World: ${world.name || 'Unnamed'} (${worldId})
WORLD_${worldName}_ID EQU ${index}
WORLD_${worldName}_SCREEN_COUNT EQU ${world.nodes?.length || 0}
`;

    // Generate constants for each screen node in the world
    if (world.nodes && world.nodes.length > 0) {
      world.nodes.forEach((node: any, nodeIndex: number) => {
        const nodeName = toConstantName(node.name || `screen_${nodeIndex}`);
        code += `WORLD_${worldName}_SCREEN_${nodeName}_ID EQU ${nodeIndex}
`;
      });
    }
    code += `\n`;
  });

  // Generate load_world_X functions for each world
  code += `; ==================================================================
; WORLD LOADING FUNCTIONS
; ==================================================================

`;

  worldMaps.forEach((world: any) => {
    const worldName = toRoutineLabel(world.name || 'unnamed');
    const worldId = world.id || 'unknown';
    const startScreenNodeId = world.startScreenNodeId;
    const nodes = world.nodes || [];

    code += `; ------------------------------------------------------------------
; Load World: ${world.name || 'Unnamed'}
; World ID: ${worldId}
; Screens: ${nodes.length}
; Start Screen Node: ${startScreenNodeId || 'none'}
; ------------------------------------------------------------------
load_world_${toRoutineLabel(worldId)}:
`;

    if (nodes.length === 0) {
      code += `    ; No screens in this world
    ret

`;
      return;
    }

    // Find the start screen node
    const startNode = nodes.find((n: any) => n.id === startScreenNodeId) || nodes[0];
    const startScreenAssetId = startNode.screenAssetId;

    if (!startScreenAssetId) {
      code += `    ; No valid start screen found
    ret

`;
      return;
    }

    // Find the screen asset - use name + ID suffix for function call (matches screensGenerator.ts)
    const screenAsset = analysis.screens?.find((s: any) => s.id === startScreenAssetId);
    const screenName = screenAsset?.name?.toUpperCase().replace(/[^A-Z0-9]/g, '_') || 'UNKNOWN';
    // Use screen ID suffix to match the load_screen function name
    const screenIdSuffix = startScreenAssetId ? `_${startScreenAssetId.replace(/[^a-zA-Z0-9]/g, '_').slice(-12)}` : '';

    code += `    ; Load start screen: ${screenAsset?.name || 'unknown'} (${startScreenAssetId})
    call load_screen_${screenName.toLowerCase()}${screenIdSuffix.toLowerCase()}

    ; Initialize world state
    ld a, WORLD_${toConstantName(world.name || 'unnamed')}_ID
    ld (current_world_id), a

    ld a, ${nodes.findIndex((n: any) => n.id === startScreenNodeId)}
    ld (current_screen_index), a

    ret

`;
  });

  // Generate screen transition functions
  code += `; ==================================================================
; SCREEN TRANSITION FUNCTIONS
; ==================================================================

`;

  worldMaps.forEach((world: any) => {
    const worldId = world.id || 'unknown';
    const nodes = world.nodes || [];
    const connections = world.connections || [];

    if (connections.length === 0) {
      code += `; World ${world.name || 'Unnamed'} has no screen connections

`;
      return;
    }

    code += `; ------------------------------------------------------------------
; World: ${world.name || 'Unnamed'}
; Connections: ${connections.length}
; ------------------------------------------------------------------

`;

    connections.forEach((conn: any, connIndex: number) => {
      const fromNode = nodes.find((n: any) => n.id === conn.from || conn.fromNodeId);
      const toNode = nodes.find((n: any) => n.id === conn.to || conn.toNodeId);

      if (!fromNode || !toNode) {
        code += `; Invalid connection ${connIndex}: missing nodes

`;
        return;
      }

      const fromScreenId = fromNode.screenAssetId;
      const toScreenId = toNode.screenAssetId;

      // Find screen assets to get their names (matches screensGenerator.ts naming)
      const toScreenAsset = analysis.screens?.find((s: any) => s.id === toScreenId);
      const toScreenName = toScreenAsset?.name?.toUpperCase().replace(/[^A-Z0-9]/g, '_') || 'UNKNOWN';
      // Use screen ID suffix to match the load_screen function name
      const toScreenIdSuffix = toScreenId ? `_${toScreenId.replace(/[^a-zA-Z0-9]/g, '_').slice(-12)}` : '';

      code += `; Transition: ${fromNode.name || 'screen'} -> ${toNode.name || 'screen'}
transition_${toRoutineLabel(worldId)}_${connIndex}:
    call load_screen_${toScreenName.toLowerCase()}${toScreenIdSuffix.toLowerCase()}
    ret

`;
    });
  });

  // Generate helper functions
  code += `; ==================================================================
; WORLD HELPER FUNCTIONS
; ==================================================================

; Get current world ID
; Output: A = current world ID
get_current_world_id:
    ld a, (current_world_id)
    ret

; Get current screen index
; Output: A = current screen index in world
get_current_screen_index:
    ld a, (current_screen_index)
    ret

; Set current screen
; Input: A = screen index
set_current_screen:
    ld (current_screen_index), a
    ret

; ==================================================================
; END OF WORLDS
; ==================================================================
`;

  return code;
}
