; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SPRITES                   EQU 1
RESOURCE_GROUP_PATTERNS                  EQU 2
RESOURCE_GROUP_COLORS                    EQU 3
RESOURCE_GROUP_SCREENS                   EQU 4

RESOURCE_TYPE_SPRITE_PATTERNS            EQU 1
RESOURCE_TYPE_TILE_PATTERNS              EQU 2
RESOURCE_TYPE_TILE_COLORS                EQU 3
RESOURCE_TYPE_SCREEN_LAYOUT              EQU 4
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 5
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 6
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 7

RESOURCE_TABLE_COUNT EQU 76

resource_table:
    ; HERO_LEFT_0_F0_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 14
    dw #9FA8
    dw 32
    ; HERO_LEFT_0_F0_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 14
    dw #9FC8
    dw 32
    ; HERO_LEFT_0_F1_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 15
    dw #9F68
    dw 32
    ; HERO_LEFT_0_F1_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 15
    dw #9F88
    dw 32
    ; HERO_LEFT_0_F2_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 15
    dw #9FA8
    dw 32
    ; HERO_LEFT_0_F2_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F2_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 15
    dw #9FC8
    dw 32
    ; HERO_LEFT_0_F3_LAYER1
    db RESOURCE_ID_HERO_LEFT_0_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8590
    dw 32
    ; HERO_LEFT_0_F3_LAYER2
    db RESOURCE_ID_HERO_LEFT_0_F3_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #85B0
    dw 32
    ; BIRD_1_F0_LAYER1
    db RESOURCE_ID_BIRD_1_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #85D0
    dw 32
    ; BIRD_1_F1_LAYER1
    db RESOURCE_ID_BIRD_1_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #85F0
    dw 32
    ; BIRD_1_F2_LAYER1
    db RESOURCE_ID_BIRD_1_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8610
    dw 32
    ; BIRD_1_F3_LAYER1
    db RESOURCE_ID_BIRD_1_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8630
    dw 32
    ; BOT1_2_F0_LAYER1
    db RESOURCE_ID_BOT1_2_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8650
    dw 32
    ; BOT2_RIGHT_3_F0_LAYER0
    db RESOURCE_ID_BOT2_RIGHT_3_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8670
    dw 32
    ; BOT2_RIGHT_3_F1_LAYER0
    db RESOURCE_ID_BOT2_RIGHT_3_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8690
    dw 32
    ; HERO_DEAD_4_F0_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #86B0
    dw 32
    ; HERO_DEAD_4_F1_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #86D0
    dw 32
    ; HERO_DEAD_4_F2_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #86F0
    dw 32
    ; HERO_DEAD_4_F3_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8710
    dw 32
    ; HERO_DEAD_4_F4_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F4_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8730
    dw 32
    ; HERO_DEAD_4_F5_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F5_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8750
    dw 32
    ; HERO_DEAD_4_F6_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F6_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8770
    dw 32
    ; HERO_DEAD_4_F7_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F7_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8790
    dw 32
    ; HERO_DEAD_4_F8_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F8_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #87B0
    dw 32
    ; HERO_DEAD_4_F9_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F9_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #87D0
    dw 32
    ; HERO_DEAD_4_F10_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F10_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #87F0
    dw 32
    ; HERO_DEAD_4_F11_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F11_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8810
    dw 32
    ; HERO_DEAD_4_F12_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F12_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8830
    dw 32
    ; HERO_DEAD_4_F13_LAYER1
    db RESOURCE_ID_HERO_DEAD_4_F13_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8850
    dw 32
    ; NEW_SPRITE_5_F0_LAYER1
    db RESOURCE_ID_NEW_SPRITE_5_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 14
    dw #9F68
    dw 64
    ; GEMA1_6_F0_LAYER2
    db RESOURCE_ID_GEMA1_6_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8870
    dw 32
    ; GEMA1_6_F1_LAYER2
    db RESOURCE_ID_GEMA1_6_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8890
    dw 32
    ; BOX_7_F0_LAYER1
    db RESOURCE_ID_BOX_7_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #88B0
    dw 32
    ; HERO_RIGHT_8_F0_LAYER1
    db RESOURCE_ID_HERO_RIGHT_8_F0_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #88D0
    dw 32
    ; HERO_RIGHT_8_F0_LAYER2
    db RESOURCE_ID_HERO_RIGHT_8_F0_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #88F0
    dw 32
    ; HERO_RIGHT_8_F1_LAYER1
    db RESOURCE_ID_HERO_RIGHT_8_F1_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8910
    dw 32
    ; HERO_RIGHT_8_F1_LAYER2
    db RESOURCE_ID_HERO_RIGHT_8_F1_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8930
    dw 32
    ; HERO_RIGHT_8_F2_LAYER1
    db RESOURCE_ID_HERO_RIGHT_8_F2_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8950
    dw 32
    ; HERO_RIGHT_8_F2_LAYER2
    db RESOURCE_ID_HERO_RIGHT_8_F2_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8970
    dw 32
    ; HERO_RIGHT_8_F3_LAYER1
    db RESOURCE_ID_HERO_RIGHT_8_F3_LAYER1, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8990
    dw 32
    ; HERO_RIGHT_8_F3_LAYER2
    db RESOURCE_ID_HERO_RIGHT_8_F3_LAYER2, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #89B0
    dw 32
    ; BOT2_LEFT_9_F0_LAYER0
    db RESOURCE_ID_BOT2_LEFT_9_F0_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #89D0
    dw 32
    ; BOT2_LEFT_9_F1_LAYER0
    db RESOURCE_ID_BOT2_LEFT_9_F1_LAYER0, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #89F0
    dw 32
    ; SPRITE_PLACEHOLDER_PATTERN
    db RESOURCE_ID_SPRITE_PLACEHOLDER_PATTERN, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 16
    dw #8A10
    dw 32
    ; tile_pattern_bank0
    db RESOURCE_ID_TILE_PATTERN_BANK0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 14
    dw #9E00
    dw 360
    ; tilebank_pattern_data_0
    db RESOURCE_ID_TILEBANK_PATTERN_DATA_0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 16
    dw #8300
    dw 328
    ; tile_color_bank0
    db RESOURCE_ID_TILE_COLOR_BANK0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 15
    dw #9E00
    dw 360
    ; tilebank_color_data_0
    db RESOURCE_ID_TILEBANK_COLOR_DATA_0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 16
    dw #8448
    dw 328
    ; SCREEN_PAN1_0_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8000
    dw 768
    ; SCREEN_PAN1_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8300
    dw 768
    ; SCREEN_PAN1_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN1_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FE8
    dw 1
    ; BEHAVIOR_PAN1_0_DATA
    db RESOURCE_ID_BEHAVIOR_PAN1_0_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 14
    dw #8600
    dw 768
    ; SCREEN_PAN2_1_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8900
    dw 768
    ; SCREEN_PAN2_1_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8C00
    dw 768
    ; SCREEN_PAN2_1_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN2_1_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FE9
    dw 1
    ; BEHAVIOR_PAN2_1_DATA
    db RESOURCE_ID_BEHAVIOR_PAN2_1_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 14
    dw #8F00
    dw 768
    ; SCREEN_PAN3_2_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_2_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #9200
    dw 768
    ; SCREEN_PAN3_2_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN3_2_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #9500
    dw 768
    ; SCREEN_PAN3_2_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN3_2_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FEA
    dw 1
    ; BEHAVIOR_PAN3_2_DATA
    db RESOURCE_ID_BEHAVIOR_PAN3_2_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 14
    dw #9800
    dw 768
    ; SCREEN_PAN4_3_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_3_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #9B00
    dw 768
    ; SCREEN_PAN4_3_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN4_3_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #8000
    dw 768
    ; SCREEN_PAN4_3_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN4_3_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FEB
    dw 1
    ; BEHAVIOR_PAN4_3_DATA
    db RESOURCE_ID_BEHAVIOR_PAN4_3_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 15
    dw #8300
    dw 768
    ; SCREEN_PAN5_4_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_4_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #8600
    dw 768
    ; SCREEN_PAN5_4_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN5_4_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #8900
    dw 768
    ; SCREEN_PAN5_4_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN5_4_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FEC
    dw 1
    ; BEHAVIOR_PAN5_4_DATA
    db RESOURCE_ID_BEHAVIOR_PAN5_4_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 15
    dw #8C00
    dw 768
    ; SCREEN_PAN62_5_LAYOUT
    db RESOURCE_ID_SCREEN_PAN62_5_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #8F00
    dw 768
    ; SCREEN_PAN62_5_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN62_5_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #9200
    dw 768
    ; SCREEN_PAN62_5_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN62_5_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FED
    dw 1
    ; BEHAVIOR_PAN62_5_DATA
    db RESOURCE_ID_BEHAVIOR_PAN62_5_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 15
    dw #9500
    dw 768
    ; SCREEN_PAN7_6_LAYOUT
    db RESOURCE_ID_SCREEN_PAN7_6_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #9800
    dw 768
    ; SCREEN_PAN7_6_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_PAN7_6_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 15
    dw #9B00
    dw 768
    ; SCREEN_PAN7_6_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_PAN7_6_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9FEE
    dw 1
    ; BEHAVIOR_PAN7_6_DATA
    db RESOURCE_ID_BEHAVIOR_PAN7_6_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 16
    dw #8000
    dw 768
