; ==================================================================
; GENERATED RESOURCE TABLE
; Descriptor format: db id, type, group, bank / dw address / dw size
; Address is the mapper-window address visible after selecting bank.
; ==================================================================
RESOURCE_TABLE_ENTRY_SIZE EQU 8

RESOURCE_GROUP_SPRITES                   EQU 1
RESOURCE_GROUP_PATTERNS                  EQU 2
RESOURCE_GROUP_COLORS                    EQU 3
RESOURCE_GROUP_SCREENS                   EQU 4
RESOURCE_GROUP_FONT                      EQU 5

RESOURCE_TYPE_SPRITE_PATTERNS            EQU 1
RESOURCE_TYPE_TILE_PATTERNS              EQU 2
RESOURCE_TYPE_TILE_COLORS                EQU 3
RESOURCE_TYPE_SCREEN_LAYOUT              EQU 4
RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT      EQU 5
RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE   EQU 6
RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP        EQU 7
RESOURCE_TYPE_FONT_PATTERNS              EQU 8
RESOURCE_TYPE_FONT_COLORS                EQU 9

RESOURCE_TABLE_COUNT EQU 9

resource_table:
    ; SPRITE_PLACEHOLDER_PATTERN
    db RESOURCE_ID_SPRITE_PLACEHOLDER_PATTERN, RESOURCE_TYPE_SPRITE_PATTERNS, RESOURCE_GROUP_SPRITES, 14
    dw #9100
    dw 32
    ; tile_pattern_bank0
    db RESOURCE_ID_TILE_PATTERN_BANK0, RESOURCE_TYPE_TILE_PATTERNS, RESOURCE_GROUP_PATTERNS, 14
    dw #9120
    dw 32
    ; tile_color_bank0
    db RESOURCE_ID_TILE_COLOR_BANK0, RESOURCE_TYPE_TILE_COLORS, RESOURCE_GROUP_COLORS, 14
    dw #9140
    dw 32
    ; SCREEN_NEW_SCREENMAP_0_LAYOUT
    db RESOURCE_ID_SCREEN_NEW_SCREENMAP_0_LAYOUT, RESOURCE_TYPE_SCREEN_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8800
    dw 768
    ; SCREEN_NEW_SCREENMAP_0_EFFECTS_LAYOUT
    db RESOURCE_ID_SCREEN_NEW_SCREENMAP_0_EFFECTS_LAYOUT, RESOURCE_TYPE_SCREEN_EFFECTS_LAYOUT, RESOURCE_GROUP_SCREENS, 14
    dw #8B00
    dw 768
    ; SCREEN_NEW_SCREENMAP_0_EFFECT_ZONE_TABLE
    db RESOURCE_ID_SCREEN_NEW_SCREENMAP_0_EFFECT_ZONE_TABLE, RESOURCE_TYPE_SCREEN_EFFECT_ZONE_TABLE, RESOURCE_GROUP_SCREENS, 14
    dw #9160
    dw 1
    ; BEHAVIOR_NEW_SCREENMAP_0_DATA
    db RESOURCE_ID_BEHAVIOR_NEW_SCREENMAP_0_DATA, RESOURCE_TYPE_SCREEN_BEHAVIOR_MAP, RESOURCE_GROUP_SCREENS, 14
    dw #8E00
    dw 768
    ; FONT_PATTERN_DATA
    db RESOURCE_ID_FONT_PATTERN_DATA, RESOURCE_TYPE_FONT_PATTERNS, RESOURCE_GROUP_FONT, 14
    dw #8000
    dw 1024
    ; FONT_COLOR_DATA
    db RESOURCE_ID_FONT_COLOR_DATA, RESOURCE_TYPE_FONT_COLORS, RESOURCE_GROUP_FONT, 14
    dw #8400
    dw 1024
