export const ConditionTypes = {
    // Logical operators
    AND: 'AND',
    OR: 'OR',
    XOR: 'XOR',
    NOT: 'NOT',
    // Input conditions (events)
    KEY_PRESSED: 'KEY_PRESSED',
    KEY_RELEASED: 'KEY_RELEASED',
    // Time conditions (events)
    TIME_OUT: 'TIME_OUT',
    // Movement/Collision conditions (events)
    CAN_MOVE_DIRECTION: 'CAN_MOVE_DIRECTION',
    HAS_COLLISION: 'HAS_COLLISION',
    PATH_CLEAR: 'PATH_CLEAR',
    ON_WALL_COLLISION: 'ON_WALL_COLLISION',
    HAS_DEADLY_TILE_COLLISION: 'HAS_DEADLY_TILE_COLLISION',
    // Animation conditions (events)
    ANIMATION_COMPLETE: 'ANIMATION_COMPLETE',
    // Composite conditions
    KEY_AND_MOVEMENT: 'KEY_AND_MOVEMENT',
    // Variable conditions
    VARIABLE_COMPARE: 'VARIABLE_COMPARE'
};
export const ActionTypes = {
    // No-op (no action)
    NONE: 'NONE',
    // Movement and Physics
    SET_POSITION: 'SET_POSITION',
    MOVE_BY: 'MOVE_BY',
    SET_VELOCITY: 'SET_VELOCITY',
    APPLY_FORCE: 'APPLY_FORCE',
    // Appearance
    CHANGE_SPRITE: 'CHANGE_SPRITE',
    PLAY_ANIMATION: 'PLAY_ANIMATION',
    SET_ANIMATION_SPEED: 'SET_ANIMATION_SPEED',
    TOGGLE_ANIMATION: 'TOGGLE_ANIMATION',
    // Sound
    PLAY_SOUND: 'PLAY_SOUND',
    PLAY_MUSIC: 'PLAY_MUSIC',
    MUTE_MUSIC: 'MUTE_MUSIC',
    STOP_MUSIC: 'STOP_MUSIC',
    // Game Logic
    SET_VARIABLE: 'SET_VARIABLE',
    INCREMENT_VARIABLE: 'INCREMENT_VARIABLE',
    DECREMENT_VARIABLE: 'DECREMENT_VARIABLE',
    SET_COMPONENT_PROPERTY: 'SET_COMPONENT_PROPERTY',
    WAIT: 'WAIT',
    GOTO_STATE: 'GOTO_STATE',
    DESTROY_ENTITY: 'DESTROY_ENTITY',
    SPAWN_ENTITY: 'SPAWN_ENTITY',
    GET_RANDOM_ENTITY_POSITION: 'GET_RANDOM_ENTITY_POSITION',
    // Game Flow
    CHANGE_GAME_FLOW_NODE: 'CHANGE_GAME_FLOW_NODE',
    REGENERATE_HUD: 'REGENERATE_HUD',
    CLEAN_SPRITES: 'CLEAN_SPRITES',
    EXIT_CURRENT_WORLD: 'EXIT_CURRENT_WORLD',
    DECREASE_LIVES: 'DECREASE_LIVES',
    INCREASE_LIVES: 'INCREASE_LIVES',
    RESPAWN_PLAYER: 'RESPAWN_PLAYER',
    // Tile Manipulation
    BREAK_TILE: 'BREAK_TILE',
    REPLACE_TILE: 'REPLACE_TILE',
    // Math
    RND: 'RND',
    POINT_AT: 'POINT_AT',
    // Mathematical Operations
    ADD_VARIABLES: 'ADD_VARIABLES',
    SUBTRACT_VARIABLES: 'SUBTRACT_VARIABLES',
    MULTIPLY_VARIABLES: 'MULTIPLY_VARIABLES',
    DIVIDE_VARIABLES: 'DIVIDE_VARIABLES',
    MODULO_VARIABLES: 'MODULO_VARIABLES',
    ASSIGN_VARIABLE: 'ASSIGN_VARIABLE',
    // Input Control
    DISABLE_INPUT: 'DISABLE_INPUT',
    ENABLE_INPUT: 'ENABLE_INPUT',
};
